Repository inventree/InvenTree, pull requests merged in 2021-08, with the labels that each got.

#1899 Refactor "CreatePartCategory" form to API
  InvenTree/part/templates/part/category.html
  InvenTree/part/test_views.py
  InvenTree/part/urls.py
  InvenTree/part/views.py
  InvenTree/templates/js/translated/part.js
Labels: api, enhancement, user interface

#1964 Added navbar on part import page
  InvenTree/part/templates/part/import_wizard/part_upload.html
Labels: user interface

#1963 Print multi part label
  InvenTree/part/templates/part/category.html
  InvenTree/templates/js/translated/part.js
Labels: part

#1968 Cleanup docker vars for dev setup
  InvenTree/InvenTree/settings.py
  docker/Dockerfile
  docker/dev-config.env
  docker/docker-compose.dev.yml
Labels: docker

#1977 Fixed company templates
  InvenTree/company/templates/company/detail.html
  InvenTree/company/templates/company/manufacturer_part.html
  InvenTree/part/templates/part/category.html
  InvenTree/part/templates/part/detail.html
Labels: user interface

#1990 Fix tooltip linebreak
  InvenTree/part/templates/part/prices.html
Labels: user interface, pricing

#1987 Disable table sorting when order is fixed
  InvenTree/templates/js/translated/part.js
Labels: bug

#1957 BOM - show purchase price
  InvenTree/part/models.py
  InvenTree/part/templates/part/part_pricing.html
  InvenTree/part/templates/part/prices.html
  InvenTree/part/views.py
Labels: pricing

#1999 Disable functions in navbars
  InvenTree/common/models.py
  InvenTree/company/templates/company/navbar.html
  InvenTree/part/templates/part/navbar.html
  InvenTree/part/templates/part/part_base.html
  InvenTree/templates/InvenTree/settings/build.html
  InvenTree/templates/InvenTree/settings/po.html
  InvenTree/templates/InvenTree/settings/so.html
  InvenTree/templates/InvenTree/settings/stock.html
  InvenTree/templates/navbar.html
Labels: pricing

#2005 Updated color of `new` and `add` UI buttons
  InvenTree/company/templates/company/detail.html
  InvenTree/company/templates/company/supplier_part.html
  InvenTree/order/templates/order/purchase_order_detail.html
  InvenTree/order/templates/order/purchase_orders.html
  InvenTree/order/templates/order/sales_orders.html
  InvenTree/part/templates/part/detail.html
  InvenTree/part/templates/part/prices.html
Labels: user interface
