Repository inventree/InvenTree, pull requests merged in 2021-10, with the labels that each got.

#2090 Fix for purchase order API
  InvenTree/order/api.py
  InvenTree/order/models.py
  InvenTree/order/test_api.py
Labels: bug, api

#2094 Refactor of build order stock assignment
  InvenTree/InvenTree/api_tester.py
  InvenTree/InvenTree/management/commands/rebuild_thumbnails.py
  InvenTree/InvenTree/version.py
  InvenTree/build/api.py
  InvenTree/build/fixtures/build.yaml
  InvenTree/build/forms.py
  InvenTree/build/models.py
  InvenTree/build/serializers.py
  InvenTree/build/templates/build/auto_allocate.html
  InvenTree/build/templates/build/create_build_item.html
  InvenTree/build/templates/build/delete_build_item.html
  InvenTree/build/templates/build/detail.html
  InvenTree/build/test_api.py
  InvenTree/build/test_build.py
  InvenTree/build/tests.py
  InvenTree/build/urls.py
  InvenTree/build/views.py
  InvenTree/company/apps.py
  InvenTree/order/api.py
  InvenTree/order/serializers.py
  InvenTree/part/apps.py
  InvenTree/part/fixtures/bom.yaml
  InvenTree/part/models.py
  InvenTree/part/test_api.py
  InvenTree/part/test_bom_item.py
  InvenTree/stock/api.py
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/helpers.js
  InvenTree/templates/js/translated/model_renderers.js
  tasks.py
Labels: enhancement, user interface, api, build

#2118 Fix error on BOM export
  InvenTree/part/bom.py
Labels: bug

#2127 Documentation URL is now hard-coded
  InvenTree/InvenTree/version.py
  ci/check_version_number.py
Labels: CI

#2128 Auto-focus on the 'sub_part' field
  InvenTree/part/templates/part/detail.html
  InvenTree/templates/js/translated/bom.js
Labels: enhancement, user interface

#2167 Standardize spelling of email / e-mail
  InvenTree/InvenTree/forms.py
  InvenTree/common/models.py
  InvenTree/templates/InvenTree/settings/user.html
  InvenTree/templates/account/email_confirm.html
  InvenTree/templates/account/password_reset.html
Labels: translation

#2161 Onboarding group
  InvenTree/InvenTree/forms.py
  InvenTree/common/models.py
  InvenTree/templates/InvenTree/settings/login.html
Labels: enhancement

#2173 fix signup with providers with extra args
  InvenTree/InvenTree/forms.py
Labels: bug

#2159 Build output improvements
  InvenTree/InvenTree/static/script/inventree/delay.js
  InvenTree/InvenTree/static/script/inventree/sidenav.js
  InvenTree/InvenTree/version.py
  InvenTree/build/api.py
  InvenTree/build/forms.py
  InvenTree/build/models.py
  InvenTree/build/serializers.py
  InvenTree/build/templates/build/allocation_card.html
  InvenTree/build/templates/build/build_base.html
  InvenTree/build/templates/build/complete_output.html
  InvenTree/build/templates/build/detail.html
  InvenTree/build/templates/build/edit_build_item.html
  InvenTree/build/templates/build/navbar.html
  InvenTree/build/test_api.py
  InvenTree/build/test_build.py
  InvenTree/build/tests.py
  InvenTree/build/urls.py
  InvenTree/build/views.py
  InvenTree/common/templates/common/delete_currency.html
  InvenTree/order/api.py
  InvenTree/order/forms.py
  InvenTree/order/templates/order/order_base.html
  InvenTree/order/templates/order/sales_order_base.html
  InvenTree/order/test_api.py
  InvenTree/part/forms.py
  InvenTree/stock/forms.py
  InvenTree/stock/templates/stock/stock_adjust.html
  InvenTree/stock/templates/stock/stock_move.html
  InvenTree/templates/attachment_delete.html
  InvenTree/templates/base.html
  InvenTree/templates/collapse.html
  InvenTree/templates/collapse_index.html
  InvenTree/templates/js/dynamic/inventree.js
  InvenTree/templates/js/dynamic/nav.js
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/helpers.js
  InvenTree/templates/js/translated/tables.js
  InvenTree/templates/required_part_table.html
  InvenTree/templates/slide.html
Labels: enhancement, user interface, api, build

#2175 Improvements to "grid view" for parts list
  InvenTree/InvenTree/static/css/inventree.css
  InvenTree/templates/js/translated/part.js
Labels: enhancement, user interface

#2176 Display stock level in quick search bar
  InvenTree/templates/js/dynamic/inventree.js
  InvenTree/templates/js/translated/model_renderers.js
  InvenTree/templates/js/translated/part.js
Labels: enhancement, user interface

#2206 Add definition for Gitpod.io
  .gitpod.yml
Labels: demo

#2209 Update README.md
  README.md
Labels: demo

#2215 [BUG] Auth screens broken
  InvenTree/InvenTree/static/css/inventree.css
  InvenTree/templates/account/base.html
Labels: bug, user interface

#2220 CSS updates
  InvenTree/InvenTree/static/css/inventree.css
  InvenTree/build/templates/build/detail.html
  InvenTree/build/templates/build/index.html
  InvenTree/company/templates/company/detail.html
  InvenTree/company/templates/company/manufacturer_part.html
  InvenTree/company/templates/company/supplier_part.html
  InvenTree/order/templates/order/purchase_order_detail.html
  InvenTree/order/templates/order/purchase_orders.html
  InvenTree/order/templates/order/sales_order_detail.html
  InvenTree/order/templates/order/sales_orders.html
  InvenTree/part/templates/part/bom.html
  InvenTree/part/templates/part/category.html
  InvenTree/part/templates/part/detail.html
  InvenTree/stock/templates/stock/item.html
  InvenTree/stock/templates/stock/location.html
  InvenTree/templates/attachment_table.html
  InvenTree/templates/filter_list.html
  InvenTree/templates/js/translated/filters.js
  InvenTree/templates/stock_table.html
Labels: enhancement, user interface
