Repository inventree/InvenTree, pull requests merged in 2022-09, with the labels that each got.

#3626 Fix default ordering for build orders
  InvenTree/build/api.py
  InvenTree/order/api.py
Labels: build

#3627 Fix sales order table refresh
  InvenTree/templates/js/translated/order.js
Labels: bug, order, user interface

#3628 Fix sales order table refresh (#3627)
  InvenTree/templates/js/translated/order.js
Labels: bug, order

#3636 Update settings value lookup to include typ
  InvenTree/common/models.py
  InvenTree/common/serializers.py
  InvenTree/plugin/models.py
  InvenTree/templates/InvenTree/settings/setting.html
  InvenTree/templates/js/dynamic/settings.js
Labels: bug, plugin

#3639 Add search to build output table
  InvenTree/templates/js/translated/build.js
Labels: user interface

#3634 Optimisations for editable installs of plugins
  InvenTree/plugin/helpers.py
  InvenTree/plugin/plugin.py
  InvenTree/plugin/test_helpers.py
Labels: enhancement, plugin, setup

#3633 Add decorator to not require auth
  InvenTree/InvenTree/middleware.py
  InvenTree/InvenTree/permissions.py
Labels: enhancement, security

#3615 Add confirmation field for incomplete purchase orders
  InvenTree/InvenTree/api_version.py
  InvenTree/order/models.py
  InvenTree/order/serializers.py
  InvenTree/order/templates/order/sales_order_base.html
  InvenTree/order/test_api.py
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/order.js
Labels: order, api

#3642 Fix report permissions
  InvenTree/users/models.py
Labels: bug, report

#3643 Fix report permissions (#3642)
  InvenTree/users/models.py
Labels: bug, report

#3620 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3657 Fix part link in stock table
  InvenTree/templates/js/translated/stock.js
Labels: bug

#3644 Feature: Supplier part pack size
  InvenTree/InvenTree/api_version.py
  InvenTree/company/api.py
  InvenTree/company/migrations/0047_supplierpart_pack_size.py
  InvenTree/company/models.py
  InvenTree/company/serializers.py
  InvenTree/company/templates/company/supplier_part.html
  InvenTree/order/models.py
  InvenTree/order/serializers.py
  InvenTree/order/templates/order/order_base.html
  InvenTree/order/tests.py
  InvenTree/part/filters.py
  InvenTree/part/models.py
  InvenTree/part/test_api.py
  InvenTree/templates/js/translated/company.js
  InvenTree/templates/js/translated/order.js
  InvenTree/templates/js/translated/part.js
  tasks.py
Labels: enhancement, order, user interface, api

#3658 Add extra information callout to stock item display
  InvenTree/stock/templates/stock/item_base.html
Labels: user interface

#3661 Pack quantity improvements
  InvenTree/InvenTree/fields.py
  InvenTree/company/serializers.py
  InvenTree/part/templates/part/part_base.html
  InvenTree/part/templates/part/stock_count.html
  InvenTree/templates/js/translated/company.js
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/stock.js
Labels: user interface

#3663 Null units fix
  InvenTree/company/templates/company/supplier_part.html
  InvenTree/part/templates/part/part_base.html
  InvenTree/part/templates/part/part_units.html
  InvenTree/part/templates/part/stock_count.html
  InvenTree/stock/templates/stock/item_base.html
  InvenTree/stock/test_views.py
  InvenTree/templates/email/build_order_required_stock.html
  InvenTree/templates/js/translated/company.js
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/stock.js
Labels: bug, user interface

#3664 Display more units
  InvenTree/part/templates/part/part_base.html
  InvenTree/templates/js/translated/bom.js
Labels: user interface

#3666 PO: Use supplier currency when creating a new extra line
  InvenTree/order/templates/order/purchase_order_detail.html
Labels: order

#3646 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3674 Fix purchase order report template
  InvenTree/report/templates/report/inventree_po_report.html
Labels: bug, report

#3675 Add support for Danish
  InvenTree/InvenTree/settings.py
  InvenTree/locale/da/LC_MESSAGES/django.po
Labels: enhancement

#3677 Fix purchase order report template (#3674)
  InvenTree/report/templates/report/inventree_po_report.html
Labels: bug, report

#3678 Adds callback for clipboard button
  InvenTree/InvenTree/static/script/inventree/inventree.js
Labels: bug, user interface

#3679 Adds callback for clipboard button (#3678)
  InvenTree/InvenTree/static/script/inventree/inventree.js
Labels: bug, user interface

#3640 Barcode Refactor
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/models.py
  InvenTree/InvenTree/tests.py
  InvenTree/build/models.py
  InvenTree/company/migrations/0048_auto_20220913_0312.py
  InvenTree/company/models.py
  InvenTree/company/templates/company/supplier_part.html
  InvenTree/company/urls.py
  InvenTree/company/views.py
  InvenTree/label/models.py
  InvenTree/order/models.py
  InvenTree/order/serializers.py
  InvenTree/order/test_api.py
  InvenTree/part/migrations/0086_auto_20220912_0007.py
  InvenTree/part/models.py
  InvenTree/part/templates/part/part_base.html
  InvenTree/part/test_part.py
  InvenTree/plugin/base/barcodes/api.py
  InvenTree/plugin/base/barcodes/mixins.py
  InvenTree/plugin/base/barcodes/test_barcode.py
  InvenTree/plugin/builtin/barcodes/inventree_barcode.py
  InvenTree/plugin/builtin/barcodes/test_inventree_barcode.py
  InvenTree/stock/fixtures/stock.yaml
  InvenTree/stock/migrations/0084_auto_20220903_0154.py
  InvenTree/stock/migrations/0085_auto_20220903_0225.py
  InvenTree/stock/migrations/0086_remove_stockitem_uid.py
  InvenTree/stock/migrations/0087_auto_20220912_2341.py
  InvenTree/stock/models.py
  InvenTree/stock/serializers.py
  InvenTree/stock/templates/stock/item_base.html
  InvenTree/stock/templates/stock/location.html
  InvenTree/stock/tests.py
  InvenTree/templates/js/translated/barcode.js
Labels: enhancement, barcode, api, breaking

#3689 Update config_template.yaml
  InvenTree/config_template.yaml
Labels: setup

#3695 Short strings
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/helpers.js
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/stock.js
  InvenTree/templates/js/translated/tables.js
Labels: user interface

#3694 Path name bug fix
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/models.py
  InvenTree/part/test_category.py
  InvenTree/stock/tests.py
Labels: bug

#3696 Bug fix for path string generation
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/models.py
  InvenTree/part/test_category.py
Labels: bug

#3699 Form field sanitization
  InvenTree/InvenTree/static/css/inventree.css
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/helpers.js
  InvenTree/templates/js/translated/part.js
Labels: bug, user interface, api

#3693 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3700 Only limit length of link if specified
  InvenTree/templates/js/translated/helpers.js
Labels: bug, user interface

#3702 Update CompleteBuildOrder form
  InvenTree/build/serializers.py
  InvenTree/build/templates/build/build_base.html
  InvenTree/templates/js/translated/build.js
Labels: user interface, build

#3704 Parameter ordering fix
  InvenTree/part/api.py
  InvenTree/part/serializers.py
  InvenTree/part/templates/part/detail.html
  InvenTree/templates/js/translated/part.js
Labels: part, user interface

#3701 Add sanitation for SVG attachments
  InvenTree/InvenTree/models.py
  InvenTree/InvenTree/sanitizer.py
  InvenTree/InvenTree/tests.py
Labels: enhancement, security

#3715 Add user setting for configuring table string length
  InvenTree/common/models.py
  InvenTree/templates/InvenTree/settings/user_display.html
  InvenTree/templates/js/translated/helpers.js
Labels: user interface

#2890 Adds 'consumable' field to BomItem model
  .github/ISSUE_TEMPLATE/feature_request.yaml
  InvenTree/build/models.py
  InvenTree/build/serializers.py
  InvenTree/part/api.py
  InvenTree/part/migrations/0087_bomitem_consumable.py
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/part/test_bom_export.py
  InvenTree/part/test_bom_item.py
  InvenTree/stock/migrations/0088_remove_stockitem_infinite.py
  InvenTree/stock/models.py
  InvenTree/templates/js/translated/bom.js
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/table_filters.js
Labels: build

#3707 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3720 Bug fix for multi-level display in BOM table
  InvenTree/templates/js/translated/bom.js
Labels: bug, user interface

#3726 Add typecasting to certain settings
  InvenTree/InvenTree/config.py
  InvenTree/InvenTree/settings.py
Labels: enhancement, setup

#3635 APIMixin: Add flag for passing data as json
  InvenTree/plugin/base/integration/mixins.py
  InvenTree/plugin/base/integration/test_mixins.py
Labels: enhancement, plugin

#3728 Add typecasting to certain settings (#3726)
  InvenTree/InvenTree/config.py
  InvenTree/InvenTree/settings.py
Labels: bug

#3727 Barcode scan fix
  InvenTree/plugin/builtin/barcodes/inventree_barcode.py
  InvenTree/templates/js/translated/barcode.js
Labels: bug, barcode

#3731 Add content headers to config
  docker/nginx.dev.conf
  docker/production/nginx.prod.conf
Labels: security, setup

#3735 Bug fix for stock adjustment actions
  InvenTree/templates/js/translated/stock.js
Labels: bug, user interface

#3736 Bug fix for stock adjustment actions (#3735)
  InvenTree/templates/js/translated/stock.js
Labels: bug, user interface
