Repository inventree/InvenTree, pull requests merged in 2022-11, with the labels that each got.

#3887 Location barcode actions
  InvenTree/common/models.py
  InvenTree/part/templates/part/category.html
  InvenTree/stock/templates/stock/location.html
  InvenTree/templates/InvenTree/settings/barcode.html
  InvenTree/templates/js/translated/barcode.js
Labels: user interface, barcode

#3888 Allow editing of extra line items in order table
  InvenTree/order/templates/order/purchase_order_detail.html
  InvenTree/order/templates/order/sales_order_detail.html
  InvenTree/templates/js/translated/order.js
  docker.dev.env
Labels: user interface

#3893 Translatable strings for plugins
  InvenTree/templates/InvenTree/settings/sidebar.html
Labels: user interface, translation

#3894 re-enable plugins by default for debug docker environment
  docker.dev.env
  docker/production/.env
Labels: bug, plugin, CI

#3874 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3895 Add metadata model to Company
  InvenTree/InvenTree/api_version.py
  InvenTree/company/api.py
  InvenTree/company/migrations/0049_company_metadata.py
  InvenTree/company/models.py
Labels: enhancement, part, plugin, api

#3889 Builtin plugins
  InvenTree/InvenTree/api_tester.py
  InvenTree/InvenTree/static/script/inventree/inventree.js
  InvenTree/InvenTree/test_api.py
  InvenTree/build/test_api.py
  InvenTree/common/models.py
  InvenTree/label/api.py
  InvenTree/part/test_api.py
  InvenTree/plugin/admin.py
  InvenTree/plugin/apps.py
  InvenTree/plugin/base/barcodes/api.py
  InvenTree/plugin/base/event/events.py
  InvenTree/plugin/builtin/action/__init__.py
  InvenTree/plugin/builtin/barcodes/inventree_barcode.py
  InvenTree/plugin/builtin/barcodes/test_inventree_barcode.py
  InvenTree/plugin/builtin/integration/core_notifications.py
  InvenTree/plugin/models.py
  InvenTree/plugin/plugin.py
  InvenTree/plugin/registry.py
  InvenTree/plugin/samples/integration/simpleactionplugin.py
  InvenTree/plugin/samples/integration/test_simpleactionplugin.py
  InvenTree/plugin/test_api.py
  InvenTree/report/tests.py
  InvenTree/templates/InvenTree/settings/plugin.html
  InvenTree/templates/InvenTree/settings/plugin_details.html
  InvenTree/templates/InvenTree/settings/plugin_settings.html
  InvenTree/templates/InvenTree/settings/settings.html
  InvenTree/templates/InvenTree/settings/sidebar.html
  InvenTree/templates/admin_button.html
Labels: enhancement

#3898 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3902 Order editing updates
  InvenTree/InvenTree/tests.py
  InvenTree/common/models.py
  InvenTree/order/templates/order/purchase_order_detail.html
  InvenTree/order/templates/order/sales_order_detail.html
  InvenTree/templates/InvenTree/settings/po.html
  InvenTree/templates/InvenTree/settings/so.html
  InvenTree/templates/js/translated/order.js
Labels: order, user interface

#3905 Adds a report template tag for dict access
  InvenTree/report/templatetags/report.py
  InvenTree/report/tests.py
Labels: report

#3906 Add 'barcode_hash' data to more API serializers:
  InvenTree/InvenTree/api_version.py
  InvenTree/company/serializers.py
  InvenTree/part/serializers.py
  InvenTree/stock/serializers.py
Labels: barcode, api

#3435 Add option to recursively delete part categories
  InvenTree/InvenTree/metadata.py
  InvenTree/InvenTree/mixins.py
  InvenTree/part/api.py
  InvenTree/part/models.py
  InvenTree/part/test_api.py
  InvenTree/templates/js/translated/part.js
Labels: enhancement, part

#3445 Add news reader
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/urls.py
  InvenTree/common/admin.py
  InvenTree/common/api.py
  InvenTree/common/migrations/0015_newsfeedentry.py
  InvenTree/common/models.py
  InvenTree/common/serializers.py
  InvenTree/common/tasks.py
  InvenTree/templates/InvenTree/index.html
  InvenTree/templates/InvenTree/settings/user_homepage.html
  InvenTree/templates/base.html
  InvenTree/templates/js/translated/news.js
  InvenTree/users/models.py
  requirements.in
  requirements.txt
Labels: enhancement

#3911 Remove client-side length validation in form inputs
  InvenTree/InvenTree/fields.py
  InvenTree/InvenTree/serializers.py
  InvenTree/company/migrations/0050_alter_company_website.py
  InvenTree/company/models.py
  InvenTree/order/migrations/0075_auto_20221110_0108.py
  InvenTree/order/models.py
  InvenTree/stock/models.py
  InvenTree/templates/js/translated/forms.js
Labels: user interface

#3913 Bug fix for PurchaseOrder template
  InvenTree/order/models.py
  InvenTree/order/templates/order/order_base.html
Labels: bug, user interface

#3920 Adds 'outstanding task count' to the health API endpoint
  InvenTree/InvenTree/api.py
Labels: api

#3922 Fixes for background worker process
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/status.py
  InvenTree/InvenTree/tasks.py
Labels: bug

#3924 Fix for barcode URL generation
  InvenTree/InvenTree/helpers.py
  InvenTree/label/models.py
  InvenTree/label/tests.py
Labels: bug, barcode

#3926 Add support for recursively delete the stock locations
  InvenTree/stock/api.py
  InvenTree/stock/models.py
  InvenTree/stock/test_api.py
  InvenTree/templates/js/translated/stock.js
Labels: enhancement

#3904 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3939 Notification fix
  InvenTree/common/api.py
  InvenTree/common/models.py
  InvenTree/common/serializers.py
  InvenTree/part/templates/part/category.html
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/news.js
  InvenTree/templates/js/translated/notification.js
Labels: bug, api

#3942 Home page adjust
  InvenTree/common/models.py
  InvenTree/templates/InvenTree/index.html
  InvenTree/templates/InvenTree/settings/user_homepage.html
Labels: user interface

#3946 Markdown notes fix
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/mixins.py
  InvenTree/part/test_api.py
Labels: bug, api

#3938 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3961 Extend installer issue option
  .github/ISSUE_TEMPLATE/install.yaml
Labels: setup

#3963 Part image delete
  InvenTree/InvenTree/static/css/inventree.css
  InvenTree/company/templates/company/company_base.html
  InvenTree/part/templates/part/part_base.html
  InvenTree/part/templates/part/part_thumb.html
  InvenTree/templates/js/translated/modals.js
Labels: part, user interface

#3949 Implement structural stock locations
  InvenTree/InvenTree/api_version.py
  InvenTree/stock/api.py
  InvenTree/stock/migrations/0090_stocklocation_structural.py
  InvenTree/stock/models.py
  InvenTree/stock/serializers.py
  InvenTree/stock/test_api.py
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/order.js
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/stock.js
Labels: enhancement

#3962 Installer fixes
  .pkgr.yml
  contrib/install.sh
  contrib/installer/install
  contrib/installer/settings.yml
  contrib/installer/src/bashly.yml
  contrib/installer/src/root_command.sh
  contrib/packager.io/functions.sh
  contrib/packager.io/postinstall.sh
Labels: bug, setup

#3968 Simple typo fix
  InvenTree/part/migrations/0090_auto_20221115_0816.py
  InvenTree/part/models.py
  InvenTree/stock/migrations/0090_stocklocation_structural.py
  InvenTree/stock/models.py
Labels: translation

#3957 Remove DO for now
  README.md
Labels: setup

#3972 Stable package
  .pkgr.yml
  Procfile
  contrib/install.sh
  contrib/installer/README
  contrib/installer/settings.yml
  contrib/installer/src/bashly.yml
  contrib/installer/src/initialize.sh
  contrib/installer/src/root_command.sh
  contrib/packager.io/functions.sh
  contrib/packager.io/postinstall.sh
  runtime.txt
Labels: enhancement, setup

#3975 allauth default login protocol setting
  InvenTree/InvenTree/settings.py
  InvenTree/config_template.yaml
Labels: security

#3976 Search field fix for admin interface
  InvenTree/company/admin.py
Labels: bug

#3970 22 04 installer patch
  contrib/install.sh
  contrib/installer/src/root_command.sh
Labels: enhancement, setup

#3977 Docker plugin config
  InvenTree/common/models.py
Labels: plugin, docker

#3951 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3984 Simple formatting fix for BOM table
  InvenTree/templates/js/translated/bom.js
Labels: user interface

#3987 Add settings for controlling variant pricing
  InvenTree/common/models.py
  InvenTree/part/models.py
  InvenTree/templates/InvenTree/settings/pricing.html
  InvenTree/templates/js/translated/pricing.js
Labels: pricing

#3988 Supplier pricing override
  InvenTree/common/models.py
  InvenTree/part/models.py
  InvenTree/templates/InvenTree/settings/pricing.html
Labels: pricing

#3989 Fix for docker workflow
  .github/workflows/docker.yaml
  InvenTree/InvenTree/tests.py
Labels: bug, CI, docker

#3995 Added config setting for logout redirect url
  InvenTree/InvenTree/settings.py
  InvenTree/config_template.yaml
Labels: enhancement, setup

#3999 Change point at which yaml module is loaded
  InvenTree/InvenTree/config.py
Labels: bug, CI, docker

#4000 Add ability to filter location and category tables by "structural"
  InvenTree/templates/js/translated/table_filters.js
Labels: part, stock, user interface

#4004 Make part variant table columns sortable
  InvenTree/templates/js/translated/part.js
Labels: user interface

#4006 Fix for stable release workflow
  .github/workflows/release.yml
  .github/workflows/social.yml.disabled
Labels: CI

#3991 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation
