Repository inventree/InvenTree, pull requests merged in 2022-06, with the labels that each got.

#3111 Adds 'multi delete' for attachment tables
  InvenTree/build/templates/build/detail.html
  InvenTree/templates/attachment_table.html
  InvenTree/templates/js/translated/attachment.js
Labels: enhancement, user interface

#3115 Fix filtering for purchaseorder table on supplierpart page
  InvenTree/company/templates/company/supplier_part.html
Labels: bug

#3116 Fix broken delete button
  InvenTree/company/templates/company/supplier_part.html
Labels: bug, user interface

#3118 Ignore auto-creation of shipments under certain conditions
  InvenTree/order/models.py
Labels: bug, order

#3119 Bug fix for part category view
  InvenTree/part/views.py
Labels: bug, user interface

#3120 Return from customer
  InvenTree/InvenTree/api_version.py
  InvenTree/stock/api.py
  InvenTree/stock/forms.py
  InvenTree/stock/models.py
  InvenTree/stock/serializers.py
  InvenTree/stock/templates/stock/item_base.html
  InvenTree/stock/test_api.py
  InvenTree/stock/urls.py
  InvenTree/stock/views.py
Labels: stock, api

#3123 Move PartParameterTemplate model to the API
  InvenTree/InvenTree/api_version.py
  InvenTree/part/api.py
  InvenTree/part/forms.py
  InvenTree/part/urls.py
  InvenTree/part/views.py
  InvenTree/templates/InvenTree/settings/settings.html
Labels: enhancement, part, api

#3125 Bugfix for stockitem serializers
  InvenTree/stock/api.py
Labels: bug, stock, user interface

#3127 Fix behaviour of attachment table for purchase orders
  InvenTree/order/templates/order/purchase_order_detail.html
Labels: user interface

#3130 Convert category parameter forms to use the API
  InvenTree/InvenTree/api_version.py
  InvenTree/part/api.py
  InvenTree/part/forms.py
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/part/test_api.py
  InvenTree/part/urls.py
  InvenTree/part/views.py
  InvenTree/templates/InvenTree/settings/category.html
  InvenTree/templates/InvenTree/settings/settings.html
Labels: api

#3132 Add more checks to pre-commit
  .pre-commit-config.yaml
  InvenTree/InvenTree/api_tester.py
  InvenTree/InvenTree/apps.py
  InvenTree/InvenTree/exchange.py
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/management/commands/rebuild_models.py
  InvenTree/InvenTree/metadata.py
  InvenTree/InvenTree/middleware.py
  InvenTree/InvenTree/models.py
  InvenTree/InvenTree/serializers.py
  InvenTree/InvenTree/tasks.py
  InvenTree/InvenTree/tests.py
  InvenTree/InvenTree/validators.py
  InvenTree/InvenTree/version.py
  InvenTree/InvenTree/views.py
  InvenTree/build/api.py
  InvenTree/build/migrations/0032_auto_20211014_0632.py
  InvenTree/build/models.py
  InvenTree/build/test_api.py
  InvenTree/common/apps.py
  InvenTree/common/files.py
  InvenTree/common/models.py
  InvenTree/common/views.py
  InvenTree/company/views.py
  InvenTree/label/api.py
  InvenTree/label/test_api.py
  InvenTree/order/api.py
  InvenTree/order/migrations/0052_auto_20211014_0631.py
  InvenTree/order/models.py
  InvenTree/part/api.py
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/part/templatetags/inventree_extras.py
  InvenTree/part/test_api.py
  InvenTree/part/test_bom_import.py
  InvenTree/part/test_part.py
  InvenTree/part/views.py
  InvenTree/plugin/apps.py
  InvenTree/plugin/base/integration/mixins.py
  InvenTree/plugin/helpers.py
  InvenTree/plugin/registry.py
  InvenTree/plugin/samples/integration/custom_panel_sample.py
  InvenTree/plugin/templatetags/plugin_extras.py
  InvenTree/report/api.py
  InvenTree/report/apps.py
  InvenTree/stock/api.py
  InvenTree/stock/migrations/0061_auto_20210511_0911.py
  InvenTree/stock/migrations/0069_auto_20211109_2347.py
  InvenTree/stock/models.py
  InvenTree/stock/tests.py
  InvenTree/users/models.py
  ci/check_js_templates.py
  ci/version_check.py
  docker/gunicorn.conf.py
  setup.cfg
  tasks.py
Labels: CI

#3140 Fix has_complete_bom_pricing logic errors
  InvenTree/part/models.py
  InvenTree/part/templates/part/part_pricing.html
  InvenTree/part/templates/part/prices.html
Labels: bug, part, pricing

#3114 Overdue order notification
  InvenTree/InvenTree/apps.py
  InvenTree/build/tasks.py
  InvenTree/build/test_build.py
  InvenTree/common/api.py
  InvenTree/common/models.py
  InvenTree/common/notifications.py
  InvenTree/common/tests.py
  InvenTree/order/tasks.py
  InvenTree/order/test_sales_order.py
  InvenTree/order/tests.py
  InvenTree/part/tasks.py
  InvenTree/part/test_part.py
  InvenTree/plugin/builtin/integration/core_notifications.py
  InvenTree/templates/email/overdue_build_order.html
  InvenTree/templates/email/overdue_purchase_order.html
  InvenTree/templates/email/overdue_sales_order.html
  InvenTree/templates/js/translated/notification.js
Labels: enhancement, order, build

#3142 Fix "polarity" of modal form submit button
  InvenTree/templates/js/translated/forms.js
Labels: bug, user interface

#3141 Separate unit cost and purchase price in BOM
  InvenTree/part/templates/part/part_pricing.html
  InvenTree/part/templates/part/prices.html
Labels: part, pricing

#3146 Adds API mixin for "bulk delete"
  InvenTree/InvenTree/api.py
  InvenTree/InvenTree/api_tester.py
  InvenTree/InvenTree/api_version.py
  InvenTree/build/api.py
  InvenTree/company/api.py
  InvenTree/order/api.py
  InvenTree/part/api.py
  InvenTree/stock/api.py
  InvenTree/stock/templates/stock/item.html
  InvenTree/stock/test_api.py
  InvenTree/templates/js/translated/api.js
  InvenTree/templates/js/translated/attachment.js
  InvenTree/templates/js/translated/bom.js
  InvenTree/templates/js/translated/company.js
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/stock.js
Labels: enhancement, api

#3145 Notification on new orders
  InvenTree/InvenTree/helpers.py
  InvenTree/build/models.py
  InvenTree/build/test_build.py
  InvenTree/common/notifications.py
  InvenTree/order/models.py
  InvenTree/order/test_sales_order.py
  InvenTree/order/tests.py
  InvenTree/templates/email/new_order_assigned.html
Labels: enhancement, order, build

#3152 Simplify version_check script
  .github/workflows/docker.yaml
  .github/workflows/qc_checks.yaml
  ci/version_check.py
Labels: CI

#3154 Adding bulk deletion endpoint for notifications
  InvenTree/InvenTree/api.py
  InvenTree/InvenTree/api_tester.py
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/metadata.py
  InvenTree/InvenTree/test_api.py
  InvenTree/common/api.py
  InvenTree/common/tests.py
  InvenTree/stock/templates/stock/item.html
  InvenTree/stock/test_api.py
  InvenTree/templates/InvenTree/notifications/history.html
  InvenTree/templates/InvenTree/notifications/inbox.html
  InvenTree/templates/InvenTree/notifications/notifications.html
  InvenTree/templates/attachment_table.html
  InvenTree/templates/js/translated/attachment.js
  InvenTree/templates/js/translated/notification.js
  InvenTree/users/fixtures/users.yaml
Labels: bug, api

#3155 Allow build orders to be deleted via the API
  InvenTree/build/api.py
  InvenTree/build/templates/build/build_base.html
  InvenTree/build/templates/build/delete_build.html
  InvenTree/build/test_api.py
  InvenTree/build/urls.py
  InvenTree/build/views.py
Labels: api, build

#3159 Update release.yml
  .github/release.yml
Labels: CI, translation

#3148 SupplierPart availability
  InvenTree/InvenTree/api_version.py
  InvenTree/company/migrations/0044_auto_20220607_2204.py
  InvenTree/company/models.py
  InvenTree/company/serializers.py
  InvenTree/company/templates/company/supplier_part.html
  InvenTree/company/test_api.py
  InvenTree/templates/js/translated/bom.js
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/company.js
  InvenTree/templates/js/translated/helpers.js
  InvenTree/templates/js/translated/stock.js
Labels: enhancement, order, api

#3170 Prevent auto-creation of SalesOrderShipment if we are importing data
  InvenTree/order/models.py
Labels: bug, order

#3171 Adds redis support to production docker-compose
  docker/production/.env
  docker/production/docker-compose.yml
Labels: docker, setup

#3175 Clean up tasks
  tasks.py
Labels: enhancement, setup

#3180 Fix container priority for docker compose recipe
  docker/production/docker-compose.yml
Labels: bug, docker

#3181 Converting more forms to the API
  InvenTree/InvenTree/forms.py
  InvenTree/InvenTree/views.py
  InvenTree/part/templates/part/category.html
  InvenTree/part/templates/part/category_delete.html
  InvenTree/part/urls.py
  InvenTree/part/views.py
  InvenTree/stock/templates/stock/item_base.html
  InvenTree/stock/templates/stock/item_delete.html
  InvenTree/stock/templates/stock/location.html
  InvenTree/stock/templates/stock/location_delete.html
  InvenTree/stock/urls.py
  InvenTree/stock/views.py
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/stock.js
Labels: api

#3179 Add error handling for case where user does not have git installed
  InvenTree/plugin/helpers.py
  InvenTree/plugin/registry.py
Labels: bug, setup

#3174 Sentry
  InvenTree/InvenTree/settings.py
  InvenTree/config_template.yaml
  requirements.txt
Labels: enhancement, CI, setup

#3178 Setting caching
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/urls.py
  InvenTree/common/apps.py
  InvenTree/common/models.py
  InvenTree/common/settings.py
  InvenTree/common/tests.py
  InvenTree/part/test_part.py
  InvenTree/plugin/apps.py
  InvenTree/report/tests.py
Labels: enhancement, api

#3184 Clear cache for more unit tests
  InvenTree/common/tests.py
  InvenTree/report/tests.py
Labels: bug, CI

#3183 Migrate "Convert to Variant" form to the API
  InvenTree/InvenTree/api_version.py
  InvenTree/part/api.py
  InvenTree/part/test_api.py
  InvenTree/stock/api.py
  InvenTree/stock/forms.py
  InvenTree/stock/serializers.py
  InvenTree/stock/templates/stock/item_base.html
  InvenTree/stock/templates/stock/stockitem_convert.html
  InvenTree/stock/test_api.py
  InvenTree/stock/urls.py
  InvenTree/stock/views.py
Labels: enhancement, api

#3190 Add security.md
  SECURITY.md
Labels: security

#3199 Fix sanitization for array case - was missing a return value
  InvenTree/InvenTree/static/script/inventree/inventree.js
Labels: bug, security

#3197 Back porting of security patches
  InvenTree/InvenTree/admin.py
  InvenTree/InvenTree/static/script/inventree/inventree.js
  InvenTree/InvenTree/version.py
  InvenTree/build/admin.py
  InvenTree/company/admin.py
  InvenTree/order/admin.py
  InvenTree/part/admin.py
  InvenTree/stock/admin.py
  InvenTree/templates/js/translated/attachment.js
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/stock.js
  InvenTree/templates/js/translated/tables.js
Labels: security

#3204 more user input sanitation
  InvenTree/InvenTree/api.py
  InvenTree/InvenTree/mixins.py
  InvenTree/build/api.py
  InvenTree/common/api.py
  InvenTree/company/api.py
  InvenTree/label/api.py
  InvenTree/order/api.py
  InvenTree/part/api.py
  InvenTree/plugin/api.py
  InvenTree/report/api.py
  InvenTree/stock/api.py
  InvenTree/users/api.py
Labels: enhancement, api, security

#3205 Sanitize data before displaying in markdown editor
  InvenTree/InvenTree/mixins.py
  InvenTree/templates/js/translated/helpers.js
Labels: security

#3206 Enable "sanitize" option for EasyMDE editor
  InvenTree/InvenTree/version.py
  InvenTree/templates/js/translated/helpers.js
Labels: security

#3208 Label dpi config
  InvenTree/common/models.py
  InvenTree/plugin/base/label/label.py
  InvenTree/templates/InvenTree/settings/label.html
  InvenTree/templates/InvenTree/settings/settings.html
  InvenTree/templates/InvenTree/settings/sidebar.html
  InvenTree/templates/InvenTree/settings/user_labels.html
  InvenTree/templates/base.html
Labels: plugin, report

#3213 Small changes to password changing
  InvenTree/InvenTree/forms.py
  InvenTree/InvenTree/views.py
Labels: enhancement, security

#3214 Auth forms fix
  InvenTree/templates/account/login.html
  InvenTree/templates/account/logout.html
  InvenTree/templates/allauth_2fa/authenticate.html
  InvenTree/templates/allauth_2fa/backup_tokens.html
  InvenTree/templates/allauth_2fa/remove.html
  InvenTree/templates/allauth_2fa/setup.html
  requirements.txt
Labels: user interface

#3185 Part page loading improvements
  InvenTree/InvenTree/context.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/static/bootstrap-table/bootstrap-table.min.css
  InvenTree/InvenTree/static/bootstrap-table/bootstrap-table.min.js
  InvenTree/InvenTree/static/css/inventree.css
  InvenTree/InvenTree/static/fullcalendar/locales-all.js
  InvenTree/InvenTree/static/fullcalendar/locales-all.min.js
  InvenTree/InvenTree/static/fullcalendar/locales/bn.js
  InvenTree/InvenTree/static/fullcalendar/locales/de-at.js
  InvenTree/InvenTree/static/fullcalendar/locales/de.js
  InvenTree/InvenTree/static/fullcalendar/locales/en-au.js
  InvenTree/InvenTree/static/fullcalendar/locales/en-gb.js
  InvenTree/InvenTree/static/fullcalendar/locales/en-nz.js
  InvenTree/InvenTree/static/fullcalendar/locales/es.js
  InvenTree/InvenTree/static/fullcalendar/locales/hu.js
  InvenTree/InvenTree/static/fullcalendar/locales/km.js
  InvenTree/InvenTree/static/fullcalendar/locales/ku.js
  InvenTree/InvenTree/static/fullcalendar/locales/nb.js
  InvenTree/InvenTree/static/fullcalendar/locales/si-lk.js
  InvenTree/InvenTree/static/fullcalendar/locales/sm.js
  InvenTree/InvenTree/static/fullcalendar/locales/sv.js
  InvenTree/InvenTree/static/fullcalendar/locales/ta-in.js
  InvenTree/InvenTree/static/fullcalendar/main.css
  InvenTree/InvenTree/static/fullcalendar/main.js
  InvenTree/InvenTree/static/fullcalendar/main.min.css
  InvenTree/InvenTree/static/fullcalendar/main.min.js
  InvenTree/InvenTree/static/script/inventree/inventree.js
  InvenTree/InvenTree/test_views.py
  InvenTree/InvenTree/urls.py
  InvenTree/InvenTree/views.py
  InvenTree/build/templates/build/build_base.html
  InvenTree/company/models.py
  InvenTree/company/templates/company/company_base.html
  InvenTree/company/templates/company/manufacturer_part.html
  InvenTree/company/templates/company/supplier_part.html
  InvenTree/part/filters.py
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/part/templates/part/detail.html
  InvenTree/part/templates/part/part_thumb.html
  InvenTree/stock/api.py
  InvenTree/stock/serializers.py
  InvenTree/stock/templates/stock/item_base.html
  InvenTree/templates/about.html
  InvenTree/templates/account/base.html
  InvenTree/templates/base.html
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/page_base.html
  InvenTree/templates/skeleton.html
  InvenTree/templates/third_party_js.html
  InvenTree/users/models.py
Labels: enhancement, user interface

#3217 Update django-allauth to 0.48.0
  InvenTree/InvenTree/settings.py
  requirements.txt
Labels: security

#3218 Fix API endpoint permission for the "AttachmentMixin" class
  InvenTree/InvenTree/api.py
  InvenTree/templates/attachment_table.html
  InvenTree/templates/js/translated/attachment.js
  InvenTree/users/models.py
Labels: bug, api, security

#3219 Hide buttons for users without required permissions
  InvenTree/build/templates/build/detail.html
  InvenTree/part/templates/part/detail.html
  InvenTree/stock/templates/stock/item.html
Labels: bug, user interface

#3221 Only enable browsable API if in debug mode
  InvenTree/InvenTree/settings.py
Labels: api

#3222 Adds a simple unit test to ensure that bleach is running on API data
  InvenTree/part/test_api.py
Labels: api, CI

#3223 Small UI improvements to the settings interface
  InvenTree/templates/InvenTree/settings/user.html
  InvenTree/templates/InvenTree/settings/user_display.html
Labels: user interface

#3225 Sales order tables
  InvenTree/build/templates/build/detail.html
  InvenTree/order/templates/order/sales_order_detail.html
  InvenTree/templates/collapse_rows.html
  InvenTree/templates/expand_rows.html
  InvenTree/templates/js/translated/order.js
Labels: user interface

#3231 Remove reliance on django-markdownx
  InvenTree/InvenTree/fields.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/static/css/color-themes/dark-reader.css
  InvenTree/InvenTree/static/css/inventree.css
  InvenTree/InvenTree/urls.py
  InvenTree/build/migrations/0008_auto_20200201_1247.py
  InvenTree/build/migrations/0014_auto_20200425_1243.py
  InvenTree/build/migrations/0035_alter_build_notes.py
  InvenTree/build/models.py
  InvenTree/company/migrations/0010_auto_20200201_1231.py
  InvenTree/company/migrations/0032_auto_20210403_1837.py
  InvenTree/company/migrations/0045_alter_company_notes.py
  InvenTree/company/models.py
  InvenTree/order/migrations/0015_auto_20200201_2346.py
  InvenTree/order/migrations/0020_auto_20200420_0940.py
  InvenTree/order/migrations/0044_auto_20210404_2016.py
  InvenTree/order/migrations/0053_salesordershipment.py
  InvenTree/order/migrations/0070_auto_20220620_0728.py
  InvenTree/order/models.py
  InvenTree/part/migrations/0026_auto_20200131_1022.py
  InvenTree/part/migrations/0029_auto_20200223_0901.py
  InvenTree/part/migrations/0048_auto_20200902_1404.py
  InvenTree/part/migrations/0061_auto_20210103_2313.py
  InvenTree/part/migrations/0079_alter_part_notes.py
  InvenTree/part/models.py
  InvenTree/part/test_api.py
  InvenTree/stock/migrations/0018_auto_20200202_0103.py
  InvenTree/stock/migrations/0020_auto_20200206_1213.py
  InvenTree/stock/migrations/0034_auto_20200426_0602.py
  InvenTree/stock/migrations/0077_alter_stockitem_notes.py
  InvenTree/stock/models.py
  requirements.txt
Labels: security

#3235 Prevent calculation of 'allocation_count' before model is saved
  InvenTree/part/models.py
Labels: bug, part, importer

#3238 Small visual tweaks to various auth views
  InvenTree/templates/account/email_confirm.html
  InvenTree/templates/allauth_2fa/authenticate.html
Labels: user interface

#3239 MFA remove improvement
  InvenTree/InvenTree/forms.py
  InvenTree/InvenTree/urls.py
  InvenTree/InvenTree/views.py
  requirements.txt
Labels: enhancement, security

#3240 Override 2FA token removal form
  InvenTree/InvenTree/forms.py
  InvenTree/InvenTree/urls.py
  InvenTree/InvenTree/views.py
  requirements.txt
Labels: security

#3243 Fix thumbnail command
  InvenTree/InvenTree/management/commands/rebuild_thumbnails.py
Labels: bug

#3242 Prevent newline characters from breaking part page rendering
  InvenTree/part/templates/part/detail.html
Labels: bug, user interface

#3245 Prevent newline chars from breaking part detail page
  InvenTree/part/templates/part/detail.html
Labels: bug, user interface

#3244 CI unit test fixes
  InvenTree/InvenTree/test_api.py
Labels: bug, api, CI

#3249 Prevent write of SERVER_RESTART_REQUIRED setting when importing dataset
  InvenTree/common/apps.py
  InvenTree/common/models.py
Labels: bug

#3250 Remove custom javascript from auth pages
  InvenTree/InvenTree/static/script/inventree/inventree.js
  InvenTree/InvenTree/static/script/inventree/message.js
  InvenTree/templates/account/base.html
  InvenTree/templates/base.html
  InvenTree/templates/js/translated/notification.js
  InvenTree/templates/skeleton.html
Labels: bug, user interface

#3246 Fix translation issue with javascript
  .github/workflows/qc_checks.yaml
  InvenTree/InvenTree/settings.py
  InvenTree/part/templatetags/i18n.py
Labels: bug, user interface, CI

#3253 Exchange backend fix
  InvenTree/InvenTree/exchange.py
Labels: bug

#3255 Notify users when a build order is completed
  InvenTree/build/models.py
  InvenTree/common/notifications.py
  InvenTree/templates/email/build_order_completed.html
Labels: enhancement, build

#3258 Bug fix for field validation on child forms
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/model_renderers.js
Labels: bug, user interface

#3260 Adds a template for handling 403 errors due to CSRF issues
  InvenTree/templates/403_csrf.html
Labels: user interface

#3259 Adds notification when items are received against a purcahse order
  InvenTree/common/notifications.py
  InvenTree/order/models.py
  InvenTree/templates/email/purchase_order_received.html
Labels: enhancement

#3263 [BUG] Duplication of "base URL" setting
  InvenTree/InvenTree/tests.py
  InvenTree/common/models.py
  InvenTree/common/tests.py
Labels: enhancement, setup

#3265 Virtual part fix
  InvenTree/company/templates/company/detail.html
  InvenTree/order/migrations/0071_auto_20220628_0133.py
  InvenTree/order/models.py
  InvenTree/part/templates/part/detail.html
  InvenTree/stock/models.py
  InvenTree/stock/serializers.py
  InvenTree/templates/js/translated/table_filters.js
Labels: bug, order, stock

#3266 Docker requirements update
  .github/workflows/docker.yaml
  docker/requirements.txt
Labels: CI, docker

#3232 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3228 Update requirements
  .github/actions/setup/action.yaml
  .github/workflows/qc_checks.yaml
  .pre-commit-config.yaml
  InvenTree/InvenTree/serializers.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/urls.py
  InvenTree/build/api.py
  InvenTree/common/api.py
  InvenTree/company/api.py
  InvenTree/company/migrations/0046_alter_company_image.py
  InvenTree/label/api.py
  InvenTree/order/api.py
  InvenTree/part/api.py
  InvenTree/part/migrations/0080_alter_part_image.py
  InvenTree/plugin/api.py
  InvenTree/report/api.py
  InvenTree/stock/api.py
  InvenTree/stock/serializers.py
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
  tasks.py
Labels: CI, dependency, security

#3268 Change the default serialization level for postgresql DB
  InvenTree/InvenTree/settings.py
Labels: setup, breaking

#3271 Part API Filter Fix
  InvenTree/part/api.py
  InvenTree/part/test_api.py
Labels: bug, part, api

#3272 Add confirmation for "over-allocated" stock when completing BuildOrder
  InvenTree/build/models.py
  InvenTree/build/serializers.py
  InvenTree/templates/js/translated/build.js
Labels: build

#3273 Pin django-stdimage to sub 6.0.0
  InvenTree/InvenTree/tasks.py
  InvenTree/InvenTree/tests.py
  requirements.in
  requirements.txt
Labels: bug, setup
