Repository inventree/InvenTree, pull requests merged in 2022-12, with the labels that each got.

#4007 Add 1D barcode support to browser webcam scanner
  InvenTree/InvenTree/static/css/inventree.css
  InvenTree/InvenTree/static/script/html5-qrcode.min.js
  InvenTree/InvenTree/static/script/qr-scanner-worker.min.js
  InvenTree/InvenTree/static/script/qr-scanner.min.js.map
  InvenTree/InvenTree/static/script/qr-scanner.umd.min.js
  InvenTree/InvenTree/static/script/qr-scanner.umd.min.js.map
  InvenTree/part/templates/part/part_base.html
  InvenTree/templates/js/translated/barcode.js
  InvenTree/templates/third_party_js.html
Labels: enhancement, user interface, barcode

#4014 Test for docker workflow
  .github/workflows/docker.yaml
  InvenTree/common/models.py
Labels: bug, CI, docker

#4018 Fix to return a boolean value
  InvenTree/common/models.py
Labels: bug, CI, docker

#4010 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#4025 Tweak how "submit" button gets hidden
  InvenTree/templates/js/translated/modals.js
  InvenTree/templates/js/translated/order.js
Labels: bug, user interface

#4031 Improvements for docker / gunicorn
  InvenTree/common/tasks.py
  InvenTree/label/apps.py
  docker/gunicorn.conf.py
  docker/init.sh
  docker/requirements.txt
Labels: docker, setup

#4032 Fix for plugin setting not working:
  InvenTree/plugin/api.py
Labels: bug, plugin, api

#4021 Debug for docker workflow
  .github/workflows/docker.yaml
  tasks.py
Labels: bug, CI, docker

#4035 gunicorn: revert support for gevent
  docker/gunicorn.conf.py
  docker/requirements.txt
Labels: CI, docker

#4043 L10 merge fix
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3986 Add unit test for deleting part which has pricing information
  .gitignore
  InvenTree/company/models.py
  InvenTree/order/models.py
  InvenTree/part/models.py
  InvenTree/part/test_api.py
  InvenTree/part/test_pricing.py
Labels: bug, part, pricing

#4054 L10 crowdin
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#4063 Use supplier part pack size for scheduling
  InvenTree/part/api.py
Labels: bug

#4061 Import setuptools in manage.py
  .github/workflows/docker.yaml
  docker/requirements.txt
Labels: CI, docker

#4059 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#4075 Fix pricing bug for automated updates
  InvenTree/part/tasks.py
Labels: bug, pricing

#4076 Save newly created pricing object
  InvenTree/part/tasks.py
Labels: bug, pricing

#4077 Load plugins for collectstatic
  InvenTree/InvenTree/ready.py
Labels: plugin

#4078 Load plugins for collectstatic (#4077)
  InvenTree/InvenTree/ready.py
Labels: plugin

#4080 Unit test for part pricing background task
  InvenTree/part/test_pricing.py
Labels: CI, pricing

#4070 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#4081 Enable rendering of table in Notes markdown into reports
  InvenTree/InvenTree/settings.py
Labels: report

#4065 UrlsMixin plugin update custom urls on load
  InvenTree/plugin/registry.py
Labels: plugin

#4090 Control build allocation of optional BOM items
  InvenTree/build/models.py
  InvenTree/build/serializers.py
  InvenTree/build/test_build.py
  InvenTree/templates/js/translated/build.js
Labels: build

#4083 List PO/SO/BO by reference in API
  InvenTree/InvenTree/api_version.py
  InvenTree/build/api.py
  InvenTree/build/test_api.py
  InvenTree/order/api.py
  InvenTree/order/test_api.py
Labels: enhancement, order, api

#4091 Serial number autofill
  InvenTree/common/models.py
  InvenTree/templates/InvenTree/settings/stock.html
  InvenTree/templates/js/translated/stock.js
Labels: stock, user interface

#4092 Use github token for version check
  .github/workflows/release.yml
  InvenTree/InvenTree/tasks.py
  ci/version_check.py
Labels: CI

#3858 Calendar export
  InvenTree/InvenTree/api_tester.py
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/settings.py
  InvenTree/order/api.py
  InvenTree/order/test_api.py
  requirements.in
  requirements.txt
Labels: enhancement, order, api

#4089 Fix stock location structural check
  InvenTree/part/models.py
  InvenTree/stock/models.py
Labels: bug, part, stock

#4095 Fix stock location structural check (#4089)
  InvenTree/part/models.py
  InvenTree/stock/models.py
Labels: bug

#4093 Replaced include tag with included files content
  InvenTree/order/templates/order/order_wizard/match_fields.html
  InvenTree/order/templates/order/order_wizard/po_upload.html
Labels: bug, user interface

#4094 Use GITHUB_TOKEN for API unit test
  InvenTree/plugin/base/integration/test_mixins.py
Labels: CI

#4098 Replace include tag by the files contents (#4093)
  InvenTree/order/templates/order/order_wizard/match_fields.html
  InvenTree/order/templates/order/order_wizard/po_upload.html
Labels: bug, user interface

#4100 Remove breaking test in CI
  InvenTree/plugin/base/integration/test_mixins.py
Labels: CI

#4082 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#4107 Test fix for ongoing CI issues
  InvenTree/plugin/base/integration/mixins.py
Labels: CI

#4109 [Testing] Fix docker build
  .github/workflows/docker.yaml
  InvenTree/plugin/base/integration/mixins.py
Labels: CI, docker

#4117 Change overflow property in order to fix horizontal scrolling (Fix #3569)
  InvenTree/InvenTree/static/css/inventree.css
Labels: user interface

#4118 docker venv fix
  docker/init.sh
Labels: docker

#4119 Change overflow property in order to fix horizontal scrolling (#4117)
  InvenTree/InvenTree/static/css/inventree.css
Labels: user interface

#4120 Parameters table fix
  InvenTree/templates/js/translated/part.js
Labels: user interface

#4121 Parameters table fix (#4120)
  InvenTree/templates/js/translated/part.js
Labels: user interface

#4124 Fix for SOCIALACCOUNT_PROVIDERS
  InvenTree/InvenTree/settings.py
  InvenTree/config_template.yaml
  InvenTree/templates/account/base.html
  InvenTree/templates/account/login.html
  InvenTree/templates/socialaccount/snippets/provider_list.html
Labels: bug, setup

#4069 Part stocktake
  InvenTree/InvenTree/api_version.py
  InvenTree/build/templates/build/detail.html
  InvenTree/common/models.py
  InvenTree/part/admin.py
  InvenTree/part/api.py
  InvenTree/part/migrations/0091_partstocktake.py
  InvenTree/part/migrations/0092_part_last_stocktake.py
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/part/templates/part/detail.html
  InvenTree/part/templates/part/part_base.html
  InvenTree/part/templates/part/part_sidebar.html
  InvenTree/part/templates/part/part_stocktake.html
  InvenTree/part/templatetags/inventree_extras.py
  InvenTree/part/test_api.py
  InvenTree/part/test_part.py
  InvenTree/templates/InvenTree/settings/user_display.html
  InvenTree/templates/js/translated/attachment.js
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/stock.js
  InvenTree/templates/js/translated/table_filters.js
  InvenTree/users/models.py
Labels: enhancement, part, api

#4129 Catch potential issues when importing data
  InvenTree/part/models.py
Labels: bug, importer

#4128 Create missing entries for default reports
  InvenTree/report/apps.py
  InvenTree/report/templates/report/inventree_bill_of_materials_report.html
Labels: report

#4108 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#4131 Create missing entries for default reports (#4128)
  InvenTree/report/apps.py
  InvenTree/report/templates/report/inventree_bill_of_materials_report.html
Labels: bug, report

#4130 Catch potential issues when importing data
  InvenTree/part/models.py
Labels: bug, importer

#4114 [FR] Slack notifications & notification method updates
  InvenTree/common/notifications.py
  InvenTree/plugin/base/integration/mixins.py
  InvenTree/plugin/builtin/integration/core_notifications.py
  InvenTree/plugin/mixins/__init__.py
  InvenTree/plugin/templatetags/plugin_extras.py
  InvenTree/templates/InvenTree/settings/mixins/settings_content.html
  InvenTree/templates/InvenTree/settings/notifications.html
  InvenTree/templates/InvenTree/settings/plugin_settings.html
  InvenTree/templates/InvenTree/settings/settings.html
  InvenTree/templates/InvenTree/settings/sidebar.html
Labels: enhancement, plugin, api
