Repository inventree/InvenTree, pull requests merged in 2022-07, with the labels that each got.

#3275 Allows sorting of attachments by 'upload date'
  InvenTree/templates/js/translated/attachment.js
  InvenTree/templates/js/translated/tables.js
Labels: user interface

#3277 Adds admin-configurability for sentry sample rate
  InvenTree/InvenTree/settings.py
Labels: setup

#3278 Allow supplier parts to be search by part.keywords field
  InvenTree/company/api.py
Labels: api

#3276 Fixes for broken CI builds
  .github/workflows/docker.yaml
  .github/workflows/qc_checks.yaml
Labels: bug, CI

#3279 Docker: Use existing task definition
  .github/workflows/docker.yaml
Labels: CI, docker

#3280 Requirements fix
  requirements-dev.in
  requirements-dev.txt
Labels: CI, docker

#3283 BREAKING: Remove old classes
  InvenTree/plugin/__init__.py
  InvenTree/plugin/plugin.py
  InvenTree/plugin/test_plugin.py
Labels: plugin, breaking

#3281 [FR] Add unit testing for emails
  InvenTree/plugin/builtin/integration/test_core_notifications.py
Labels: enhancement, CI

#3285 Update package requirements for docker
  Dockerfile
  requirements.in
  requirements.txt
Labels: CI, docker

#3286 Use modern configuration for django-markdownify
  InvenTree/InvenTree/settings.py
Labels: setup

#3288 Fix spelling error
  InvenTree/templates/InvenTree/settings/plugin.html
Labels: translation

#3269 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3289 Fix table sorting issues
  InvenTree/templates/js/translated/attachment.js
  InvenTree/templates/js/translated/tables.js
Labels: bug, user interface

#3290 Optionally show/hide the "accept_overallocated" dialog option
  InvenTree/build/models.py
  InvenTree/build/templates/build/build_base.html
  InvenTree/templates/js/translated/build.js
Labels: user interface, build

#3295 Bug fix for sales order allocation table
  InvenTree/order/serializers.py
  InvenTree/templates/js/translated/order.js
Labels: order, user interface

#3296 Allow searching of BOM List API endpoint
  InvenTree/InvenTree/api_version.py
  InvenTree/part/api.py
  InvenTree/part/fixtures/bom.yaml
  InvenTree/part/test_api.py
Labels: part, api

#3299 Bump django version
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: security

#3301 Allow BOM table to be filtered by "stock available" parameter
  InvenTree/InvenTree/api_version.py
  InvenTree/part/api.py
  InvenTree/templates/js/translated/table_filters.js
Labels: part, api

#3303 Use python executable we were invoked with
  tasks.py
Labels: setup

#3309 Revert "Use python executable we were invoked with"
  tasks.py
Labels: docker

#3310 BOM Table Improvements
  InvenTree/InvenTree/api_version.py
  InvenTree/part/api.py
  InvenTree/part/serializers.py
  InvenTree/stock/templates/stock/item.html
  InvenTree/templates/InvenTree/notifications/notifications.html
  InvenTree/templates/js/translated/attachment.js
  InvenTree/templates/js/translated/bom.js
  InvenTree/templates/js/translated/company.js
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/table_filters.js
Labels: enhancement, user interface, api

#3311 Allow negative currency values for "extra" line items
  InvenTree/InvenTree/fields.py
  InvenTree/order/models.py
Labels: order, pricing

#3313 Make "confirm" buttons a user-configurable option.
  InvenTree/common/models.py
  InvenTree/templates/InvenTree/settings/global.html
  InvenTree/templates/js/translated/forms.js
Labels: enhancement, user interface

#3314 Fix broken copy
  InvenTree/InvenTree/static/script/clipboard.min.js
  InvenTree/InvenTree/static/script/inventree/inventree.js
  InvenTree/templates/about.html
Labels: bug, dependency

#3282 Use metadata in projects for plugin info
  InvenTree/plugin/plugin.py
  InvenTree/plugin/registry.py
Labels: enhancement, plugin

#3316 [FR] Automated releases
  .github/workflows/release.yml
Labels: enhancement, CI

#3267 Reference fields
  InvenTree/InvenTree/api_tester.py
  InvenTree/InvenTree/format.py
  InvenTree/InvenTree/models.py
  InvenTree/InvenTree/serializers.py
  InvenTree/InvenTree/tests.py
  InvenTree/InvenTree/validators.py
  InvenTree/build/fixtures/build.yaml
  InvenTree/build/migrations/0019_auto_20201019_1302.py
  InvenTree/build/migrations/0030_alter_build_reference.py
  InvenTree/build/migrations/0036_auto_20220707_1101.py
  InvenTree/build/models.py
  InvenTree/build/serializers.py
  InvenTree/build/test_api.py
  InvenTree/build/test_build.py
  InvenTree/build/test_migrations.py
  InvenTree/build/tests.py
  InvenTree/build/validators.py
  InvenTree/common/models.py
  InvenTree/order/fixtures/order.yaml
  InvenTree/order/migrations/0048_auto_20210702_2321.py
  InvenTree/order/migrations/0072_alter_salesorder_reference.py
  InvenTree/order/migrations/0073_alter_purchaseorder_reference.py
  InvenTree/order/migrations/0074_auto_20220709_0108.py
  InvenTree/order/models.py
  InvenTree/order/serializers.py
  InvenTree/order/templates/order/order_base.html
  InvenTree/order/templates/order/sales_order_base.html
  InvenTree/order/test_api.py
  InvenTree/order/test_sales_order.py
  InvenTree/order/tests.py
  InvenTree/order/validators.py
  InvenTree/part/test_api.py
  InvenTree/report/models.py
  InvenTree/stock/models.py
  InvenTree/stock/serializers.py
  InvenTree/stock/tests.py
  InvenTree/templates/InvenTree/settings/build.html
  InvenTree/templates/InvenTree/settings/po.html
  InvenTree/templates/InvenTree/settings/so.html
  InvenTree/templates/js/translated/bom.js
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/model_renderers.js
  InvenTree/templates/js/translated/order.js
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/stock.js
Labels: enhancement, order, api, build, breaking

#3319 Prevent creation of new settings objects when importing data
  InvenTree/common/models.py
Labels: bug

#3300 Remove custom 2FA code
  InvenTree/InvenTree/forms.py
  InvenTree/InvenTree/views.py
  requirements.txt
Labels: security

#3328 Update unit tests for API plugin mixin class
  InvenTree/InvenTree/settings.py
  InvenTree/plugin/base/integration/mixins.py
  InvenTree/plugin/base/integration/test_mixins.py
Labels: bug, CI

#3325 Migration bug fix
  InvenTree/InvenTree/settings.py
  InvenTree/build/migrations/0032_auto_20211014_0632.py
  InvenTree/order/migrations/0052_auto_20211014_0631.py
  InvenTree/order/test_migrations.py
  InvenTree/plugin/base/integration/mixins.py
  InvenTree/plugin/base/integration/test_mixins.py
  InvenTree/stock/migrations/0069_auto_20211109_2347.py
  InvenTree/stock/test_migrations.py
Labels: bug

#3333 Specify upper bound for mariadb python version
  docker/requirements.txt
Labels: bug, docker, setup

#3335 Annotate "in_stock" quantity to SupplierPart API
  InvenTree/InvenTree/api_version.py
  InvenTree/company/api.py
  InvenTree/company/serializers.py
  InvenTree/templates/js/translated/company.js
Labels: enhancement, api

#3336 Bug fix for recent SupplierPart API annotation
  InvenTree/company/serializers.py
  InvenTree/stock/migrations/0078_alter_stockitem_supplier_part.py
  InvenTree/stock/models.py
Labels: bug, api

#3346 Fix POST testing
  InvenTree/plugin/base/integration/test_mixins.py
Labels: CI

#3349 Fix pre-commit complaints
  InvenTree/build/models.py
Labels: CI

#3350 Use env-variable for image tag on docker-compose deployments
  docker/production/.env
  docker/production/docker-compose.yml
Labels: enhancement, docker, setup

#3351 docker: prevent ports being exposed outside container context
  docker-compose.yml
  docker/production/docker-compose.yml
Labels: docker, security

#3356 Fix API filtering for PurchaseOrderLineItem
  InvenTree/order/api.py
Labels: bug, api

#3357 Docker compose plugins fix
  Dockerfile
  docker-compose.yml
  docker/production/.env
Labels: bug, CI, docker

#3360 Update unit tests to match new docker paths
  InvenTree/InvenTree/tests.py
  tasks.py
Labels: bug, CI, docker

#3361 Create SupplierPart directly from PurchaseOrderLineItem dialog
  InvenTree/order/templates/order/purchase_order_detail.html
  InvenTree/templates/js/translated/company.js
  InvenTree/templates/js/translated/model_renderers.js
  InvenTree/templates/js/translated/order.js
Labels: enhancement, user interface

#3347 [FR] Sign artifacts with sigstore
  .github/workflows/docker.yaml
Labels: enhancement, CI, docker, security

#3363 Fix for docker signing
  .github/workflows/docker.yaml
Labels: bug, CI, docker

#3370 Remove special characters restriction in category names
  InvenTree/InvenTree/models.py
  InvenTree/InvenTree/validators.py
  InvenTree/part/migrations/0081_alter_partcategory_name.py
  InvenTree/part/test_category.py
  InvenTree/stock/migrations/0079_alter_stocklocation_name.py
Labels: enhancement, part

#3376 Fix API filtering for PurchaseOrderLineItem (#3356)
  InvenTree/order/api.py
Labels: bug, api

#3378 Handle exception when path is not relative to base path
  InvenTree/plugin/plugin.py
Labels: bug, plugin

#3377 Refactor template helpers for displaying uploaded images
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/tests.py
  InvenTree/company/models.py
  InvenTree/part/templatetags/inventree_extras.py
  InvenTree/report/models.py
  InvenTree/report/templates/report/inventree_build_order_base.html
  InvenTree/report/templatetags/barcode.py
  InvenTree/report/templatetags/report.py
  InvenTree/report/tests.py
Labels: enhancement, report

#3387 Use different twitter action
  .github/workflows/release.yml
Labels: CI

#3393 Refctor image downloader
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/serializers.py
  InvenTree/InvenTree/tests.py
  InvenTree/InvenTree/views.py
  InvenTree/common/models.py
  InvenTree/company/forms.py
  InvenTree/company/serializers.py
  InvenTree/company/templates/company/company_base.html
  InvenTree/company/urls.py
  InvenTree/company/views.py
  InvenTree/part/forms.py
  InvenTree/part/serializers.py
  InvenTree/part/templates/part/part_base.html
  InvenTree/part/urls.py
  InvenTree/part/views.py
  InvenTree/templates/InvenTree/settings/global.html
  InvenTree/templates/image_download.html
Labels: enhancement, api, breaking

#3394 Fix LabelPrintingMixin label_instance contains now specific data
  InvenTree/label/api.py
Labels: bug, plugin, report

#3395 Pre-fill quantity on part ordering form
  InvenTree/InvenTree/api_version.py
  InvenTree/part/api.py
  InvenTree/templates/js/translated/order.js
Labels: enhancement, order, api

#3315 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3399 Correct the docstring for PurchaseOrderIssue
  InvenTree/order/api.py
Labels: api

#3402 Make sure PIP is upgraded to latest version
  tasks.py
Labels: bug, setup

#3364 Allow plugin loading from external directory
  InvenTree/InvenTree/settings.py
  InvenTree/plugin/helpers.py
  InvenTree/plugin/plugin.py
  InvenTree/plugin/registry.py
Labels: plugin, setup

#3406 Remove references to "plugins" volume in production docker-compose file
  docker/production/docker-compose.yml
Labels: docker, setup

#3410 Docker compose relative path
  .github/workflows/docker.yaml
  InvenTree/plugin/registry.py
  docker-compose.yml
  docker/production/docker-compose.yml
Labels: bug, CI, docker, setup

#3414 [BUG] Extra url schemes not working.
  InvenTree/InvenTree/fields.py
  InvenTree/InvenTree/serializers.py
Labels: bug, part, api

#3392 Switch to pathlib
  .gitpod.yml
  InvenTree/InvenTree/config.py
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/models.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/tests.py
  InvenTree/InvenTree/views.py
  InvenTree/common/views.py
  InvenTree/label/apps.py
  InvenTree/label/models.py
  InvenTree/label/tests.py
  InvenTree/part/views.py
  InvenTree/plugin/helpers.py
  InvenTree/plugin/registry.py
  InvenTree/plugin/serializers.py
  InvenTree/report/apps.py
  InvenTree/report/models.py
  InvenTree/report/templatetags/report.py
  InvenTree/report/tests.py
  tasks.py
Labels: enhancement, dependency

#3417 Allow SupplierPart list to be filtered by SKU
  InvenTree/InvenTree/api_version.py
  InvenTree/company/api.py
Labels: enhancement, api

#3416 docker: disable redis image by default
  docker/production/.env
  docker/production/docker-compose.yml
Labels: docker

#3419 Fixes bug introduced by moving to pathlib
  InvenTree/InvenTree/test_views.py
  InvenTree/InvenTree/views.py
  InvenTree/templates/InvenTree/settings/user.html
Labels: bug, user interface

#3405 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3422 Fix "part" column sorting in BOM table
  InvenTree/templates/js/translated/bom.js
Labels: bug

#3423 Convert PosixPath to string for plugin loading
  InvenTree/plugin/registry.py
Labels: bug, plugin

#3425 Fix version-copy button according to #3373
  InvenTree/InvenTree/static/script/inventree/inventree.js
Labels: bug

#3426 Fit for unit test
  InvenTree/InvenTree/tests.py
  InvenTree/common/tests.py
Labels: bug, CI

#3413 Development improvements
  CONTRIBUTING.md
  tasks.py
Labels: enhancement, setup

#3427 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3429 Simplification of development docker-compose file
  .gitignore
  CONTRIBUTING.md
  docker-compose.yml
  docker.dev.env
  docker/production/docker-compose.yml
  tasks.py
Labels: docker, setup

#3434 Fix for docker-compose v1
  docker-compose.yml
  docker/production/docker-compose.yml
Labels: bug, CI, docker

#3439 Add no cov to settings
  InvenTree/InvenTree/settings.py
Labels: enhancement, CI

#3436 [FR] Don't log 404 errors
  InvenTree/InvenTree/exceptions.py
  InvenTree/InvenTree/middleware.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/test_middleware.py
Labels: enhancement, CI

#3431 Add links to all notifications that do not have a link
  InvenTree/InvenTree/models.py
  InvenTree/common/serializers.py
Labels: enhancement

#3440 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3441 Update demo data hook to copy media files
  .gitignore
  CONTRIBUTING.md
  InvenTree/InvenTree/apps.py
  InvenTree/InvenTree/config.py
  InvenTree/InvenTree/exceptions.py
  InvenTree/InvenTree/middleware.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/test_middleware.py
  InvenTree/common/migrations/0010_migrate_currency_setting.py
  InvenTree/config_template.yaml
  InvenTree/plugin/registry.py
  docker/requirements.txt
  tasks.py
Labels: setup
