Repository inventree/InvenTree, pull requests merged in 2022-10, with the labels that each got.

#3737 Show placeholder for null IPN values in "stock" table
  InvenTree/templates/js/translated/stock.js
Labels: user interface

#3742 Remove broken action
  .github/workflows/welcome.yml
Labels: CI

#3744 Update pre-commit
  .pre-commit-config.yaml
Labels: dependency

#3752 Adds 'status_text' functions to models
  InvenTree/build/models.py
  InvenTree/order/models.py
  InvenTree/stock/models.py
Labels: report

#3751 UI fixes for barcode actions
  InvenTree/templates/js/translated/barcode.js
Labels: bug, user interface, barcode

#3754 Fixes #3514
  InvenTree/part/templates/part/detail.html
Labels: user interface

#3760 Bug fix for boolean settings
  InvenTree/templates/InvenTree/settings/setting.html
  InvenTree/templates/InvenTree/settings/setting_boolean.html
  InvenTree/templates/InvenTree/settings/settings.html
Labels: bug, user interface

#3763 Allow auto-loading of plugins in certain conditions
  InvenTree/InvenTree/ready.py
  InvenTree/plugin/apps.py
Labels: bug, plugin

#3762 Allow auto-loading of plugins in certain conditions
  InvenTree/InvenTree/ready.py
  InvenTree/plugin/apps.py
Labels: bug, plugin

#3761 Settings panel bug fix
  InvenTree/templates/InvenTree/settings/setting.html
  InvenTree/templates/InvenTree/settings/setting_boolean.html
  InvenTree/templates/InvenTree/settings/settings.html
Labels: bug, user interface

#3768 Plugin load fix
  InvenTree/plugin/helpers.py
  InvenTree/plugin/plugin.py
  InvenTree/templates/InvenTree/settings/plugin_settings.html
Labels: bug, plugin

#3769 Fix for allowing plugins without explicit metadata
  InvenTree/plugin/helpers.py
  InvenTree/plugin/plugin.py
  InvenTree/templates/InvenTree/settings/plugin_settings.html
Labels: bug, plugin

#3771 Display build output status code
  InvenTree/templates/js/translated/build.js
Labels: build

#3765 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3779 Save language settings for 30 days
  InvenTree/InvenTree/settings.py
Labels: bug, translation

#3782 Update deps to newest releases
  requirements-dev.txt
  requirements.txt
Labels: dependency, security

#3772 Check user permissions before linking or un-linking barcodes
  InvenTree/InvenTree/api_version.py
  InvenTree/plugin/base/barcodes/api.py
  InvenTree/plugin/base/barcodes/test_barcode.py
  InvenTree/plugin/builtin/barcodes/test_inventree_barcode.py
Labels: api, security

#3777 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3743 Add package-based install method
  .github/CODEOWNERS
  .pkgr.yml
  InvenTree/InvenTree/config.py
  InvenTree/config_template.yaml
  Procfile
  README.md
  contrib/install.sh
  contrib/packager.io/functions.sh
  contrib/packager.io/postinstall.sh
  runtime.txt
Labels: enhancement, security, setup

#3783 Add db an media backups
  .devcontainer/devcontainer.json
  .github/workflows/check_translations.yaml
  .github/workflows/qc_checks.yaml
  .github/workflows/translations.yml
  .gitpod.yml
  .pkgr.yml
  Dockerfile
  InvenTree/InvenTree/apps.py
  InvenTree/InvenTree/config.py
  InvenTree/InvenTree/ready.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/tasks.py
  InvenTree/config_template.yaml
  contrib/packager.io/functions.sh
  docker/init.sh
  requirements.in
  requirements.txt
  tasks.py
Labels: enhancement, roadmap, setup

#3790 Switch to registry for tasks
  InvenTree/InvenTree/apps.py
  InvenTree/InvenTree/tasks.py
  InvenTree/build/tasks.py
  InvenTree/common/tasks.py
  InvenTree/order/tasks.py
Labels: enhancement

#3800 Reduce duplication in plugin testing
  InvenTree/InvenTree/api_tester.py
  InvenTree/common/tests.py
  InvenTree/plugin/test_api.py
Labels: plugin, CI

#3637 Plugin API refactor
  InvenTree/common/tests.py
  InvenTree/plugin/api.py
  InvenTree/plugin/registry.py
Labels: bug, enhancement, plugin, breaking

#3803 Revert "Switch to registry for tasks"
  InvenTree/InvenTree/apps.py
  InvenTree/InvenTree/tasks.py
  InvenTree/build/tasks.py
  InvenTree/common/tasks.py
  InvenTree/order/tasks.py
Labels: bug

#3538 [FR]Unit test for Schema allowance
  InvenTree/InvenTree/fields.py
  InvenTree/InvenTree/validators.py
  InvenTree/stock/tests.py
Labels: enhancement, CI

#3792 Raise error if version fails
  InvenTree/common/notifications.py
  InvenTree/plugin/registry.py
Labels: enhancement, plugin

#3806 Add settings for backups
  InvenTree/InvenTree/tasks.py
  InvenTree/common/models.py
  InvenTree/templates/InvenTree/settings/global.html
Labels: enhancement, setup

#3776 [Plugin] Allow custom plugins for running validation routines
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/static/css/inventree.css
  InvenTree/InvenTree/tests.py
  InvenTree/InvenTree/validators.py
  InvenTree/build/serializers.py
  InvenTree/build/test_api.py
  InvenTree/build/validators.py
  InvenTree/common/models.py
  InvenTree/order/serializers.py
  InvenTree/part/api.py
  InvenTree/part/models.py
  InvenTree/part/templates/part/part_base.html
  InvenTree/plugin/base/integration/mixins.py
  InvenTree/plugin/mixins/__init__.py
  InvenTree/plugin/registry.py
  InvenTree/plugin/samples/integration/validation_sample.py
  InvenTree/stock/api.py
  InvenTree/stock/fixtures/stock.yaml
  InvenTree/stock/models.py
  InvenTree/stock/serializers.py
  InvenTree/stock/test_api.py
  InvenTree/stock/tests.py
  InvenTree/templates/InvenTree/settings/stock.html
  InvenTree/templates/js/translated/forms.js
Labels: enhancement, plugin

#3819 Prevent name check on null attachment file
  InvenTree/InvenTree/models.py
Labels: bug

#3818 Attachment bug fix
  InvenTree/InvenTree/models.py
  InvenTree/part/test_api.py
Labels: bug

#3821 Housekeeping Settings
  InvenTree/InvenTree/tasks.py
  InvenTree/common/models.py
  InvenTree/templates/InvenTree/settings/global.html
Labels: enhancement

#3826 Bom table load fix
  InvenTree/templates/js/translated/bom.js
  InvenTree/templates/js/translated/filters.js
  InvenTree/templates/js/translated/part.js
Labels: bug, user interface

#3830 Workflow fix
  .github/workflows/check_translations.yaml
  .github/workflows/docker.yaml
  .github/workflows/release.yml.disabled
Labels: CI

#3831 Improve redraw speed of build allocation table
  InvenTree/templates/js/translated/build.js
Labels: bug, user interface

#3833 Build table improvements
  InvenTree/templates/js/translated/build.js
Labels: user interface

#3832 Fix email notification setting
  InvenTree/build/test_build.py
  InvenTree/common/notifications.py
  InvenTree/common/tests.py
  InvenTree/order/test_sales_order.py
  InvenTree/order/tests.py
  InvenTree/plugin/builtin/integration/core_notifications.py
Labels: bug

#3847 Add reverse proxy docs
  InvenTree/config_template.yaml
Labels: enhancement, setup

#3849 Fix decimal rendering in progress bars
  InvenTree/templates/js/translated/helpers.js
Labels: bug, user interface

#3834 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3850 Improvements for CI tests
  InvenTree/InvenTree/tests.py
Labels: CI

#3851 Prevent assigning of empty barcode data
  InvenTree/plugin/base/barcodes/api.py
  InvenTree/plugin/base/barcodes/test_barcode.py
Labels: barcode

#3854 Make PartCategories to be filterable by name and description
  InvenTree/InvenTree/api_version.py
  InvenTree/part/api.py
Labels: part, api

#3855 Fix bug which prevented loading of test results
  InvenTree/templates/js/translated/build.js
Labels: bug, user interface

#3856 Enable build order search in quick-search window
  InvenTree/common/models.py
  InvenTree/templates/InvenTree/settings/user_search.html
  InvenTree/templates/js/translated/search.js
Labels: user interface

#3829 [BUG] Confirmation Email uses local ip for link URL
  InvenTree/InvenTree/forms.py
Labels: bug

#3863 Serial increment fix
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/tests.py
Labels: bug

#3853 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3870 Part name validation fix
  InvenTree/InvenTree/validators.py
  InvenTree/part/models.py
  InvenTree/templates/js/translated/forms.js
Labels: bug, user interface

#3869 Fix url mangeling
  InvenTree/company/test_api.py
Labels: enhancement

#3877 Floating point API bug
  InvenTree/InvenTree/fields.py
  InvenTree/InvenTree/serializers.py
  InvenTree/part/test_api.py
Labels: bug, api

#3879 Fix for label printing plugin hook
  InvenTree/plugin/base/label/label.py
Labels: bug, plugin

#3881 Fix mode switching for part category table
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/stock.js
Labels: bug, user interface
