Repository inventree/InvenTree, pull requests merged in 2022-08, with the labels that each got.

#3448 Update version_check.py CI scrips
  ci/version_check.py
Labels: bug, CI

#3443 Tree query improvements
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/models.py
  InvenTree/part/api.py
  InvenTree/part/filters.py
  InvenTree/part/migrations/0082_partcategory_pathstring.py
  InvenTree/part/migrations/0083_auto_20220731_2357.py
  InvenTree/part/serializers.py
  InvenTree/part/test_api.py
  InvenTree/part/test_category.py
  InvenTree/part/test_part.py
  InvenTree/stock/api.py
  InvenTree/stock/filters.py
  InvenTree/stock/migrations/0080_stocklocation_pathstring.py
  InvenTree/stock/migrations/0081_auto_20220801_0044.py
  InvenTree/stock/serializers.py
  InvenTree/stock/tests.py
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/stock.js
Labels: bug, api

#3447 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3449 Check that notification target is not null
  InvenTree/common/serializers.py
  InvenTree/templates/js/translated/notification.js
Labels: bug

#3446 update devtools
  .pre-commit-config.yaml
  ci/check_api_endpoint.py
Labels: CI

#3452 Handle missing color themes directory
  InvenTree/common/models.py
Labels: bug

#3453 Return early if themes dir does not exist
  InvenTree/InvenTree/version.py
  InvenTree/common/models.py
Labels: bug

#3455 Improvements to version check CI script
  ci/version_check.py
Labels: CI

#3456 gitpod.io fixes
  .gitpod.yml
Labels: CI

#3457 Ci version fix
  ci/version_check.py
Labels: CI

#3459 Remove os usage in common
  InvenTree/InvenTree/settings.py
  InvenTree/common/models.py
Labels: dependency

#3462 Fix bug introduced in #3459
  InvenTree/common/models.py
Labels: bug

#3465 Login with url
  InvenTree/InvenTree/test_views.py
  InvenTree/InvenTree/urls.py
  InvenTree/InvenTree/views.py
Labels: enhancement, demo

#3466 Fix translated string
  InvenTree/order/models.py
Labels: translation

#3454 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3451 Fix: Treegrid is loading an eternity for huge amounts of data
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/helpers.py
  InvenTree/common/models.py
  InvenTree/part/api.py
  InvenTree/part/test_api.py
  InvenTree/stock/api.py
  InvenTree/stock/test_api.py
  InvenTree/templates/InvenTree/settings/global.html
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/stock.js
Labels: enhancement, part, stock, api

#3472 Depenency updates
  .github/workflows/update.yml
  requirements-dev.txt
  requirements.txt
Labels: CI, dependency, security

#3467 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3489 Improved loading for custom logo
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/settings.py
Labels: bug

#3488 Url field fix
  InvenTree/InvenTree/fields.py
  InvenTree/InvenTree/metadata.py
  InvenTree/stock/migrations/0082_alter_stockitem_link.py
  InvenTree/stock/models.py
  InvenTree/stock/tests.py
Labels: bug

#3484 load admin first
  InvenTree/InvenTree/settings.py
Labels: bug

#3490 Improved loading for custom logo (#3489)
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/settings.py
Labels: bug

#3491 Url field fix (#3488)
  InvenTree/InvenTree/fields.py
  InvenTree/InvenTree/metadata.py
  InvenTree/stock/migrations/0082_alter_stockitem_link.py
  InvenTree/stock/models.py
  InvenTree/stock/tests.py
Labels: bug

#3492 load admin first (#3484)
  InvenTree/InvenTree/settings.py
Labels: bug

#3496 [FR] Add plugin keys, state and version to version info
  InvenTree/InvenTree/api.py
  InvenTree/part/templatetags/inventree_extras.py
  InvenTree/templates/version.html
Labels: enhancement, plugin

#3495 Update issue templates to GH forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
  CONTRIBUTING.md
Labels: enhancement, CI

#3493 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3499 Custom splash screen
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/static/css/inventree.css
  InvenTree/InvenTree/static/img/inventree_splash.jpg
  InvenTree/config_template.yaml
  InvenTree/part/templatetags/inventree_extras.py
  InvenTree/templates/account/base.html
Labels: enhancement, user interface

#3474 vscode devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/postCreateCommand.sh
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
  tasks.py
Labels: enhancement, docker, setup

#3237 Check for (and reduce) overallocated stock when editing build orders.
  InvenTree/build/models.py
  InvenTree/build/serializers.py
  InvenTree/build/test_api.py
  InvenTree/build/test_build.py
Labels: enhancement, build

#3507 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3516 Plugin meta detection improvements
  InvenTree/plugin/helpers.py
  InvenTree/plugin/plugin.py
  InvenTree/plugin/registry.py
Labels: enhancement, plugin

#3518 Allow builds to be completed without any outputs
  InvenTree/build/serializers.py
  InvenTree/build/templates/build/build_base.html
Labels: build

#3532 [FR] Tie github actions to specific commit hashes
  .github/workflows/check_translations.yaml
  .github/workflows/docker.yaml
  .github/workflows/qc_checks.yaml
  .github/workflows/release.yml
  .github/workflows/stale.yml
  .github/workflows/translations.yml
  .github/workflows/update.yml
  .github/workflows/welcome.yml
Labels: CI, security

#3539 Fix weasyprint version
  InvenTree/label/api.py
  InvenTree/label/templates/label/label_base.html
  InvenTree/report/api.py
  requirements.in
  requirements.txt
Labels: bug, report, dependency

#3540 Fix weasyprint version (#3539)
  InvenTree/label/api.py
  InvenTree/label/templates/label/label_base.html
  InvenTree/report/api.py
  requirements.in
  requirements.txt
Labels: bug, report, dependency

#3519 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3503 Update bleach clean function
  InvenTree/InvenTree/mixins.py
  InvenTree/part/test_api.py
Labels: api

#3536 refactor custom file lookup
  InvenTree/InvenTree/config.py
  InvenTree/InvenTree/settings.py
Labels: enhancement, setup

#3541 fix typo in variable name
  InvenTree/InvenTree/settings.py
Labels: bug

#3547 moves imports to enable startup without django beeing loaded
  InvenTree/InvenTree/config.py
Labels: bug, setup

#3548 Update README links to point to our specific projects / workspaces
  README.md
Labels: enhancement

#3545 Fix bug in exporting records
  tasks.py
Labels: bug, report

#3552 Fix bug in exporting records (#3545)
  tasks.py
Labels: bug

#3543 fix typo in variable name (#3541)
  InvenTree/InvenTree/settings.py
Labels: bug

#3517 Improve plugin testing
  InvenTree/plugin/apps.py
  InvenTree/plugin/helpers.py
  InvenTree/plugin/mock/__init__.py
  InvenTree/plugin/mock/simple.py
  InvenTree/plugin/registry.py
  InvenTree/plugin/test_helpers.py
  InvenTree/plugin/test_plugin.py
Labels: plugin, CI

#3535 Plugin framework updates
  InvenTree/common/models.py
  InvenTree/plugin/admin.py
  InvenTree/plugin/models.py
  InvenTree/plugin/plugin.py
  InvenTree/plugin/registry.py
  InvenTree/plugin/samples/integration/version.py
  InvenTree/plugin/template.py
  InvenTree/plugin/test_plugin.py
  InvenTree/templates/InvenTree/settings/plugin.html
  InvenTree/templates/InvenTree/settings/plugin_settings.html
Labels: enhancement, plugin, breaking

#3542 Feature/icons for PartCategory and StockLocation
  InvenTree/InvenTree/static/css/inventree.css
  InvenTree/common/models.py
  InvenTree/part/migrations/0084_partcategory_icon.py
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/part/templates/part/category.html
  InvenTree/stock/migrations/0083_stocklocation_icon.py
  InvenTree/stock/models.py
  InvenTree/stock/serializers.py
  InvenTree/stock/templates/stock/location.html
  InvenTree/templates/InvenTree/settings/part.html
  InvenTree/templates/InvenTree/settings/stock.html
  InvenTree/templates/js/dynamic/nav.js
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/stock.js
Labels: enhancement, part, stock, user interface

#3559 Fix: Broken subfolder tests in postgres/docker CI in master
  .github/workflows/qc_checks.yaml
  InvenTree/plugin/test_plugin.py
Labels: bug, plugin, CI

#3561 Update 'stock' icons for part table
  InvenTree/templates/js/translated/part.js
Labels: user interface

#3551 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3564 Scheduling improvements
  InvenTree/InvenTree/api_version.py
  InvenTree/part/api.py
  InvenTree/part/models.py
  InvenTree/part/templates/part/detail.html
  InvenTree/part/templates/part/part_scheduling.html
  InvenTree/templates/js/translated/bom.js
  InvenTree/templates/js/translated/part.js
Labels: enhancement

#3565 Add ability to quickly duplicate build orders
  InvenTree/build/templates/build/build_base.html
  InvenTree/order/templates/order/order_base.html
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/order.js
Labels: build

#3566 Fix bug in recent part scheduling table
  InvenTree/part/templates/part/detail.html
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/part.js
Labels: bug, user interface

#3573 Include variant stock in part table
  InvenTree/templates/js/translated/part.js
Labels: bug

#3567 Adds option for duplicating an existing purchase order
  InvenTree/InvenTree/api_version.py
  InvenTree/order/api.py
  InvenTree/order/templates/order/order_base.html
  InvenTree/order/test_api.py
  InvenTree/templates/js/translated/bom.js
  InvenTree/templates/js/translated/order.js
Labels: enhancement, order, api

#3563 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3577 fix: invalid chas in cache key (#3574)
  InvenTree/common/models.py
Labels: bug

#3578 Fix dimensions for label templates
  InvenTree/label/templates/label/label_base.html
  InvenTree/label/templates/label/part/part_label.html
  InvenTree/label/templates/label/part/part_label_code128.html
  InvenTree/label/templates/label/stockitem/qr.html
  InvenTree/label/templates/label/stocklocation/qr.html
  InvenTree/label/templates/label/stocklocation/qr_and_text.html
Labels: bug, report

#3579 Inherited BOM fix
  InvenTree/part/api.py
  InvenTree/part/models.py
Labels: bug, build

#3580 Fix dimensions for label templates (#3578)
  InvenTree/label/templates/label/label_base.html
  InvenTree/label/templates/label/part/part_label.html
  InvenTree/label/templates/label/part/part_label_code128.html
  InvenTree/label/templates/label/stockitem/qr.html
  InvenTree/label/templates/label/stocklocation/qr.html
  InvenTree/label/templates/label/stocklocation/qr_and_text.html
Labels: bug

#3581 Build API improvements
  InvenTree/build/api.py
  InvenTree/build/serializers.py
  InvenTree/build/templates/build/detail.html
  InvenTree/stock/serializers.py
  InvenTree/templates/js/translated/build.js
Labels: build

#3585 Display "on order" quantity in build order allocation table
  InvenTree/templates/js/translated/build.js
Labels: user interface, build

#3586 Improve "overdue" display for part purchase order table
  InvenTree/templates/js/translated/part.js
Labels: order, part, user interface

#3587 Add a 'zero stock' threshold line to the part scheduling tab
  InvenTree/templates/js/translated/part.js
Labels: part, user interface

#3583 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3596 Bug fix for loading asset files in reports
  InvenTree/report/templatetags/report.py
  InvenTree/report/tests.py
Labels: bug, report

#3591 Sanitize search input
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/helpers.js
  InvenTree/templates/js/translated/search.js
Labels: bug, user interface, security, breaking

#3598 Bug fix for loading asset files in reports (#3596)
  InvenTree/report/templatetags/report.py
  InvenTree/report/tests.py
Labels: bug, report

#3600 Floating point formatting for BOM table
  InvenTree/templates/js/translated/bom.js
Labels: part, user interface

#3597 Remove hidden characters from form fields
  InvenTree/InvenTree/mixins.py
  InvenTree/part/test_api.py
  InvenTree/templates/js/translated/helpers.js
  requirements.in
  requirements.txt
Labels: api, security, breaking

#3602 Open labels and reports in a new window
  InvenTree/templates/js/translated/label.js
  InvenTree/templates/js/translated/report.js
Labels: report

#3603 Improve filter for auto-allocation of build item
  InvenTree/build/models.py
Labels: build

#3601 StockItem page template fix
  InvenTree/stock/templates/stock/item_base.html
Labels: bug, stock, user interface

#3604 StockItem page template fix (#3601)
  InvenTree/stock/templates/stock/item_base.html
Labels: bug, user interface

#3605 Part parameter update
  InvenTree/InvenTree/api_version.py
  InvenTree/part/migrations/0085_partparametertemplate_description.py
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/templates/InvenTree/settings/settings.html
Labels: enhancement, part, api

#3609 Sanitize search text in bootstrap table
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/mixins.py
  InvenTree/InvenTree/views.py
  InvenTree/templates/InvenTree/search.html
  InvenTree/templates/js/translated/tables.js
Labels: bug

#3610 Add missing 'remove stock' action
  InvenTree/stock/templates/stock/item_base.html
  InvenTree/stock/test_views.py
Labels: bug, stock, user interface

#3611 Add missing 'remove stock' action (#3610)
  InvenTree/stock/templates/stock/item_base.html
  InvenTree/stock/test_views.py
Labels: bug, stock, user interface

#3608 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#3619 Fix for stable branch push
  .github/workflows/docker.yaml
  .github/workflows/release.yml
Labels: CI

#3623 Remove broken URL
  InvenTree/part/urls.py
Labels: bug, user interface
