Repository inventree/InvenTree, pull requests merged in 2023-05, with the labels that each got.

#4735 Use coveralls github action
  .github/workflows/qc_checks.yaml
Labels: CI

#4721 Make sure plugins are always on a new line
  InvenTree/plugin/serializers.py
Labels: bug, setup

#4724 Plugin metadata docs
  docs/docs/assets/images/plugin/model_metadata_api.png
  docs/docs/extend/plugins/metadata.md
  docs/mkdocs.yml
Labels: plugin, documentation

#4738 Scan in items fix
  InvenTree/templates/js/translated/barcode.js
  InvenTree/templates/js/translated/modals.js
Labels: bug, user interface, barcode

#4742 Update README.md with digitalocean info
  README.md
  docs/docs/extend/integrate.md
Labels: documentation

#4740 [FR] Remove Gitpod integration
  .gitpod.yml
Labels: enhancement, CI

#4744 CI cleanup
  .github/workflows/check_docs_config.yaml
  .github/workflows/qc_checks.yaml
  .github/workflows/social.yml.disabled
Labels: enhancement, CI

#4727 Display proper printing target name in the label printing modal dialog
  InvenTree/part/templates/part/part_base.html
  InvenTree/stock/templates/stock/item_base.html
  InvenTree/stock/templates/stock/location.html
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/filters.js
  InvenTree/templates/js/translated/label.js
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/stock.js
Labels: bug, user interface

#4737 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#4747 Remove restriction on manual stock item installation
  InvenTree/stock/models.py
Labels: stock

#4748 Fix filters for part variant table
  InvenTree/part/templates/part/detail.html
Labels: user interface

#4749 Base URL configuration options
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/settings.py
  InvenTree/config_template.yaml
  InvenTree/label/models.py
  InvenTree/order/api.py
  InvenTree/part/templatetags/inventree_extras.py
  InvenTree/report/models.py
  InvenTree/report/templatetags/report.py
  docs/docs/start/config.md
Labels: setup

#4755 Update FUNDING.yml
  .github/FUNDING.yml
Labels: CI

#4753 Fix for sales order tables
  InvenTree/templates/js/translated/sales_order.js
Labels: bug, order, user interface

#4751 Bug fix for label printing
  InvenTree/label/api.py
Labels: bug, plugin, report

#4752 Ignore variant stock when performing stocktake
  InvenTree/part/tasks.py
  InvenTree/part/test_api.py
Labels: bug, pricing

#4367 Add 'Tag' management
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/serializers.py
  InvenTree/InvenTree/settings.py
  InvenTree/company/api.py
  InvenTree/company/migrations/0057_auto_20230427_2033.py
  InvenTree/company/models.py
  InvenTree/company/serializers.py
  InvenTree/part/api.py
  InvenTree/part/migrations/0106_part_tags.py
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/part/test_api.py
  InvenTree/part/test_category.py
  InvenTree/stock/api.py
  InvenTree/stock/migrations/0098_auto_20230427_2033.py
  InvenTree/stock/models.py
  InvenTree/stock/serializers.py
  InvenTree/users/models.py
  docs/docs/extend/plugins/tags.md
  docs/mkdocs.yml
  requirements.in
  requirements.txt
Labels: enhancement, order, part, stock

#4750 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#4725 Metadata fix
  InvenTree/InvenTree/models.py
  InvenTree/build/test_build.py
  InvenTree/company/tests.py
  InvenTree/label/tests.py
  InvenTree/order/test_sales_order.py
  InvenTree/order/tests.py
  InvenTree/part/test_bom_item.py
  InvenTree/part/test_param.py
  InvenTree/part/test_part.py
  InvenTree/report/tests.py
  InvenTree/stock/tests.py
Labels: bug, plugin

#4761 Fix various devcontainer issues
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/postCreateCommand.sh
Labels: docker, setup

#4768 Improve documentation on currency rendering
  .devcontainer/postCreateCommand.sh
  InvenTree/InvenTree/helpers.py
  docs/docs/report/helpers.md
Labels: documentation

#4772 Project code docs
  docs/docs/assets/images/order/assign_project_code.png
  docs/docs/assets/images/order/filter_by_project.png
  docs/docs/assets/images/settings/project_codes.png
  docs/docs/order/project_codes.md
  docs/mkdocs.yml
Labels: documentation

#4767 Add option to hide plugin setting from auto-generated plugin setting page
  InvenTree/templates/InvenTree/settings/mixins/settings.html
  docs/docs/extend/plugins/settings.md
Labels: user interface, plugin

#4778 Add missing triage:not-checked to documentation issue
  .github/ISSUE_TEMPLATE/documentation.yaml
Labels: CI

#4773 Build filters
  InvenTree/build/templates/build/build_base.html
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/filters.js
  InvenTree/templates/js/translated/table_filters.js
  InvenTree/templates/js/translated/tables.js
Labels: user interface, build

#4781 Extend docs for report filename generation
  docs/docs/assets/images/report/filename_pattern.png
  docs/docs/report/report.md
Labels: documentation

#4782 Sales order button fix
  InvenTree/company/templates/company/detail.html
  InvenTree/templates/js/translated/table_filters.js
Labels: bug, user interface

#4786 fix strarting -> starting
  InvenTree/common/models.py
Labels: translation

#4784 Fix metadatalookup
  InvenTree/plugin/plugin.py
Labels: bug, plugin

#4775 Add list of pending shipment to home page, with corresponding setting
  InvenTree/common/models.py
  InvenTree/templates/InvenTree/index.html
  InvenTree/templates/InvenTree/settings/user_homepage.html
  InvenTree/templates/js/translated/sales_order.js
Labels: enhancement, order, user interface

#4799 Add reload functionality for build item table
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/filters.js
  requirements.txt
Labels: user interface, build

#4787 Docs/devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/postCreateCommand.sh
  .vscode/tasks.json
  docs/docs/start/devcontainer.md
  docs/mkdocs.yml
Labels: setup, documentation

#4741 Add flag to API which allows using pack size
  InvenTree/InvenTree/api_version.py
  InvenTree/company/fixtures/supplier_part.yaml
  InvenTree/stock/api.py
  InvenTree/stock/serializers.py
  InvenTree/stock/test_api.py
  InvenTree/templates/js/translated/stock.js
  docs/docs/stock/stock.md
Labels: api

#4800 [Feature] Scrap Build Outputs
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/status_codes.py
  InvenTree/build/api.py
  InvenTree/build/models.py
  InvenTree/build/serializers.py
  InvenTree/build/templates/build/detail.html
  InvenTree/build/test_api.py
  InvenTree/plugin/registry.py
  InvenTree/stock/api.py
  InvenTree/stock/migrations/0099_alter_stockitem_status.py
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/stock.js
  InvenTree/templates/js/translated/table_filters.js
  InvenTree/templates/stock_table.html
  docs/docs/assets/images/build/build_example_allocate_untracked.png
  docs/docs/assets/images/build/build_example_allocated_tracked.png
  docs/docs/assets/images/build/build_example_complete_outputs.png
  docs/docs/assets/images/build/build_example_create.png
  docs/docs/assets/images/build/build_example_create_outputs.png
  docs/docs/assets/images/build/build_example_incomplete_list.png
  docs/docs/assets/images/build/build_output_complete.png
  docs/docs/assets/images/build/build_output_create.png
  docs/docs/assets/images/build/build_output_delete.png
  docs/docs/assets/images/build/build_output_scrap.png
  docs/docs/assets/images/build/build_outputs_complete.png
  docs/docs/assets/images/build/build_outputs_incomplete.png
  docs/docs/assets/images/stock/stock_status_change_multiple.png
  docs/docs/assets/images/stock/stock_status_change_multiple_done.png
  docs/docs/assets/images/stock/stock_status_edit.png
  docs/docs/assets/images/stock/stock_status_edit_multiple.png
  docs/docs/assets/images/stock/stock_status_label.png
  docs/docs/assets/images/stock/stock_status_label_updated.png
  docs/docs/build/allocate.md
  docs/docs/build/build.md
  docs/docs/build/example.md
  docs/docs/build/output.md
  docs/docs/stock/status.md
  docs/docs/stylesheets/extra.css
  docs/mkdocs.yml
Labels: enhancement, api, build

#4801 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#4812 Add faq entry for permission error
  docs/docs/faq.md
Labels: enhancement, documentation

#4811 Docker build fix
  .github/workflows/qc_checks.yaml
  requirements.in
  requirements.txt
Labels: CI, docker

#4816 Allow tag fields to be empty
  InvenTree/company/migrations/0058_auto_20230515_0004.py
  InvenTree/company/models.py
  InvenTree/part/migrations/0107_alter_part_tags.py
  InvenTree/part/models.py
  InvenTree/stock/migrations/0100_auto_20230515_0004.py
  InvenTree/stock/models.py
Labels: bug

#4819 Small visual tweaks for notifications tab
  InvenTree/templates/notifications.html
Labels: user interface

#4822 Bug fix for improperly configured SSO provider
  InvenTree/part/templatetags/sso.py
  InvenTree/templates/InvenTree/settings/user.html
  InvenTree/templates/InvenTree/settings/user_sso.html
  InvenTree/templates/socialaccount/login.html
  InvenTree/templates/socialaccount/snippets/provider_list.html
Labels: bug, setup

#4817 Build consume stock
  InvenTree/InvenTree/tasks.py
  InvenTree/build/models.py
  InvenTree/build/templates/build/detail.html
  InvenTree/build/templates/build/sidebar.html
  InvenTree/build/test_build.py
  InvenTree/company/templates/company/supplier_part.html
  InvenTree/part/templates/part/detail.html
  InvenTree/stock/api.py
  InvenTree/stock/migrations/0100_stockitem_consumed_by.py
  InvenTree/stock/models.py
  InvenTree/stock/serializers.py
  InvenTree/stock/templates/stock/item.html
  InvenTree/stock/templates/stock/item_base.html
  InvenTree/stock/templates/stock/location.html
  InvenTree/templates/InvenTree/index.html
  InvenTree/templates/InvenTree/search.html
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/stock.js
  docs/docs/build/allocate.md
  docs/docs/build/build.md
  docs/docs/terminology.md
Labels: enhancement, build

#4810 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#4831 Cleanup / consolidate unit testing code
  InvenTree/InvenTree/ci_render_js.py
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/test_api.py
  InvenTree/InvenTree/test_middleware.py
  InvenTree/InvenTree/test_views.py
  InvenTree/InvenTree/tests.py
  InvenTree/InvenTree/unit_test.py
  InvenTree/build/test_api.py
  InvenTree/build/test_migrations.py
  InvenTree/build/tests.py
  InvenTree/common/tests.py
  InvenTree/company/test_api.py
  InvenTree/company/test_migrations.py
  InvenTree/company/test_views.py
  InvenTree/label/test_api.py
  InvenTree/label/tests.py
  InvenTree/order/test_api.py
  InvenTree/order/test_views.py
  InvenTree/part/test_api.py
  InvenTree/part/test_bom_export.py
  InvenTree/part/test_bom_import.py
  InvenTree/part/test_migrations.py
  InvenTree/part/test_part.py
  InvenTree/part/test_pricing.py
  InvenTree/part/test_views.py
  InvenTree/plugin/base/action/test_action.py
  InvenTree/plugin/base/barcodes/test_barcode.py
  InvenTree/plugin/base/integration/test_mixins.py
  InvenTree/plugin/base/label/test_label_mixin.py
  InvenTree/plugin/base/locate/test_locate.py
  InvenTree/plugin/builtin/barcodes/test_inventree_barcode.py
  InvenTree/plugin/samples/integration/test_sample.py
  InvenTree/plugin/samples/integration/test_simpleactionplugin.py
  InvenTree/plugin/samples/locate/test_locate_sample.py
  InvenTree/plugin/test_api.py
  InvenTree/report/tests.py
  InvenTree/stock/test_api.py
  InvenTree/stock/test_migrations.py
  InvenTree/stock/test_views.py
  InvenTree/stock/tests.py
  InvenTree/users/test_api.py
  InvenTree/users/test_migrations.py
  InvenTree/users/tests.py
Labels: CI

#4844 Add docs for more helper functions
  docs/docs/report/helpers.md
Labels: documentation

#4843 Add InvenTreePluginViewMixin to PartIndex
  InvenTree/part/views.py
Labels: part, plugin

#4846 Adds ability to partially scrap build outputs
  InvenTree/InvenTree/api_version.py
  InvenTree/build/models.py
  InvenTree/build/serializers.py
  InvenTree/build/templates/build/detail.html
  InvenTree/build/test_api.py
  InvenTree/stock/models.py
  InvenTree/templates/filter_list.html
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/stock_table.html
Labels: enhancement, build

#4842 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#4823 Parameter filtering
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/conversion.py
  InvenTree/InvenTree/static/css/inventree.css
  InvenTree/InvenTree/tasks.py
  InvenTree/InvenTree/validators.py
  InvenTree/build/migrations/0013_auto_20200425_0507.py
  InvenTree/build/migrations/0018_build_reference.py
  InvenTree/build/migrations/0029_auto_20210601_1525.py
  InvenTree/build/migrations/0032_auto_20211014_0632.py
  InvenTree/build/migrations/0036_auto_20220707_1101.py
  InvenTree/order/migrations/0052_auto_20211014_0631.py
  InvenTree/order/migrations/0058_auto_20211126_1210.py
  InvenTree/order/migrations/0074_auto_20220709_0108.py
  InvenTree/order/migrations/0079_auto_20230304_0904.py
  InvenTree/part/admin.py
  InvenTree/part/api.py
  InvenTree/part/filters.py
  InvenTree/part/migrations/0039_auto_20200515_1127.py
  InvenTree/part/migrations/0083_auto_20220731_2357.py
  InvenTree/part/migrations/0102_auto_20230314_0112.py
  InvenTree/part/migrations/0108_auto_20230516_1334.py
  InvenTree/part/migrations/0109_auto_20230517_1048.py
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/part/tasks.py
  InvenTree/part/templates/part/category.html
  InvenTree/part/templates/part/category_sidebar.html
  InvenTree/part/test_api.py
  InvenTree/part/test_migrations.py
  InvenTree/part/test_param.py
  InvenTree/plugin/registry.py
  InvenTree/stock/migrations/0061_auto_20210511_0911.py
  InvenTree/stock/migrations/0064_auto_20210621_1724.py
  InvenTree/stock/migrations/0069_auto_20211109_2347.py
  InvenTree/stock/migrations/0071_auto_20211205_1733.py
  InvenTree/stock/migrations/0081_auto_20220801_0044.py
  InvenTree/stock/migrations/0094_auto_20230220_0025.py
  InvenTree/stock/migrations/0096_auto_20230330_1121.py
  InvenTree/templates/InvenTree/settings/part.html
  InvenTree/templates/InvenTree/settings/part_parameters.html
  InvenTree/templates/InvenTree/settings/settings.html
  InvenTree/templates/InvenTree/settings/settings_staff_js.html
  InvenTree/templates/InvenTree/settings/sidebar.html
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/status_codes.js
  InvenTree/templates/js/translated/table_filters.js
  docs/docs/assets/images/part/part_invalid_units.png
  docs/docs/assets/images/part/part_sort_by_param.png
  docs/docs/assets/images/part/part_sorting_units.png
  docs/docs/credits.md
  docs/docs/part/parameter.md
  requirements.in
  requirements.txt
Labels: enhancement, part, api

#4861 Fix category filtering for parameteric part table
  InvenTree/part/templates/part/category.html
Labels: bug, part, user interface

#4852 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#4868 Handle ValidationError when creating a new setting
  InvenTree/common/models.py
Labels: bug

#4872 Reorganize FAQ section
  docs/docs/faq.md
Labels: documentation

#4873 Fix for currency migration
  InvenTree/InvenTree/settings.py
  InvenTree/common/migrations/0010_migrate_currency_setting.py
Labels: bug, pricing

#4880 Make nginx more clear that changing the port is 'dangerous'
  docker/production/docker-compose.yml
  docker/production/nginx.prod.conf
Labels: setup, documentation

#4885 Fix for PurchaseOrder template
  InvenTree/order/templates/order/purchase_order_detail.html
Labels: bug, user interface

#4881 Improve cli experience
  InvenTree/InvenTree/version.py
  Procfile
  tasks.py
Labels: enhancement, setup

#4892 Fix for data migration
  InvenTree/part/migrations/0109_auto_20230517_1048.py
Labels: bug, setup

#4894 Documentation Improvements
  docs/.gitignore
  docs/_includes/overrides/main.html
  docs/_includes/overrides/partials/version_banner.html
  docs/docs/extend/how_to_plugin.md
  docs/docs/extend/plugins.md
  docs/docs/hooks.py
  docs/docs/terminology.md
  docs/mkdocs.yml
Labels: documentation

#4882 Possible fix for git messages
  InvenTree/InvenTree/version.py
Labels: setup

#4899 Add API Calendar for Return Orders
  InvenTree/order/api.py
  InvenTree/order/test_api.py
  docs/docs/order/return_order.md
Labels: order, api

#4875 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#4901 Part unit migration fix
  InvenTree/part/migrations/0111_auto_20230521_1350.py
Labels: bug, setup

#4907 - Bump djLint to 1.29.0 (from 1.25.0) in the CI linting scripts
  .pre-commit-config.yaml
  InvenTree/build/templates/build/build_base.html
  InvenTree/order/templates/order/order_base.html
  InvenTree/order/templates/order/return_order_base.html
  InvenTree/order/templates/order/sales_order_base.html
Labels: dependency

#4908 Fix completeSalesOrderShipment typo in sales_order.js
  InvenTree/templates/js/translated/sales_order.js
Labels: bug, user interface

#4912 Add workflow for backporting PRs
  .github/workflows/backport.yml
  backportrc.json
Labels: CI, backport, backport-to-0.11.x

#4914 Add name to backport workflow
  .github/workflows/backport.yml
Labels: CI

#4910 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#4918 js fixes
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/purchase_order.js
Labels: bug, user interface

#4919 Fix Unink to Unlink
  InvenTree/part/templates/part/part_base.html
Labels: bug, translation

#4905 Change target of PurchaseOrder notification
  InvenTree/order/models.py
  InvenTree/order/tests.py
Labels: order, breaking

#4911 Bump deps
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: dependency

#4930 BOM table: remove quantity footer
  InvenTree/templates/js/translated/bom.js
Labels: user interface

#4933 Improve docs for report helpers
  docs/docs/report/helpers.md
Labels: documentation
