Repository inventree/InvenTree, pull requests merged in 2023-06, with the labels that each got.

#4939 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#4940 Improvements for parameteric part table
  InvenTree/templates/js/translated/part.js
Labels: part, user interface

#4944 Fix/settings bugs and added model SettingKeyType typing
  .gitignore
  InvenTree/common/models.py
  InvenTree/part/templatetags/inventree_extras.py
  InvenTree/plugin/api.py
  InvenTree/templates/js/dynamic/settings.js
Labels: bug

#4945 Test flexibility
  CONTRIBUTING.md
  tasks.py
Labels: CI

#4946 Report files
  InvenTree/report/templatetags/report.py
  docs/docs/report/helpers.md
Labels: enhancement, report

#4947 Metadata bugfixes
  InvenTree/order/api.py
  InvenTree/part/api.py
Labels: api

#4949 Update action.md
  docs/docs/extend/plugins/action.md
Labels: documentation

#4951 Shorten displayed linked by default
  InvenTree/templates/js/translated/helpers.js
Labels: user interface

#4952 Fix for 'available' filter
  InvenTree/stock/api.py
Labels: bug, api, backport, backport-to-0.11.x

#4958 Parameter validation via plugin
  InvenTree/part/models.py
  InvenTree/plugin/base/integration/mixins.py
  InvenTree/plugin/samples/integration/validation_sample.py
  docs/docs/assets/images/plugin/enable_events.png
  docs/docs/assets/images/plugin/enable_schedule.png
  docs/docs/extend/plugins/event.md
  docs/docs/extend/plugins/panel.md
  docs/docs/extend/plugins/schedule.md
  docs/docs/extend/plugins/settings.md
  docs/docs/extend/plugins/validation.md
Labels: enhancement, plugin

#4961 Fix for improper migrations
  InvenTree/part/migrations/0112_auto_20230525_1606.py
  InvenTree/part/migrations/0113_auto_20230531_1205.py
Labels: bug, setup

#4558 Add openssf badge
  README.md
Labels: enhancement, CI

#4964 Enable and disable plugins via the API
  InvenTree/plugin/api.py
  InvenTree/plugin/models.py
  InvenTree/plugin/plugin.py
  InvenTree/plugin/serializers.py
  InvenTree/templates/InvenTree/settings/plugin.html
  InvenTree/templates/InvenTree/settings/plugin_details.html
  InvenTree/templates/InvenTree/settings/settings.html
  InvenTree/templates/InvenTree/settings/settings_staff_js.html
  InvenTree/templates/js/translated/plugin.js
  InvenTree/templates/js/translated/table_filters.js
Labels: user interface, plugin, api

#4967 Prevent div-by-zero error
  InvenTree/part/models.py
Labels: bug, backport, backport-to-0.11.x

#4966 [FR] Switch from git to dulwich
  InvenTree/InvenTree/version.py
  InvenTree/plugin/apps.py
  InvenTree/plugin/helpers.py
  InvenTree/plugin/registry.py
  requirements.in
  requirements.txt
Labels: enhancement, refactor

#4950 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#4977 Migration bug fix 2
  InvenTree/part/migrations/0112_auto_20230525_1606.py
Labels: bug, setup

#4978 Refactor label API code
  InvenTree/label/admin.py
  InvenTree/label/api.py
  InvenTree/label/serializers.py
Labels: refactor

#4985 Add note on SSO behind proxy
  docs/docs/settings/SSO.md
Labels: documentation

#4975 Currency migrations - stop migrations when defaults change
  InvenTree/common/settings.py
  InvenTree/company/migrations/0025_auto_20201110_1001.py
  InvenTree/order/migrations/0038_auto_20201112_1737.py
  InvenTree/order/migrations/0039_auto_20201112_2203.py
  InvenTree/order/migrations/0045_auto_20210504_1946.py
  InvenTree/part/migrations/0055_auto_20201110_1001.py
  InvenTree/part/migrations/0067_partinternalpricebreak.py
  InvenTree/part/migrations/0089_auto_20221112_0128.py
  InvenTree/stock/migrations/0053_auto_20201110_0513.py
  InvenTree/stock/migrations/0055_auto_20201117_1453.py
Labels: refactor

#4988 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#4994 Place uninstalled items back in stock
  InvenTree/stock/models.py
Labels: bug, stock, build

#4987 Fix for faulty data migrations
  InvenTree/part/migrations/0112_auto_20230525_1606.py
  InvenTree/part/test_migrations.py
Labels: bug, setup, migration

#5000 CSS fix for 2FA token
  InvenTree/InvenTree/static/css/inventree.css
  InvenTree/templates/allauth_2fa/setup.html
Labels: bug, user interface, backport, backport-to-0.11.x

#5006 Migration fix
  InvenTree/stock/migrations/0071_auto_20211205_1733.py
Labels: bug, backport, backport-to-0.11.x, migration

#4813 Improve devdocs
  .github/workflows/qc_checks.yaml
  CONTRIBUTING.md
  docs/docs/develop/contributing.md
  docs/docs/develop/devcontainer.md
  docs/docs/develop/starting.md
  docs/docs/faq.md
  docs/docs/start/bare_dev.md
  docs/docs/start/bare_prod.md
  docs/docs/start/install.md
  docs/docs/start/intro.md
  docs/docs/start/serving_files.md
  docs/mkdocs.yml
  docs/requirements.txt
Labels: enhancement, documentation

#4857 Refactor states/status
  InvenTree/InvenTree/api.py
  InvenTree/InvenTree/context.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/status_codes.py
  InvenTree/build/api.py
  InvenTree/build/models.py
  InvenTree/build/serializers.py
  InvenTree/build/tasks.py
  InvenTree/build/templates/build/build_base.html
  InvenTree/build/templates/build/detail.html
  InvenTree/build/test_api.py
  InvenTree/company/models.py
  InvenTree/generic/__init__.py
  InvenTree/generic/states/__init__.py
  InvenTree/generic/states/api.py
  InvenTree/generic/states/states.py
  InvenTree/generic/states/tags.py
  InvenTree/generic/states/tests.py
  InvenTree/generic/templatetags/__init__.py
  InvenTree/generic/templatetags/generic.py
  InvenTree/order/api.py
  InvenTree/order/migrations/0096_alter_returnorderlineitem_outcome.py
  InvenTree/order/models.py
  InvenTree/order/serializers.py
  InvenTree/order/tasks.py
  InvenTree/order/templates/order/order_base.html
  InvenTree/order/templates/order/purchase_order_detail.html
  InvenTree/order/templates/order/return_order_base.html
  InvenTree/order/templates/order/return_order_detail.html
  InvenTree/order/templates/order/sales_order_base.html
  InvenTree/order/templates/order/sales_order_detail.html
  InvenTree/order/test_api.py
  InvenTree/order/test_migrations.py
  InvenTree/part/api.py
  InvenTree/part/filters.py
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/part/templatetags/status_codes.py
  InvenTree/part/test_api.py
  InvenTree/part/test_pricing.py
  InvenTree/stock/api.py
  InvenTree/stock/migrations/0061_auto_20210511_0911.py
  InvenTree/stock/migrations/0096_auto_20230330_1121.py
  InvenTree/stock/migrations/0102_alter_stockitem_status.py
  InvenTree/stock/models.py
  InvenTree/stock/templates/stock/item_base.html
  InvenTree/stock/test_api.py
  InvenTree/stock/test_views.py
  InvenTree/templates/js/translated/status_codes.js
  InvenTree/templates/js/translated/stock.js
  InvenTree/templates/js/translated/table_filters.js
Labels: refactor

#4976 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#5017 Add SBOM to container
  .github/workflows/docker.yaml
Labels: security, setup

#5014 Add more version information
  .pkgr.yml
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/version.py
  InvenTree/part/templatetags/inventree_extras.py
  InvenTree/templates/about.html
  InvenTree/templates/version.html
  contrib/packager.io/before.sh
  docs/docs/start/advanced.md
  docs/mkdocs.yml
  requirements.in
  requirements.txt
Labels: enhancement, setup

#4982 [FR] Add Feature flags
  InvenTree/InvenTree/settings.py
  InvenTree/common/api.py
  InvenTree/common/serializers.py
  InvenTree/common/tests.py
  InvenTree/config_template.yaml
  InvenTree/users/models.py
  requirements.in
  requirements.txt
Labels: enhancement, api

#5018 Remove signatur checking
  InvenTree/common/models.py
  InvenTree/plugin/helpers.py
  InvenTree/plugin/plugin.py
  InvenTree/templates/InvenTree/settings/plugin.html
  InvenTree/templates/InvenTree/settings/plugin_settings.html
Labels: user interface, refactor

#5027 Fix migration order
  InvenTree/company/migrations/0059_supplierpart_pack_units.py
Labels: bug, migration

#5025 Migration fixes
  InvenTree/InvenTree/status.py
  InvenTree/InvenTree/tasks.py
  InvenTree/common/migrations/0001_initial.py
Labels: bug, CI, migration

#5026 Skip pricing updates when importing data
  InvenTree/InvenTree/ready.py
  InvenTree/part/models.py
Labels: CI, pricing, migration

#4855 Build Order Updates
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/apps.py
  InvenTree/InvenTree/static/css/inventree.css
  InvenTree/InvenTree/tasks.py
  InvenTree/InvenTree/test_urls.py
  InvenTree/InvenTree/views.py
  InvenTree/build/admin.py
  InvenTree/build/api.py
  InvenTree/build/migrations/0043_buildline.py
  InvenTree/build/migrations/0044_auto_20230528_1410.py
  InvenTree/build/migrations/0045_builditem_build_line.py
  InvenTree/build/migrations/0046_auto_20230606_1033.py
  InvenTree/build/migrations/0047_auto_20230606_1058.py
  InvenTree/build/models.py
  InvenTree/build/serializers.py
  InvenTree/build/templates/build/build_base.html
  InvenTree/build/templates/build/detail.html
  InvenTree/build/templates/build/sidebar.html
  InvenTree/build/test_api.py
  InvenTree/build/test_build.py
  InvenTree/build/test_migrations.py
  InvenTree/build/views.py
  InvenTree/common/api.py
  InvenTree/common/settings.py
  InvenTree/company/migrations/0025_auto_20201110_1001.py
  InvenTree/company/migrations/0039_auto_20210701_0509.py
  InvenTree/company/migrations/0051_alter_supplierpricebreak_price.py
  InvenTree/order/migrations/0038_auto_20201112_1737.py
  InvenTree/order/models.py
  InvenTree/order/test_sales_order.py
  InvenTree/part/api.py
  InvenTree/part/filters.py
  InvenTree/part/fixtures/part.yaml
  InvenTree/part/migrations/0055_auto_20201110_1001.py
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/part/test_api.py
  InvenTree/part/test_category.py
  InvenTree/part/test_pricing.py
  InvenTree/plugin/base/event/events.py
  InvenTree/report/models.py
  InvenTree/stock/api.py
  InvenTree/stock/migrations/0053_auto_20201110_0513.py
  InvenTree/stock/migrations/0065_auto_20210701_0509.py
  InvenTree/stock/serializers.py
  InvenTree/templates/js/translated/bom.js
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/sales_order.js
  InvenTree/templates/js/translated/table_filters.js
  InvenTree/users/models.py
  docs/docs/build/allocate.md
  docs/docs/build/bom.md
  docs/docs/build/build.md
  docs/docs/report/build.md
Labels: enhancement, api, build, breaking, refactor, migration

#5032 Update app docs
  docs/docs/app/settings.md
  docs/docs/assets/images/app/app_settings.png
  docs/docs/assets/images/app/barcode_settings.png
  docs/docs/assets/images/app/settings.png
Labels: documentation

#4808 Add ProjectCode support to build orders
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/middleware.py
  InvenTree/InvenTree/serializers.py
  InvenTree/InvenTree/unit_test.py
  InvenTree/InvenTree/views.py
  InvenTree/build/api.py
  InvenTree/build/migrations/0048_build_project_code.py
  InvenTree/build/models.py
  InvenTree/build/serializers.py
  InvenTree/build/templates/build/build_base.html
  InvenTree/build/test_migrations.py
  InvenTree/common/api.py
  InvenTree/common/notifications.py
  InvenTree/common/serializers.py
  InvenTree/common/tests.py
  InvenTree/company/test_api.py
  InvenTree/company/test_migrations.py
  InvenTree/order/api.py
  InvenTree/order/models.py
  InvenTree/order/serializers.py
  InvenTree/plugin/test_api.py
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/table_filters.js
Labels: enhancement, api, build

#5039 Improve error logging
  InvenTree/InvenTree/middleware.py
Labels: bug, backport, backport-to-0.11.x

#5034 Build line labels
  InvenTree/InvenTree/api_version.py
  InvenTree/label/admin.py
  InvenTree/label/api.py
  InvenTree/label/apps.py
  InvenTree/label/migrations/0010_buildlinelabel.py
  InvenTree/label/models.py
  InvenTree/label/serializers.py
  InvenTree/label/templates/label/buildline/buildline_label.html
  InvenTree/label/templates/label/buildline/buildline_label_base.html
  InvenTree/templates/js/translated/build.js
  InvenTree/users/models.py
  docs/docs/assets/images/report/label_build_example.png
  docs/docs/assets/images/report/label_build_print.png
  docs/docs/report/labels.md
  docs/docs/report/labels/build_labels.md
  docs/docs/report/labels/location_labels.md
  docs/docs/report/labels/part_labels.md
  docs/docs/report/labels/stock_labels.md
  docs/mkdocs.yml
Labels: enhancement, api, build

#5042 Improve StockItem API speed
  InvenTree/InvenTree/unit_test.py
  InvenTree/company/serializers.py
  InvenTree/stock/api.py
  InvenTree/stock/serializers.py
  InvenTree/stock/test_api.py
Labels: api, CI

#5045 Replace assertation with more targeted logging check
  InvenTree/plugin/samples/event/event_sample.py
  InvenTree/plugin/samples/event/test_event_sample.py
Labels: bug, CI

#5019 Add metadata to plugin configs
  InvenTree/InvenTree/api_version.py
  InvenTree/plugin/admin.py
  InvenTree/plugin/api.py
  InvenTree/plugin/migrations/0006_pluginconfig_metadata.py
  InvenTree/plugin/models.py
Labels: enhancement, plugin, api

#5030 Stock installed items
  InvenTree/common/models.py
  InvenTree/stock/api.py
  InvenTree/stock/serializers.py
  InvenTree/templates/InvenTree/settings/stock.html
  InvenTree/templates/js/translated/stock.js
Labels: stock, user interface, api

#5049 custom panel fix
  InvenTree/plugin/base/integration/mixins.py
Labels: bug, plugin, backport, backport-to-0.11.x

#5055 Parameter by name
  InvenTree/part/models.py
  InvenTree/part/test_param.py
  InvenTree/report/templatetags/report.py
  docs/docs/assets/images/report/label_with_parameters.png
  docs/docs/report/helpers.md
  docs/docs/report/labels/part_labels.md
Labels: report

#5057 Homepage Improvements
  InvenTree/InvenTree/api_version.py
  InvenTree/common/models.py
  InvenTree/part/api.py
  InvenTree/templates/InvenTree/index.html
  InvenTree/templates/InvenTree/settings/user_homepage.html
Labels: user interface, api

#4732 [Feature] Company Addresses
  .pre-commit-config.yaml
  InvenTree/company/admin.py
  InvenTree/company/api.py
  InvenTree/company/migrations/0063_auto_20230502_1956.py
  InvenTree/company/migrations/0064_move_address_field_to_address_model.py
  InvenTree/company/migrations/0065_remove_company_address.py
  InvenTree/company/migrations/0066_auto_20230616_2059.py
  InvenTree/company/models.py
  InvenTree/company/serializers.py
  InvenTree/company/templates/company/detail.html
  InvenTree/company/templates/company/sidebar.html
  InvenTree/company/test_api.py
  InvenTree/company/test_migrations.py
  InvenTree/company/tests.py
  InvenTree/order/migrations/0097_auto_20230529_0107.py
  InvenTree/order/models.py
  InvenTree/order/serializers.py
  InvenTree/order/templates/order/order_base.html
  InvenTree/order/templates/order/return_order_base.html
  InvenTree/order/templates/order/sales_order_base.html
  InvenTree/templates/js/translated/company.js
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/model_renderers.js
  InvenTree/templates/js/translated/purchase_order.js
  InvenTree/templates/js/translated/return_order.js
  InvenTree/templates/js/translated/sales_order.js
  InvenTree/users/models.py
  docs/docs/order/company.md
Labels: enhancement, user interface, api

#5063 Simplify release notes docs
  docs/_includes/release_table.html
  docs/_includes/release_table_head.html
  docs/_includes/release_table_tail.html
  docs/docs/releases/release_notes.md
Labels: documentation

#5064 Stock status change API
  InvenTree/InvenTree/api_version.py
  InvenTree/stock/api.py
  InvenTree/stock/serializers.py
  InvenTree/stock/test_api.py
  InvenTree/templates/js/translated/stock.js
  InvenTree/templates/stock_table.html
Labels: api

#5067 Decouble ruleset migration
  InvenTree/users/migrations/0007_alter_ruleset_name.py
Labels: refactor

#5072 Fixes for purchase order receive buttons
  InvenTree/order/templates/order/order_base.html
  InvenTree/order/templates/order/purchase_order_detail.html
Labels: bug, order, user interface

#5075 Table custom buttons
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/static/css/inventree.css
  InvenTree/InvenTree/urls.py
  InvenTree/build/templates/build/detail.html
  InvenTree/build/templates/build/index.html
  InvenTree/company/templates/company/detail.html
  InvenTree/company/templates/company/index.html
  InvenTree/company/templates/company/manufacturer_part.html
  InvenTree/company/templates/company/supplier_part.html
  InvenTree/order/templates/order/purchase_order_detail.html
  InvenTree/order/templates/order/purchase_orders.html
  InvenTree/order/templates/order/return_order_detail.html
  InvenTree/order/templates/order/return_orders.html
  InvenTree/order/templates/order/sales_order_detail.html
  InvenTree/order/templates/order/sales_orders.html
  InvenTree/part/api.py
  InvenTree/part/serializers.py
  InvenTree/part/templates/part/bom.html
  InvenTree/part/templates/part/category.html
  InvenTree/part/templates/part/detail.html
  InvenTree/stock/templates/stock/item.html
  InvenTree/stock/templates/stock/location.html
  InvenTree/templates/InvenTree/notifications/history.html
  InvenTree/templates/InvenTree/notifications/inbox.html
  InvenTree/templates/InvenTree/settings/part_stocktake.html
  InvenTree/templates/InvenTree/settings/plugin.html
  InvenTree/templates/attachment_table.html
  InvenTree/templates/base.html
  InvenTree/templates/filter_list.html
  InvenTree/templates/js/dynamic/permissions.js
  InvenTree/templates/js/translated/attachment.js
  InvenTree/templates/js/translated/barcode.js
  InvenTree/templates/js/translated/bom.js
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/company.js
  InvenTree/templates/js/translated/filters.js
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/purchase_order.js
  InvenTree/templates/js/translated/search.js
  InvenTree/templates/js/translated/stock.js
  InvenTree/templates/js/translated/table_filters.js
  InvenTree/templates/js/translated/tables.js
  InvenTree/templates/stock_table.html
Labels: bug, user interface, api, refactor

#5077 Required for order fix
  InvenTree/InvenTree/urls.py
  InvenTree/part/api.py
  InvenTree/templates/InvenTree/index.html
  InvenTree/templates/base.html
  InvenTree/templates/js/translated/index.js
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/stock.js
Labels: user interface

#4187 Add dj-rest-auth
  InvenTree/InvenTree/forms.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/social_auth_urls.py
  InvenTree/InvenTree/urls.py
  InvenTree/config_template.yaml
  requirements.in
  requirements.txt
Labels: api, security

#5076 Fix constraint for address model
  InvenTree/company/migrations/0063_auto_20230502_1956.py
  InvenTree/company/models.py
  InvenTree/company/tests.py
Labels: bug, CI, migration

#5061 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#4973 Add migration test workflow
  .github/actions/migration/action.yaml
  .github/workflows/migration_test.yaml
Labels: CI, migration

#5082 Fix for loadPartTable
  InvenTree/templates/InvenTree/index.html
Labels: bug, user interface

#5086 Table filters refactor
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/filters.js
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/stock.js
  InvenTree/templates/js/translated/table_filters.js
  InvenTree/templates/js/translated/tables.js
Labels: user interface

#5087 Unit Test Improvements
  .github/workflows/docker.yaml
  .github/workflows/migration_test.yaml
  .github/workflows/qc_checks.yaml
  InvenTree/InvenTree/apps.py
  InvenTree/InvenTree/conversion.py
  InvenTree/InvenTree/management/commands/wait_for_db.py
  InvenTree/InvenTree/tasks.py
  InvenTree/common/migrations/0017_notesimage.py
  InvenTree/label/apps.py
  InvenTree/plugin/helpers.py
  InvenTree/plugin/registry.py
  InvenTree/plugin/test_api.py
  InvenTree/report/apps.py
  tasks.py
Labels: CI

#5091 Pin mysqlclient lib for docker
  docker/requirements.txt
Labels: CI, dependency, docker

#5092 Catch Part.DoesNotExist
  InvenTree/part/models.py
Labels: bug

#5093 Scheduling api fix
  InvenTree/part/api.py
  InvenTree/part/test_api.py
Labels: bug, api

#5094 PartParameter API improvements
  InvenTree/InvenTree/api_version.py
  InvenTree/part/api.py
  InvenTree/part/serializers.py
Labels: api

#5083 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#5102 Variant low stock
  InvenTree/InvenTree/version.py
  InvenTree/part/api.py
Labels: api

#5103 Merge workflows
  .github/workflows/migration_test.yaml
  .github/workflows/qc_checks.yaml
Labels: CI, refactor

#5101 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#5105 Fix for stock status change
  InvenTree/templates/js/translated/stock.js
Labels: bug, user interface

#5115 Fix for index page badge
  InvenTree/templates/js/translated/index.js
Labels: bug, user interface

#5114 Child items table
  InvenTree/build/templates/build/detail.html
  InvenTree/company/templates/company/detail.html
  InvenTree/company/templates/company/supplier_part.html
  InvenTree/order/templates/order/purchase_order_detail.html
  InvenTree/part/templates/part/detail.html
  InvenTree/stock/api.py
  InvenTree/stock/templates/stock/item.html
  InvenTree/stock/templates/stock/location.html
  InvenTree/templates/js/translated/stock.js
Labels: bug, user interface

#5117 Transfer stock location
  InvenTree/part/tasks.py
  InvenTree/templates/js/translated/stock.js
Labels: stock, user interface

#5120 remove old method
  InvenTree/report/models.py
Labels: refactor

#5113 Get git log fix
  InvenTree/plugin/helpers.py
  InvenTree/plugin/plugin.py
Labels: plugin
