Repository inventree/InvenTree, pull requests merged in 2023-09, with the labels that each got.

#5502 Login form fix
  InvenTree/InvenTree/forms.py
  InvenTree/InvenTree/settings.py
Labels: bug, security, backport, backport-to-0.12.x

#5503 Paginate notifications on the server
  InvenTree/templates/js/translated/notification.js
Labels: user interface

#5505 Increase yarn timeout in dockerfile
  Dockerfile
Labels: docker, setup

#5487 Bump deps
  InvenTree/InvenTree/status.py
  requirements-dev.txt
  requirements.in
  requirements.txt
  src/frontend/package.json
  src/frontend/yarn.lock
Labels: dependency

#5511 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hi/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
  InvenTree/locale/zh_hant/LC_MESSAGES/django.po
  src/frontend/src/locales/de/messages.po
  src/frontend/src/locales/es/messages.po
  src/frontend/src/locales/hu/messages.po
  src/frontend/src/locales/pt/messages.po
  src/frontend/src/locales/zh/messages.po
Labels: translation

#5515 Issued by filter
  InvenTree/InvenTree/api_version.py
  InvenTree/build/api.py
  InvenTree/templates/js/translated/table_filters.js
Labels: api, build

#5355 Modal api forms
  src/frontend/package.json
  src/frontend/src/App.tsx
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/forms/fields/ChoiceField.tsx
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
  src/frontend/src/components/items/Thumbnail.tsx
  src/frontend/src/components/nav/SearchDrawer.tsx
  src/frontend/src/components/render/Company.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/render/Order.tsx
  src/frontend/src/components/render/Part.tsx
  src/frontend/src/components/render/Stock.tsx
  src/frontend/src/components/render/User.tsx
  src/frontend/src/components/tables/Column.tsx
  src/frontend/src/components/tables/RowActions.tsx
  src/frontend/src/components/tables/part/PartTable.tsx
  src/frontend/src/components/tables/stock/StockItemTable.tsx
  src/frontend/src/contexts/ThemeContext.tsx
  src/frontend/src/functions/forms.tsx
  src/frontend/src/functions/forms/PartForms.tsx
  src/frontend/src/functions/forms/StockForms.tsx
  src/frontend/src/functions/notifications.tsx
  src/frontend/src/functions/uid.tsx
  src/frontend/src/pages/Index/Playground.tsx
  src/frontend/yarn.lock
Labels: enhancement, Platform UI

#5518 Transfer fields
  InvenTree/InvenTree/api_version.py
  InvenTree/stock/models.py
  InvenTree/stock/serializers.py
Labels: stock, api

#5519 Refactor table columns
  src/frontend/src/components/tables/InvenTreeTable.tsx
  src/frontend/src/components/tables/RowActions.tsx
  src/frontend/src/components/tables/part/PartTable.tsx
  src/frontend/src/components/tables/stock/StockItemTable.tsx
Labels: Platform UI

#5480 Fix missing filters for get settings validator
  InvenTree/common/models.py
  InvenTree/common/tests.py
  InvenTree/plugin/samples/integration/sample.py
  InvenTree/plugin/samples/integration/test_sample.py
Labels: bug, plugin, backport, backport-to-0.12.x

#5521 [PUI] Part detail page
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/nav/PanelGroup.tsx
  src/frontend/src/components/nav/SearchDrawer.tsx
  src/frontend/src/components/tables/RowActions.tsx
  src/frontend/src/components/tables/part/PartTable.tsx
  src/frontend/src/defaults/links.tsx
  src/frontend/src/functions/forms/PartForms.tsx
  src/frontend/src/pages/Index/Part.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/part/PartIndex.tsx
  src/frontend/src/router.tsx
Labels: Platform UI

#5522 [0.12.x] Fix missing filters for get settings validator (#5480)
  InvenTree/common/models.py
  InvenTree/common/tests.py
  InvenTree/plugin/samples/integration/sample.py
  InvenTree/plugin/samples/integration/test_sample.py
Labels: bug

#5524 [PUI] Fix related field
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
Labels: bug, Platform UI

#5527 Fix for `%` (percent) unit (missing unary operator "%")
  InvenTree/InvenTree/conversion.py
  InvenTree/part/test_param.py
Labels: bug, backport, backport-to-0.12.x

#5525 [PUI] Attachment table
  InvenTree/InvenTree/api.py
  InvenTree/InvenTree/api_version.py
  InvenTree/build/api.py
  InvenTree/company/api.py
  InvenTree/order/api.py
  InvenTree/part/api.py
  InvenTree/stock/api.py
  src/frontend/src/components/items/AttachmentLink.tsx
  src/frontend/src/components/nav/PanelGroup.tsx
  src/frontend/src/components/tables/AttachmentTable.tsx
  src/frontend/src/components/tables/InvenTreeTable.tsx
  src/frontend/src/components/tables/RowActions.tsx
  src/frontend/src/functions/forms/AttachmentForms.tsx
  src/frontend/src/hooks/TableRefresh.tsx
  src/frontend/src/pages/part/PartDetail.tsx
Labels: api, Platform UI

#5529 [PUI] Implement Notes editor
  src/frontend/package.json
  src/frontend/src/components/widgets/MarkdownEditor.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/yarn.lock
Labels: Platform UI

#5530 [PUI] Add simple "related parts" table
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/items/Thumbnail.tsx
  src/frontend/src/components/tables/AttachmentTable.tsx
  src/frontend/src/components/tables/RowActions.tsx
  src/frontend/src/components/tables/part/RelatedPartTable.tsx
  src/frontend/src/functions/forms.tsx
  src/frontend/src/pages/part/PartDetail.tsx
Labels: Platform UI

#5534 Reset table pagination when search term changes
  src/frontend/src/components/tables/InvenTreeTable.tsx
Labels: bug, Platform UI

#5537 [PUI]: Basic notifications page
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/components/nav/MainMenu.tsx
  src/frontend/src/components/nav/NotificationDrawer.tsx
  src/frontend/src/components/tables/notifications/NotificationsTable.tsx
  src/frontend/src/pages/Notifications.tsx
  src/frontend/src/router.tsx
Labels: Platform UI

#5542 Update required parts for build orders
  InvenTree/build/models.py
  InvenTree/build/tasks.py
  InvenTree/part/models.py
Labels: bug, build, backport, backport-to-0.12.x

#5535 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hi/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
  InvenTree/locale/zh_hant/LC_MESSAGES/django.po
  src/frontend/src/locales/cs/messages.po
  src/frontend/src/locales/da/messages.po
  src/frontend/src/locales/de/messages.po
  src/frontend/src/locales/el/messages.po
  src/frontend/src/locales/en/messages.po
  src/frontend/src/locales/es/messages.po
  src/frontend/src/locales/fa/messages.po
  src/frontend/src/locales/fi/messages.po
  src/frontend/src/locales/fr/messages.po
  src/frontend/src/locales/he/messages.po
  src/frontend/src/locales/hi/messages.po
  src/frontend/src/locales/hu/messages.po
  src/frontend/src/locales/id/messages.po
  src/frontend/src/locales/it/messages.po
  src/frontend/src/locales/ja/messages.po
  src/frontend/src/locales/ko/messages.po
  src/frontend/src/locales/nl/messages.po
  src/frontend/src/locales/no/messages.po
  src/frontend/src/locales/pl/messages.po
  src/frontend/src/locales/pseudo-LOCALE/messages.po
  src/frontend/src/locales/pt/messages.po
  src/frontend/src/locales/ru/messages.po
  src/frontend/src/locales/sl/messages.po
  src/frontend/src/locales/sv/messages.po
  src/frontend/src/locales/th/messages.po
  src/frontend/src/locales/tr/messages.po
  src/frontend/src/locales/vi/messages.po
  src/frontend/src/locales/zh/messages.po
Labels: translation

#5546 Copy notes
  InvenTree/part/serializers.py
  InvenTree/templates/js/translated/part.js
Labels: part

#5544 Docker CI test
  .github/workflows/docker.yaml
  InvenTree/plugin/test_api.py
Labels: bug, CI, docker

#5500 PUI: Scan Page
  src/frontend/src/components/items/DocInfo.tsx
  src/frontend/src/components/items/DocTooltip.tsx
  src/frontend/src/components/items/Thumbnail.tsx
  src/frontend/src/components/items/TitleWithDoc.tsx
  src/frontend/src/components/renderers/BuildOrderRenderer.tsx
  src/frontend/src/components/renderers/GeneralRenderer.tsx
  src/frontend/src/components/renderers/PartRenderer.tsx
  src/frontend/src/components/renderers/PurchaseOrderRenderer.tsx
  src/frontend/src/components/renderers/SalesOrderRenderer.tsx
  src/frontend/src/components/renderers/StockItemRenderer.tsx
  src/frontend/src/components/renderers/StockLocationRenderer.tsx
  src/frontend/src/components/renderers/SupplierPartRenderer.tsx
  src/frontend/src/components/renderers/index.tsx
  src/frontend/src/defaults/menuItems.tsx
  src/frontend/src/pages/Index/Scan.tsx
  src/frontend/src/router.tsx
  src/frontend/src/states/ApiState.tsx
Labels: enhancement, barcode, Platform UI

#5552 Pin setuptools version for docker CI
  .github/workflows/docker.yaml
  docs/docs/settings/SSO.md
  docs/docs/start/config.md
Labels: bug, CI

#5554 [PUI] Build detail page
  src/frontend/src/components/items/Placeholder.tsx
  src/frontend/src/components/nav/BreadcrumbList.tsx
  src/frontend/src/components/nav/PageDetail.tsx
  src/frontend/src/components/nav/PanelGroup.tsx
  src/frontend/src/components/tables/InvenTreeTable.tsx
  src/frontend/src/components/tables/build/BuildOrderTable.tsx
  src/frontend/src/components/tables/stock/StockItemTable.tsx
  src/frontend/src/pages/Index/Build.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/build/BuildIndex.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/part/PartIndex.tsx
  src/frontend/src/router.tsx
Labels: Platform UI

#5555 [PUI] Part category page
  src/frontend/src/components/items/StylishText.tsx
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/components/nav/NotificationDrawer.tsx
  src/frontend/src/components/nav/PageDetail.tsx
  src/frontend/src/components/tables/AttachmentTable.tsx
  src/frontend/src/components/tables/InvenTreeTable.tsx
  src/frontend/src/components/tables/build/BuildOrderTable.tsx
  src/frontend/src/components/tables/notifications/NotificationsTable.tsx
  src/frontend/src/components/tables/part/PartCategoryTable.tsx
  src/frontend/src/components/tables/part/PartTable.tsx
  src/frontend/src/components/tables/part/RelatedPartTable.tsx
  src/frontend/src/components/tables/stock/StockItemTable.tsx
  src/frontend/src/hooks/TableRefresh.tsx
  src/frontend/src/pages/Index/Stock.tsx
  src/frontend/src/pages/Notifications.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/part/PartIndex.tsx
  src/frontend/src/router.tsx
Labels: Platform UI

#5562 Fix set password when no old password exists
  InvenTree/InvenTree/forms.py
  InvenTree/InvenTree/views.py
Labels: enhancement, backport, backport-to-0.12.x

#5564 [PUI] Instance hook
  src/frontend/src/hooks/UseInstance.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
Labels: api, Platform UI

#5566 [PUI] Stock location table
  src/frontend/src/components/nav/PanelGroup.tsx
  src/frontend/src/components/tables/AttachmentTable.tsx
  src/frontend/src/components/tables/stock/StockItemTable.tsx
  src/frontend/src/components/tables/stock/StockLocationTable.tsx
  src/frontend/src/pages/Index/Stock.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/router.tsx
Labels: Platform UI

#5567 Fix useInstance hook
  src/frontend/src/hooks/UseInstance.tsx
Labels: Platform UI

#5565 Update readthedocs
  readthedocs.yml
Labels: CI, documentation

#5569 Path detail API
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/email.py
  InvenTree/InvenTree/models.py
  InvenTree/part/api.py
  InvenTree/part/serializers.py
  InvenTree/part/test_api.py
  InvenTree/stock/api.py
  InvenTree/stock/serializers.py
Labels: api, Platform UI

#5570 Improve breadcrumbs using new path API
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: Platform UI

#5550 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hi/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
  InvenTree/locale/zh_hant/LC_MESSAGES/django.po
  src/frontend/src/locales/cs/messages.po
  src/frontend/src/locales/da/messages.po
  src/frontend/src/locales/de/messages.po
  src/frontend/src/locales/el/messages.po
  src/frontend/src/locales/en/messages.po
  src/frontend/src/locales/es/messages.po
  src/frontend/src/locales/fa/messages.po
  src/frontend/src/locales/fi/messages.po
  src/frontend/src/locales/fr/messages.po
  src/frontend/src/locales/he/messages.po
  src/frontend/src/locales/hi/messages.po
  src/frontend/src/locales/hu/messages.po
  src/frontend/src/locales/id/messages.po
  src/frontend/src/locales/it/messages.po
  src/frontend/src/locales/ja/messages.po
  src/frontend/src/locales/ko/messages.po
  src/frontend/src/locales/nl/messages.po
  src/frontend/src/locales/no/messages.po
  src/frontend/src/locales/pl/messages.po
  src/frontend/src/locales/pseudo-LOCALE/messages.po
  src/frontend/src/locales/pt/messages.po
  src/frontend/src/locales/ru/messages.po
  src/frontend/src/locales/sl/messages.po
  src/frontend/src/locales/sv/messages.po
  src/frontend/src/locales/th/messages.po
  src/frontend/src/locales/tr/messages.po
  src/frontend/src/locales/vi/messages.po
  src/frontend/src/locales/zh/messages.po
Labels: translation

#5572 Plugin loading fixes
  InvenTree/InvenTree/config.py
  InvenTree/InvenTree/urls.py
  InvenTree/plugin/base/integration/AppMixin.py
  InvenTree/plugin/registry.py
Labels: bug, plugin

#5574 Fix static url error for favicon.ico
  InvenTree/InvenTree/urls.py
Labels: bug

#5575 [P UI] Router syntax switch
  src/frontend/src/router.tsx
  src/frontend/src/views/DesktopAppView.tsx
Labels: refactor, Platform UI

#5577 [P UI] Make base url configurable
  InvenTree/InvenTree/middleware.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/tests.py
  InvenTree/config_template.yaml
  InvenTree/web/templatetags/spa_helper.py
  InvenTree/web/urls.py
  src/frontend/src/main.tsx
  src/frontend/src/views/DesktopAppView.tsx
Labels: enhancement, setup, refactor, Platform UI

#5580 Update context_variables.md
  docs/docs/report/context_variables.md
Labels: documentation

#5581 Update context_variables.md
  docs/docs/report/context_variables.md
Labels: documentation

#5583 Add validation check to "Convert to Variant" form
  InvenTree/label/tests.py
  InvenTree/stock/serializers.py
Labels: bug, backport, backport-to-0.12.x

#5592 Primary address fix
  InvenTree/company/models.py
  InvenTree/company/serializers.py
  InvenTree/company/tests.py
  InvenTree/templates/js/translated/company.js
Labels: bug, backport, backport-to-0.12.x

#5599 Make idAccessor configurable
  src/frontend/src/components/tables/InvenTreeTable.tsx
Labels: refactor, Platform UI

#5608 Interactive forms
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
  src/frontend/src/functions/forms/StockForms.tsx
Labels: Platform UI

#5609 Update minimum_stock field
  InvenTree/part/migrations/0114_alter_part_minimum_stock.py
  InvenTree/part/models.py
  InvenTree/part/templates/part/part_base.html
Labels: part

#5613 Use prefetch to improve query efficiency
  InvenTree/users/models.py
Labels: backport, backport-to-0.12.x

#5612 Fix bug in loading setting from cache
  InvenTree/build/test_build.py
  InvenTree/common/models.py
  InvenTree/common/settings.py
Labels: bug, backport, backport-to-0.12.x

#5617 Adds optional config setting to enable database level logging
  InvenTree/InvenTree/settings.py
  InvenTree/config_template.yaml
  docker.dev.env
  docs/docs/start/config.md
Labels: setup, documentation

#5573 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hi/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
  InvenTree/locale/zh_hant/LC_MESSAGES/django.po
  src/frontend/src/locales/cs/messages.po
  src/frontend/src/locales/da/messages.po
  src/frontend/src/locales/de/messages.po
  src/frontend/src/locales/el/messages.po
  src/frontend/src/locales/en/messages.po
  src/frontend/src/locales/es/messages.po
  src/frontend/src/locales/fa/messages.po
  src/frontend/src/locales/fi/messages.po
  src/frontend/src/locales/fr/messages.po
  src/frontend/src/locales/he/messages.po
  src/frontend/src/locales/hi/messages.po
  src/frontend/src/locales/hu/messages.po
  src/frontend/src/locales/id/messages.po
  src/frontend/src/locales/it/messages.po
  src/frontend/src/locales/ja/messages.po
  src/frontend/src/locales/ko/messages.po
  src/frontend/src/locales/nl/messages.po
  src/frontend/src/locales/no/messages.po
  src/frontend/src/locales/pl/messages.po
  src/frontend/src/locales/pseudo-LOCALE/messages.po
  src/frontend/src/locales/pt/messages.po
  src/frontend/src/locales/ru/messages.po
  src/frontend/src/locales/sl/messages.po
  src/frontend/src/locales/sv/messages.po
  src/frontend/src/locales/th/messages.po
  src/frontend/src/locales/tr/messages.po
  src/frontend/src/locales/vi/messages.po
  src/frontend/src/locales/zh/messages.po
Labels: translation

#5622 Exception handling
  InvenTree/InvenTree/apps.py
  InvenTree/common/models.py
  InvenTree/label/apps.py
  InvenTree/part/apps.py
Labels: bug

#5620 Add flake8-logging linting
  .pre-commit-config.yaml
  InvenTree/InvenTree/apps.py
  InvenTree/InvenTree/config.py
  InvenTree/InvenTree/conversion.py
  InvenTree/InvenTree/forms.py
  InvenTree/InvenTree/management/commands/clean_settings.py
  InvenTree/InvenTree/management/commands/rebuild_thumbnails.py
  InvenTree/InvenTree/middleware.py
  InvenTree/InvenTree/models.py
  InvenTree/InvenTree/sentry.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/social_auth_urls.py
  InvenTree/InvenTree/tasks.py
  InvenTree/build/models.py
  InvenTree/build/tasks.py
  InvenTree/common/models.py
  InvenTree/common/notifications.py
  InvenTree/common/tasks.py
  InvenTree/label/apps.py
  InvenTree/order/models.py
  InvenTree/part/apps.py
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/part/stocktake.py
  InvenTree/part/tasks.py
  InvenTree/part/templatetags/inventree_extras.py
  InvenTree/part/templatetags/sso.py
  InvenTree/plugin/base/event/events.py
  InvenTree/plugin/base/integration/AppMixin.py
  InvenTree/plugin/base/integration/ScheduleMixin.py
  InvenTree/plugin/base/integration/SettingsMixin.py
  InvenTree/plugin/base/integration/mixins.py
  InvenTree/plugin/base/label/label.py
  InvenTree/plugin/base/locate/mixins.py
  InvenTree/plugin/helpers.py
  InvenTree/plugin/registry.py
  InvenTree/plugin/samples/event/event_sample.py
  InvenTree/plugin/samples/locate/locate_sample.py
  InvenTree/plugin/views.py
  InvenTree/report/apps.py
  InvenTree/report/models.py
  InvenTree/report/templatetags/report.py
  InvenTree/users/apps.py
  InvenTree/users/models.py
  docker/gunicorn.conf.py
Labels: CI, refactor

#5628 Fixed LOG style errors
  InvenTree/InvenTree/apps.py
  InvenTree/InvenTree/tests.py
  InvenTree/common/tests.py
  InvenTree/label/apps.py
  InvenTree/part/apps.py
Labels: bug

#5623 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hi/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
  InvenTree/locale/zh_hant/LC_MESSAGES/django.po
  src/frontend/src/locales/de/messages.po
  src/frontend/src/locales/en/messages.po
  src/frontend/src/locales/es/messages.po
  src/frontend/src/locales/hi/messages.po
  src/frontend/src/locales/hu/messages.po
  src/frontend/src/locales/pseudo-LOCALE/messages.po
  src/frontend/src/locales/pt/messages.po
  src/frontend/src/locales/th/messages.po
  src/frontend/src/locales/vi/messages.po
  src/frontend/src/locales/zh/messages.po
Labels: translation
