Repository inventree/InvenTree, pull requests merged in 2023-11, with the labels that each got.

#5786 Printing options
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/metadata.py
  InvenTree/InvenTree/permissions.py
  InvenTree/label/api.py
  InvenTree/plugin/base/label/mixins.py
  InvenTree/plugin/base/label/test_label_mixin.py
  InvenTree/plugin/samples/integration/label_sample.py
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/label.js
  docs/docs/extend/plugins/label.md
Labels: enhancement, plugin, api

#5833 [React] SupplierPart table
  InvenTree/company/serializers.py
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/images/Thumbnail.tsx
  src/frontend/src/components/render/Company.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/settings/SettingItem.tsx
  src/frontend/src/components/tables/InvenTreeTable.tsx
  src/frontend/src/components/tables/RowActions.tsx
  src/frontend/src/components/tables/TableHoverCard.tsx
  src/frontend/src/components/tables/bom/BomTable.tsx
  src/frontend/src/components/tables/general/AttachmentTable.tsx
  src/frontend/src/components/tables/part/PartParameterTable.tsx
  src/frontend/src/components/tables/part/PartTable.tsx
  src/frontend/src/components/tables/part/RelatedPartTable.tsx
  src/frontend/src/components/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/components/tables/purchasing/SupplierPartTable.tsx
  src/frontend/src/components/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/components/tables/sales/SalesOrderTable.tsx
  src/frontend/src/components/tables/settings/CustomUnitsTable.tsx
  src/frontend/src/components/tables/settings/ProjectCodeTable.tsx
  src/frontend/src/components/tables/stock/StockItemTable.tsx
  src/frontend/src/forms/AttachmentForms.tsx
  src/frontend/src/forms/CompanyForms.tsx
  src/frontend/src/forms/PartForms.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/functions/forms.tsx
  src/frontend/src/functions/forms/CompanyForms.tsx
  src/frontend/src/pages/Index/Playground.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: user interface, Platform UI

#5834 Addec context variables for contacts to docs
  InvenTree/company/.models.py.swp
  docs/docs/report/context_variables.md
  docs/docs/report/purchase_order.md
Labels: report, documentation

#5822 [PUI] Settings simplification and restructure
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/social_auth_urls.py
  InvenTree/InvenTree/urls.py
  src/frontend/src/components/nav/MainMenu.tsx
  src/frontend/src/components/nav/SettingsHeader.tsx
  src/frontend/src/pages/Index/Profile/Profile.tsx
  src/frontend/src/pages/Index/Profile/UserPanel.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/AccountDetailPanel.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/DisplaySettingsPanel.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/SecurityContent.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/UserPanel.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/UserThemePanel.tsx
  src/frontend/src/pages/Index/Settings/PluginSettings.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/pages/Index/Settings/UserSettings.tsx
  src/frontend/src/router.tsx
  src/frontend/src/states/ApiState.tsx
Labels: enhancement, Platform UI

#5842 Wrap inventreeBranch check in try/except
  InvenTree/InvenTree/version.py
Labels: bug

#5844 Prevent settings from writing to the database during import
  InvenTree/common/models.py
Labels: bug, backport, backport-to-0.12.x

#5843 Fix exchange rate updates
  InvenTree/InvenTree/exchange.py
Labels: bug, pricing

#5851 Deactivated coverage analyzer
  .deepsource.toml
Labels: CI

#5852 Small size optimisation for devcontainer
  .devcontainer/Dockerfile
Labels: docker, setup

#5854 Bump python dependencies
  requirements-dev.txt
  requirements.txt
Labels: dependency

#5857 [PUI] Added pricing settings
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
Labels: Platform UI

#5856 Use gpg for install script instead of apt-key
  contrib/install.sh
  contrib/installer/src/root_command.sh
Labels: setup

#5847 [React] PO detail pgae
  src/frontend/src/components/buttons/ActionButton.tsx
  src/frontend/src/components/buttons/AddItemButton.tsx
  src/frontend/src/components/buttons/ButtonMenu.tsx
  src/frontend/src/components/items/ActionButton.tsx
  src/frontend/src/components/items/ActionDropdown.tsx
  src/frontend/src/components/items/ProgressBar.tsx
  src/frontend/src/components/render/Company.tsx
  src/frontend/src/components/render/User.tsx
  src/frontend/src/components/renderers/PurchaseOrderRenderer.tsx
  src/frontend/src/components/tables/Column.tsx
  src/frontend/src/components/tables/ColumnSelect.tsx
  src/frontend/src/components/tables/InvenTreeTable.tsx
  src/frontend/src/components/tables/RowActions.tsx
  src/frontend/src/components/tables/TableHoverCard.tsx
  src/frontend/src/components/tables/bom/BomTable.tsx
  src/frontend/src/components/tables/bom/UsedInTable.tsx
  src/frontend/src/components/tables/build/BuildOrderTable.tsx
  src/frontend/src/components/tables/general/AttachmentTable.tsx
  src/frontend/src/components/tables/general/CompanyTable.tsx
  src/frontend/src/components/tables/part/PartCategoryTable.tsx
  src/frontend/src/components/tables/part/PartParameterTable.tsx
  src/frontend/src/components/tables/part/PartTable.tsx
  src/frontend/src/components/tables/plugin/PluginListTable.tsx
  src/frontend/src/components/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/components/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/components/tables/purchasing/SupplierPartTable.tsx
  src/frontend/src/components/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/components/tables/sales/SalesOrderTable.tsx
  src/frontend/src/components/tables/settings/CustomUnitsTable.tsx
  src/frontend/src/components/tables/settings/ProjectCodeTable.tsx
  src/frontend/src/components/tables/stock/StockItemTable.tsx
  src/frontend/src/components/tables/stock/StockLocationTable.tsx
  src/frontend/src/forms/PurchaseOrderForms.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/states/ApiState.tsx
Labels: user interface, Platform UI

#5858 [React] Currency table
  src/frontend/src/components/nav/PanelGroup.tsx
  src/frontend/src/components/tables/InvenTreeTable.tsx
  src/frontend/src/components/tables/settings/CurrencyTable.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/states/ApiState.tsx
Labels: Platform UI

#5859 [React] Build improvements
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/items/ActionDropdown.tsx
  src/frontend/src/components/render/Generic.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/render/ModelType.tsx
  src/frontend/src/components/tables/build/BuildOrderTable.tsx
  src/frontend/src/forms/BuildForms.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/build/BuildIndex.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/states/ApiState.tsx
Labels: Platform UI

#5862 [PUI] Add user managment to frontend
  src/frontend/src/components/nav/MainMenu.tsx
  src/frontend/src/components/nav/PanelGroup.tsx
  src/frontend/src/components/nav/SettingsHeader.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter.tsx
  src/frontend/src/router.tsx
Labels: enhancement, api, Platform UI

#5860 [React] Order tables
  InvenTree/InvenTree/api_version.py
  InvenTree/order/serializers.py
  src/frontend/src/components/renderers/StatusRenderer.tsx
  src/frontend/src/components/tables/ColumnRenderers.tsx
  src/frontend/src/components/tables/TableHoverCard.tsx
  src/frontend/src/components/tables/build/BuildOrderTable.tsx
  src/frontend/src/components/tables/general/CompanyTable.tsx
  src/frontend/src/components/tables/part/PartCategoryTable.tsx
  src/frontend/src/components/tables/part/PartTable.tsx
  src/frontend/src/components/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/components/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/components/tables/purchasing/SupplierPartTable.tsx
  src/frontend/src/components/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/components/tables/sales/SalesOrderTable.tsx
  src/frontend/src/components/tables/settings/ProjectCodeTable.tsx
  src/frontend/src/components/tables/stock/StockItemTable.tsx
  src/frontend/src/components/tables/stock/StockLocationTable.tsx
Labels: order, user interface, api, Platform UI

#5771 [PUI] Add more formatters
  src/frontend/src/components/tables/ColumnRenderers.tsx
  src/frontend/src/components/tables/build/BuildOrderTable.tsx
  src/frontend/src/components/tables/stock/StockItemTable.tsx
  src/frontend/src/defaults/formatters.tsx
  src/frontend/src/states/SettingsState.tsx
  src/frontend/src/states/states.tsx
Labels: enhancement, Platform UI

#5864 [PUI] Added tests for PUI backend stuff
  InvenTree/web/tests.py
Labels: CI

#5867 Fixed error "Line 39 in Markdown file: Encountered unknown tag 'load'."
  docs/docs/extend/plugins/urls.md
Labels: documentation

#5855 [PUI] Small nav additions
  src/frontend/src/components/items/InvenTreeLogo.tsx
  src/frontend/src/components/nav/Footer.tsx
  src/frontend/src/components/nav/NavHoverMenu.tsx
  src/frontend/src/defaults/menuItems.tsx
Labels: Platform UI

#5871 PO auto fill fix
  InvenTree/templates/js/translated/purchase_order.js
  docs/docs/extend/plugins/panel.md
  docs/docs/extend/plugins/urls.md
Labels: order, user interface

#5872 Ulugbek erkinov master
  InvenTree/InvenTree/api_version.py
  InvenTree/stock/serializers.py
  InvenTree/templates/js/translated/stock.js
Labels: stock, api

#5874 Fully remove deepsource cov
  .github/workflows/qc_checks.yaml
Labels: bug, CI

#5865 Expose API version descriptors for admins via API
  InvenTree/InvenTree/api.py
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/test_api_version.py
  InvenTree/InvenTree/urls.py
  InvenTree/InvenTree/version.py
Labels: enhancement, api

#5876 [Platform] BOM Table
  InvenTree/InvenTree/api_version.py
  InvenTree/part/api.py
  InvenTree/part/serializers.py
  src/frontend/src/components/items/YesNoButton.tsx
  src/frontend/src/components/tables/ColumnRenderers.tsx
  src/frontend/src/components/tables/bom/BomTable.tsx
  src/frontend/src/forms/BomForms.tsx
Labels: user interface, Platform UI

#5880 Pinned action column
  src/frontend/package.json
  src/frontend/src/components/tables/InvenTreeTable.tsx
  src/frontend/src/components/tables/RowActions.tsx
  src/frontend/yarn.lock
Labels: Platform UI

#5881 Allow decimal values in new forms
  src/frontend/src/components/forms/fields/ApiFormField.tsx
Labels: Platform UI

#5878 Added a chapter for more complicated data
  docs/docs/extend/plugins/panel.md
Labels: documentation

#5883 Label sheet printer
  InvenTree/label/api.py
  InvenTree/label/models.py
  InvenTree/label/templates/label/buildline/buildline_label_base.html
  InvenTree/label/templates/label/label_base.html
  InvenTree/label/templates/label/part/part_label.html
  InvenTree/label/templates/label/part/part_label_code128.html
  InvenTree/label/templates/label/stockitem/qr.html
  InvenTree/label/templates/label/stocklocation/qr.html
  InvenTree/label/templates/label/stocklocation/qr_and_text.html
  InvenTree/plugin/base/label/test_label_mixin.py
  InvenTree/plugin/builtin/labels/inventree_label.py
  InvenTree/plugin/builtin/labels/label_sheet.py
  InvenTree/report/helpers.py
  docs/docs/extend/plugins/panel.md
Labels: enhancement, plugin, report

#5887 Update sponsors action
  .github/workflows/sponsors.yml
Labels: CI

#5891 Token admin fix
  InvenTree/users/admin.py
  InvenTree/users/migrations/0010_alter_apitoken_key.py
  InvenTree/users/models.py
Labels: bug

#5892 Parameter table updates
  src/frontend/src/components/nav/PanelGroup.tsx
  src/frontend/src/components/tables/RowActions.tsx
  src/frontend/src/components/tables/TableHoverCard.tsx
  src/frontend/src/components/tables/bom/BomTable.tsx
  src/frontend/src/components/tables/part/PartParameterTable.tsx
  src/frontend/src/components/tables/part/PartParameterTemplateTable.tsx
  src/frontend/src/components/tables/part/RelatedPartTable.tsx
  src/frontend/src/components/tables/plugin/PluginListTable.tsx
  src/frontend/src/components/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/components/tables/purchasing/SupplierPartTable.tsx
  src/frontend/src/components/tables/settings/CustomUnitsTable.tsx
  src/frontend/src/components/tables/settings/ProjectCodeTable.tsx
  src/frontend/src/forms/PartForms.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/pages/Notifications.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/states/UserState.tsx
Labels: user interface, Platform UI

#5895 Activate / deactivate plugins
  src/frontend/src/components/tables/plugin/PluginListTable.tsx
Labels: plugin, Platform UI

#5896 Updated URL documentation with more information about panels
  docs/docs/extend/plugins/urls.md
Labels: plugin, documentation

#5900 Minor documentation updates
  docs/docs/extend/plugins/urls.md
Labels: documentation

#5902 [Doc] python example Part uploadImage correction
  docs/docs/api/python/examples.md
Labels: bug, documentation

#5889 Bumped docker base image
  Dockerfile
Labels: dependency, docker

#5875 Added first UI components for user managment
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/serializers.py
  InvenTree/users/api.py
  src/frontend/src/components/nav/SettingsHeader.tsx
  src/frontend/src/components/tables/settings/GroupTable.tsx
  src/frontend/src/components/tables/settings/UserDrawer.tsx
  src/frontend/src/components/tables/settings/UserTable.tsx
  src/frontend/src/defaults/menuItems.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter.tsx
  src/frontend/src/states/ApiState.tsx
Labels: enhancement, Platform UI

#5905 Revert "Bumped docker base image"
  Dockerfile
Labels: bug, CI, docker

#5906 Owner list API updates
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/purchase_order.js
  InvenTree/templates/js/translated/return_order.js
  InvenTree/templates/js/translated/sales_order.js
  InvenTree/users/api.py
Labels: api

#5837 Form improvements
  InvenTree/InvenTree/metadata.py
  InvenTree/InvenTree/serializers.py
  InvenTree/label/api.py
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/label.js
Labels: enhancement, user interface

#5910 Improve RenderOwner function
  src/frontend/src/components/render/User.tsx
  src/frontend/src/forms/BuildForms.tsx
  src/frontend/src/forms/PartForms.tsx
Labels: Platform UI

#5907 Report image rendering fix
  InvenTree/InvenTree/api_version.py
  InvenTree/label/tests.py
  InvenTree/report/helpers.py
  InvenTree/report/templates/report/inventree_bill_of_materials_report.html
  InvenTree/report/templates/report/inventree_build_order_base.html
  InvenTree/report/templates/report/inventree_po_report_base.html
  InvenTree/report/templates/report/inventree_return_order_report_base.html
  InvenTree/report/templates/report/inventree_so_report_base.html
  InvenTree/report/templates/report/inventree_test_report_base.html
  InvenTree/report/templatetags/barcode.py
  InvenTree/report/templatetags/report.py
  InvenTree/report/tests.py
  docs/docs/report/helpers.md
Labels: report

#5913 Revert "Form improvements"
  InvenTree/InvenTree/metadata.py
  InvenTree/InvenTree/serializers.py
  InvenTree/label/api.py
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/label.js
Labels: bug, user interface

#5912 Added order cancel notifications
  InvenTree/build/models.py
  InvenTree/common/notifications.py
  InvenTree/order/models.py
  InvenTree/templates/email/canceled_order_assigned.html
Labels: enhancement, order

#5916 Distinct query fix
  InvenTree/build/models.py
  InvenTree/company/api.py
  InvenTree/company/models.py
  InvenTree/part/api.py
  InvenTree/stock/api.py
  InvenTree/stock/test_api.py
Labels: bug, backport, backport-to-0.12.x

#5918 Fix some issues in report docs.
  docs/docs/report/purchase_order.md
Labels: documentation

#5920 Quick fix for unit test
  InvenTree/stock/test_api.py
Labels: bug, CI

#5917 Cherry pick changes from fe0d9c19230013471a2100fbc1f41c7694f318fa
  InvenTree/InvenTree/version.py
  InvenTree/build/models.py
  InvenTree/company/api.py
  InvenTree/company/models.py
  InvenTree/part/api.py
  InvenTree/stock/api.py
  InvenTree/stock/test_api.py
Labels: bug

#5919 Fix some issues with supplier barcode plugins
  InvenTree/plugin/base/barcodes/api.py
  InvenTree/plugin/base/barcodes/mixins.py
  InvenTree/plugin/builtin/suppliers/digikey.py
  InvenTree/plugin/builtin/suppliers/lcsc.py
  InvenTree/plugin/builtin/suppliers/mouser.py
  InvenTree/plugin/builtin/suppliers/tme.py
Labels: barcode, plugin

#5921 Refactoring
  InvenTree/plugin/base/barcodes/api.py
  InvenTree/plugin/base/barcodes/mixins.py
Labels: barcode, plugin, refactor

#5922 Refactoring supplier barcode support
  InvenTree/plugin/base/barcodes/api.py
  InvenTree/plugin/base/barcodes/mixins.py
  InvenTree/plugin/builtin/suppliers/digikey.py
  InvenTree/plugin/builtin/suppliers/lcsc.py
  InvenTree/plugin/builtin/suppliers/mouser.py
  InvenTree/plugin/builtin/suppliers/test_supplier_barcodes.py
  InvenTree/plugin/builtin/suppliers/tme.py
Labels: barcode, plugin

#5925 Factored typecasting out
  InvenTree/InvenTree/config.py
Labels: refactor

#5931 Only run sposnor action if on upstream repo
  .github/workflows/sponsors.yml
Labels: CI

#5885 Bump weasyprint
  InvenTree/plugin/base/label/test_label_mixin.py
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: dependency

#5926 New Crowdin updates
  InvenTree/locale/bg/LC_MESSAGES/django.po
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hi/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
  InvenTree/locale/zh_hant/LC_MESSAGES/django.po
  src/frontend/src/locales/bg/messages.po
  src/frontend/src/locales/cs/messages.po
  src/frontend/src/locales/da/messages.po
  src/frontend/src/locales/de/messages.po
  src/frontend/src/locales/el/messages.po
  src/frontend/src/locales/es/messages.po
  src/frontend/src/locales/fa/messages.po
  src/frontend/src/locales/fi/messages.po
  src/frontend/src/locales/fr/messages.po
  src/frontend/src/locales/he/messages.po
  src/frontend/src/locales/hi/messages.po
  src/frontend/src/locales/hu/messages.po
  src/frontend/src/locales/it/messages.po
  src/frontend/src/locales/ja/messages.po
  src/frontend/src/locales/ko/messages.po
  src/frontend/src/locales/nl/messages.po
  src/frontend/src/locales/no/messages.po
  src/frontend/src/locales/pl/messages.po
  src/frontend/src/locales/pt/messages.po
  src/frontend/src/locales/ru/messages.po
  src/frontend/src/locales/sl/messages.po
  src/frontend/src/locales/sv/messages.po
  src/frontend/src/locales/th/messages.po
  src/frontend/src/locales/tr/messages.po
  src/frontend/src/locales/vi/messages.po
  src/frontend/src/locales/zh/messages.po
Labels: translation

#5937 Refactor existing barcode API endpoints
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/helpers_model.py
  InvenTree/order/models.py
  InvenTree/plugin/base/barcodes/api.py
  InvenTree/plugin/base/barcodes/serializers.py
  InvenTree/plugin/base/barcodes/test_barcode.py
  InvenTree/plugin/builtin/barcodes/inventree_barcode.py
  InvenTree/plugin/builtin/barcodes/test_inventree_barcode.py
Labels: barcode, plugin, api, refactor

#5934 [PUI] Api state extension/cleanup
  src/frontend/src/components/tables/settings/UserDrawer.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/SecurityContent.tsx
  src/frontend/src/states/ApiState.tsx
  src/frontend/src/states/UserState.tsx
  src/frontend/src/states/states.tsx
Labels: Platform UI

#5940 API bug fix: Distinct query
  InvenTree/order/api.py
  InvenTree/stock/api.py
  InvenTree/stock/test_api.py
Labels: bug, api

#5943 Fixes call to processField
  InvenTree/templates/js/translated/forms.js
Labels: bug, user interface

#5897 Make modals/forms more reactive
  InvenTree/part/serializers.py
  src/frontend/package.json
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/forms/fields/ChoiceField.tsx
  src/frontend/src/components/forms/fields/NestedObjectField.tsx
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
  src/frontend/src/components/settings/SettingItem.tsx
  src/frontend/src/components/tables/purchasing/SupplierPartTable.tsx
  src/frontend/src/contexts/LanguageContext.tsx
  src/frontend/src/forms/CompanyForms.tsx
  src/frontend/src/forms/PartForms.tsx
  src/frontend/src/forms/PurchaseOrderForms.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/functions/forms.tsx
  src/frontend/src/hooks/UseForm.tsx
  src/frontend/src/hooks/UseModal.tsx
  src/frontend/src/pages/Index/Playground.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/yarn.lock
Labels: refactor, Platform UI

#5947 PUI general improvements
  src/frontend/src/components/buttons/ButtonMenu.tsx
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/items/ActionDropdown.tsx
  src/frontend/src/components/nav/BreadcrumbList.tsx
  src/frontend/src/components/nav/NotificationDrawer.tsx
  src/frontend/src/components/nav/PageDetail.tsx
  src/frontend/src/components/nav/PanelGroup.tsx
  src/frontend/src/components/nav/SearchDrawer.tsx
  src/frontend/src/components/settings/SettingItem.tsx
  src/frontend/src/components/settings/SettingList.tsx
  src/frontend/src/components/tables/Column.tsx
  src/frontend/src/components/tables/InvenTreeTable.tsx
  src/frontend/src/components/tables/RowActions.tsx
  src/frontend/src/functions/forms.tsx
  src/frontend/src/states/ApiState.tsx
  src/frontend/src/states/SessionState.tsx
  src/frontend/src/states/SettingsState.tsx
Labels: enhancement, Platform UI

#5949 PO barcode- add line
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/models.py
  InvenTree/company/migrations/0068_auto_20231120_1108.py
  InvenTree/company/models.py
  InvenTree/company/serializers.py
  InvenTree/plugin/base/barcodes/api.py
  InvenTree/plugin/base/barcodes/serializers.py
  InvenTree/plugin/builtin/barcodes/inventree_barcode.py
Labels: enhancement, barcode, api

#5956 Part pricing override
  InvenTree/InvenTree/api_version.py
  InvenTree/part/migrations/0119_auto_20231120_0457.py
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/part/templates/part/prices.html
  InvenTree/part/templates/part/pricing_javascript.html
  docs/docs/part/pricing.md
Labels: part, api, pricing, migration

#5960 Bug fix: distinct query
  InvenTree/order/api.py
  InvenTree/stock/api.py
  InvenTree/stock/test_api.py
Labels: bug, api

#5958 Update docker workflow action
  .github/workflows/docker.yaml
Labels: CI, docker

#5909 Docker CI Updates
  .github/workflows/docker.yaml
  InvenTree/plugin/test_api.py
  docker/requirements.txt
  tasks.py
Labels: CI, dependency, docker

#5963 Revert base requirements for docker build
  docker/requirements.txt
Labels: bug, CI, docker

#5969 [PUI] Fixed a few modeltype links
  src/frontend/src/components/render/ModelType.tsx
Labels: bug, Platform UI

#5970 Add custom InvenTreeDateFilter class
  InvenTree/InvenTree/filters.py
  InvenTree/part/api.py
  InvenTree/stock/api.py
Labels: bug, api

#5971 add ability to export part image data
  InvenTree/part/admin.py
Labels: importer

#5976 Improve handling of checkUserRole
  src/frontend/src/states/UserState.tsx
Labels: bug, Platform UI

#5979 API filter fix
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/filters.py
  InvenTree/part/fixtures/part.yaml
  InvenTree/part/serializers.py
  InvenTree/part/test_api.py
  docker/production/.env
Labels: bug, api

#5985 Translation string fixes
  src/frontend/src/components/modals/ServerInfoModal.tsx
  src/frontend/src/components/tables/settings/UserTable.tsx
Labels: bug, translation

#5987 Translation test : Add context
  InvenTree/company/models.py
Labels: translation

#5980 New Crowdin updates
  InvenTree/locale/bg/LC_MESSAGES/django.po
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hi/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
  InvenTree/locale/zh_hant/LC_MESSAGES/django.po
  src/frontend/src/locales/bg/messages.po
  src/frontend/src/locales/cs/messages.po
  src/frontend/src/locales/da/messages.po
  src/frontend/src/locales/de/messages.po
  src/frontend/src/locales/el/messages.po
  src/frontend/src/locales/es/messages.po
  src/frontend/src/locales/fa/messages.po
  src/frontend/src/locales/fi/messages.po
  src/frontend/src/locales/fr/messages.po
  src/frontend/src/locales/he/messages.po
  src/frontend/src/locales/hi/messages.po
  src/frontend/src/locales/hu/messages.po
  src/frontend/src/locales/it/messages.po
  src/frontend/src/locales/ja/messages.po
  src/frontend/src/locales/ko/messages.po
  src/frontend/src/locales/nl/messages.po
  src/frontend/src/locales/no/messages.po
  src/frontend/src/locales/pl/messages.po
  src/frontend/src/locales/pt/messages.po
  src/frontend/src/locales/ru/messages.po
  src/frontend/src/locales/sl/messages.po
  src/frontend/src/locales/sv/messages.po
  src/frontend/src/locales/th/messages.po
  src/frontend/src/locales/tr/messages.po
  src/frontend/src/locales/vi/messages.po
  src/frontend/src/locales/zh/messages.po
Labels: translation

#5986 Store data from example panel
  docs/docs/extend/plugins/panel.md
Labels: documentation

#5977 [PUI] Helper to render an instance for an url
  src/frontend/src/components/render/InstanceFromUrl.tsx
Labels: Platform UI

#5989 [PUI] URL fixes
  InvenTree/InvenTree/urls.py
  InvenTree/web/urls.py
Labels: bug, refactor, Platform UI

#5990 Fix 'Maximimum' typo
  InvenTree/common/models.py
Labels: translation

#5993 [PUI] Template helpers
  InvenTree/web/templatetags/spa_helper.py
Labels: Platform UI

#6000 Add useTable hook
  src/frontend/src/components/tables/InvenTreeTable.tsx
  src/frontend/src/components/tables/bom/BomTable.tsx
  src/frontend/src/components/tables/bom/UsedInTable.tsx
  src/frontend/src/components/tables/build/BuildOrderTable.tsx
  src/frontend/src/components/tables/general/AttachmentTable.tsx
  src/frontend/src/components/tables/general/CompanyTable.tsx
  src/frontend/src/components/tables/notifications/NotificationsTable.tsx
  src/frontend/src/components/tables/part/PartCategoryTable.tsx
  src/frontend/src/components/tables/part/PartParameterTable.tsx
  src/frontend/src/components/tables/part/PartParameterTemplateTable.tsx
  src/frontend/src/components/tables/part/PartTable.tsx
  src/frontend/src/components/tables/part/RelatedPartTable.tsx
  src/frontend/src/components/tables/plugin/PluginListTable.tsx
  src/frontend/src/components/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/components/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/components/tables/purchasing/SupplierPartTable.tsx
  src/frontend/src/components/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/components/tables/sales/SalesOrderTable.tsx
  src/frontend/src/components/tables/settings/CurrencyTable.tsx
  src/frontend/src/components/tables/settings/CustomUnitsTable.tsx
  src/frontend/src/components/tables/settings/GroupTable.tsx
  src/frontend/src/components/tables/settings/ProjectCodeTable.tsx
  src/frontend/src/components/tables/settings/UserTable.tsx
  src/frontend/src/components/tables/stock/StockItemTable.tsx
  src/frontend/src/components/tables/stock/StockLocationTable.tsx
  src/frontend/src/hooks/TableRefresh.tsx
  src/frontend/src/hooks/UseTable.tsx
  src/frontend/src/pages/Notifications.tsx
Labels: refactor, Platform UI

#5999 More tables
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/items/YesNoButton.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/tables/bom/BomTable.tsx
  src/frontend/src/components/tables/company/AddressTable.tsx
  src/frontend/src/components/tables/company/CompanyTable.tsx
  src/frontend/src/components/tables/company/ContactTable.tsx
  src/frontend/src/components/tables/part/PartParameterTable.tsx
  src/frontend/src/components/tables/part/PartParameterTemplateTable.tsx
  src/frontend/src/components/tables/part/PartVariantTable.tsx
  src/frontend/src/components/tables/part/RelatedPartTable.tsx
  src/frontend/src/components/tables/purchasing/SupplierPartTable.tsx
  src/frontend/src/components/tables/settings/CustomUnitsTable.tsx
  src/frontend/src/components/tables/settings/GroupTable.tsx
  src/frontend/src/components/tables/settings/ProjectCodeTable.tsx
  src/frontend/src/components/tables/settings/UserTable.tsx
  src/frontend/src/forms/AttachmentForms.tsx
  src/frontend/src/forms/CompanyForms.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/purchasing/PurchasingIndex.tsx
  src/frontend/src/pages/sales/SalesIndex.tsx
Labels: Platform UI

#6005 Fix reloading on viewport size change
  src/frontend/src/App.tsx
Labels: bug, Platform UI

#6008 [PUI] Allow rendering of custom states
  src/frontend/src/components/render/StatusRenderer.tsx
  src/frontend/src/states/ApiState.tsx
Labels: enhancement, Platform UI

#6003 LDAP group membership support
  InvenTree/InvenTree/settings.py
  InvenTree/config_template.yaml
  docs/docs/start/advanced.md
Labels: enhancement

#6011 Check for null part instance
  InvenTree/order/views.py
Labels: bug
