Repository inventree/InvenTree, pull requests merged in 2023-12, with the labels that each got.

#6021 Give the people what they want
  .gitignore
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/serializers.py
  InvenTree/part/helpers.py
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/part/test_api.py
  InvenTree/part/views.py
Labels: enhancement, part, api

#6012 [PUI] Enable passing of string urls to apiUrl
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/functions/forms.tsx
  src/frontend/src/states/ApiState.tsx
Labels: plugin, Platform UI

#6030 Bug fix for label-skip implementation
  InvenTree/plugin/builtin/labels/label_sheet.py
Labels: bug, plugin

#5953 PUI: navigation/admin center improvements
  InvenTree/InvenTree/api_version.py
  InvenTree/plugin/api.py
  InvenTree/plugin/serializers.py
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
  src/frontend/src/components/items/InfoItem.tsx
  src/frontend/src/components/nav/DetailDrawer.tsx
  src/frontend/src/components/nav/MainMenu.tsx
  src/frontend/src/components/nav/NotificationDrawer.tsx
  src/frontend/src/components/nav/PanelGroup.tsx
  src/frontend/src/components/settings/SettingItem.tsx
  src/frontend/src/components/settings/SettingList.tsx
  src/frontend/src/components/tables/plugin/PluginErrorTable.tsx
  src/frontend/src/components/tables/plugin/PluginListTable.tsx
  src/frontend/src/components/tables/settings/GroupTable.tsx
  src/frontend/src/components/tables/settings/UserDrawer.tsx
  src/frontend/src/components/tables/settings/UserTable.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/functions/forms.tsx
  src/frontend/src/hooks/UseForm.tsx
  src/frontend/src/hooks/UseInstance.tsx
  src/frontend/src/hooks/UseModal.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/PluginManagementPanel.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/UserManagementPanel.tsx
  src/frontend/src/pages/Index/Settings/PluginSettings.tsx
  src/frontend/src/pages/Notifications.tsx
  src/frontend/src/router.tsx
  src/frontend/src/states/ApiState.tsx
  src/frontend/src/states/LocalState.tsx
  src/frontend/src/states/SettingsState.tsx
  src/frontend/src/states/states.tsx
Labels: enhancement, Platform UI

#6033 Admin section refactor
  src/frontend/src/components/nav/MainMenu.tsx
  src/frontend/src/components/tables/part/PartParameterTemplateTable.tsx
  src/frontend/src/components/tables/settings/CustomUnitsTable.tsx
  src/frontend/src/components/tables/settings/ProjectCodeTable.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/PluginManagementPanel.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
Labels: user interface, refactor, Platform UI

#6034 Api image fix
  src/frontend/src/components/images/ApiImage.tsx
Labels: user interface, refactor, Platform UI

#6039 Notify when packager build fails
  .pkgr.yml
Labels: CI, setup

#6038 Fix validation for Build model
  InvenTree/build/models.py
  InvenTree/build/test_build.py
Labels: bug, build

#6043 Tweak installer docs
  docs/docs/start/installer.md
Labels: setup, documentation

#6017 State transition support for generic states
  InvenTree/InvenTree/apps.py
  InvenTree/generic/states/__init__.py
  InvenTree/generic/states/test_transition.py
  InvenTree/generic/states/transition.py
  InvenTree/order/models.py
  InvenTree/order/serializers.py
  InvenTree/plugin/samples/integration/transition.py
Labels: order, plugin

#6050 Plugin docs
  docs/docs/extend/how_to_plugin.md
Labels: plugin, documentation

#6047 [PUI] refactor table filter selector
  InvenTree/part/api.py
  src/frontend/src/components/tables/Filter.tsx
  src/frontend/src/components/tables/FilterBadge.tsx
  src/frontend/src/components/tables/FilterGroup.tsx
  src/frontend/src/components/tables/FilterSelectDrawer.tsx
  src/frontend/src/components/tables/FilterSelectModal.tsx
  src/frontend/src/components/tables/InvenTreeTable.tsx
  src/frontend/src/components/tables/bom/BomTable.tsx
  src/frontend/src/components/tables/bom/UsedInTable.tsx
  src/frontend/src/components/tables/build/BuildOrderTable.tsx
  src/frontend/src/components/tables/part/PartCategoryTable.tsx
  src/frontend/src/components/tables/part/PartParameterTemplateTable.tsx
  src/frontend/src/components/tables/part/PartVariantTable.tsx
  src/frontend/src/components/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/components/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/components/tables/sales/SalesOrderTable.tsx
  src/frontend/src/components/tables/stock/StockItemTable.tsx
  src/frontend/src/components/tables/stock/StockLocationTable.tsx
  src/frontend/src/hooks/UseTable.tsx
Labels: user interface, refactor, Platform UI

#6055 Prevent check for low stock when creating new items
  InvenTree/stock/models.py
Labels: part

#6049 Installer CLI fix
  Procfile
  contrib/install.sh
  contrib/installer/src/root_command.sh
  docs/docs/start/installer.md
Labels: setup

#6014 [PUI] Table loading refactor
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: refactor, Platform UI

#6062 Handle "showmigrations" command
  InvenTree/InvenTree/ready.py
Labels: bug

#6056 Plugin loading improvements
  InvenTree/InvenTree/api_version.py
  InvenTree/plugin/api.py
  InvenTree/plugin/registry.py
  InvenTree/plugin/serializers.py
  InvenTree/templates/InvenTree/settings/plugin.html
  InvenTree/templates/InvenTree/settings/settings_staff_js.html
  InvenTree/templates/js/translated/plugin.js
  src/frontend/src/components/tables/plugin/PluginListTable.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/states/ApiState.tsx
Labels: plugin, api, Platform UI

#6068 chore(docker): Remove intermediate `prebuild` stage
  Dockerfile
Labels: CI, docker

#6070 Handle IntegrityError when saving PartPricing object
  InvenTree/part/models.py
Labels: bug, part

#6076 Allow plugin loading when calling 'showmigrations'
  InvenTree/InvenTree/ready.py
Labels: bug, plugin

#6081 FAQ - removeSuffix error
  docs/docs/faq.md
  tasks.py
Labels: setup

#6079 Bump django-maintenance-mode
  requirements.txt
Labels: bug, dependency

#6072 Sales order barcode allocate
  InvenTree/InvenTree/api_version.py
  InvenTree/order/models.py
  InvenTree/order/test_sales_order.py
  InvenTree/plugin/base/barcodes/api.py
  InvenTree/plugin/base/barcodes/serializers.py
  InvenTree/plugin/base/barcodes/test_barcode.py
  InvenTree/plugin/builtin/suppliers/test_supplier_barcodes.py
  InvenTree/stock/models.py
  InvenTree/templates/js/translated/barcode.js
  docs/docs/app/barcode.md
  docs/docs/app/po.md
  docs/docs/app/so.md
  docs/docs/assets/images/app/so_detail.png
  docs/docs/assets/images/app/so_lines.png
  docs/docs/assets/images/app/so_list.png
  docs/mkdocs.yml
Labels: enhancement, barcode, api

#6083 Add docs on using editable install for plugin development
  docs/docs/extend/how_to_plugin.md
Labels: plugin, documentation

#6085 Update devcontainer docs
  docs/docs/develop/devcontainer.md
Labels: documentation

#6088 Revert "[PUI] URl / panel fix"
  src/frontend/src/App.tsx
  src/frontend/src/components/nav/PanelGroup.tsx
  src/frontend/src/functions/auth.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/part/PartIndex.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockIndex.tsx
  src/frontend/src/router.tsx
  src/frontend/src/states/LocalState.tsx
Labels: Platform UI

#6089 Add item key
  src/frontend/src/components/tables/FilterSelectDrawer.tsx
Labels: Platform UI

#6091 Add support for serbian language
  InvenTree/InvenTree/settings.py
  InvenTree/locale/sr/LC_MESSAGES/django.po
  src/frontend/.linguirc
Labels: translation

#6093 Table Hook Updates
  src/frontend/src/components/tables/InvenTreeTable.tsx
  src/frontend/src/hooks/UseTable.tsx
Labels: Platform UI

#6084 Fix unit test
  InvenTree/InvenTree/helpers.py
  InvenTree/generic/states/test_transition.py
  InvenTree/generic/states/transition.py
Labels: bug, CI

#6096 Another attempt at fixing unit test
  InvenTree/generic/states/test_transition.py
Labels: bug, CI

#6100 Add information on auto-update param to docs
  docs/docs/start/config.md
Labels: setup, documentation

#6102 Small tweak for log output
  InvenTree/InvenTree/conversion.py
Labels: backport, backport-to-0.13.x

#6106 Update RowActions
  src/frontend/src/components/tables/RowActions.tsx
  src/frontend/src/components/tables/part/PartParameterTable.tsx
Labels: Platform UI

#6107 [PUI] Price range formatting
  src/frontend/src/components/images/ApiImage.tsx
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/components/nav/NotificationDrawer.tsx
  src/frontend/src/components/tables/bom/BomTable.tsx
  src/frontend/src/components/tables/part/PartTable.tsx
  src/frontend/src/defaults/formatters.tsx
Labels: Platform UI

#6111 Remove --no-frontend option from installer
  contrib/packager.io/functions.sh
Labels: bug, setup, backport, backport-to-0.13.x

#6099 Update django-allauth version
  InvenTree/InvenTree/forms.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/social_auth_urls.py
  InvenTree/InvenTree/sso.py
  InvenTree/config_template.yaml
  InvenTree/part/templatetags/sso.py
  InvenTree/templates/socialaccount/authentication_error.html
  InvenTree/templates/socialaccount/login.html
  InvenTree/templates/socialaccount/signup.html
  docs/docs/settings/SSO.md
  requirements.in
  requirements.txt
Labels: CI, dependency, backport, backport-to-0.13.x

#6115 [PUI] Implement manufacturer part table
  src/frontend/src/components/tables/ColumnRenderers.tsx
  src/frontend/src/components/tables/part/PartParameterTable.tsx
  src/frontend/src/components/tables/part/PartParameterTemplateTable.tsx
  src/frontend/src/components/tables/purchasing/ManufacturerPartTable.tsx
  src/frontend/src/components/tables/purchasing/SupplierPartTable.tsx
  src/frontend/src/components/tables/stock/StockItemTable.tsx
  src/frontend/src/forms/CompanyForms.tsx
  src/frontend/src/pages/part/PartDetail.tsx
Labels: user interface, Platform UI

#6117 Fix to clear SO Allocations on receipt of Return Order Line Item
  InvenTree/order/models.py
Labels: bug, order, stock, backport, backport-to-0.13.x

#6130 [PUI] Move UI rendering out of App.tsx
  src/frontend/src/App.tsx
  src/frontend/src/main.tsx
  src/frontend/src/views/MainView.tsx
Labels: Platform UI

#6131 Remove py2 exception handeling and move file to dj4 standard
  InvenTree/manage.py
Labels: dependency

#6137 [BUG] Fix old cancel checks
  InvenTree/order/serializers.py
Labels: bug, backport, backport-to-0.13.x
