Repository inventree/InvenTree, pull requests merged in 2023-02, with the labels that each got.

#4281 Improvements for part creation API endpoint
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/serializers.py
  InvenTree/common/models.py
  InvenTree/company/fixtures/company.yaml
  InvenTree/company/models.py
  InvenTree/part/api.py
  InvenTree/part/fixtures/params.yaml
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/part/templates/part/category.html
  InvenTree/part/test_api.py
  InvenTree/part/test_part.py
  InvenTree/templates/InvenTree/settings/part.html
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/part.js
Labels: bug, part, user interface, api

#4291 Prevent duplicate groups in reference format fields
  InvenTree/InvenTree/format.py
  InvenTree/InvenTree/models.py
Labels: bug

#4292 Include stock item purchase price in pricing cache
  InvenTree/common/models.py
  InvenTree/order/templates/order/order_base.html
  InvenTree/order/templates/order/sales_order_base.html
  InvenTree/part/models.py
  InvenTree/part/templates/part/prices.html
  InvenTree/part/test_pricing.py
  InvenTree/stock/models.py
  InvenTree/stock/templates/stock/item_base.html
  InvenTree/templates/InvenTree/settings/pricing.html
  InvenTree/templates/InvenTree/settings/setting.html
Labels: enhancement, stock, pricing

#4293 Client side currency conversion
  InvenTree/InvenTree/api_version.py
  InvenTree/common/api.py
  InvenTree/common/models.py
  InvenTree/common/tests.py
  InvenTree/templates/js/translated/helpers.js
  InvenTree/templates/js/translated/order.js
  InvenTree/templates/js/translated/pricing.js
Labels: enhancement, api, pricing

#4295 Plugin schedule fix
  InvenTree/plugin/apps.py
  InvenTree/plugin/base/integration/mixins.py
  InvenTree/plugin/samples/integration/scheduled_task.py
Labels: bug, plugin

#4298 Docker build fix
  docker/init.sh
Labels: bug, CI, docker, setup

#4297 Disable filter controls for part parameter table
  InvenTree/templates/js/translated/part.js
Labels: user interface

#4300 Currency API Updates
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/urls.py
  InvenTree/InvenTree/views.py
  InvenTree/common/api.py
  InvenTree/templates/InvenTree/settings/pricing.html
  InvenTree/templates/InvenTree/settings/settings.html
Labels: api, pricing

#4303 Currency update fix
  InvenTree/common/api.py
  InvenTree/common/tests.py
Labels: bug, pricing

#4308 Translation merge
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#4311 Translation fix
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#4315 Add option to specify cache attribute when loading a plugin setting
  InvenTree/plugin/base/integration/mixins.py
Labels: plugin

#4327 Group API
  InvenTree/InvenTree/api_version.py
  InvenTree/common/models.py
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/model_renderers.js
  InvenTree/users/api.py
  InvenTree/users/serializers.py
  InvenTree/users/test_api.py
  InvenTree/users/tests.py
Labels: api

#4333 Sort part parameter creation modal (#4251)
  InvenTree/part/templates/part/detail.html
Labels: user interface

#4326 Set Responsible User for a Part during creation or API
  InvenTree/build/migrations/0038_alter_build_responsible.py
  InvenTree/build/models.py
  InvenTree/part/migrations/0095_alter_part_responsible.py
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/part/templates/part/part_base.html
  InvenTree/templates/js/translated/part.js
Labels: enhancement, part, user interface, api

#4342 add libwebp-dev dependency (fixes #4269) (#4335)
  Dockerfile
Labels: bug, docker

#4344 Allow currency list to be specified from environment variables
  InvenTree/InvenTree/config.py
  InvenTree/InvenTree/settings.py
Labels: bug, setup

#4320 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#4346 Company attachment
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/serializers.py
  InvenTree/build/serializers.py
  InvenTree/company/api.py
  InvenTree/company/migrations/0054_companyattachment.py
  InvenTree/company/models.py
  InvenTree/company/serializers.py
  InvenTree/company/templates/company/detail.html
  InvenTree/company/templates/company/sidebar.html
  InvenTree/company/templates/company/supplier_part_navbar.html
  InvenTree/order/serializers.py
  InvenTree/part/serializers.py
  InvenTree/stock/serializers.py
  InvenTree/users/models.py
Labels: enhancement

#4350 Stock API filtering fix
  InvenTree/part/api.py
  InvenTree/stock/api.py
  InvenTree/stock/test_api.py
  InvenTree/templates/InvenTree/index.html
  InvenTree/templates/js/translated/stock.js
Labels: api

#4355 Configure CORS and allowed_hosts using env vars
  InvenTree/InvenTree/settings.py
Labels: setup

#4345 [Feature] Stocktake reports
  InvenTree/InvenTree/api_tester.py
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/apps.py
  InvenTree/InvenTree/permissions.py
  InvenTree/InvenTree/serializers.py
  InvenTree/common/models.py
  InvenTree/common/notifications.py
  InvenTree/common/serializers.py
  InvenTree/company/serializers.py
  InvenTree/order/serializers.py
  InvenTree/part/admin.py
  InvenTree/part/api.py
  InvenTree/part/migrations/0096_auto_20230211_0029.py
  InvenTree/part/migrations/0097_partstocktakereport.py
  InvenTree/part/migrations/0098_auto_20230214_1115.py
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/part/tasks.py
  InvenTree/part/templates/part/category.html
  InvenTree/part/templates/part/detail.html
  InvenTree/part/templates/part/part_base.html
  InvenTree/part/templates/part/part_sidebar.html
  InvenTree/part/templates/part/part_stocktake.html
  InvenTree/part/test_api.py
  InvenTree/plugin/base/event/events.py
  InvenTree/plugin/registry.py
  InvenTree/stock/serializers.py
  InvenTree/stock/templates/stock/location.html
  InvenTree/templates/InvenTree/settings/part_stocktake.html
  InvenTree/templates/InvenTree/settings/settings.html
  InvenTree/templates/InvenTree/settings/settings_js.html
  InvenTree/templates/InvenTree/settings/settings_staff_js.html
  InvenTree/templates/InvenTree/settings/sidebar.html
  InvenTree/templates/InvenTree/settings/stock.html
  InvenTree/templates/js/translated/attachment.js
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/helpers.js
  InvenTree/templates/js/translated/notification.js
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/pricing.js
  InvenTree/users/admin.py
  InvenTree/users/migrations/0006_alter_ruleset_name.py
  InvenTree/users/models.py
  InvenTree/users/tests.py
  docker/init.sh
Labels: enhancement, part, stock, report

#4357 Client side QR Codes
  InvenTree/InvenTree/static/script/qrcode.min.js
  InvenTree/InvenTree/views.py
  InvenTree/company/templates/company/supplier_part.html
  InvenTree/company/urls.py
  InvenTree/company/views.py
  InvenTree/part/api.py
  InvenTree/part/templates/part/part_base.html
  InvenTree/part/test_views.py
  InvenTree/part/views.py
  InvenTree/stock/templates/stock/item_base.html
  InvenTree/stock/templates/stock/location.html
  InvenTree/stock/urls.py
  InvenTree/stock/views.py
  InvenTree/templates/js/translated/modals.js
  InvenTree/templates/third_party_js.html
Labels: user interface, barcode

#4361 Bug fix for ensuring location and category names are unique for common parent
  InvenTree/InvenTree/models.py
  InvenTree/part/models.py
  InvenTree/stock/migrations/0093_auto_20230217_2140.py
  InvenTree/stock/models.py
Labels: bug, part, stock

#4368 Update dependencies
  .pre-commit-config.yaml
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: dependency

#4369 Fix bug rendering part without a category
  InvenTree/templates/js/translated/part.js
Labels: bug, user interface

#4354 Support podman and selinux for dev setup
  docker-compose.yml
Labels: docker, setup

#4373 Bug fix for purchase order pricing
  InvenTree/order/models.py
  InvenTree/order/tests.py
  InvenTree/part/templates/part/part_base.html
  InvenTree/stock/migrations/0094_auto_20230220_0025.py
  InvenTree/stock/templates/stock/item_base.html
Labels: bug, pricing

#4370 Part duplicate bug fix
  InvenTree/part/api.py
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/part/test_api.py
  InvenTree/part/test_param.py
  InvenTree/templates/js/translated/part.js
Labels: bug, part

#4377 Add "external" field to StockLocation
  InvenTree/InvenTree/api_version.py
  InvenTree/stock/api.py
  InvenTree/stock/migrations/0095_stocklocation_external.py
  InvenTree/stock/models.py
  InvenTree/stock/serializers.py
  InvenTree/templates/js/translated/stock.js
  InvenTree/templates/js/translated/table_filters.js
Labels: stock, api

#4362 add user setting to select a default label printer (#4349)
  InvenTree/common/models.py
  InvenTree/templates/InvenTree/settings/user_labels.html
  InvenTree/templates/js/translated/label.js
Labels: user interface

#4378 Js forms updates
  InvenTree/company/templates/company/supplier_part.html
  InvenTree/order/templates/order/sales_order_base.html
  InvenTree/part/templates/part/detail.html
  InvenTree/stock/templates/stock/item.html
  InvenTree/stock/templates/stock/item_base.html
  InvenTree/templates/js/translated/attachment.js
  InvenTree/templates/js/translated/bom.js
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/company.js
  InvenTree/templates/js/translated/order.js
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/stock.js
Labels: user interface

#4381 Adding icons for forms
  InvenTree/templates/js/translated/pricing.js
  InvenTree/templates/js/translated/stock.js
Labels: user interface

#4388 add missing units to Build Order view (#4386)
  InvenTree/templates/js/translated/build.js
Labels: user interface, build

#4356 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#4392 Adds ability to export sales order line table to a file
  InvenTree/order/api.py
  InvenTree/order/templates/order/sales_order_detail.html
  InvenTree/templates/collapse_rows.html
  InvenTree/templates/expand_rows.html
  InvenTree/templates/js/translated/order.js
  InvenTree/templates/js/translated/tables.js
Labels: order, user interface, api

#4393 improve stock status badges for parts (#4385)
  InvenTree/templates/js/translated/part.js
Labels: enhancement, stock, user interface

#4398 Add migration test
  InvenTree/stock/migrations/0071_auto_20211205_1733.py
  InvenTree/stock/test_migrations.py
Labels: bug, CI

#4400 Allow pricing updates when PartPricing object does not yet exist
  InvenTree/part/models.py
Labels: bug, pricing

#4401 Backport for data migration fix
  InvenTree/stock/migrations/0071_auto_20211205_1733.py
  InvenTree/stock/test_migrations.py
Labels: bug

#4399 fix stock health calculation to account for allocated stock (#4385)
  InvenTree/templates/js/translated/part.js
Labels: stock

#4405 Fix bug rendering part without a category (#4369)
  InvenTree/templates/js/translated/part.js
Labels: bug, user interface

#4407 Add option to filter stockitems by "external" location status
  InvenTree/stock/api.py
  InvenTree/templates/js/translated/table_filters.js
Labels: stock

#4412 Bug fix for build detail template
  InvenTree/build/templates/build/detail.html
  InvenTree/templates/js/translated/build.js
Labels: bug, user interface

#4408 Filter build orders by responsible owner (#4383)
  InvenTree/InvenTree/api_version.py
  InvenTree/build/api.py
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/filters.js
  InvenTree/templates/js/translated/table_filters.js
Labels: api, build

#4406 Bugfix for auto-backup task
  InvenTree/InvenTree/tasks.py
  InvenTree/InvenTree/test_tasks.py
  InvenTree/InvenTree/version.py
  InvenTree/common/api.py
  InvenTree/common/models.py
Labels: bug

#4415 Consolidate label printing and reporting options into a single screen
  InvenTree/templates/InvenTree/settings/settings.html
  InvenTree/templates/InvenTree/settings/sidebar.html
  InvenTree/templates/InvenTree/settings/user_reporting.html
Labels: user interface

#4414 Bugfix for auto-backup task (#4406)
  InvenTree/InvenTree/tasks.py
  InvenTree/InvenTree/test_tasks.py
  InvenTree/InvenTree/version.py
  InvenTree/common/api.py
  InvenTree/common/models.py
Labels: bug, setup

#3741 Auto migrating
  InvenTree/InvenTree/apps.py
  InvenTree/InvenTree/migrations/0001_initial.py
  InvenTree/InvenTree/migrations/__init__.py
  InvenTree/InvenTree/tasks.py
  InvenTree/InvenTree/test_tasks.py
  InvenTree/config_template.yaml
  InvenTree/plugin/registry.py
  InvenTree/plugin/serializers.py
  tasks.py
Labels: enhancement, setup, breaking

#4416 Improve rendering efficiency for build detail page
  InvenTree/build/templates/build/detail.html
  InvenTree/build/views.py
Labels: user interface, build

#4417 Convert pricing data in stock table
  InvenTree/templates/js/translated/pricing.js
  InvenTree/templates/js/translated/stock.js
Labels: stock, user interface

#4420 Fix typo in user display settings
  InvenTree/common/models.py
Labels: bug, user interface

#4422 Pricing bug fix
  InvenTree/company/migrations/0026_auto_20201110_1011.py
  InvenTree/company/models.py
  InvenTree/order/models.py
  InvenTree/part/migrations/0056_auto_20201110_1125.py
  InvenTree/part/models.py
  InvenTree/part/test_pricing.py
  InvenTree/stock/models.py
Labels: bug, pricing

#4423 Part API query tests
  InvenTree/part/api.py
  InvenTree/part/serializers.py
  InvenTree/part/test_api.py
Labels: api, CI

#4425 Add unallocated quantity to StockItem renderer
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/model_renderers.js
Labels: user interface, build

#4427 Add base part info to [Add Supplier Part] modal form
  InvenTree/templates/js/translated/company.js
  InvenTree/templates/js/translated/forms.js
Labels: user interface
