Repository inventree/InvenTree, pull requests merged in 2023-07, with the labels that each got.

#5127 fix: add missing build model property
  InvenTree/build/models.py
Labels: bug, backport, backport-to-0.12.x

#5141 Fix some documentation issues
  docs/docs/start/config.md
Labels: documentation

#5144 Database config spelling error
  docs/docs/start/config.md
Labels: documentation

#5107 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#5145 Rendering fix for build allocation table
  InvenTree/templates/js/translated/build.js
Labels: bug, user interface, backport, backport-to-0.12.x

#5147 Contributing docs
  CONTRIBUTING.md
Labels: documentation

#5150 Fix link to background tasks documentation
  InvenTree/templates/stats.html
Labels: documentation

#5151 Order table improvements
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/purchase_order.js
  InvenTree/templates/js/translated/return_order.js
  InvenTree/templates/js/translated/sales_order.js
Labels: bug, user interface, backport, backport-to-0.12.x

#5156 Remove old method
  InvenTree/build/models.py
Labels: refactor

#5161 Handle case where git head is detached
  InvenTree/InvenTree/version.py
Labels: bug

#5163 Handle exception when creating default labels
  InvenTree/InvenTree/apps.py
  InvenTree/label/apps.py
  docker/production/.env
Labels: bug, backport, backport-to-0.12.x

#5165 Restrict "recently updated" stock to "available"
  InvenTree/templates/InvenTree/index.html
Labels: user interface

#5168 Bump django - fix CVE-2023-36053
  requirements-dev.txt
  requirements.txt
Labels: dependency, security

#5169 Update 2fa lib
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/urls.py
  InvenTree/InvenTree/views.py
Labels: dependency, refactor

#5170 Bump general deps
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: dependency

#5174 Add migration check for 0.12.0 database
  .github/workflows/qc_checks.yaml
Labels: CI, migration

#5134 add report feature for stock locations
  InvenTree/report/admin.py
  InvenTree/report/api.py
  InvenTree/report/apps.py
  InvenTree/report/migrations/0020_stocklocationreport.py
  InvenTree/report/models.py
  InvenTree/report/serializers.py
  InvenTree/report/templates/report/inventree_slr_report.html
  InvenTree/report/tests.py
  InvenTree/stock/templates/stock/location.html
  InvenTree/users/models.py
Labels: enhancement, stock, report

#5167 use django-q2
  requirements.in
  requirements.txt
Labels: dependency

#5183 Param fix
  InvenTree/InvenTree/conversion.py
  InvenTree/InvenTree/tests.py
  InvenTree/templates/js/translated/part.js
Labels: bug, backport, backport-to-0.12.x

#5186 Add 'available' filter for BuildLine API endpoint
  InvenTree/InvenTree/api_version.py
  InvenTree/build/api.py
  InvenTree/build/serializers.py
Labels: enhancement, api, build

#5185 Stocktake location filter
  InvenTree/part/stocktake.py
Labels: enhancement, part

#5187 Shorten string fix
  InvenTree/templates/js/translated/bom.js
  InvenTree/templates/js/translated/model_renderers.js
Labels: bug, user interface

#5188 Fix quantity aggregation for stock table
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/stock.js
Labels: bug, user interface, backport, backport-to-0.12.x

#5189 Fix range filtering for serial number
  InvenTree/InvenTree/api_version.py
  InvenTree/stock/api.py
Labels: bug, api

#5172 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#5193 Fix 404 link in docker_prod.md
  docs/docs/start/docker_prod.md
Labels: documentation

#5199 Fix allocation check for completing build order
  InvenTree/build/serializers.py
Labels: bug, build, backport, backport-to-0.12.x

#5192 fix: generic status import
  InvenTree/build/api.py
  InvenTree/generic/states/__init__.py
  InvenTree/order/api.py
  InvenTree/stock/api.py
Labels: refactor

#5204 Fix cli on 22.04
  Procfile
Labels: bug, setup

#5205 Support Debian 12 on installer
  .pkgr.yml
  contrib/install.sh
  contrib/installer/src/root_command.sh
Labels: enhancement, setup

#5210 Fix link to SalesOrder in stock history table
  InvenTree/templates/js/translated/stock.js
Labels: bug, user interface, backport, backport-to-0.12.x

#5007 Refactor: Dockerimage
  Dockerfile
  docker/init.sh
Labels: docker, breaking, refactor

#5213 Docker: add missing reporting libs
  Dockerfile
Labels: bug, docker, setup

#5209 Add email login
  InvenTree/InvenTree/magic_login.py
  InvenTree/InvenTree/middleware.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/templates/InvenTree/user_simple_login.txt
  InvenTree/InvenTree/tests.py
  InvenTree/InvenTree/urls.py
  requirements.in
  requirements.txt
Labels: enhancement, api, security

#5219 Add missing callback for attachment delete button
  InvenTree/templates/js/translated/attachment.js
Labels: bug, user interface, backport, backport-to-0.12.x

#5224 Added required attribute to settings/plugins, refactor: allValues
  InvenTree/common/models.py
  InvenTree/common/tests.py
  InvenTree/plugin/base/integration/SettingsMixin.py
  InvenTree/plugin/samples/integration/sample.py
  InvenTree/plugin/samples/integration/test_sample.py
  docs/docs/extend/plugins/settings.md
Labels: enhancement, plugin, refactor

#5229 Protected settings fix
  InvenTree/common/serializers.py
  InvenTree/plugin/samples/integration/sample.py
  InvenTree/plugin/test_api.py
  InvenTree/templates/InvenTree/settings/setting.html
Labels: bug, plugin, backport, backport-to-0.12.x

#5236 fix typo
  InvenTree/templates/js/translated/stock.js
Labels: bug, translation, backport, backport-to-0.12.x

#5240 Only update theme if value provided
  InvenTree/InvenTree/views.py
Labels: bug, backport, backport-to-0.12.x

#5244 Fix weasyprint links
  docs/docs/report/report.md
  docs/docs/start/install.md
Labels: documentation

#5243 Add https comment to nginx file
  docker/production/nginx.prod.conf
Labels: setup, documentation

#5245 fix: make protected setting again changeable through admin ui
  InvenTree/templates/InvenTree/settings/setting.html
Labels: bug, plugin

#5250 Translation stat fix
  InvenTree/InvenTree/translation.py
  InvenTree/InvenTree/views.py
  InvenTree/part/templatetags/i18n.py
  InvenTree/templates/InvenTree/settings/user_display.html
Labels: bug

#5221 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#5255 Update docs to match reality
  docs/docs/order/sales_order.md
Labels: documentation

#5256 Fix language code for pt-br
  InvenTree/InvenTree/settings.py
Labels: bug, backport, backport-to-0.12.x

#5259 Fix settings function callback
  InvenTree/common/models.py
Labels: bug, backport, backport-to-0.12.x

#5248 Remove unneeded gunicorn
  docs/_includes/gunicorn.conf.py
Labels: documentation

#5251 Label plugin refactor
  .gitignore
  InvenTree/InvenTree/api_version.py
  InvenTree/common/models.py
  InvenTree/label/api.py
  InvenTree/label/migrations/0012_labeloutput.py
  InvenTree/label/models.py
  InvenTree/label/tasks.py
  InvenTree/label/tests.py
  InvenTree/plugin/base/label/label.py
  InvenTree/plugin/base/label/mixins.py
  InvenTree/plugin/base/label/test_label_mixin.py
  InvenTree/plugin/builtin/labels/__init__.py
  InvenTree/plugin/builtin/labels/inventree_label.py
  InvenTree/plugin/samples/integration/label_sample.py
  InvenTree/templates/js/translated/api.js
  InvenTree/templates/js/translated/label.js
  InvenTree/users/models.py
  docs/docs/extend/plugins/label.md
Labels: enhancement, plugin, report, api, breaking

#5264 Update python.md
  docs/docs/api/python/python.md
Labels: bug, documentation

#5266 Label plugin fix
  InvenTree/label/api.py
Labels: bug

#5270 Docker build: Update python deps
  docker/requirements.txt
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: CI, docker, setup, backport, backport-to-0.12.x

#5011 Platform UI - React integration
  .devcontainer/Dockerfile
  .devcontainer/postCreateCommand.sh
  .github/workflows/qc_checks.yaml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Dockerfile
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/urls.py
  InvenTree/config_template.yaml
  InvenTree/web/templates/web/index.html
  InvenTree/web/templatetags/spa_helper.py
  InvenTree/web/urls.py
  src/frontend/.babelrc
  src/frontend/.eslintrc.cjs
  src/frontend/.gitignore
  src/frontend/.linguirc
  src/frontend/.prettierrc
  src/frontend/index.html
  src/frontend/package.json
  src/frontend/playwright.config.ts
  src/frontend/public/inventree.svg
  src/frontend/src/App.tsx
  src/frontend/src/assets/inventree.svg
  src/frontend/src/locales/de/messages.d.ts
  src/frontend/src/locales/de/messages.po
  src/frontend/src/locales/de/messages.ts
  src/frontend/src/locales/en/messages.d.ts
  src/frontend/src/locales/en/messages.po
  src/frontend/src/locales/en/messages.ts
  src/frontend/src/locales/hu/messages.d.ts
  src/frontend/src/locales/hu/messages.po
  src/frontend/src/locales/hu/messages.ts
  src/frontend/src/locales/pseudo-LOCALE/messages.d.ts
  src/frontend/src/locales/pseudo-LOCALE/messages.po
  src/frontend/src/locales/pseudo-LOCALE/messages.ts
  src/frontend/src/main.tsx
  src/frontend/src/vite-env.d.ts
  src/frontend/tests/classic.spec.ts
  src/frontend/tests/ui_plattform.spec.ts
  src/frontend/tsconfig.json
  src/frontend/tsconfig.node.json
  src/frontend/vite.config.ts
  src/frontend/yarn.lock
  tasks.py
Labels: user interface, translation, refactor, feature

#5268 Add database model for defining custom units
  InvenTree/InvenTree/conversion.py
  InvenTree/InvenTree/tests.py
  InvenTree/common/api.py
  InvenTree/common/migrations/0020_customunit.py
  InvenTree/common/models.py
  InvenTree/common/serializers.py
  InvenTree/common/tests.py
  InvenTree/templates/InvenTree/settings/physical_units.html
  InvenTree/templates/InvenTree/settings/settings.html
  InvenTree/templates/InvenTree/settings/settings_staff_js.html
  InvenTree/templates/InvenTree/settings/sidebar.html
  InvenTree/users/models.py
  docs/docs/concepts/terminology.md
  docs/docs/concepts/units.md
  docs/docs/part/parameter.md
  docs/docs/part/part.md
  docs/mkdocs.yml
Labels: enhancement

#5274 Mantine
  Dockerfile
  InvenTree/web/.gitignore
  package.json
  yarn.lock
Labels: user interface

#5283 Update translate task
  .github/workflows/translations.yml
  tasks.py
Labels: bug, CI

#5276 P UI: Rearrange CI
  .github/workflows/qc_checks.yaml
Labels: CI

#5288 Fix company index page title
  InvenTree/company/templates/company/index.html
Labels: bug, user interface, backport, backport-to-0.12.x

#5277 P UI: Added frontend publishing for bare-metal (git)
  .devcontainer/postCreateCommand.sh
  .github/workflows/qc_checks.yaml
  .github/workflows/release.yml
  contrib/packager.io/functions.sh
  docs/docs/start/docker_dev.md
  docs/docs/start/docker_prod.md
  tasks.py
Labels: CI, setup

#5253 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#5260 Adds trigger when plugins are loaded
  InvenTree/plugin/registry.py
Labels: enhancement, plugin

#5299 P-UI: Adapt translation CI
  .github/workflows/translations.yml
  crowdin.yml
  tasks.py
Labels: CI, translation

#5304 Show built in label printing plugin even if the external plugins are …
  InvenTree/templates/js/translated/label.js
Labels: bug, plugin

#5305 Stock installed table fix
  InvenTree/templates/js/translated/stock.js
Labels: bug, user interface, backport, backport-to-0.12.x

#5301 P-UI: Fast language / theme / server selection
  .github/workflows/qc_checks.yaml
  src/frontend/playwright.config.ts
  src/frontend/src/components/forms/AuthFormOptions.tsx
  src/frontend/src/components/forms/AuthenticationForm.tsx
  src/frontend/src/components/forms/InstanceOptions.tsx
  src/frontend/src/components/items/ColorToggle.tsx
  src/frontend/src/components/items/EditButton.tsx
  src/frontend/src/components/items/LanguageSelect.tsx
  src/frontend/src/components/items/LanguageToggle.tsx
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/components/nav/MainMenu.tsx
  src/frontend/src/pages/Auth/Login.tsx
  src/frontend/src/pages/Index/Profile/UserPanel.tsx
  src/frontend/src/states/LocalState.tsx
  tasks.py
Labels: enhancement, Platform UI

#5307 Typo fix
  src/frontend/src/components/forms/AuthenticationForm.tsx
  src/frontend/src/functions/auth.tsx
Labels: Platform UI

#5312 Add DIO identifier
  docs/docs/start/advanced.md
Labels: documentation

#5314 P UI: Show server version on auth
  src/frontend/src/components/forms/AuthFormOptions.tsx
  src/frontend/src/components/forms/InstanceOptions.tsx
  src/frontend/src/components/nav/NavHoverMenu.tsx
  src/frontend/src/functions/auth.tsx
  src/frontend/src/pages/Auth/Login.tsx
  src/frontend/src/states/ApiState.tsx
Labels: enhancement, Platform UI

#5319 Fix admin url to point to right model
  InvenTree/company/templates/company/manufacturer_part.html
Labels: bug, user interface, backport, backport-to-0.12.x

#5327 Fix translation generation
  tasks.py
Labels: bug, CI, translation

#5298 P-UI: Dependency bumps
  requirements-dev.txt
  requirements.txt
  src/frontend/package.json
  src/frontend/yarn.lock
Labels: dependency, Platform UI

#5336 Email config fix
  InvenTree/InvenTree/email.py
  InvenTree/InvenTree/settings.py
  docs/docs/start/config.md
Labels: bug, setup, backport, backport-to-0.12.x

#5005 Skip ready functions if not in main thread or plugins are not loaded yet
  InvenTree/InvenTree/apps.py
  InvenTree/InvenTree/ready.py
  InvenTree/InvenTree/settings.py
  InvenTree/common/tests.py
  InvenTree/gunicorn.conf.py
  InvenTree/label/apps.py
  InvenTree/part/apps.py
  InvenTree/plugin/apps.py
  InvenTree/plugin/base/integration/AppMixin.py
  InvenTree/plugin/registry.py
  InvenTree/report/apps.py
  InvenTree/users/apps.py
  docker/gunicorn.conf.py
Labels: enhancement, plugin, breaking

#5325 P-UI: Add old dashboard page for now
  src/frontend/src/components/DashboardItemProxy.tsx
  src/frontend/src/components/items/DashboardItem.tsx
  src/frontend/src/defaults/dashboardItems.tsx
  src/frontend/src/defaults/links.tsx
  src/frontend/src/pages/Index/Dashboard.tsx
  src/frontend/src/router.tsx
Labels: Platform UI

#5347 Allow duplicate BOM items when duplicating a part
  InvenTree/part/models.py
Labels: bug, backport, backport-to-0.12.x

#5349 Exclude some common fields from django-import-export
  InvenTree/InvenTree/admin.py
Labels: bug, importer, backport, backport-to-0.12.x

#5218 [WIP] Mantine datatables
  .github/workflows/qc_checks.yaml
  package-lock.json
  package.json
  src/frontend/package.json
  src/frontend/src/components/items/ActionButton.tsx
  src/frontend/src/components/items/ButtonMenu.tsx
  src/frontend/src/components/items/Thumbnail.tsx
  src/frontend/src/components/tables/Column.tsx
  src/frontend/src/components/tables/ColumnSelect.tsx
  src/frontend/src/components/tables/DownloadAction.tsx
  src/frontend/src/components/tables/Filter.tsx
  src/frontend/src/components/tables/FilterBadge.tsx
  src/frontend/src/components/tables/FilterGroup.tsx
  src/frontend/src/components/tables/FilterSelectModal.tsx
  src/frontend/src/components/tables/InvenTreeTable.tsx
  src/frontend/src/components/tables/Search.tsx
  src/frontend/src/components/tables/build/BuildOrderTable.tsx
  src/frontend/src/components/tables/part/PartTable.tsx
  src/frontend/src/components/tables/stock/StockItemTable.tsx
  src/frontend/src/defaults/links.tsx
  src/frontend/src/functions/notifications.tsx
  src/frontend/src/functions/tables.tsx
  src/frontend/src/pages/Index/Build.tsx
  src/frontend/src/pages/Index/Part.tsx
  src/frontend/src/pages/Index/Stock.tsx
  src/frontend/src/router.tsx
  src/frontend/vite.config.ts
  src/frontend/yarn.lock
  yarn.lock
Labels: refactor, Platform UI

#5353 Add netlify for fast previews
  README.md
  src/frontend/netlify.toml
  src/frontend/src/main.tsx
Labels: CI, Platform UI

#5346 Global search input drawer
  src/frontend/src/components/items/ScanButton.tsx
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/components/nav/SearchDrawer.tsx
Labels: Platform UI

#5360 Handle errors when printing reports
  InvenTree/report/api.py
Labels: bug, report, api, backport, backport-to-0.12.x

#5362 Handle purchase price export for .xls files
  InvenTree/order/admin.py
Labels: bug, backport, backport-to-0.12.x

#5365 Return 404 on API requests other than GET
  InvenTree/InvenTree/api.py
Labels: bug, api, backport, backport-to-0.12.x

#5371 Fix for label printing plugins
  InvenTree/plugin/base/label/mixins.py
Labels: bug, plugin

#5372 Fix for migration - updating from old version
  InvenTree/stock/migrations/0094_auto_20230220_0025.py
Labels: bug, setup, backport, migration, backport-to-0.12.x
