Repository inventree/InvenTree, pull requests merged in 2023-04, with the labels that each got.

#4551 Fix wget command and links in Readme
  CONTRIBUTING.md
  README.md
  contrib/install.sh
  contrib/installer/src/root_command.sh
Labels: bug, setup

#4552 Bashscript update
  contrib/install.sh
Labels: CI

#4555 Fix incorrect string
  InvenTree/part/templates/part/part_base.html
Labels: bug, user interface

#4539 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#4556 Sales Order Allocation Improvements
  InvenTree/order/models.py
  InvenTree/stock/models.py
  InvenTree/stock/templates/stock/item.html
  InvenTree/stock/templates/stock/item_base.html
  InvenTree/templates/js/translated/sales_order.js
Labels: order, user interface

#4559 Update deps
  requirements-dev.txt
  requirements.txt
Labels: CI, dependency

#4453 Add azure pipelines
  .devops/testing_ci.yml
Labels: enhancement, CI

#4563 Bug fix for "receive items" form
  InvenTree/templates/js/translated/filters.js
  InvenTree/templates/js/translated/purchase_order.js
Labels: bug, user interface

#4569 Fix sentry.io integration for DRF exceptions
  InvenTree/InvenTree/exceptions.py
  InvenTree/InvenTree/settings.py
Labels: setup

#4570 Line item links
  InvenTree/order/migrations/0088_auto_20230403_1402.py
  InvenTree/order/models.py
  InvenTree/order/serializers.py
  InvenTree/templates/js/translated/order.js
  InvenTree/templates/js/translated/purchase_order.js
  InvenTree/templates/js/translated/return_order.js
  InvenTree/templates/js/translated/sales_order.js
Labels: enhancement, order, user interface

#4568 Cryptography version update
  Dockerfile
  requirements.in
  requirements.txt
Labels: security, setup

#4566 Enable regex search
  InvenTree/InvenTree/api.py
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/filters.py
  InvenTree/InvenTree/ready.py
  InvenTree/build/api.py
  InvenTree/common/api.py
  InvenTree/common/models.py
  InvenTree/company/api.py
  InvenTree/label/api.py
  InvenTree/order/api.py
  InvenTree/part/api.py
  InvenTree/part/templatetags/inventree_extras.py
  InvenTree/plugin/api.py
  InvenTree/report/api.py
  InvenTree/stock/api.py
  InvenTree/templates/InvenTree/settings/user_search.html
  InvenTree/templates/js/translated/search.js
  InvenTree/templates/js/translated/tables.js
  InvenTree/users/api.py
Labels: enhancement, api

#4575 Order barcodes
  InvenTree/company/templates/company/supplier_part.html
  InvenTree/order/migrations/0089_auto_20230404_0030.py
  InvenTree/order/models.py
  InvenTree/order/serializers.py
  InvenTree/order/templates/order/order_base.html
  InvenTree/order/templates/order/return_order_base.html
  InvenTree/order/templates/order/sales_order_base.html
  InvenTree/part/templates/part/part_base.html
  InvenTree/plugin/builtin/barcodes/inventree_barcode.py
  InvenTree/stock/templates/stock/item_base.html
  InvenTree/stock/templates/stock/location.html
  InvenTree/templates/barcode_data.html
Labels: enhancement, user interface, barcode

#4574 Allow barcodes to be added to incoming items via web UI
  InvenTree/InvenTree/models.py
  InvenTree/InvenTree/static/css/inventree.css
  InvenTree/order/models.py
  InvenTree/order/serializers.py
  InvenTree/order/test_api.py
  InvenTree/templates/js/translated/barcode.js
  InvenTree/templates/js/translated/helpers.js
  InvenTree/templates/js/translated/purchase_order.js
Labels: enhancement, user interface, barcode

#4577 Bump API version
  InvenTree/InvenTree/api_version.py
Labels: api

#4576 Don't log to sentry in debug mode
  InvenTree/InvenTree/exceptions.py
Labels: setup

#4580 UI tweaks
  InvenTree/build/templates/build/build_base.html
  InvenTree/part/templates/part/part_base.html
  InvenTree/stock/templates/stock/item_base.html
Labels: user interface

#4578 Update dockerfile requirements
  Dockerfile
Labels: CI, docker

#4581 Build order barcodes
  InvenTree/InvenTree/api_version.py
  InvenTree/build/migrations/0040_auto_20230404_1310.py
  InvenTree/build/models.py
  InvenTree/build/serializers.py
  InvenTree/build/templates/build/build_base.html
  InvenTree/plugin/builtin/barcodes/inventree_barcode.py
Labels: enhancement, barcode

#4594 Ignore validation errors when uploading to sentry.io
  InvenTree/InvenTree/exceptions.py
Labels: setup

#4597 Fix for scanning invalid barcode
  InvenTree/plugin/builtin/barcodes/inventree_barcode.py
Labels: bug, barcode

#4596 Update data migration file
  InvenTree/part/migrations/0102_auto_20230314_0112.py
  InvenTree/part/models.py
  InvenTree/part/test_migrations.py
Labels: bug, CI, setup

#4598 Docker: Add pinwheels.org repo for armv7 architecture
  Dockerfile
Labels: CI, docker, setup

#4599 Change text for purchase order
  InvenTree/order/templates/order/order_base.html
Labels: user interface, translation

#4601 Import fix for StockLocation
  InvenTree/build/admin.py
  InvenTree/part/admin.py
  InvenTree/stock/admin.py
Labels: bug, importer

#4595 Remove "required" attribute for order descriptions
  InvenTree/build/migrations/0041_alter_build_title.py
  InvenTree/build/models.py
  InvenTree/order/migrations/0090_auto_20230412_1752.py
  InvenTree/order/models.py
  InvenTree/part/migrations/0104_alter_part_description.py
  InvenTree/part/models.py
Labels: enhancement, order, build

#4617 Pin PIP version (for testing)
  .github/actions/setup/action.yaml
Labels: bug, CI

#4624 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#4629 Implement pagination for stock history tracking API
  InvenTree/stock/api.py
Labels: bug, stock, api

#4178 [FR] Update to OpenAPI from CoreAPI
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/urls.py
  InvenTree/InvenTree/version.py
  requirements.in
  requirements.txt
  tasks.py
Labels: enhancement, api, dependency

#4627 Remove hashes from dev requirements
  .github/actions/setup/action.yaml
  .pre-commit-config.yaml
  requirements-dev.txt
Labels: bug, CI, security

#4615 Support image uploads in the "notes" markdown fields
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/models.py
  InvenTree/InvenTree/tests.py
  InvenTree/build/migrations/0042_alter_build_notes.py
  InvenTree/build/models.py
  InvenTree/common/api.py
  InvenTree/common/migrations/0017_notesimage.py
  InvenTree/common/models.py
  InvenTree/common/serializers.py
  InvenTree/common/tasks.py
  InvenTree/common/tests.py
  InvenTree/company/migrations/0056_alter_company_notes.py
  InvenTree/company/models.py
  InvenTree/order/migrations/0091_auto_20230419_0037.py
  InvenTree/order/models.py
  InvenTree/part/migrations/0105_alter_part_notes.py
  InvenTree/part/models.py
  InvenTree/plugin/builtin/barcodes/inventree_barcode.py
  InvenTree/stock/migrations/0097_alter_stockitem_notes.py
  InvenTree/stock/models.py
  InvenTree/templates/js/translated/helpers.js
  InvenTree/templates/notes_buttons.html
  InvenTree/users/models.py
Labels: enhancement, user interface, api

#4340 [FR] Refactor plugin registry
  InvenTree/plugin/base/integration/AppMixin.py
  InvenTree/plugin/base/integration/ScheduleMixin.py
  InvenTree/plugin/base/integration/SettingsMixin.py
  InvenTree/plugin/base/integration/UrlsMixin.py
  InvenTree/plugin/base/integration/mixins.py
  InvenTree/plugin/mixins/__init__.py
  InvenTree/plugin/registry.py
  InvenTree/plugin/urls.py
Labels: plugin

#4638 Catch error if notes directory does not exist
  InvenTree/common/tasks.py
Labels: bug

#4636 Project code support
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/fields.py
  InvenTree/InvenTree/filters.py
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/models.py
  InvenTree/InvenTree/permissions.py
  InvenTree/build/models.py
  InvenTree/common/api.py
  InvenTree/common/migrations/0018_projectcode.py
  InvenTree/common/migrations/0019_projectcode_metadata.py
  InvenTree/common/models.py
  InvenTree/common/serializers.py
  InvenTree/common/tests.py
  InvenTree/company/models.py
  InvenTree/label/models.py
  InvenTree/order/admin.py
  InvenTree/order/api.py
  InvenTree/order/migrations/0092_auto_20230419_0250.py
  InvenTree/order/models.py
  InvenTree/order/serializers.py
  InvenTree/order/templates/order/order_base.html
  InvenTree/order/templates/order/return_order_base.html
  InvenTree/order/templates/order/sales_order_base.html
  InvenTree/part/models.py
  InvenTree/plugin/models.py
  InvenTree/report/models.py
  InvenTree/stock/models.py
  InvenTree/templates/InvenTree/settings/project_codes.html
  InvenTree/templates/InvenTree/settings/settings.html
  InvenTree/templates/InvenTree/settings/settings_staff_js.html
  InvenTree/templates/InvenTree/settings/sidebar.html
  InvenTree/templates/js/translated/company.js
  InvenTree/templates/js/translated/model_renderers.js
  InvenTree/templates/js/translated/purchase_order.js
  InvenTree/templates/js/translated/return_order.js
  InvenTree/templates/js/translated/sales_order.js
  InvenTree/templates/js/translated/table_filters.js
  InvenTree/templates/project_code_data.html
  InvenTree/users/models.py
Labels: enhancement, order, user interface, api

#4643 Report Plugins
  InvenTree/plugin/base/integration/ReportMixin.py
  InvenTree/plugin/mixins/__init__.py
  InvenTree/plugin/registry.py
  InvenTree/plugin/samples/integration/report_plugin_sample.py
  InvenTree/report/models.py
Labels: enhancement, plugin, report

#4640 Fix persist buttons
  InvenTree/part/templates/part/category.html
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/stock.js
Labels: user interface

#4644 Fix for "focus" field in forms
  InvenTree/templates/js/translated/forms.js
Labels: bug, user interface

#4641 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#4645 Add ordering and search to ProjectCodeList API endpoint
  InvenTree/common/api.py
Labels: bug, api

#4649 Update to report plugin API
  InvenTree/plugin/base/integration/ReportMixin.py
  InvenTree/plugin/samples/integration/report_plugin_sample.py
  InvenTree/report/models.py
Labels: plugin, report

#4648 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#4659 Fixes for docs building
  docs/.gitignore
  docs/__init__.py
  docs/docs/__init__.py
  docs/mkdocs.yml
Labels: documentation

#4678 Extend ReportMixin class to support labels
  InvenTree/label/models.py
  InvenTree/plugin/base/integration/ReportMixin.py
  docs/docs/extend/plugins/report.md
Labels: plugin, report

#4658 Fix sorting by location in stock item table
  InvenTree/stock/api.py
Labels: api

#4679 Update README.md
  README.md
Labels: documentation

#4684 Fix plugin meta lookup
  InvenTree/plugin/plugin.py
Labels: bug, plugin

#4693 Mark "supplier" field as required on PurchaseOrder serializer
  InvenTree/order/serializers.py
Labels: bug, api

#4699 Disable httpstat.us tests
  InvenTree/InvenTree/tests.py
Labels: CI

#4700 Homepage hide inactive
  InvenTree/common/models.py
  InvenTree/templates/InvenTree/index.html
  InvenTree/templates/InvenTree/settings/user_homepage.html
Labels: user interface

#4698 Specify order currency
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/serializers.py
  InvenTree/order/migrations/0093_auto_20230426_0248.py
  InvenTree/order/models.py
  InvenTree/order/serializers.py
  InvenTree/order/templates/order/order_base.html
  InvenTree/order/templates/order/purchase_order_detail.html
  InvenTree/order/templates/order/return_order_base.html
  InvenTree/order/templates/order/sales_order_base.html
  InvenTree/order/templates/order/sales_order_detail.html
  InvenTree/order/test_api.py
  InvenTree/report/templates/report/inventree_po_report_base.html
  InvenTree/report/templates/report/inventree_so_report_base.html
  InvenTree/templates/currency_data.html
  InvenTree/templates/js/translated/purchase_order.js
  InvenTree/templates/js/translated/return_order.js
  InvenTree/templates/js/translated/sales_order.js
  docs/README.md
  docs/docs/buy/po.md
  docs/docs/report/purchase_order.md
  docs/docs/report/sales_order.md
  docs/docs/sell/so.md
Labels: enhancement, order, api, pricing, documentation

#4703 Add python example for deleting a part
  .github/release.yml
  docs/docs/api/python/examples.md
Labels: documentation

#4686 Check if doc links are broken
  .github/workflows/check_docs_config.yaml
  docs/docs/extend/integrate.md
Labels: CI, documentation

#4706 Add custom template loader class
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/template.py
Labels: enhancement, report

#4705 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
Labels: translation

#4712 sentry.io improvements
  InvenTree/InvenTree/exceptions.py
  InvenTree/InvenTree/sentry.py
  InvenTree/InvenTree/settings.py
  docs/docs/settings/logs.md
Labels: setup

#4714 Fix export of order data
  InvenTree/InvenTree/api_tester.py
  InvenTree/order/admin.py
  InvenTree/order/test_api.py
Labels: bug, order, CI, importer

#4692 bump deps
  .markuplintrc
  package-lock.json
  package.json
  requirements-dev.txt
  requirements.txt
Labels: dependency

#4683 Code style improvements
  .pre-commit-config.yaml
  InvenTree/InvenTree/fields.py
  InvenTree/InvenTree/middleware.py
  InvenTree/InvenTree/models.py
  InvenTree/InvenTree/sentry.py
  InvenTree/InvenTree/serializers.py
  InvenTree/InvenTree/tasks.py
  InvenTree/InvenTree/template.py
  InvenTree/InvenTree/tests.py
  InvenTree/build/admin.py
  InvenTree/build/models.py
  InvenTree/common/files.py
  InvenTree/common/models.py
  InvenTree/common/notifications.py
  InvenTree/common/settings.py
  InvenTree/company/admin.py
  InvenTree/label/api.py
  InvenTree/label/apps.py
  InvenTree/order/admin.py
  InvenTree/order/api.py
  InvenTree/order/models.py
  InvenTree/order/test_api.py
  InvenTree/part/admin.py
  InvenTree/part/api.py
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/part/test_bom_import.py
  InvenTree/plugin/admin.py
  InvenTree/plugin/base/event/events.py
  InvenTree/plugin/base/integration/mixins.py
  InvenTree/plugin/base/label/label.py
  InvenTree/plugin/mixins/__init__.py
  InvenTree/plugin/models.py
  InvenTree/plugin/plugin.py
  InvenTree/plugin/samples/event/event_sample.py
  InvenTree/report/api.py
  InvenTree/report/templatetags/barcode.py
  InvenTree/stock/admin.py
  InvenTree/stock/api.py
  InvenTree/stock/models.py
  InvenTree/stock/test_migrations.py
  InvenTree/users/admin.py
  docs/main.py
  setup.cfg
Labels: enhancement, CI
