Repository inventree/InvenTree, pull requests merged in 2023-08, with the labels that each got.

#5340 Fix SSO check comparing id against name and extend log output
  InvenTree/part/templatetags/sso.py
Labels: bug, setup, backport, backport-to-0.12.x

#5378 Fix auto-allocation of build outputs
  InvenTree/build/models.py
Labels: bug, build, backport, backport-to-0.12.x

#5380 Build output table sort
  InvenTree/templates/js/translated/build.js
Labels: user interface

#5381 Pint unit fix
  InvenTree/InvenTree/conversion.py
  InvenTree/InvenTree/tests.py
  InvenTree/company/models.py
  InvenTree/part/models.py
Labels: bug, backport, backport-to-0.12.x

#5388 Pin mkdocs version to 1.4.3
  docs/requirements.txt
Labels: documentation

#5394 Handle case where calculation may be performed on invalid values
  InvenTree/stock/api.py
Labels: bug, pricing

#5395 fix cli on 22.04 (#5204)
  Procfile
  docs/docs/report/report.md
  docs/docs/start/install.md
Labels: bug, setup

#5385 Bump deps
  InvenTree/InvenTree/config.py
  InvenTree/InvenTree/email.py
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/sanitizer.py
  InvenTree/generic/states/states.py
  InvenTree/part/api.py
  InvenTree/part/templatetags/inventree_extras.py
  InvenTree/report/models.py
  InvenTree/report/tests.py
  requirements-dev.txt
  requirements.txt
Labels: dependency

#5171 Use error report fork
  requirements.in
  requirements.txt
Labels: enhancement, dependency

#5403 Increased settings value length from 200 to 2000
  InvenTree/common/migrations/0021_auto_20230805_1748.py
  InvenTree/common/models.py
  InvenTree/plugin/migrations/0007_auto_20230805_1748.py
Labels: enhancement

#5402 Added docs on the panel plugin example
  docs/docs/assets/images/plugin/plugin_dataflow.png
  docs/docs/extend/plugins/panel.md
Labels: documentation

#5206 Packages - force python 3.9
  .pkgr.yml
  contrib/packager.io/functions.sh
  contrib/packager.io/postinstall.sh
Labels: bug, setup

#5359 P-UI: Add playground for new components
  src/frontend/src/defaults/links.tsx
  src/frontend/src/defaults/menuItems.tsx
  src/frontend/src/pages/Index/Playground.tsx
  src/frontend/src/router.tsx
Labels: Platform UI

#5396 Email fix
  InvenTree/InvenTree/forms.py
  InvenTree/InvenTree/helpers_model.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/tests.py
  InvenTree/InvenTree/urls.py
Labels: bug, backport, backport-to-0.12.x

#5409 backport email fix
  InvenTree/InvenTree/forms.py
  InvenTree/InvenTree/helpers_model.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/urls.py
Labels: bug

#5412 Fix plugin pickeling
  InvenTree/plugin/models.py
Labels: bug, plugin

#5415 Sales order variant stock
  InvenTree/InvenTree/api_version.py
  InvenTree/order/serializers.py
  InvenTree/stock/api.py
  InvenTree/templates/js/translated/sales_order.js
Labels: order, user interface, api

#5344 [P-UI] Home page
  InvenTree/InvenTree/middleware.py
  InvenTree/InvenTree/urls.py
  InvenTree/web/templatetags/spa_helper.py
  InvenTree/web/urls.py
  src/frontend/package.json
  src/frontend/src/components/items/GettingStartedCarousel.tsx
  src/frontend/src/components/widgets/DisplayWidget.tsx
  src/frontend/src/components/widgets/FeedbackWidget.tsx
  src/frontend/src/components/widgets/GetStartedWidget.tsx
  src/frontend/src/components/widgets/WidgetLayout.tsx
  src/frontend/src/functions/loading.tsx
  src/frontend/src/locales/de/messages.po
  src/frontend/src/locales/de/messages.ts
  src/frontend/src/locales/en/messages.po
  src/frontend/src/locales/en/messages.ts
  src/frontend/src/locales/hu/messages.po
  src/frontend/src/locales/hu/messages.ts
  src/frontend/src/locales/pseudo-LOCALE/messages.po
  src/frontend/src/locales/pseudo-LOCALE/messages.ts
  src/frontend/src/main.tsx
  src/frontend/src/pages/Index/Home.tsx
  src/frontend/tests/ui_plattform.spec.ts
  src/frontend/yarn.lock
Labels: enhancement, Platform UI

#5419 Add optional "description" column to SalesOrderLineItem table
  InvenTree/templates/js/translated/sales_order.js
Labels: order, user interface

#5421 Purchase history graph fix
  InvenTree/templates/js/translated/pricing.js
Labels: bug, user interface, pricing, backport, backport-to-0.12.x

#5343 [P_UI] Added django settings for p_ui
  InvenTree/InvenTree/settings.py
  InvenTree/config_template.yaml
  InvenTree/web/templates/web/index.html
  InvenTree/web/templatetags/spa_helper.py
  src/frontend/netlify.toml
  src/frontend/src/components/forms/AuthFormOptions.tsx
  src/frontend/src/defaults/defaultHostList.tsx
  src/frontend/src/main.tsx
  src/frontend/src/pages/Auth/Login.tsx
  src/frontend/src/vite-env.d.ts
  src/frontend/vite.config.ts
Labels: Platform UI

#5426 Fix build output unallocate button
  InvenTree/templates/js/translated/build.js
Labels: bug, user interface, build, backport, backport-to-0.12.x

#5425 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hi/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
  InvenTree/locale/zh_hant/LC_MESSAGES/django.po
  src/frontend/src/locales/cs/messages.po
  src/frontend/src/locales/da/messages.po
  src/frontend/src/locales/de/messages.po
  src/frontend/src/locales/el/messages.po
  src/frontend/src/locales/en/messages.po
  src/frontend/src/locales/es/messages.po
  src/frontend/src/locales/fa/messages.po
  src/frontend/src/locales/fi/messages.po
  src/frontend/src/locales/fr/messages.po
  src/frontend/src/locales/he/messages.po
  src/frontend/src/locales/hi/messages.po
  src/frontend/src/locales/hu/messages.po
  src/frontend/src/locales/id/messages.po
  src/frontend/src/locales/it/messages.po
  src/frontend/src/locales/ja/messages.po
  src/frontend/src/locales/ko/messages.po
  src/frontend/src/locales/nl/messages.po
  src/frontend/src/locales/no/messages.po
  src/frontend/src/locales/pl/messages.po
  src/frontend/src/locales/pseudo-LOCALE/messages.po
  src/frontend/src/locales/pt/messages.po
  src/frontend/src/locales/ru/messages.po
  src/frontend/src/locales/sl/messages.po
  src/frontend/src/locales/sv/messages.po
  src/frontend/src/locales/th/messages.po
  src/frontend/src/locales/tr/messages.po
  src/frontend/src/locales/vi/messages.po
  src/frontend/src/locales/zh/messages.po
Labels: translation

#5428 Update migrate.md to handle exporting json via docker volume #5420
  docs/docs/start/migrate.md
Labels: documentation

#5440 Fix for potential NoReverseMatch error
  InvenTree/stock/templates/stock/item_base.html
Labels: bug, user interface, backport, backport-to-0.12.x

#5439 Catch IndexError when importing data
  InvenTree/part/views.py
Labels: bug, backport, backport-to-0.12.x

#5444 Disable "add rate" button in Admin interface
  InvenTree/InvenTree/admin.py
Labels: bug, backport, backport-to-0.12.x

#5445 Fix html tag in template
  InvenTree/stock/templates/stock/item_base.html
Labels: bug, user interface, backport, backport-to-0.12.x

#5446 Update unit tests
  InvenTree/part/test_param.py
Labels: bug

#5431 Add comments and warnings to documentation so readers would follow the correct version
  docs/docs/start/docker.md
  docs/docs/start/docker_prod.md
Labels: documentation

#5437 New Crowdin updates
  .pre-commit-config.yaml
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hi/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
  InvenTree/locale/zh_hant/LC_MESSAGES/django.po
  src/frontend/src/locales/cs/messages.po
  src/frontend/src/locales/da/messages.po
  src/frontend/src/locales/de/messages.po
  src/frontend/src/locales/el/messages.po
  src/frontend/src/locales/en/messages.po
  src/frontend/src/locales/es/messages.po
  src/frontend/src/locales/fa/messages.po
  src/frontend/src/locales/fi/messages.po
  src/frontend/src/locales/fr/messages.po
  src/frontend/src/locales/he/messages.po
  src/frontend/src/locales/hi/messages.po
  src/frontend/src/locales/hu/messages.po
  src/frontend/src/locales/id/messages.po
  src/frontend/src/locales/it/messages.po
  src/frontend/src/locales/ja/messages.po
  src/frontend/src/locales/ko/messages.po
  src/frontend/src/locales/nl/messages.po
  src/frontend/src/locales/no/messages.po
  src/frontend/src/locales/pl/messages.po
  src/frontend/src/locales/pseudo-LOCALE/messages.po
  src/frontend/src/locales/pt/messages.po
  src/frontend/src/locales/ru/messages.po
  src/frontend/src/locales/sl/messages.po
  src/frontend/src/locales/sv/messages.po
  src/frontend/src/locales/th/messages.po
  src/frontend/src/locales/tr/messages.po
  src/frontend/src/locales/vi/messages.po
  src/frontend/src/locales/zh/messages.po
Labels: translation

#5454 Use `IS_DEV_OR_DEMO` for playground
  src/frontend/src/defaults/links.tsx
  src/frontend/src/defaults/menuItems.tsx
Labels: enhancement, Platform UI

#5455 Bug fix for daily stocktake check
  InvenTree/part/stocktake.py
  InvenTree/part/tasks.py
Labels: bug, backport, backport-to-0.12.x

#5456 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hi/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
  InvenTree/locale/zh_hant/LC_MESSAGES/django.po
  src/frontend/src/locales/cs/messages.po
  src/frontend/src/locales/da/messages.po
  src/frontend/src/locales/de/messages.po
  src/frontend/src/locales/el/messages.po
  src/frontend/src/locales/es/messages.po
  src/frontend/src/locales/fa/messages.po
  src/frontend/src/locales/fi/messages.po
  src/frontend/src/locales/fr/messages.po
  src/frontend/src/locales/he/messages.po
  src/frontend/src/locales/hi/messages.po
  src/frontend/src/locales/hu/messages.po
  src/frontend/src/locales/id/messages.po
  src/frontend/src/locales/it/messages.po
  src/frontend/src/locales/ja/messages.po
  src/frontend/src/locales/ko/messages.po
  src/frontend/src/locales/nl/messages.po
  src/frontend/src/locales/no/messages.po
  src/frontend/src/locales/pl/messages.po
  src/frontend/src/locales/pt/messages.po
  src/frontend/src/locales/ru/messages.po
  src/frontend/src/locales/sl/messages.po
  src/frontend/src/locales/sv/messages.po
  src/frontend/src/locales/th/messages.po
  src/frontend/src/locales/tr/messages.po
  src/frontend/src/locales/vi/messages.po
  src/frontend/src/locales/zh/messages.po
Labels: translation

#5466 Default expiry fix
  InvenTree/label/tests.py
  InvenTree/stock/api.py
  InvenTree/stock/test_api.py
Labels: bug, stock, backport, backport-to-0.12.x

#5453 [FR/P_UI] Sentry.io integration for front-end
  InvenTree/config_template.yaml
  src/frontend/package.json
  src/frontend/src/main.tsx
  src/frontend/yarn.lock
Labels: enhancement, Platform UI

#5472 Url fix
  InvenTree/InvenTree/helpers_model.py
  InvenTree/InvenTree/tests.py
Labels: bug, backport, backport-to-0.12.x

#5479 Fix docker instructions
  docs/docs/start/docker_dev.md
Labels: documentation

#5486 Fixed allauth docs links
  docs/docs/settings/SSO.md
  docs/docs/start/config.md
Labels: bug, documentation

#5476 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hi/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
  InvenTree/locale/zh_hant/LC_MESSAGES/django.po
  src/frontend/src/locales/de/messages.po
  src/frontend/src/locales/en/messages.po
  src/frontend/src/locales/es/messages.po
  src/frontend/src/locales/hu/messages.po
  src/frontend/src/locales/pseudo-LOCALE/messages.po
  src/frontend/src/locales/pt/messages.po
  src/frontend/src/locales/ru/messages.po
  src/frontend/src/locales/sv/messages.po
  src/frontend/src/locales/zh/messages.po
Labels: translation
