Repository inventree/InvenTree, pull requests merged in 2023-10, with the labels that each got.

#5638 Backport for plugin bug fix
  InvenTree/plugin/serializers.py
Labels: bug, plugin

#5605 Add worker task to VS Code
  .vscode/tasks.json
  docs/docs/develop/devcontainer.md
Labels: CI, setup, Add to docs

#5618 Let plugins decide if events should be processed or not
  InvenTree/plugin/base/event/events.py
  InvenTree/plugin/base/event/mixins.py
  InvenTree/plugin/samples/event/filtered_event_sample.py
  InvenTree/plugin/samples/event/test_filtered_event_sample.py
  docs/docs/extend/plugins/event.md
Labels: enhancement, plugin, Add to docs

#5642 Move broken plugin samples to disabled folders
  InvenTree/plugin/broken/__init__.py
  InvenTree/plugin/broken/broken_file.py
  InvenTree/plugin/broken/broken_sample.py
  InvenTree/plugin/registry.py
  InvenTree/plugin/test_plugin.py
Labels: plugin, CI

#5627 Don't ignore parts without stock in stocktake
  InvenTree/part/stocktake.py
  InvenTree/part/test_api.py
Labels: part, stock, backport, backport-to-0.12.x

#5644 Allow stocktake quantity to be zero
  InvenTree/part/tasks.py
  InvenTree/part/test_api.py
Labels: bug, part

#5647 Allow plugin list to be filtered by "sample" or "builtin" status
  InvenTree/plugin/api.py
  InvenTree/templates/js/translated/table_filters.js
Labels: plugin

#5632 Exchange rate emergency fix
  InvenTree/InvenTree/exchange.py
  InvenTree/InvenTree/tests.py
  InvenTree/common/tests.py
Labels: bug, pricing, backport, backport-to-0.12.x

#5651 Fix for readthedocs build config file
  readthedocs.yml
Labels: CI, documentation

#5650 Exchange rate backend fix - backport
  InvenTree/InvenTree/exchange.py
  InvenTree/InvenTree/tests.py
Labels: bug, pricing

#5648 Prevent plugin URL routing if ENABLE_PLUGINS_URL setting is disabled
  InvenTree/plugin/samples/integration/test_sample.py
  InvenTree/plugin/urls.py
Labels: bug, plugin

#5646 Fix for plugin installation via web interface
  InvenTree/plugin/installer.py
  InvenTree/plugin/registry.py
  InvenTree/plugin/serializers.py
  InvenTree/plugin/test_api.py
  InvenTree/templates/js/translated/plugin.js
Labels: bug, plugin

#5653 Plugin missing fix
  InvenTree/plugin/api.py
  InvenTree/plugin/models.py
  InvenTree/plugin/serializers.py
  InvenTree/templates/js/translated/plugin.js
  InvenTree/templates/js/translated/table_filters.js
Labels: plugin

#5656 Fix: Allow allocation of variants to sales order lines
  InvenTree/order/models.py
  InvenTree/order/test_api.py
  InvenTree/order/test_sales_order.py
  InvenTree/part/fixtures/part.yaml
Labels: bug, order

#5660 Bug fix for plugin reload mechanism
  InvenTree/plugin/registry.py
Labels: bug, plugin

#5595 Feature/Tree picker
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/static/css/inventree.css
  InvenTree/part/serializers.py
  InvenTree/part/templates/part/category.html
  InvenTree/part/templates/part/detail.html
  InvenTree/stock/serializers.py
  InvenTree/stock/templates/stock/item_base.html
  InvenTree/stock/templates/stock/location.html
  InvenTree/templates/InvenTree/settings/settings_staff_js.html
  InvenTree/templates/js/dynamic/nav.js
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/modals.js
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/purchase_order.js
  InvenTree/templates/js/translated/return_order.js
  InvenTree/templates/js/translated/stock.js
Labels: enhancement, user interface

#5661 Fix location priority when receiving items
  InvenTree/order/serializers.py
  InvenTree/order/test_api.py
Labels: bug, order, backport, backport-to-0.12.x

#5662 Allow reload of plugin registry when config changes
  InvenTree/common/models.py
  InvenTree/plugin/base/integration/ScheduleMixin.py
  InvenTree/plugin/registry.py
Labels: plugin

#5226 Native LDAP support
  .devcontainer/Dockerfile
  Dockerfile
  InvenTree/InvenTree/settings.py
  InvenTree/config_template.yaml
  docker/requirements.txt
  docs/docs/start/advanced.md
Labels: enhancement, docker

#5666 Bump deps
  requirements-dev.txt
  requirements.txt
  src/frontend/package.json
  src/frontend/yarn.lock
Labels: dependency

#5667 Exchange rate plugin
  InvenTree/InvenTree/exchange.py
  InvenTree/InvenTree/tasks.py
  InvenTree/common/api.py
  InvenTree/common/models.py
  InvenTree/plugin/admin.py
  InvenTree/plugin/base/integration/APICallMixin.py
  InvenTree/plugin/base/integration/CurrencyExchangeMixin.py
  InvenTree/plugin/base/integration/ValidationMixin.py
  InvenTree/plugin/base/integration/mixins.py
  InvenTree/plugin/base/label/test_label_mixin.py
  InvenTree/plugin/builtin/integration/currency_exchange.py
  InvenTree/plugin/mixins/__init__.py
  InvenTree/plugin/plugin.py
  InvenTree/plugin/samples/integration/label_sample.py
  InvenTree/plugin/samples/integration/report_plugin_sample.py
  InvenTree/plugin/samples/integration/sample_currency_exchange.py
  InvenTree/plugin/samples/integration/version.py
  InvenTree/plugin/test_plugin.py
  InvenTree/templates/InvenTree/settings/plugin_settings.html
  InvenTree/templates/InvenTree/settings/pricing.html
  docs/docs/assets/images/settings/currency.png
  docs/docs/extend/plugins.md
  docs/docs/extend/plugins/currency.md
  docs/docs/extend/plugins/report.md
  docs/docs/settings/currency.md
  docs/docs/start/config.md
  docs/mkdocs.yml
Labels: enhancement, plugin, pricing, documentation

#5668 Plugin auto migrate
  InvenTree/InvenTree/apps.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/tasks.py
  InvenTree/common/models.py
  InvenTree/common/tests.py
  InvenTree/plugin/serializers.py
  InvenTree/templates/base.html
  docker.dev.env
  docker/production/.env
Labels: enhancement, plugin

#5597 Type model information in SearchDrawer
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
  src/frontend/src/components/nav/SearchDrawer.tsx
  src/frontend/src/components/render/Build.tsx
  src/frontend/src/components/render/Company.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/render/ModelType.tsx
  src/frontend/src/components/render/Order.tsx
  src/frontend/src/components/render/Part.tsx
  src/frontend/src/components/render/Stock.tsx
  src/frontend/src/components/render/User.tsx
Labels: refactor, Platform UI

#5677 Import export fix
  InvenTree/InvenTree/admin.py
  requirements.in
  requirements.txt
Labels: importer

#5678 Report orientation
  InvenTree/common/models.py
  InvenTree/report/helpers.py
  InvenTree/report/migrations/0021_auto_20231009_0144.py
  InvenTree/report/models.py
  InvenTree/report/templates/report/inventree_report_base.html
  docs/docs/report/context_variables.md
Labels: enhancement, report

#5588 Feature/location types
  InvenTree/InvenTree/api_version.py
  InvenTree/stock/admin.py
  InvenTree/stock/api.py
  InvenTree/stock/migrations/0103_stock_location_types.py
  InvenTree/stock/models.py
  InvenTree/stock/serializers.py
  InvenTree/stock/test_api.py
  InvenTree/templates/InvenTree/settings/settings_staff_js.html
  InvenTree/templates/InvenTree/settings/stock.html
  InvenTree/templates/js/translated/model_renderers.js
  InvenTree/templates/js/translated/stock.js
  InvenTree/templates/js/translated/table_filters.js
  InvenTree/users/models.py
Labels: enhancement, stock, api

#5684 Update settings API endpoints:
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/serializers.py
  InvenTree/common/api.py
  InvenTree/common/models.py
  InvenTree/common/serializers.py
Labels: api

#5685 User roles state
  src/frontend/src/components/nav/MainMenu.tsx
  src/frontend/src/functions/auth.tsx
  src/frontend/src/pages/Index/Home.tsx
  src/frontend/src/states/ApiState.tsx
  src/frontend/src/states/UserState.tsx
  src/frontend/src/states/states.tsx
  src/frontend/src/views/DesktopAppView.tsx
Labels: Platform UI

#5686 [React] Use typed paths
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/forms/fields/ChoiceField.tsx
  src/frontend/src/components/renderers/BuildOrderRenderer.tsx
  src/frontend/src/components/renderers/PartRenderer.tsx
  src/frontend/src/components/renderers/PurchaseOrderRenderer.tsx
  src/frontend/src/components/renderers/SalesOrderRenderer.tsx
  src/frontend/src/components/renderers/StockItemRenderer.tsx
  src/frontend/src/components/renderers/StockLocationRenderer.tsx
  src/frontend/src/components/renderers/SupplierPartRenderer.tsx
  src/frontend/src/components/tables/AttachmentTable.tsx
  src/frontend/src/components/tables/InvenTreeTable.tsx
  src/frontend/src/components/tables/build/BuildOrderTable.tsx
  src/frontend/src/components/tables/notifications/NotificationsTable.tsx
  src/frontend/src/components/tables/part/PartCategoryTable.tsx
  src/frontend/src/components/tables/part/PartTable.tsx
  src/frontend/src/components/tables/part/RelatedPartTable.tsx
  src/frontend/src/components/tables/stock/StockItemTable.tsx
  src/frontend/src/components/tables/stock/StockLocationTable.tsx
  src/frontend/src/functions/forms.tsx
  src/frontend/src/functions/forms/AttachmentForms.tsx
  src/frontend/src/functions/forms/PartForms.tsx
  src/frontend/src/functions/forms/StockForms.tsx
  src/frontend/src/hooks/UseInstance.tsx
  src/frontend/src/pages/Index/Playground.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/states/ApiState.tsx
Labels: Platform UI

#5687 [React] Settings state manager
  src/frontend/src/components/nav/MainMenu.tsx
  src/frontend/src/functions/auth.tsx
  src/frontend/src/states/ApiState.tsx
  src/frontend/src/states/SettingsState.tsx
  src/frontend/src/states/UserState.tsx
  src/frontend/src/states/states.tsx
  src/frontend/src/views/DesktopAppView.tsx
Labels: Platform UI

#5688 Add new "location_type" column to stock location table
  src/frontend/src/components/tables/stock/StockLocationTable.tsx
Labels: Platform UI

#5690 Api tweaks
  src/frontend/src/components/forms/InstanceOptions.tsx
  src/frontend/src/components/modals/QrCodeModal.tsx
  src/frontend/src/components/nav/BreadcrumbList.tsx
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/components/nav/NavHoverMenu.tsx
  src/frontend/src/components/nav/NotificationDrawer.tsx
  src/frontend/src/components/nav/PanelGroup.tsx
  src/frontend/src/components/nav/SearchDrawer.tsx
  src/frontend/src/components/renderers/GeneralRenderer.tsx
  src/frontend/src/components/tables/build/BuildOrderTable.tsx
  src/frontend/src/components/tables/notifications/NotificationsTable.tsx
  src/frontend/src/components/tables/part/PartCategoryTable.tsx
  src/frontend/src/components/tables/part/PartTable.tsx
  src/frontend/src/components/tables/part/RelatedPartTable.tsx
  src/frontend/src/components/tables/stock/StockItemTable.tsx
  src/frontend/src/components/tables/stock/StockLocationTable.tsx
  src/frontend/src/functions/auth.tsx
  src/frontend/src/functions/forms.tsx
  src/frontend/src/hooks/UseInstance.tsx
  src/frontend/src/main.tsx
  src/frontend/src/pages/Auth/Login.tsx
  src/frontend/src/pages/Auth/Set-Password.tsx
  src/frontend/src/pages/Index/Profile/UserPanel.tsx
  src/frontend/src/pages/Index/Scan.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/states/ApiState.tsx
  src/frontend/src/states/SettingsState.tsx
  src/frontend/src/states/UserState.tsx
Labels: Platform UI

#5698 Improved BOM import process
  InvenTree/part/serializers.py
Labels: importer

#5699 Catch potential exception when performing unit conversion
  InvenTree/InvenTree/conversion.py
  InvenTree/InvenTree/tests.py
Labels: bug

#5700 Improve sentry.io integration
  InvenTree/InvenTree/sentry.py
Labels: setup

#5641 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hi/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
  InvenTree/locale/zh_hant/LC_MESSAGES/django.po
  src/frontend/src/locales/cs/messages.po
  src/frontend/src/locales/da/messages.po
  src/frontend/src/locales/de/messages.po
  src/frontend/src/locales/el/messages.po
  src/frontend/src/locales/es/messages.po
  src/frontend/src/locales/fa/messages.po
  src/frontend/src/locales/fi/messages.po
  src/frontend/src/locales/fr/messages.po
  src/frontend/src/locales/he/messages.po
  src/frontend/src/locales/hi/messages.po
  src/frontend/src/locales/hu/messages.po
  src/frontend/src/locales/id/messages.po
  src/frontend/src/locales/it/messages.po
  src/frontend/src/locales/ja/messages.po
  src/frontend/src/locales/ko/messages.po
  src/frontend/src/locales/nl/messages.po
  src/frontend/src/locales/no/messages.po
  src/frontend/src/locales/pl/messages.po
  src/frontend/src/locales/pt/messages.po
  src/frontend/src/locales/ru/messages.po
  src/frontend/src/locales/sl/messages.po
  src/frontend/src/locales/sv/messages.po
  src/frontend/src/locales/th/messages.po
  src/frontend/src/locales/tr/messages.po
  src/frontend/src/locales/vi/messages.po
  src/frontend/src/locales/zh/messages.po
Labels: translation

#5701 Docs fix
  docs/docs/start/docker_prod.md
Labels: docker, documentation

#5705 Platform URL fixes
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/nav/NotificationDrawer.tsx
  src/frontend/src/components/tables/AttachmentTable.tsx
  src/frontend/src/functions/forms/AttachmentForms.tsx
  src/frontend/src/pages/Notifications.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: bug, Platform UI

#5696 [React] API Image Functionality
  InvenTree/InvenTree/settings.py
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
  src/frontend/src/components/images/ApiImage.tsx
  src/frontend/src/components/images/Thumbnail.tsx
  src/frontend/src/components/nav/PageDetail.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/renderers/GeneralRenderer.tsx
  src/frontend/src/components/tables/build/BuildOrderTable.tsx
  src/frontend/src/components/tables/part/PartTable.tsx
  src/frontend/src/components/tables/part/RelatedPartTable.tsx
  src/frontend/src/hooks/UseInstance.tsx
  src/frontend/src/pages/part/PartDetail.tsx
Labels: Platform UI

#5706 Adds toggle for text elements in panel tabs
  src/frontend/src/components/nav/PanelGroup.tsx
Labels: Platform UI

#5708 Improved implementation of panel collapse
  src/frontend/src/components/nav/PanelGroup.tsx
Labels: user interface, Platform UI

#5709 [React] Part parameters table
  InvenTree/InvenTree/settings.py
  InvenTree/part/api.py
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/items/YesNoButton.tsx
  src/frontend/src/components/nav/PanelGroup.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/render/ModelType.tsx
  src/frontend/src/components/render/Part.tsx
  src/frontend/src/components/tables/InvenTreeTable.tsx
  src/frontend/src/components/tables/part/PartParameterTable.tsx
  src/frontend/src/components/tables/part/PartTable.tsx
  src/frontend/src/components/tables/part/RelatedPartTable.tsx
  src/frontend/src/components/tables/stock/StockItemTable.tsx
  src/frontend/src/components/tables/stock/StockLocationTable.tsx
  src/frontend/src/defaults/dashboardItems.tsx
  src/frontend/src/pages/Notifications.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/states/ApiState.tsx
Labels: Platform UI

#5710 Improve useInstance hook
  src/frontend/src/hooks/UseInstance.tsx
Labels: Platform UI

#5679 [React] Settings interface
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/components/nav/MainMenu.tsx
  src/frontend/src/components/nav/PanelGroup.tsx
  src/frontend/src/components/settings/SettingItem.tsx
  src/frontend/src/components/settings/SettingList.tsx
  src/frontend/src/components/tables/part/PartTable.tsx
  src/frontend/src/components/tables/plugin/PluginListTable.tsx
  src/frontend/src/components/tables/settings/CustomUnitsTable.tsx
  src/frontend/src/components/tables/settings/ProjectCodeTable.tsx
  src/frontend/src/contexts/BaseContext.tsx
  src/frontend/src/contexts/ThemeContext.tsx
  src/frontend/src/functions/forms.tsx
  src/frontend/src/pages/Index/Home.tsx
  src/frontend/src/pages/Index/PluginSettings.tsx
  src/frontend/src/pages/Index/SystemSettings.tsx
  src/frontend/src/pages/Index/UserSettings.tsx
  src/frontend/src/router.tsx
  src/frontend/src/states/ApiState.tsx
  src/frontend/src/states/SettingsState.tsx
  src/frontend/src/states/UserState.tsx
  src/frontend/src/states/states.tsx
Labels: Platform UI

#5714 Add deepsource for more security testing
  .deepsource.toml
  README.md
Labels: CI, security

#5433 add /static/ relative comment and update splash image path in config_template.yaml
  InvenTree/config_template.yaml
Labels: inactive

#5721 BOM Table - Fix pricing when subassembly is open
  InvenTree/templates/js/translated/bom.js
Labels: bug, user interface, pricing

#5724 Improve checks for scheduled tasks at startup
  InvenTree/InvenTree/apps.py
Labels: refactor

#5726 Refactor plugin loading
  InvenTree/plugin/registry.py
Labels: refactor

#5727 Remove stockitemmanager
  InvenTree/stock/models.py
Labels: refactor

#5728 [React] Maximize screen width
  src/frontend/src/components/nav/Footer.tsx
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/components/nav/Layout.tsx
Labels: Platform UI

#5568 Remove --no-frontend option
  docs/docs/start/docker_dev.md
  docs/docs/start/docker_prod.md
  tasks.py
Labels: setup

#5731 [React] Update part parameters table
  InvenTree/part/api.py
  InvenTree/part/serializers.py
  src/frontend/src/components/images/ApiImage.tsx
  src/frontend/src/components/images/Thumbnail.tsx
  src/frontend/src/components/tables/part/PartParameterTable.tsx
  src/frontend/src/components/tables/part/PartTable.tsx
  src/frontend/src/components/tables/part/PartVariantTable.tsx
  src/frontend/src/components/tables/stock/StockItemTable.tsx
  src/frontend/src/functions/tables.tsx
  src/frontend/src/pages/part/PartDetail.tsx
Labels: Platform UI

#5740 Version bump
  .pre-commit-config.yaml
  InvenTree/InvenTree/fields.py
  InvenTree/InvenTree/forms.py
  InvenTree/InvenTree/mixins.py
  InvenTree/InvenTree/sanitizer.py
  InvenTree/InvenTree/status.py
  InvenTree/common/notifications.py
  InvenTree/company/test_migrations.py
  InvenTree/company/test_supplier_parts.py
  InvenTree/order/test_api.py
  InvenTree/part/api.py
  InvenTree/report/api.py
  InvenTree/templates/js/translated/barcode.js
  InvenTree/templates/js/translated/return_order.js
  InvenTree/templates/js/translated/table_filters.js
  docs/docs/build/build.md
  docs/docs/start/intro.md
  docs/docs/stock/test.md
  package.json
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
  src/frontend/package.json
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/nav/SearchDrawer.tsx
  src/frontend/src/components/tables/InvenTreeTable.tsx
  src/frontend/src/functions/forms/PartForms.tsx
  src/frontend/src/pages/Index/Profile/UserPanel.tsx
  src/frontend/yarn.lock
  tasks.py
  yarn.lock
Labels: dependency

#5737 Refactor: replace multiple `==` checks with `in`
  InvenTree/part/test_api.py
  InvenTree/plugin/registry.py
  InvenTree/stock/test_api.py
Labels: refactor

#5735 Refactor unnecessary else / elif when if block has a return statement
  InvenTree/InvenTree/api.py
  InvenTree/InvenTree/conversion.py
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/middleware.py
  InvenTree/InvenTree/models.py
  InvenTree/InvenTree/version.py
  InvenTree/InvenTree/views.py
  InvenTree/build/api.py
  InvenTree/build/models.py
  InvenTree/common/admin.py
  InvenTree/common/api.py
  InvenTree/common/models.py
  InvenTree/common/views.py
  InvenTree/company/models.py
  InvenTree/label/api.py
  InvenTree/order/admin.py
  InvenTree/order/api.py
  InvenTree/order/models.py
  InvenTree/part/api.py
  InvenTree/part/models.py
  InvenTree/part/templatetags/inventree_extras.py
  InvenTree/plugin/builtin/integration/currency_exchange.py
  InvenTree/plugin/builtin/labels/inventree_label.py
  InvenTree/plugin/plugin.py
  InvenTree/plugin/registry.py
  InvenTree/report/templatetags/report.py
  InvenTree/stock/api.py
  InvenTree/stock/models.py
  InvenTree/users/models.py
Labels: refactor

#5741 Fix news dashboard
  src/frontend/src/components/DashboardItemProxy.tsx
  src/frontend/src/defaults/dashboardItems.tsx
  src/frontend/src/states/ApiState.tsx
Labels: bug

#5733 Adds 'A3' as report size option
  InvenTree/report/helpers.py
Labels: report

#5742 [React] Improvements to API forms
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/forms/fields/ChoiceField.tsx
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
  src/frontend/src/functions/forms.tsx
  src/frontend/src/pages/part/PartDetail.tsx
Labels: bug, Platform UI

#5738 Added python test paths to deepsource
  .deepsource.toml
Labels: CI

#5743 [React] Purchasing and Sales
  src/frontend/src/components/tables/InvenTreeTable.tsx
  src/frontend/src/components/tables/general/AttachmentTable.tsx
  src/frontend/src/components/tables/general/CompanyTable.tsx
  src/frontend/src/components/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/components/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/components/tables/sales/SalesOrderTable.tsx
  src/frontend/src/components/tables/settings/ProjectCodeTable.tsx
  src/frontend/src/defaults/links.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchasingIndex.tsx
  src/frontend/src/pages/sales/SalesIndex.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/router.tsx
  src/frontend/src/states/ApiState.tsx
Labels: user interface, Platform UI

#5751 Handle ValueError when creating stock item
  InvenTree/stock/api.py
Labels: bug

#5752 [React] Login improvements
  src/frontend/src/components/forms/AuthenticationForm.tsx
  src/frontend/src/functions/auth.tsx
  src/frontend/src/pages/Auth/Logged-In.tsx
  src/frontend/src/states/UserState.tsx
Labels: Platform UI

#5509 Add basic support for scanning vendor barcodes
  InvenTree/InvenTree/api_version.py
  InvenTree/plugin/base/barcodes/api.py
  InvenTree/plugin/base/barcodes/mixins.py
  InvenTree/plugin/builtin/suppliers/__init__.py
  InvenTree/plugin/builtin/suppliers/digikey.py
  InvenTree/plugin/builtin/suppliers/lcsc.py
  InvenTree/plugin/builtin/suppliers/mouser.py
  InvenTree/plugin/builtin/suppliers/test_supplier_barcodes.py
  InvenTree/plugin/builtin/suppliers/tme.py
  InvenTree/plugin/mixins/__init__.py
  docs/docs/barcodes/custom.md
Labels: enhancement, barcode, plugin, feature

#5756 React UI improvements
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/images/Thumbnail.tsx
  src/frontend/src/components/items/ActionDropdown.tsx
  src/frontend/src/components/nav/Layout.tsx
  src/frontend/src/components/nav/PageDetail.tsx
  src/frontend/src/components/tables/general/AttachmentTable.tsx
  src/frontend/src/components/tables/general/CompanyTable.tsx
  src/frontend/src/functions/forms.tsx
  src/frontend/src/functions/forms/CompanyForms.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/company/CustomerDetail.tsx
  src/frontend/src/pages/company/ManufacturerDetail.tsx
  src/frontend/src/pages/company/SupplierDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchasingIndex.tsx
  src/frontend/src/pages/sales/SalesIndex.tsx
  src/frontend/src/router.tsx
  src/frontend/src/states/ApiState.tsx
  src/frontend/src/states/ModalState.tsx
  src/frontend/src/states/UserState.tsx
Labels: user interface, Platform UI

#5758 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hi/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
  InvenTree/locale/zh_hant/LC_MESSAGES/django.po
  src/frontend/src/locales/cs/messages.po
  src/frontend/src/locales/da/messages.po
  src/frontend/src/locales/de/messages.po
  src/frontend/src/locales/el/messages.po
  src/frontend/src/locales/en/messages.po
  src/frontend/src/locales/es/messages.po
  src/frontend/src/locales/fa/messages.po
  src/frontend/src/locales/fi/messages.po
  src/frontend/src/locales/fr/messages.po
  src/frontend/src/locales/he/messages.po
  src/frontend/src/locales/hi/messages.po
  src/frontend/src/locales/hu/messages.po
  src/frontend/src/locales/id/messages.po
  src/frontend/src/locales/it/messages.po
  src/frontend/src/locales/ja/messages.po
  src/frontend/src/locales/ko/messages.po
  src/frontend/src/locales/nl/messages.po
  src/frontend/src/locales/no/messages.po
  src/frontend/src/locales/pl/messages.po
  src/frontend/src/locales/pseudo-LOCALE/messages.po
  src/frontend/src/locales/pt/messages.po
  src/frontend/src/locales/ru/messages.po
  src/frontend/src/locales/sl/messages.po
  src/frontend/src/locales/sv/messages.po
  src/frontend/src/locales/th/messages.po
  src/frontend/src/locales/tr/messages.po
  src/frontend/src/locales/vi/messages.po
  src/frontend/src/locales/zh/messages.po
Labels: translation

#5664 Api token updates
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/middleware.py
  InvenTree/InvenTree/settings.py
  InvenTree/users/admin.py
  InvenTree/users/api.py
  InvenTree/users/authentication.py
  InvenTree/users/migrations/0008_apitoken.py
  InvenTree/users/models.py
  InvenTree/users/test_api.py
  InvenTree/users/tests.py
  src/frontend/src/components/nav/NotificationDrawer.tsx
  src/frontend/src/functions/auth.tsx
  tasks.py
Labels: enhancement, api, security

#5760 Fixed PlaygroundArea accordion behaviour
  src/frontend/src/pages/Index/Playground.tsx
Labels: bug, Platform UI

#5761 Token tweaks
  InvenTree/users/api.py
  InvenTree/users/models.py
  InvenTree/users/test_api.py
Labels: api

#5764 More token tweaks
  InvenTree/users/admin.py
  InvenTree/users/api.py
  InvenTree/users/authentication.py
  InvenTree/users/migrations/0009_auto_20231020_2356.py
  InvenTree/users/models.py
  InvenTree/users/test_api.py
Labels: api

#5767 Stock item bug fix
  InvenTree/stock/models.py
Labels: bug, stock

#5766 Fix admin site - Custom admin URL
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/urls.py
  InvenTree/build/templates/build/build_base.html
  InvenTree/company/templates/company/company_base.html
  InvenTree/company/templates/company/manufacturer_part.html
  InvenTree/company/templates/company/supplier_part.html
  InvenTree/config_template.yaml
  InvenTree/order/templates/order/order_base.html
  InvenTree/order/templates/order/return_order_base.html
  InvenTree/order/templates/order/sales_order_base.html
  InvenTree/part/templates/part/category.html
  InvenTree/part/templates/part/part_base.html
  InvenTree/part/templatetags/inventree_extras.py
  InvenTree/plugin/registry.py
  InvenTree/stock/templates/stock/item_base.html
  InvenTree/stock/templates/stock/location.html
  InvenTree/templates/InvenTree/settings/plugin.html
  InvenTree/templates/admin_button.html
  InvenTree/templates/navbar.html
  InvenTree/templates/registration/logged_out.html
  docs/docs/start/config.md
Labels: enhancement, security

#5770 Fix imports in inventree_extras.py
  InvenTree/part/templatetags/inventree_extras.py
Labels: bug

#5774 Part responsible owner
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/social_auth_urls.py
  InvenTree/InvenTree/urls.py
  InvenTree/part/migrations/0115_part_responsible_owner.py
  InvenTree/part/migrations/0116_auto_20231023_0332.py
  InvenTree/part/migrations/0117_remove_part_responsible.py
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/part/templates/part/part_base.html
Labels: part

#5765 Frontend server settings
  InvenTree/InvenTree/config.py
  InvenTree/InvenTree/middleware.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/tests.py
  InvenTree/config_template.yaml
  InvenTree/users/admin.py
  InvenTree/users/models.py
  InvenTree/web/templatetags/spa_helper.py
  InvenTree/web/urls.py
  src/frontend/src/functions/auth.tsx
  src/frontend/src/main.tsx
  src/frontend/src/views/DesktopAppView.tsx
Labels: Platform UI

#5776 Bump action versions
  .github/actions/setup/action.yaml
  .github/workflows/backport.yml
  .github/workflows/check_translations.yaml
  .github/workflows/docker.yaml
  .github/workflows/qc_checks.yaml
  .github/workflows/release.yml
  .github/workflows/stale.yml
  .github/workflows/translations.yml
  .github/workflows/update.yml.disabled
Labels: dependency

#5782 Fixes for table rendering
  InvenTree/templates/js/translated/purchase_order.js
  InvenTree/templates/js/translated/sales_order.js
  InvenTree/templates/js/translated/stock.js
Labels: bug, user interface, backport, backport-to-0.12.x

#5784 Update sales_order.js
  InvenTree/templates/js/translated/sales_order.js
Labels: bug, user interface

#5785 Fixes for PUI CI run/login timeouts
  src/frontend/src/functions/auth.tsx
  src/frontend/src/main.tsx
  src/frontend/src/states/ApiState.tsx
  src/frontend/src/states/UserState.tsx
  src/frontend/src/views/DesktopAppView.tsx
  src/frontend/tests/ui_plattform.spec.ts
Labels: bug, CI

#5789 Readme sponsors
  .github/workflows/sponsors.yml
  README.md
Labels: CI, documentation

#5793 Update sponsors.yml
  .github/workflows/sponsors.yml
Labels: CI

#5759 [PUI] Render status labels
  InvenTree/InvenTree/api_version.py
  InvenTree/common/api.py
  InvenTree/generic/states/api.py
  src/frontend/src/components/nav/SearchDrawer.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/render/ModelType.tsx
  src/frontend/src/components/renderers/StatusRenderer.tsx
  src/frontend/src/components/tables/build/BuildOrderTable.tsx
  src/frontend/src/components/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/components/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/components/tables/sales/SalesOrderTable.tsx
  src/frontend/src/components/tables/stock/StockItemTable.tsx
  src/frontend/src/defaults/backendMappings.tsx
  src/frontend/src/pages/Index/Playground.tsx
  src/frontend/src/states/ApiState.tsx
Labels: enhancement, api, Platform UI

#5797 Various style fixes
  InvenTree/InvenTree/forms.py
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/models.py
  InvenTree/company/models.py
  InvenTree/label/models.py
  InvenTree/order/views.py
  InvenTree/part/models.py
  InvenTree/part/templatetags/inventree_extras.py
  InvenTree/part/views.py
  InvenTree/report/models.py
  InvenTree/stock/api.py
  InvenTree/stock/models.py
  src/frontend/src/components/forms/fields/ChoiceField.tsx
  src/frontend/src/components/images/Thumbnail.tsx
  src/frontend/src/components/items/AttachmentLink.tsx
  src/frontend/src/components/items/MenuLinks.tsx
  src/frontend/src/components/nav/NotificationDrawer.tsx
  src/frontend/src/components/settings/SettingItem.tsx
  src/frontend/src/components/settings/SettingList.tsx
  src/frontend/src/components/tables/DownloadAction.tsx
  src/frontend/src/components/tables/FilterSelectModal.tsx
  src/frontend/src/defaults/defaultHostList.tsx
  src/frontend/src/defaults/menuItems.tsx
  src/frontend/src/functions/forms/PartForms.tsx
  src/frontend/src/functions/forms/StockForms.tsx
  src/frontend/src/pages/Index/Playground.tsx
  src/frontend/src/pages/Index/PluginSettings.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/states/ApiState.tsx
Labels: refactor

#5769 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hi/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
  InvenTree/locale/zh_hant/LC_MESSAGES/django.po
  src/frontend/src/locales/cs/messages.po
  src/frontend/src/locales/da/messages.po
  src/frontend/src/locales/de/messages.po
  src/frontend/src/locales/el/messages.po
  src/frontend/src/locales/en/messages.po
  src/frontend/src/locales/es/messages.po
  src/frontend/src/locales/fa/messages.po
  src/frontend/src/locales/fi/messages.po
  src/frontend/src/locales/fr/messages.po
  src/frontend/src/locales/he/messages.po
  src/frontend/src/locales/hi/messages.po
  src/frontend/src/locales/hu/messages.po
  src/frontend/src/locales/id/messages.po
  src/frontend/src/locales/it/messages.po
  src/frontend/src/locales/ja/messages.po
  src/frontend/src/locales/ko/messages.po
  src/frontend/src/locales/nl/messages.po
  src/frontend/src/locales/no/messages.po
  src/frontend/src/locales/pl/messages.po
  src/frontend/src/locales/pseudo-LOCALE/messages.po
  src/frontend/src/locales/pt/messages.po
  src/frontend/src/locales/ru/messages.po
  src/frontend/src/locales/sl/messages.po
  src/frontend/src/locales/sv/messages.po
  src/frontend/src/locales/th/messages.po
  src/frontend/src/locales/tr/messages.po
  src/frontend/src/locales/vi/messages.po
  src/frontend/src/locales/zh/messages.po
Labels: translation

#5794 Update sponsors.yml
  .github/workflows/sponsors.yml
Labels: CI

#5798 React interface updates
  src/frontend/src/components/images/ApiImage.tsx
  src/frontend/src/components/items/ActionDropdown.tsx
  src/frontend/src/components/nav/BreadcrumbList.tsx
  src/frontend/src/components/nav/PageDetail.tsx
  src/frontend/src/components/renderers/StatusRenderer.tsx
  src/frontend/src/components/tables/InvenTreeTable.tsx
  src/frontend/src/components/tables/general/AttachmentTable.tsx
  src/frontend/src/components/tables/general/CompanyTable.tsx
  src/frontend/src/components/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/components/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/components/tables/sales/SalesOrderTable.tsx
  src/frontend/src/components/tables/stock/StockItemTable.tsx
  src/frontend/src/hooks/UseInstance.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/build/BuildIndex.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/router.tsx
  src/frontend/src/states/ApiState.tsx
  src/frontend/vite.config.ts
Labels: Platform UI

#5801 Corrected example in report mixin
  docs/docs/extend/plugins/report.md
Labels: report, documentation

#5800 [React] Tree navigation
  src/frontend/package.json
  src/frontend/src/components/images/ApiImage.tsx
  src/frontend/src/components/nav/BreadcrumbList.tsx
  src/frontend/src/components/nav/NotificationDrawer.tsx
  src/frontend/src/components/nav/PageDetail.tsx
  src/frontend/src/components/nav/PartCategoryTree.tsx
  src/frontend/src/components/nav/StockLocationTree.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/states/ApiState.tsx
  src/frontend/yarn.lock
Labels: user interface, Platform UI

#5805 Documentation - Added Views, blocks, and templates documentation
  docs/docs/extend/plugins/urls.md
Labels: plugin, documentation

#5807 Added context variables for address
  InvenTree/company/.models.py.swp
  docs/docs/extend/plugins/urls.md
  docs/docs/report/context_variables.md
Labels: report, documentation

#5808 Build part change fix
  InvenTree/InvenTree/mixins.py
  InvenTree/build/models.py
  InvenTree/build/test_build.py
  InvenTree/templates/js/translated/build.js
Labels: bug, build

#5809 [PUI] Adjust default radius
  src/frontend/src/states/LocalState.tsx
Labels: Platform UI

#5717 Add deepsource code coverage
  .deepsource.toml
  .github/workflows/qc_checks.yaml
  InvenTree/InvenTree/settings.py
Labels: CI

#5810 [PUI] Added Server Info Modal
  InvenTree/InvenTree/api.py
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/version.py
  InvenTree/part/templatetags/inventree_extras.py
  src/frontend/src/components/items/DocumentationLinks.tsx
  src/frontend/src/components/items/OnlyStaff.tsx
  src/frontend/src/components/modals/ServerInfoModal.tsx
  src/frontend/src/contexts/ThemeContext.tsx
  src/frontend/src/defaults/defaults.tsx
  src/frontend/src/defaults/links.tsx
  src/frontend/src/states/states.tsx
Labels: enhancement, Platform UI

#5812 Update .deepsource.toml
  .deepsource.toml
Labels: bug, CI

#5814 Update .deepsource.toml
  .deepsource.toml
Labels: bug, CI

#5817 [React] Stylish form titles
  src/frontend/src/components/nav/Layout.tsx
  src/frontend/src/functions/forms.tsx
  src/frontend/src/states/ModalState.tsx
Labels: user interface, Platform UI

#5821 Part table extra options
  InvenTree/part/serializers.py
  src/frontend/src/components/tables/part/PartTable.tsx
Labels: Platform UI

#5813 [PUI] Added AboutInventreeModal
  InvenTree/InvenTree/api.py
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/urls.py
  InvenTree/InvenTree/version.py
  InvenTree/part/templatetags/inventree_extras.py
  InvenTree/templates/about.html
  src/frontend/src/components/items/ButtonMenu.tsx
  src/frontend/src/components/items/CopyButton.tsx
  src/frontend/src/components/modals/AboutInvenTreeModal.tsx
  src/frontend/src/contexts/ThemeContext.tsx
  src/frontend/src/defaults/defaults.tsx
  src/frontend/src/defaults/links.tsx
  src/frontend/src/pages/Notifications.tsx
  src/frontend/src/states/ApiState.tsx
  src/frontend/src/states/states.tsx
Labels: enhancement, Platform UI

#5823 Skip plugin registry reload if performing django functions
  InvenTree/plugin/registry.py
Labels: plugin

#5778 Update django money / py-moneyed dependencies
  InvenTree/InvenTree/format.py
  InvenTree/InvenTree/helpers_model.py
  InvenTree/InvenTree/tests.py
  InvenTree/company/migrations/0067_alter_supplierpricebreak_price_currency.py
  InvenTree/order/migrations/0098_auto_20231024_1844.py
  InvenTree/part/migrations/0118_auto_20231024_1844.py
  InvenTree/stock/migrations/0104_alter_stockitem_purchase_price_currency.py
  requirements.in
  requirements.txt
Labels: pricing

#5819 Recursive delete fix fix
  .github/workflows/qc_checks.yaml
  InvenTree/InvenTree/models.py
  InvenTree/part/test_category.py
Labels: bug, CI

#5826 React updates
  src/frontend/src/components/items/ActionDropdown.tsx
  src/frontend/src/components/tables/part/PartTable.tsx
  src/frontend/src/components/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/components/tables/stock/StockItemTable.tsx
  src/frontend/src/functions/forms/PartForms.tsx
  src/frontend/src/functions/forms/StockForms.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: user interface, Platform UI
