Repository inventree/InvenTree, pull requests merged in 2023-01, with the labels that each got.

#4127 Fixes and improvements for the part import wizard
  InvenTree/InvenTree/settings.py
  InvenTree/part/admin.py
  InvenTree/part/part.py
  InvenTree/part/templates/part/import_wizard/ajax_part_upload.html
  InvenTree/part/templates/part/import_wizard/match_fields.html
  InvenTree/part/templates/part/import_wizard/part_upload.html
  InvenTree/part/urls.py
  InvenTree/part/views.py
Labels: bug, user interface, importer

#4132 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#4137 Add test description field
  InvenTree/templates/js/translated/stock.js
Labels: user interface

#4141 Update django-allauth lib version
  requirements.in
  requirements.txt
Labels: dependency

#4142 Update django-allauth version
  requirements.in
  requirements.txt
Labels: dependency

#4145 Disable cosign step in docker workflow
  .github/workflows/docker.yaml
  .github/workflows/update.yml.disabled
Labels: CI

#4148 Issues with maintenance_mode.txt
  InvenTree/InvenTree/settings.py
  requirements.txt
Labels: bug

#4067 Add Date input for table filter
  InvenTree/InvenTree/api_version.py
  InvenTree/stock/api.py
  InvenTree/templates/js/translated/filters.js
  InvenTree/templates/js/translated/table_filters.js
Labels: user interface, api

#4147 BUG: Fix settings lookup
  InvenTree/InvenTree/settings.py
Labels: bug, setup

#4153 Backport settings fix
  InvenTree/InvenTree/settings.py
Labels: bug, setup

#4160 Adds concurrency config for docker CI workflow
  .github/workflows/docker.yaml
Labels: CI, docker

#4154 Catch potential error when refreshing part pricing
  InvenTree/part/models.py
Labels: bug

#4161 Logic fix for build calculation
  InvenTree/build/models.py
Labels: bug, build

#4165 Label api refactor
  InvenTree/label/api.py
Labels: api

#4163 [FR] Move URL endpoints to API namespace
  InvenTree/part/api.py
  InvenTree/part/templates/part/part_base.html
  InvenTree/part/test_bom_export.py
  InvenTree/part/test_views.py
  InvenTree/part/urls.py
  InvenTree/templates/js/translated/bom.js
Labels: api

#4152 [FR] Simplify / optimize setting loading
  InvenTree/InvenTree/config.py
  InvenTree/InvenTree/permissions.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/urls.py
  InvenTree/common/api.py
  InvenTree/common/serializers.py
  InvenTree/common/tests.py
Labels: setup

#4169 SSO tweaks
  InvenTree/InvenTree/exceptions.py
  InvenTree/InvenTree/forms.py
  InvenTree/InvenTree/static/css/inventree.css
  InvenTree/templates/InvenTree/settings/login.html
  InvenTree/templates/account/base.html
  InvenTree/templates/account/login.html
  InvenTree/templates/account/signup.html
  InvenTree/templates/account/signup_closed.html
  InvenTree/templates/socialaccount/authentication_error.html
  InvenTree/templates/socialaccount/login.html
  InvenTree/templates/socialaccount/signup.html
  InvenTree/templates/socialaccount/snippets/provider_list.html
Labels: user interface, security

#4172 [FR] Enable restrictions on allowed domains for signup
  InvenTree/InvenTree/forms.py
  InvenTree/common/models.py
  InvenTree/common/tests.py
  InvenTree/templates/InvenTree/settings/login.html
Labels: enhancement, security, setup

#4176 Dep updates
  .pre-commit-config.yaml
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: dependency

#4189 Change default value for auto-backup setting
  InvenTree/common/models.py
Labels: setup

#4192 Gunicorn options
  docker/gunicorn.conf.py
  docker/production/.env
Labels: setup

#4190 Configuration options for dbbackup
  InvenTree/InvenTree/settings.py
  InvenTree/config_template.yaml
  tasks.py
Labels: setup

#4170 Initialize target date for new PO line and SO line
  InvenTree/order/templates/order/purchase_order_detail.html
  InvenTree/order/templates/order/sales_order_detail.html
  InvenTree/templates/js/translated/order.js
Labels: enhancement, order, user interface

#4244 [BUG] Fix ownership
  InvenTree/stock/models.py
  InvenTree/stock/test_views.py
  InvenTree/users/models.py
Labels: bug, stock, api

#4241 Fix debian 11 detection on installer
  contrib/install.sh
  contrib/installer/src/root_command.sh
Labels: bug, setup

#4240 Make sure that print label dialog has a submit button.
  InvenTree/templates/js/translated/label.js
Labels: bug, user interface

#4235 Rewording templates
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/install.yaml
Labels: bug

#4224 [BUG] Quick Installer: `INVENTREE_DB_PORT` errors
  InvenTree/config_template.yaml
  contrib/packager.io/functions.sh
Labels: bug, setup

#4219 Reload purchase order table after part order
  InvenTree/part/templates/part/detail.html
  InvenTree/templates/js/translated/order.js
Labels: bug, user interface

#4213 Fixed typo in settings page
  InvenTree/common/models.py
Labels: bug, translation

#4208 Fix for returning stock from the customer to a specified location
  InvenTree/stock/models.py
  InvenTree/stock/tests.py
Labels: bug, order

#4203 Bom export with substitute part numbers
  InvenTree/part/bom.py
  InvenTree/part/views.py
  InvenTree/templates/js/translated/bom.js
Labels: enhancement, part

#4225 [FR] Add "priority" field to BuildOrder
  InvenTree/InvenTree/api_version.py
  InvenTree/build/api.py
  InvenTree/build/migrations/0037_build_priority.py
  InvenTree/build/models.py
  InvenTree/build/serializers.py
  InvenTree/build/templates/build/build_base.html
  InvenTree/build/templates/build/detail.html
  InvenTree/templates/js/translated/build.js
Labels: enhancement, user interface, api, build

#4243 [BUG] Plugin Schedule do not update when beeing changed + plugin testing
  InvenTree/plugin/base/integration/mixins.py
  InvenTree/plugin/base/integration/test_mixins.py
  InvenTree/plugin/builtin/barcodes/inventree_barcode.py
  InvenTree/plugin/samples/integration/test_scheduled_task.py
  InvenTree/plugin/samples/locate/test_locate_sample.py
Labels: bug, enhancement, plugin, CI

#4214 [FR] Add last updated column for supplier parts
  InvenTree/InvenTree/api_version.py
  InvenTree/common/migrations/0016_alter_notificationentry_updated.py
  InvenTree/common/models.py
  InvenTree/company/api.py
  InvenTree/company/migrations/0052_alter_supplierpricebreak_updated.py
  InvenTree/company/migrations/0053_supplierpart_updated.py
  InvenTree/company/models.py
  InvenTree/company/serializers.py
  InvenTree/part/migrations/0093_auto_20230115_1404.py
  InvenTree/part/models.py
  InvenTree/stock/migrations/0092_alter_stockitem_updated.py
  InvenTree/stock/models.py
  InvenTree/templates/js/translated/company.js
Labels: enhancement, part, user interface, api

#4191 New Crowdin updates
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
Labels: translation

#4151 [FR] Simple API endpoint to change own user metadata
  InvenTree/users/api.py
  InvenTree/users/tests.py
Labels: api

#4186 [FR] Add API endpoint to activate plugins
  InvenTree/InvenTree/api_version.py
  InvenTree/plugin/api.py
  InvenTree/plugin/serializers.py
  InvenTree/plugin/test_plugin.py
  InvenTree/templates/InvenTree/settings/settings.html
  InvenTree/templates/js/dynamic/settings.js
  InvenTree/templates/js/translated/label.js
  InvenTree/templates/js/translated/plugin.js
Labels: plugin, api, breaking

#4259 Fix for showing about dialog
  InvenTree/part/templatetags/inventree_extras.py
Labels: bug, user interface

#4263 Tweak SSO settings page
  InvenTree/templates/InvenTree/settings/login.html
Labels: user interface

#4264 Bug fix for creating Part or Company via API
  InvenTree/company/models.py
  InvenTree/part/models.py
Labels: bug

#4185 Plugin settings refactor
  InvenTree/InvenTree/metadata.py
  InvenTree/plugin/api.py
  InvenTree/plugin/models.py
  InvenTree/plugin/test_api.py
Labels: enhancement, plugin, api

#4274 Add cli to package installs
  .pkgr.yml
  Procfile
Labels: enhancement, setup

#4275 Do not auto-fill target_date for line items
  InvenTree/order/migrations/0077_auto_20230129_0154.py
  InvenTree/order/models.py
  InvenTree/order/templates/order/purchase_order_detail.html
  InvenTree/order/templates/order/sales_order_detail.html
  InvenTree/templates/js/translated/order.js
Labels: order

#4276 Force builtin plugins to be active
  InvenTree/plugin/models.py
  InvenTree/plugin/registry.py
  InvenTree/plugin/test_api.py
Labels: bug, plugin

#4285 [BUG] Increase worker-timeout to account for install times
  docker/gunicorn.conf.py
Labels: setup
