Repository inventree/InvenTree, pull requests merged in 2024-06, with the labels that each got.

#7388 Cache updates
  .devcontainer/docker-compose.yml
  contrib/container/.env
  contrib/container/docker-compose.yml
  docs/docs/develop/devcontainer.md
  docs/docs/start/config.md
  docs/docs/start/docker.md
  src/backend/InvenTree/InvenTree/cache.py
  src/backend/InvenTree/InvenTree/helpers_model.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/config_template.yaml
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/plugin/base/event/events.py
  src/backend/InvenTree/plugin/registry.py
Labels: docker, setup

#7391 Template permission fix
  src/backend/InvenTree/InvenTree/unit_test.py
  src/backend/InvenTree/report/api.py
  src/backend/InvenTree/report/tests.py
Labels: bug, report, api

#7390 Currency setting
  docs/docs/settings/currency.md
  docs/docs/start/config.md
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/apps.py
  src/backend/InvenTree/InvenTree/exchange.py
  src/backend/InvenTree/InvenTree/fields.py
  src/backend/InvenTree/InvenTree/helpers.py
  src/backend/InvenTree/InvenTree/serializers.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/tasks.py
  src/backend/InvenTree/InvenTree/templatetags/inventree_extras.py
  src/backend/InvenTree/InvenTree/tests.py
  src/backend/InvenTree/InvenTree/views.py
  src/backend/InvenTree/common/currency.py
  src/backend/InvenTree/common/migrations/0010_migrate_currency_setting.py
  src/backend/InvenTree/common/migrations/0023_auto_20240602_1332.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/common/settings.py
  src/backend/InvenTree/common/tests.py
  src/backend/InvenTree/company/migrations/0025_auto_20201110_1001.py
  src/backend/InvenTree/company/migrations/0040_alter_company_currency.py
  src/backend/InvenTree/company/models.py
  src/backend/InvenTree/config_template.yaml
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/order/migrations/0038_auto_20201112_1737.py
  src/backend/InvenTree/order/migrations/0039_auto_20201112_2203.py
  src/backend/InvenTree/order/migrations/0045_auto_20210504_1946.py
  src/backend/InvenTree/order/migrations/0079_auto_20230304_0904.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/test_api.py
  src/backend/InvenTree/part/migrations/0055_auto_20201110_1001.py
  src/backend/InvenTree/part/migrations/0067_partinternalpricebreak.py
  src/backend/InvenTree/part/migrations/0089_auto_20221112_0128.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/part/stocktake.py
  src/backend/InvenTree/part/tasks.py
  src/backend/InvenTree/part/test_pricing.py
  src/backend/InvenTree/stock/migrations/0053_auto_20201110_0513.py
  src/backend/InvenTree/stock/migrations/0055_auto_20201117_1453.py
  src/backend/InvenTree/templates/InvenTree/settings/pricing.html
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
Labels: enhancement, refactor

#7393 Global Cache Fix
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/cache.py
  src/backend/InvenTree/InvenTree/ready.py
  src/backend/InvenTree/common/currency.py
Labels: bug

#7398 Currency format fix
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/common/validators.py
  src/frontend/src/defaults/formatters.tsx
Labels: bug, user interface, backport, Platform UI, backport-to-0.15.x

#7407 [Docs] Add more info on branching
  docs/docs/develop/contributing.md
Labels: documentation

#7408 Null url fix
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
Labels: bug, Platform UI

#7406 Provide setup keys for two-factor authentication alongside QR codes
  src/backend/InvenTree/templates/allauth_2fa/setup.html
Labels: enhancement, security

#7405 Panel placeholders
  src/frontend/src/components/nav/PanelGroup.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/pages/Index/Settings/UserSettings.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: refactor, Platform UI

#7417 Test result choices
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/part/migrations/0123_parttesttemplate_choices.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/part/test_api.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/test_api.py
  src/backend/InvenTree/templates/js/translated/part.js
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/tables/part/PartTestTemplateTable.tsx
  src/frontend/src/tables/stock/StockItemTestResultTable.tsx
Labels: enhancement, stock, api

#7418 Stock SKU export
  src/backend/InvenTree/stock/admin.py
Labels: import / export

#7419 Mantine charts
  src/frontend/package.json
  src/frontend/src/components/charts/colors.tsx
  src/frontend/src/components/charts/tooltipFormatter.tsx
  src/frontend/src/main.tsx
  src/frontend/src/pages/part/pricing/BomPricingPanel.tsx
  src/frontend/src/pages/part/pricing/PriceBreakPanel.tsx
  src/frontend/src/pages/part/pricing/PricingOverviewPanel.tsx
  src/frontend/src/pages/part/pricing/PurchaseHistoryPanel.tsx
  src/frontend/src/pages/part/pricing/SaleHistoryPanel.tsx
  src/frontend/src/pages/part/pricing/SupplierPricingPanel.tsx
  src/frontend/src/pages/part/pricing/VariantPricingPanel.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/tests/pages/pui_part.spec.ts
  src/frontend/yarn.lock
Labels: user interface, refactor, Platform UI

#7425 [plugins] allow static files for plugins
  src/backend/InvenTree/InvenTree/management/commands/collectplugins.py
  src/backend/InvenTree/InvenTree/ready.py
  src/backend/InvenTree/plugin/models.py
  src/backend/InvenTree/plugin/serializers.py
  src/backend/InvenTree/plugin/staticfiles.py
  tasks.py
Labels: enhancement, plugin

#7428 Adds support for Romanian locale tranaslations
  src/backend/InvenTree/InvenTree/locales.py
  src/backend/InvenTree/locale/ro/LC_MESSAGES/django.po
  src/frontend/.linguirc
  src/frontend/src/contexts/LanguageContext.tsx
Labels: enhancement

#7438 Fix for report migration
  src/backend/InvenTree/report/migrations/0026_auto_20240422_1301.py
Labels: bug, migration

#7404 Setting refactor
  src/backend/InvenTree/InvenTree/apps.py
  src/backend/InvenTree/InvenTree/fields.py
  src/backend/InvenTree/InvenTree/forms.py
  src/backend/InvenTree/InvenTree/helpers_model.py
  src/backend/InvenTree/InvenTree/social_auth_urls.py
  src/backend/InvenTree/InvenTree/sso.py
  src/backend/InvenTree/InvenTree/tasks.py
  src/backend/InvenTree/InvenTree/templatetags/inventree_extras.py
  src/backend/InvenTree/InvenTree/test_tasks.py
  src/backend/InvenTree/InvenTree/version.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/test_build.py
  src/backend/InvenTree/common/api.py
  src/backend/InvenTree/common/apps.py
  src/backend/InvenTree/common/currency.py
  src/backend/InvenTree/common/settings.py
  src/backend/InvenTree/common/tests.py
  src/backend/InvenTree/common/validators.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/part/settings.py
  src/backend/InvenTree/part/tasks.py
  src/backend/InvenTree/part/test_part.py
  src/backend/InvenTree/part/test_pricing.py
  src/backend/InvenTree/plugin/base/event/events.py
  src/backend/InvenTree/plugin/base/integration/AppMixin.py
  src/backend/InvenTree/plugin/base/integration/UrlsMixin.py
  src/backend/InvenTree/plugin/registry.py
  src/backend/InvenTree/plugin/templatetags/plugin_extras.py
  src/backend/InvenTree/plugin/test_api.py
  src/backend/InvenTree/report/helpers.py
  src/backend/InvenTree/report/templatetags/report.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/serializers.py
  src/backend/InvenTree/stock/views.py
  src/backend/InvenTree/users/models.py
Labels: refactor

#7440 fix: Add installer check for python version
  contrib/packager.io/functions.sh
Labels: bug, setup, backport, installer, backport-to-0.15.x

#7442 Allow build line list to be searched by IPN
  src/backend/InvenTree/build/api.py
Labels: api, build

#7449 Small refactor for stock item post-save signals
  src/backend/InvenTree/stock/models.py
Labels: refactor

#7450 Fix for gunicorn command
  tasks.py
Labels: bug, backport, backport-to-0.15.x

#7451 Improve stock item tracking API query
  src/backend/InvenTree/stock/api.py
Labels: bug, api, backport, backport-to-0.15.x

#7454 small code tweaks
  src/backend/InvenTree/part/helpers.py
  src/backend/InvenTree/part/urls.py
  src/backend/InvenTree/stock/serializers.py
Labels: refactor

#7455 Update data migration
  src/backend/InvenTree/report/migrations/0026_auto_20240422_1301.py
Labels: bug, migration, full-run

#7459 Add unit test for stockitemtracking API
  src/backend/InvenTree/stock/test_api.py
Labels: api, CI

#7472 Fix click-through for purchase order line item table
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
Labels: bug, user interface, Platform UI

#7474 Added details on stock ownership control
  docs/docs/stock/owner.md
Labels: documentation

#7481 Fix fields for PurchaseOrderCancelSerializer
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/order/test_api.py
Labels: bug, api, backport, backport-to-0.15.x

#7486 [PUI] Bug fix
  src/frontend/src/components/details/Details.tsx
Labels: bug, user interface, Platform UI

#7488 Fix non null field 'description'
  src/backend/InvenTree/report/migrations/0026_auto_20240422_1301.py
Labels: bug, migration

#7490 PUI bug fix
  src/frontend/src/pages/part/PartDetail.tsx
Labels: bug, user interface, Platform UI

#7492 New Crowdin updates
  src/backend/InvenTree/locale/cs/LC_MESSAGES/django.po
  src/backend/InvenTree/locale/pl/LC_MESSAGES/django.po
  src/frontend/src/locales/bg/messages.po
  src/frontend/src/locales/cs/messages.po
  src/frontend/src/locales/da/messages.po
  src/frontend/src/locales/de/messages.po
  src/frontend/src/locales/el/messages.po
  src/frontend/src/locales/en/messages.po
  src/frontend/src/locales/es-mx/messages.po
  src/frontend/src/locales/es/messages.po
  src/frontend/src/locales/fa/messages.po
  src/frontend/src/locales/fi/messages.po
  src/frontend/src/locales/fr/messages.po
  src/frontend/src/locales/he/messages.po
  src/frontend/src/locales/hi/messages.po
  src/frontend/src/locales/hu/messages.po
  src/frontend/src/locales/it/messages.po
  src/frontend/src/locales/ja/messages.po
  src/frontend/src/locales/ko/messages.po
  src/frontend/src/locales/lv/messages.po
  src/frontend/src/locales/nl/messages.po
  src/frontend/src/locales/no/messages.po
  src/frontend/src/locales/pl/messages.po
  src/frontend/src/locales/pseudo-LOCALE/messages.po
  src/frontend/src/locales/pt-br/messages.po
  src/frontend/src/locales/pt/messages.po
  src/frontend/src/locales/ro/messages.po
  src/frontend/src/locales/ru/messages.po
  src/frontend/src/locales/sk/messages.po
  src/frontend/src/locales/sl/messages.po
  src/frontend/src/locales/sr/messages.po
  src/frontend/src/locales/sv/messages.po
  src/frontend/src/locales/th/messages.po
  src/frontend/src/locales/tr/messages.po
  src/frontend/src/locales/uk/messages.po
  src/frontend/src/locales/vi/messages.po
  src/frontend/src/locales/zh-hans/messages.po
  src/frontend/src/locales/zh-hant/messages.po
Labels: translation

#7497 Handle missing dulwich module
  src/backend/InvenTree/InvenTree/version.py
  tasks.py
Labels: bug

#7498 Fix for example test report
  src/backend/InvenTree/report/templates/report/inventree_test_report.html
Labels: bug, report

#7500 [PUI] Allow search results to be opened in a new tab
  src/frontend/src/components/nav/SearchDrawer.tsx
Labels: user interface, Platform UI

#7506 Error checking for attachment model type
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/common/validators.py
Labels: bug

#7505 Plugin load fix
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/plugin/registry.py
  src/backend/InvenTree/plugin/test_plugin.py
Labels: bug, plugin, setup, backport, backport-to-0.15.x

#7511 Fix for notification query
  src/frontend/src/components/nav/Header.tsx
Labels: Platform UI

#7255 Bump pre commit versions
  .github/actions/setup/action.yaml
  .github/workflows/qc_checks.yaml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  contrib/dev_reqs/requirements.txt
  docs/docs/part/scheduling.md
  docs/docs/releases/0.1.4.md
  docs/docs/releases/0.4.0.md
  docs/docs/stock/stock.md
  docs/requirements.txt
  pyproject.toml
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/models.py
  src/backend/InvenTree/InvenTree/unit_test.py
  src/backend/InvenTree/config_template.yaml
  src/backend/InvenTree/templates/js/translated/barcode.js
  src/backend/requirements-dev.txt
  src/backend/requirements.txt
  src/frontend/playwright.config.ts
Labels: dependency

#7512 Handle null response case
  src/frontend/src/functions/auth.tsx
Labels: bug, Platform UI

#7513 Fix table permissions for CUI
  src/backend/InvenTree/templates/js/translated/attachment.js
Labels: bug, user interface

#7514 Top level cascade
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/models.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/part/templates/part/category.html
  src/backend/InvenTree/stock/api.py
  src/backend/InvenTree/stock/serializers.py
  src/backend/InvenTree/stock/templates/stock/location.html
  src/frontend/src/tables/part/PartCategoryTable.tsx
  src/frontend/src/tables/stock/StockLocationTable.tsx
Labels: bug, user interface, api

#7515 [Bug] Fix for BOM import
  src/backend/InvenTree/templates/js/translated/forms.js
Labels: bug, user interface

#7516 [bug] Handle case where deltas is null
  src/backend/InvenTree/stock/api.py
Labels: bug, api

#7519 [PUI] Table filters
  src/frontend/src/hooks/UseFilter.tsx
  src/frontend/src/tables/ColumnSelect.tsx
  src/frontend/src/tables/Filter.tsx
  src/frontend/src/tables/FilterSelectDrawer.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/tests/pui_tables.spec.ts
Labels: bug, user interface, CI, Platform UI

#7518 Add field info to user serializer
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/metadata.py
  src/backend/InvenTree/InvenTree/serializers.py
  src/backend/InvenTree/users/test_api.py
Labels: api

#7532 Plugin static files fix
  src/backend/InvenTree/plugin/staticfiles.py
Labels: plugin, refactor

#7293 Feat: SSO group sync
  README.md
  docs/docs/settings/SSO.md
  docs/docs/settings/global.md
  src/backend/InvenTree/InvenTree/apps.py
  src/backend/InvenTree/InvenTree/forms.py
  src/backend/InvenTree/InvenTree/sso.py
  src/backend/InvenTree/InvenTree/test_sso.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/templates/InvenTree/settings/login.html
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
Labels: enhancement, setup

#7535 Fix import widget type
  src/backend/InvenTree/stock/admin.py
Labels: bug, import / export, backport, backport-to-0.15.x

#7534 Calculate weighted average price when merging stock items
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/tests.py
Labels: bug, backport, backport-to-0.15.x
