Repository inventree/InvenTree, pull requests merged in 2024-04, with the labels that each got.

#6900 Fix TME supplier order number splitting
  InvenTree/plugin/builtin/suppliers/tme.py
Labels: bug, barcode, backport, backport-to-0.14.x

#6883 Add test start, end date and test station to the next gen UI
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/forms/fields/DateField.tsx
  src/frontend/src/defaults/formatters.tsx
  src/frontend/src/tables/stock/StockItemTestResultTable.tsx
Labels: stock, user interface, Platform UI

#6905 Dockerfile fixes
  Dockerfile
Labels: docker, refactor

#6906 Linting fixes
  InvenTree/InvenTree/config.py
  InvenTree/InvenTree/conversion.py
  InvenTree/InvenTree/exchange.py
  InvenTree/InvenTree/filters.py
  InvenTree/InvenTree/format.py
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/permissions.py
  InvenTree/InvenTree/social_auth_urls.py
  InvenTree/InvenTree/sso.py
Labels: refactor

#6909 [PUI] Hide blank contact field
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
Labels: Platform UI

#6907 Remove incorrect field from BomItemResource
  InvenTree/part/admin.py
Labels: bug, import / export, backport, backport-to-0.14.x

#6910 Add serializer context to CategoryDetail
  InvenTree/part/api.py
Labels: bug, user interface, api

#6912 allow write access for backport action
  .github/workflows/backport.yml
Labels: bug, CI

#6913 Remove incorrect field from BomItemResource (#6907)
  InvenTree/part/admin.py
Labels: bug, import / export

#6914 Remove translation macro
  src/frontend/src/tables/part/PartCategoryTemplateTable.tsx
Labels: bug, Platform UI

#6890 Security improvements
  .deepsource.toml
  .github/workflows/docker.yaml
  .github/workflows/qc_checks.yaml
  .github/workflows/release.yml
  .github/workflows/scorecard.yml
  .github/workflows/translations.yml
  .sonarcloud.properties
  Dockerfile
  README.md
  contrib/packager.io/functions.sh
Labels: CI

#6932 Fix unit tests
  .github/scripts/version_check.py
  .github/workflows/qc_checks.yaml
  docs/mkdocs.yml
  src/backend/InvenTree/InvenTree/tests.py
Labels: bug, CI

#6916 Some small style fixes
  contrib/container/Dockerfile
  docs/extract_schema.py
  src/backend/InvenTree/InvenTree/admin.py
  src/backend/InvenTree/InvenTree/config.py
  src/backend/InvenTree/InvenTree/fields.py
  src/backend/InvenTree/InvenTree/models.py
  src/backend/InvenTree/InvenTree/serializers.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/test_api.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/generic/states/__init__.py
  src/backend/InvenTree/label/test_api.py
  src/backend/InvenTree/machine/machine_type.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/plugin/base/barcodes/mixins.py
  src/backend/InvenTree/plugin/base/event/events.py
  src/backend/InvenTree/plugin/base/integration/ScheduleMixin.py
  src/backend/InvenTree/plugin/base/label/mixins.py
  src/backend/InvenTree/plugin/base/locate/mixins.py
  src/backend/InvenTree/plugin/builtin/integration/currency_exchange.py
  src/backend/InvenTree/plugin/helpers.py
  src/backend/InvenTree/plugin/models.py
  src/backend/InvenTree/plugin/registry.py
  src/backend/InvenTree/plugin/samples/integration/validation_sample.py
  src/backend/InvenTree/stock/models.py
  src/frontend/package.json
  src/frontend/src/components/nav/Layout.tsx
Labels: refactor

#6881 [PUI] Add coverage testing
  .github/workflows/qc_checks.yaml
  src/frontend/.gitignore
  src/frontend/package.json
  src/frontend/playwright.config.ts
  src/frontend/src/components/items/LanguageSelect.tsx
  src/frontend/src/components/nav/NavHoverMenu.tsx
  src/frontend/tests/baseFixtures.ts
  src/frontend/tests/classic.spec.ts
  src/frontend/tests/ui_plattform.spec.ts
  src/frontend/vite.config.ts
  src/frontend/yarn.lock
Labels: enhancement, CI, Platform UI

#6934 Fix docker push action
  .github/workflows/docker.yaml
Labels: bug, CI, docker, refactor

#6946 Fix locate plugin testing
  src/backend/InvenTree/plugin/base/locate/__init__.py
  src/backend/InvenTree/plugin/base/locate/test_locate.py
Labels: CI

#6855 [PUI] Add licenses texts to PUI
  .github/workflows/qc_checks.yaml
  .gitignore
  src/backend/InvenTree/InvenTree/api.py
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/urls.py
  src/backend/requirements.in
  src/backend/requirements.txt
  src/frontend/package.json
  src/frontend/src/components/modals/LicenseModal.tsx
  src/frontend/src/contexts/ThemeContext.tsx
  src/frontend/src/defaults/links.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/vite.config.ts
  src/frontend/yarn.lock
  tasks.py
Labels: enhancement, api, Platform UI

#6949 Fetch server state when refetching all global states
  src/frontend/src/states/states.tsx
Labels: Platform UI

#6950 Enable backup value option for plugin settings check
  src/backend/InvenTree/plugin/base/integration/SettingsMixin.py
Labels: enhancement, plugin

#6921 Fix TME supplier order number splitting (Backport #6900)
  InvenTree/plugin/builtin/suppliers/tme.py
Labels: bug, barcode, api

#6953 [Docker] Fix broken production image
  .github/workflows/docker.yaml
  contrib/container/Dockerfile
Labels: bug, CI, docker, setup

#6958 Update backport.yml
  .github/workflows/backport.yml
Labels: CI, dependency

#6959 Revert "Update backport.yml"
  .github/workflows/backport.yml
Labels: CI

#6960 [Docker] Another fix
  contrib/container/Dockerfile
Labels: bug, docker

#6962 Improve logic for non-nullable fields
  src/backend/InvenTree/InvenTree/admin.py
Labels: bug, import / export, backport, backport-to-0.14.x

#6965 Tests: remove dead paths in test files
  src/backend/InvenTree/InvenTree/tests.py
  src/backend/InvenTree/InvenTree/unit_test.py
  src/backend/InvenTree/common/test_tasks.py
  src/backend/InvenTree/common/tests.py
  src/backend/InvenTree/generic/states/test_transition.py
  src/backend/InvenTree/generic/states/tests.py
  src/backend/InvenTree/label/test_api.py
  src/backend/InvenTree/machine/test_api.py
  src/backend/InvenTree/stock/test_api.py
Labels: CI

#6968 Use pinned eslint version
  .github/workflows/qc_checks.yaml
  src/backend/.eslintrc.yml
Labels: bug, CI

#6969 Bump dependencies
  .pre-commit-config.yaml
  src/backend/package-lock.json
  src/backend/requirements-dev.txt
  src/backend/requirements.txt
  src/frontend/package.json
  src/frontend/yarn.lock
Labels: dependency

#6973 [BUG] Include .vite subdir in PUI releases
  .github/workflows/qc_checks.yaml
  src/frontend/vite.config.ts
Labels: bug, Platform UI

#6967 Add codecov
  .github/workflows/qc_checks.yaml
  README.md
  codecov.yml
  src/backend/InvenTree/InvenTree/urls.py
  src/frontend/src/main.tsx
Labels: enhancement, CI

#6945 Fix test coverage
  .github/workflows/qc_checks.yaml
  codecov.yml
  src/backend/InvenTree/generic/states/test_transition.py
  src/backend/InvenTree/machine/tests.py
  src/backend/InvenTree/web/tests.py
  tasks.py
Labels: CI, full-run

#6947 Use xml for coverage info
  .github/workflows/qc_checks.yaml
  tasks.py
Labels: CI

#6984 Revert "Bump sqren/backport-github-action from 8.9.3 to 9.3.1"
  .github/workflows/backport.yml
Labels: bug, CI, dependency

#6988 [PUI] Move buttons form components
  src/frontend/src/components/buttons/CopyButton.tsx
  src/frontend/src/components/buttons/EditButton.tsx
  src/frontend/src/components/buttons/ScanButton.tsx
  src/frontend/src/components/buttons/YesNoButton.tsx
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/components/forms/InstanceOptions.tsx
  src/frontend/src/components/items/InfoItem.tsx
  src/frontend/src/components/modals/AboutInvenTreeModal.tsx
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/AccountDetailPanel.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/bom/BomTable.tsx
  src/frontend/src/tables/company/AddressTable.tsx
  src/frontend/src/tables/machine/MachineListTable.tsx
  src/frontend/src/tables/part/ParametricPartTable.tsx
  src/frontend/src/tables/part/PartCategoryTable.tsx
  src/frontend/src/tables/part/PartParameterTable.tsx
  src/frontend/src/tables/stock/StockItemTestResultTable.tsx
Labels: refactor, Platform UI

#6991 [CI] Optimize runs
  .github/workflows/qc_checks.yaml
Labels: CI

#6992 [CI] Re-add playwright reporting
  .github/workflows/qc_checks.yaml
  src/frontend/playwright.config.ts
Labels: CI

#6993 [PUI] Fix licensing dialog
  src/frontend/src/components/modals/LicenseModal.tsx
Labels: bug, Platform UI

#6996 Improve DB efficiency for user settings
  src/backend/InvenTree/common/api.py
Labels: enhancement, api, refactor

#6995 [CI] Increase migration test coverage
  .github/workflows/qc_checks.yaml
  src/backend/InvenTree/stock/test_migrations.py
Labels: CI, full-run

#6987 [PUI] Quick commands pallet
  src/frontend/package.json
  src/frontend/src/components/buttons/SpotlightButton.tsx
  src/frontend/src/components/items/MenuLinks.tsx
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/components/nav/Layout.tsx
  src/frontend/src/components/nav/NavHoverMenu.tsx
  src/frontend/src/components/nav/NavigationDrawer.tsx
  src/frontend/src/contexts/LanguageContext.tsx
  src/frontend/src/defaults/actions.tsx
  src/frontend/src/defaults/links.tsx
  src/frontend/src/defaults/menuItems.tsx
  src/frontend/src/pages/Index/Playground.tsx
  src/frontend/src/states/LocalState.tsx
  src/frontend/tests/baseFixtures.ts
  src/frontend/tests/pui_command.spec.ts
  src/frontend/yarn.lock
Labels: enhancement, Platform UI

#7007 [PUI] Tweaks
  src/frontend/src/components/details/DetailsBadge.tsx
  src/frontend/src/components/nav/PageDetail.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/bom/UsedInTable.tsx
  src/frontend/src/tables/part/ParametricPartTable.tsx
Labels: bug, user interface, Platform UI

#7009 [PUI] Mobile ignore warning in dev
  src/frontend/src/states/LocalState.tsx
  src/frontend/src/views/MainView.tsx
  src/frontend/src/views/MobileAppView.tsx
Labels: Platform UI

#7013 [BUG] JS translation syntax error (stock-badge in search window)
  src/backend/InvenTree/templates/js/translated/model_renderers.js
  src/backend/InvenTree/templates/js/translated/return_order.js
Labels: bug, user interface, backport, backport-to-0.14.x

#7017 Allow write permission for backport.yml
  .github/workflows/backport.yml
Labels: bug, CI, backport, backport-to-0.14.x

#7018 Trying again to fix backport action
  .github/workflows/backport.yml
Labels: CI, backport, backport-to-0.14.x

#7010 [PUI] Add more tests
  .github/workflows/qc_checks.yaml
  codecov.yml
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/tests/baseFixtures.ts
  src/frontend/tests/cui.spec.ts
  src/frontend/tests/defaults.ts
  src/frontend/tests/pui_basic.spec.ts
  src/frontend/tests/pui_command.spec.ts
  src/frontend/tests/pui_general.spec.ts
  src/frontend/tests/pui_stock.spec.ts
  tasks.py
Labels: CI, Platform UI

#7021 Revert "Trying again to fix backport action"
  .github/workflows/backport.yml
Labels: bug, CI, backport, backport-to-0.14.x

#7008 Form focus
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/forms/fields/DateField.tsx
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
  src/frontend/src/tables/part/ParametricPartTable.tsx
  src/frontend/src/tables/part/PartParameterTable.tsx
Labels: enhancement, user interface, Platform UI

#6985 [PUI] pricing tab
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/company/api.py
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/serializers.py
  src/frontend/package.json
  src/frontend/src/components/charts/colors.tsx
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/images/Thumbnail.tsx
  src/frontend/src/defaults/formatters.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/functions/urls.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/part/PartPricingPanel.tsx
  src/frontend/src/pages/part/pricing/BomPricingPanel.tsx
  src/frontend/src/pages/part/pricing/PriceBreakPanel.tsx
  src/frontend/src/pages/part/pricing/PricingOverviewPanel.tsx
  src/frontend/src/pages/part/pricing/PricingPanel.tsx
  src/frontend/src/pages/part/pricing/PurchaseHistoryPanel.tsx
  src/frontend/src/pages/part/pricing/SaleHistoryPanel.tsx
  src/frontend/src/pages/part/pricing/SupplierPricingPanel.tsx
  src/frontend/src/pages/part/pricing/VariantPricingPanel.tsx
  src/frontend/src/tables/Column.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/purchasing/SupplierPriceBreakTable.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
  src/frontend/yarn.lock
  tasks.py
Labels: enhancement, api, pricing, refactor, Platform UI

#7043 Fix typo in Procfile
  Procfile
Labels: bug, installer

#7044 BOM pricing table fix
  src/frontend/src/pages/part/pricing/BomPricingPanel.tsx
  src/frontend/src/pages/part/pricing/VariantPricingPanel.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/bom/BomTable.tsx
  src/frontend/src/tables/bom/UsedInTable.tsx
  src/frontend/src/tables/part/PartTable.tsx
Labels: user interface, Platform UI

#7046 Change backport action
  .github/workflows/backport.yml
  backportrc.json
Labels: bug, CI, dependency, backport, backport-to-0.14.x

#7048 Fix regex
  .github/workflows/backport.yml
Labels: bug, CI, backport-to-0.14.x

#7050 backport.yml : Fix copy_labels_pattern
  .github/workflows/backport.yml
Labels: bug, CI, backport-to-0.14.x

#7049 PUI BOM table updates
  src/frontend/src/tables/bom/BomTable.tsx
Labels: user interface, Platform UI

#7051 Revert to sqren backport action
  .github/workflows/backport.yml
Labels: CI, backport, backport-to-0.14.x

#7053 [PUI] Pricing UX improvements
  src/frontend/src/components/charts/tooltipFormatter.tsx
  src/frontend/src/pages/part/PartPricingPanel.tsx
  src/frontend/src/pages/part/pricing/BomPricingPanel.tsx
  src/frontend/src/pages/part/pricing/PriceBreakPanel.tsx
  src/frontend/src/pages/part/pricing/PricingOverviewPanel.tsx
  src/frontend/src/pages/part/pricing/PricingPanel.tsx
  src/frontend/src/pages/part/pricing/PurchaseHistoryPanel.tsx
  src/frontend/src/pages/part/pricing/SaleHistoryPanel.tsx
  src/frontend/src/pages/part/pricing/SupplierPricingPanel.tsx
  src/frontend/src/pages/part/pricing/VariantPricingPanel.tsx
Labels: Platform UI

#7022 [PUI] Add quick login via url
  src/frontend/src/pages/Auth/Login.tsx
  src/frontend/tests/defaults.ts
  src/frontend/tests/pui_command.spec.ts
  src/frontend/tests/pui_general.spec.ts
  src/frontend/tests/pui_stock.spec.ts
Labels: CI, Platform UI

#7019 Update broken links
  RELEASE.md
  docs/docs/develop/contributing.md
  docs/docs/extend/plugins/urls.md
  docs/docs/report/stock_location.md
Labels: documentation

#6970 [PUI] Session authentication
  .github/workflows/qc_checks.yaml
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/urls.py
  src/backend/InvenTree/users/api.py
  src/backend/InvenTree/users/models.py
  src/frontend/src/App.tsx
  src/frontend/src/components/forms/AuthenticationForm.tsx
  src/frontend/src/components/images/ApiImage.tsx
  src/frontend/src/components/items/AttachmentLink.tsx
  src/frontend/src/components/nav/Layout.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/functions/auth.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/functions/notifications.tsx
  src/frontend/src/pages/Auth/Logout.tsx
  src/frontend/src/router.tsx
  src/frontend/src/states/SessionState.tsx
  src/frontend/src/states/SettingsState.tsx
  src/frontend/src/states/StatusState.tsx
  src/frontend/src/states/UserState.tsx
  src/frontend/src/states/states.tsx
  src/frontend/src/views/DesktopAppView.tsx
  src/frontend/tests/cui.spec.ts
  src/frontend/tests/defaults.ts
  src/frontend/tests/login.ts
  src/frontend/tests/pui_basic.spec.ts
  src/frontend/tests/pui_command.spec.ts
  src/frontend/tests/pui_general.spec.ts
  src/frontend/tests/pui_stock.spec.ts
Labels: api, Platform UI

#7059 Catch potential missing element
  src/backend/InvenTree/common/views.py
Labels: bug, import / export, backport, backport-to-0.14.x

#7062 Update docker_install.md
  docs/docs/start/docker_install.md
Labels: docker, documentation

#7061 Update docker_install.md
  RELEASE.md
  docs/docs/start/docker_install.md
  docs/mlc_config.json
Labels: bug, documentation

#7066 Fix currency rendering in order tables
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/company/serializers.py
  src/backend/InvenTree/templates/js/dynamic/nav.js
  src/backend/InvenTree/templates/js/translated/purchase_order.js
  src/backend/InvenTree/templates/js/translated/return_order.js
  src/backend/InvenTree/templates/js/translated/sales_order.js
  src/frontend/src/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/tables/sales/SalesOrderTable.tsx
Labels: bug, order, user interface, pricing, backport, Platform UI, backport-to-0.14.x

#7024 Adds "active" field for Company model
  docs/README.md
  docs/docs/assets/images/order/company_disable.png
  docs/docs/assets/images/order/disable_supplier_part.png
  docs/docs/assets/images/order/disable_supplier_part_edit.png
  docs/docs/order/company.md
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/company/api.py
  src/backend/InvenTree/company/migrations/0069_company_active.py
  src/backend/InvenTree/company/models.py
  src/backend/InvenTree/company/serializers.py
  src/backend/InvenTree/company/templates/company/company_base.html
  src/backend/InvenTree/company/test_api.py
  src/backend/InvenTree/templates/js/translated/company.js
  src/backend/InvenTree/templates/js/translated/table_filters.js
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/render/StatusRenderer.tsx
  src/frontend/src/forms/BuildForms.tsx
  src/frontend/src/forms/CompanyForms.tsx
  src/frontend/src/forms/PurchaseOrderForms.tsx
  src/frontend/src/forms/SalesOrderForms.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
  src/frontend/src/tables/company/CompanyTable.tsx
  src/frontend/src/tables/company/ContactTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/tables/purchasing/SupplierPartTable.tsx
  src/frontend/src/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/tables/sales/SalesOrderTable.tsx
  src/frontend/src/tables/stock/StockItemTestResultTable.tsx
  src/frontend/tests/pui_stock.spec.ts
Labels: enhancement, order, api, Platform UI

#7075 Fix for update_pricing method:
  src/backend/InvenTree/order/models.py
Labels: bug, order, pricing, backport, backport-to-0.14.x

#7079 Add contenttype model to API
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/metadata.py
  src/backend/InvenTree/common/api.py
  src/backend/InvenTree/common/serializers.py
  src/backend/InvenTree/common/tests.py
Labels: api

#7098 Group dependabot PRs per ecosystem
  .github/dependabot.yml
Labels: CI

#7057 [PUI] Add playground / pricing tests
  src/frontend/playwright.config.ts
  src/frontend/src/pages/part/pricing/BomPricingPanel.tsx
  src/frontend/src/pages/part/pricing/PricingOverviewPanel.tsx
  src/frontend/src/pages/part/pricing/PricingPanel.tsx
  src/frontend/tests/defaults.ts
  src/frontend/tests/login.ts
  src/frontend/tests/pages/pui_index.spec.ts
  src/frontend/tests/pages/pui_part.spec.ts
Labels: CI, Platform UI

#7099 Remove coveralls integration
  .github/workflows/qc_checks.yaml
  README.md
  docs/docs/credits.md
  docs/docs/security.md
  src/backend/requirements-dev.in
  src/backend/requirements-dev.txt
Labels: CI, dependency

#7106 Build allocation table updates
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/templates/js/translated/build.js
  src/frontend/src/functions/conversion.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
Labels: user interface, api, build, Platform UI

#7081 Pin hashes in requirements
  .devops/testing_ci.yml
  .github/actions/setup/action.yaml
  .github/requirements.in
  .github/requirements.txt
  .github/workflows/docker.yaml
  .github/workflows/qc_checks.yaml
  .github/workflows/release.yaml
  .github/workflows/update.yml.disabled
  .pre-commit-config.yaml
  contrib/container/Dockerfile
  docs/docs/faq.md
  src/backend/requirements-dev.txt
  src/backend/requirements.txt
  tasks.py
Labels: CI, security

#7097 Add PUI info banner to CUI
  docs/docs/start/config.md
  src/backend/InvenTree/config_template.yaml
  src/backend/InvenTree/templates/InvenTree/settings/global.html
  src/backend/InvenTree/templates/InvenTree/settings/login.html
  src/backend/InvenTree/templates/InvenTree/settings/plugin.html
  src/backend/InvenTree/templates/InvenTree/settings/report.html
  src/backend/InvenTree/templates/account/login.html
  src/backend/InvenTree/templates/pui_banner.html
Labels: enhancement, user interface, Platform UI

#7113 [PUI] Test modals
  src/frontend/src/components/buttons/ScanButton.tsx
  src/frontend/src/components/modals/LicenseModal.tsx
  src/frontend/tests/modals.spec.ts
Labels: CI, Platform UI

#7115 [PUI] Implement "build outputs" table
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/items/ActionDropdown.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/hooks/UseTable.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/company/ManufacturerPartDetail.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/TableHoverCard.tsx
  src/frontend/src/tables/bom/BomTable.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
  src/frontend/src/tables/company/CompanyTable.tsx
  src/frontend/src/tables/machine/MachineListTable.tsx
  src/frontend/src/tables/part/PartTable.tsx
  src/frontend/src/tables/purchasing/ManufacturerPartTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/tables/sales/SalesOrderTable.tsx
  src/frontend/src/tables/settings/TemplateTable.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
Labels: user interface, build, Platform UI

#7114 [PUI] Test for errors in console
  src/frontend/src/components/details/DetailsBadge.tsx
  src/frontend/src/components/nav/PageDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/part/pricing/PricingOverviewPanel.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/states/ApiState.tsx
  src/frontend/src/states/SettingsState.tsx
  src/frontend/src/states/StatusState.tsx
  src/frontend/src/states/UserState.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
  src/frontend/src/tables/settings/ErrorTable.tsx
  src/frontend/tests/baseFixtures.ts
  src/frontend/tests/modals.spec.ts
  src/frontend/tests/pages/pui_part.spec.ts
Labels: CI, Platform UI

#7121 Fix CI filters
  .github/workflows/docker.yaml
Labels: CI, docker

#7126 CI: Add pre-commit hook to use modern testing asserts
  .pre-commit-config.yaml
  src/backend/InvenTree/InvenTree/test_api.py
  src/backend/InvenTree/InvenTree/tests.py
  src/backend/InvenTree/InvenTree/unit_test.py
  src/backend/InvenTree/build/test_api.py
  src/backend/InvenTree/common/tests.py
  src/backend/InvenTree/company/test_api.py
  src/backend/InvenTree/label/tests.py
  src/backend/InvenTree/machine/test_api.py
  src/backend/InvenTree/order/test_api.py
  src/backend/InvenTree/part/test_api.py
  src/backend/InvenTree/part/test_category.py
  src/backend/InvenTree/plugin/base/integration/test_mixins.py
  src/backend/InvenTree/plugin/base/label/test_label_mixin.py
  src/backend/InvenTree/plugin/base/locate/test_locate.py
  src/backend/InvenTree/plugin/test_api.py
  src/backend/InvenTree/plugin/test_helpers.py
  src/backend/InvenTree/plugin/test_plugin.py
  src/backend/InvenTree/report/tests.py
  src/backend/InvenTree/stock/test_api.py
  src/backend/InvenTree/users/tests.py
  src/backend/InvenTree/web/tests.py
Labels: CI

#7117 Small style fixes
  src/backend/InvenTree/InvenTree/settings.py
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/components/details/ItemDetails.tsx
  src/frontend/src/components/editors/TemplateEditor/TemplateEditor.tsx
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/forms/fields/DateField.tsx
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
  src/frontend/src/components/items/AttachmentLink.tsx
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/forms/CompanyForms.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/pages/Index/Scan.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/pages/company/ManufacturerPartDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
  src/frontend/src/tables/company/CompanyTable.tsx
  src/frontend/src/tables/part/ParametricPartTable.tsx
  src/frontend/src/tables/part/PartCategoryTemplateTable.tsx
  src/frontend/src/tables/part/PartTable.tsx
  src/frontend/src/tables/purchasing/SupplierPartTable.tsx
  src/frontend/tests/pages/pui_index.spec.ts
  src/frontend/tests/pui_basic.spec.ts
  src/frontend/tests/pui_general.spec.ts
  src/frontend/tests/pui_stock.spec.ts
Labels: Platform UI

#7120 Improve reproduciblity of image
  .github/dependabot.yml
  .github/requirements.in
  .github/requirements.txt
  .github/workflows/qc_checks.yaml
  .pre-commit-config.yaml
  contrib/container/Dockerfile
  contrib/container/requirements.in
  contrib/container/requirements.txt
  contrib/packager.io/functions.sh
  docs/README.md
  docs/docs/start/install.md
  docs/requirements.in
  docs/requirements.txt
  tasks.py
Labels: docker

#7119 [FR] Increase Length of URL limit on import
  src/backend/InvenTree/company/models.py
Labels: part

#7129 Add ukrainian as a language option
  src/backend/InvenTree/InvenTree/locales.py
  src/backend/InvenTree/locale/uk/LC_MESSAGES/django.po
  src/frontend/.linguirc
  src/frontend/src/contexts/LanguageContext.tsx
  src/frontend/src/locales/uk/messages.d.ts
  src/frontend/src/locales/uk/messages.po
Labels: enhancement, translation

#7133 Session cookie fix
  docs/docs/start/config.md
  src/backend/InvenTree/InvenTree/settings.py
Labels: bug

#7112 Fixes to make compatible with Python 3.12
  .github/workflows/qc_checks.yaml
  src/backend/InvenTree/InvenTree/unit_test.py
  src/backend/InvenTree/plugin/helpers.py
  src/backend/InvenTree/plugin/registry.py
Labels: CI, setup

#7135 CI: Fix vul attribution
  src/backend/osv-scanner.toml
Labels: security

#7136 [PUI]: Refactor columns
  src/frontend/src/pages/part/pricing/SaleHistoryPanel.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
Labels: user interface, Platform UI

#7143 [PUI] Add more table tests
  src/frontend/tests/pui_general.spec.ts
  src/frontend/tests/pui_stock.spec.ts
Labels: CI, Platform UI

#7144 PUI tweaks
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/order/serializers.py
  src/frontend/src/components/items/ProgressBar.tsx
  src/frontend/src/hooks/UseFilter.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
  src/frontend/src/tables/part/PartTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/tables/sales/SalesOrderTable.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
Labels: user interface, api, Platform UI

#7142 [PUI] More style fixes
  contrib/packager.io/functions.sh
  src/frontend/src/components/buttons/AddItemButton.tsx
  src/frontend/src/components/buttons/SplitButton.tsx
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/components/details/DetailsBadge.tsx
  src/frontend/src/components/details/DetailsImage.tsx
  src/frontend/src/components/editors/TemplateEditor/TemplateEditor.tsx
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/forms/fields/ChoiceField.tsx
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
  src/frontend/src/components/images/Thumbnail.tsx
  src/frontend/src/components/items/DocInfo.tsx
  src/frontend/src/components/items/DocTooltip.tsx
  src/frontend/src/components/items/ProgressBar.tsx
  src/frontend/src/components/items/TitleWithDoc.tsx
  src/frontend/src/components/nav/DetailDrawer.tsx
  src/frontend/src/components/nav/NotificationDrawer.tsx
  src/frontend/src/components/nav/PageDetail.tsx
  src/frontend/src/components/nav/PanelGroup.tsx
  src/frontend/src/components/nav/SearchDrawer.tsx
  src/frontend/src/components/nav/SettingsHeader.tsx
  src/frontend/src/components/render/Build.tsx
  src/frontend/src/components/render/Company.tsx
  src/frontend/src/components/render/Generic.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/render/Order.tsx
  src/frontend/src/components/render/Part.tsx
  src/frontend/src/components/render/StatusRenderer.tsx
  src/frontend/src/components/render/Stock.tsx
  src/frontend/src/components/render/User.tsx
  src/frontend/src/components/widgets/MarkdownEditor.tsx
  src/frontend/src/components/widgets/WidgetLayout.tsx
  src/frontend/src/defaults/formatters.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/pages/Index/Playground.tsx
  src/frontend/src/pages/Index/Scan.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/tables/ColumnSelect.tsx
  src/frontend/src/tables/DownloadAction.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/RowActions.tsx
  src/frontend/src/tables/general/AttachmentTable.tsx
  src/frontend/src/tables/part/PartThumbTable.tsx
  src/frontend/src/tables/plugin/PluginListTable.tsx
Labels: Platform UI
