Repository inventree/InvenTree, pull requests merged in 2024-02, with the labels that each got.

#6379 Fix for invoke update
  tasks.py
Labels: bug, setup, backport, backport-to-0.13.x

#6380 Fix for tasks.py - docker
  .github/workflows/docker.yaml
  Dockerfile
  tasks.py
Labels: bug, CI, docker

#6381 [PUI] API URL fixes
  src/frontend/src/components/forms/AuthenticationForm.tsx
  src/frontend/src/components/modals/AboutInvenTreeModal.tsx
  src/frontend/src/components/modals/QrCodeModal.tsx
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/components/nav/NotificationDrawer.tsx
  src/frontend/src/components/nav/PartCategoryTree.tsx
  src/frontend/src/components/nav/SearchDrawer.tsx
  src/frontend/src/components/nav/StockLocationTree.tsx
  src/frontend/src/components/tables/part/PartThumbTable.tsx
  src/frontend/src/states/ApiState.tsx
Labels: Platform UI

#6383 Fix urls loading for plugin testing
  InvenTree/plugin/urls.py
Labels: bug, plugin

#6368 [PUI] Login / Logout State Fixes
  .vscode/launch.json
  InvenTree/InvenTree/api.py
  InvenTree/InvenTree/middleware.py
  InvenTree/InvenTree/settings.py
  docs/docs/develop/react-frontend.md
  src/frontend/src/App.tsx
  src/frontend/src/components/forms/AuthenticationForm.tsx
  src/frontend/src/components/nav/MainMenu.tsx
  src/frontend/src/components/render/StatusRenderer.tsx
  src/frontend/src/components/settings/SettingItem.tsx
  src/frontend/src/contexts/LanguageContext.tsx
  src/frontend/src/functions/auth.tsx
  src/frontend/src/pages/Auth/Login.tsx
  src/frontend/src/states/ApiState.tsx
  src/frontend/src/states/SessionState.tsx
  src/frontend/src/states/SettingsState.tsx
  src/frontend/src/states/StatusState.tsx
  src/frontend/src/states/UserState.tsx
  src/frontend/src/states/states.tsx
  src/frontend/src/tables/Filter.tsx
  src/frontend/src/views/DesktopAppView.tsx
  src/frontend/src/views/MainView.tsx
Labels: bug, Platform UI

#6387 BuildOrder: UI bug fix
  InvenTree/templates/js/translated/build.js
Labels: bug, user interface, build, backport, backport-to-0.13.x

#6393 Error message fix
  src/frontend/src/functions/forms.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
Labels: user interface, Platform UI

#6390 [WIP] Site ID Fixes
  InvenTree/InvenTree/apps.py
  InvenTree/InvenTree/context.py
  InvenTree/InvenTree/forms.py
  InvenTree/InvenTree/helpers_model.py
  InvenTree/InvenTree/magic_login.py
  InvenTree/InvenTree/serializers.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/tests.py
  InvenTree/common/models.py
  InvenTree/config_template.yaml
  InvenTree/users/models.py
  InvenTree/users/tests.py
  docs/docs/assets/images/settings/social_application_configure.png
  docs/docs/start/advanced.md
  docs/docs/start/config.md
Labels: bug, enhancement, setup, breaking

#6396 Fix for filter adjustment in related field
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
Labels: bug, user interface, Platform UI

#6398 Remove devcontainer Git Feature
  .devcontainer/devcontainer.json
Labels: dependency, docker

#6404 Simplify translation
  InvenTree/InvenTree/serializers.py
Labels: translation

#6405 [PUI] Tweaks and refactor for "part details" page
  src/frontend/src/components/render/ModelType.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/tables/Details.tsx
Labels: bug, Platform UI

#6406 Fix contentexcludes in tasks.py
  tasks.py
Labels: bug

#6408 Use registry.get_plugin()
  InvenTree/common/notifications.py
  InvenTree/plugin/base/event/events.py
  InvenTree/plugin/base/event/mixins.py
  InvenTree/plugin/builtin/integration/core_notifications.py
  InvenTree/plugin/builtin/integration/test_core_notifications.py
Labels: bug, plugin, backport, backport-to-0.13.x

#6407 [Docker] Pin postgresql version
  Dockerfile
  docker/install_build_packages.sh
Labels: dependency, docker, setup

#5405 Add mermaid to docs
  .github/workflows/qc_checks.yaml
  docs/ci/check_mkdocs_config.py
  docs/mkdocs.yml
  docs/requirements.txt
Labels: enhancement, documentation

#6173 Bump to Dj 4.x
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/test_api.py
  InvenTree/InvenTree/test_middleware.py
  InvenTree/build/admin.py
  InvenTree/build/migrations/0013_auto_20200425_0507.py
  InvenTree/build/migrations/0029_auto_20210601_1525.py
  InvenTree/common/models.py
  InvenTree/company/admin.py
  InvenTree/order/api.py
  InvenTree/order/models.py
  InvenTree/order/test_api.py
  InvenTree/order/test_views.py
  InvenTree/part/filters.py
  InvenTree/part/migrations/0020_auto_20190908_0404.py
  InvenTree/part/migrations/0039_auto_20200515_1127.py
  InvenTree/part/models.py
  InvenTree/part/test_views.py
  InvenTree/plugin/test_plugin.py
  InvenTree/report/admin.py
  InvenTree/stock/admin.py
  InvenTree/stock/filters.py
  InvenTree/stock/migrations/0012_auto_20190908_0405.py
  InvenTree/stock/migrations/0022_auto_20200217_1109.py
  InvenTree/stock/models.py
  InvenTree/users/admin.py
  InvenTree/users/api.py
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: enhancement, dependency

#6421 Bump deps
  requirements-dev.txt
  requirements.txt
Labels: dependency

#6427 Fix display of allocated stock items in build table
  InvenTree/build/serializers.py
Labels: user interface, javascript, backport, backport-to-0.13.x

#6436 Mention the API version bump in CONTRIBUTION.md
  CONTRIBUTING.md
Labels: documentation

#6437 Fix for build.js
  InvenTree/templates/js/translated/build.js
Labels: user interface, build

#6422 Maintenance Mode Fix
  InvenTree/InvenTree/backends.py
  InvenTree/InvenTree/settings.py
Labels: bug, setup

#6439 Week number
  InvenTree/stock/models.py
  docs/docs/stock/tracking.md
Labels: bug, stock, documentation

#6443 Fix for issue 6442
  InvenTree/stock/serializers.py
Labels: bug, stock, api, backport, backport-to-0.13.x

#6441 Postgresql fix
  Dockerfile
  InvenTree/InvenTree/backends.py
  docker/init.sh
  docker/requirements.txt
Labels: bug, dependency, docker, setup

#6446 Update tasks.py
  tasks.py
Labels: import / export

#6450 Label printing errors
  InvenTree/label/api.py
  InvenTree/plugin/base/label/mixins.py
Labels: report

#6451 Maintenance Mode Improvements
  InvenTree/InvenTree/backends.py
  InvenTree/InvenTree/management/commands/rebuild_models.py
  InvenTree/InvenTree/management/commands/runmigrations.py
  InvenTree/InvenTree/ready.py
  InvenTree/InvenTree/tasks.py
  InvenTree/common/models.py
  InvenTree/label/apps.py
  InvenTree/report/apps.py
  tasks.py
Labels: setup

#6452 (Yet another) Fix for dockerfile
  docker/requirements.txt
Labels: bug, dependency, docker, setup

#6453 Update Proxy support for django 4.2
  InvenTree/InvenTree/settings.py
  InvenTree/config_template.yaml
  docs/docs/start/config.md
Labels: dependency, setup, breaking

#6454 Report helper
  InvenTree/report/templatetags/report.py
  docs/docs/report/helpers.md
Labels: report, documentation

#6319 Generate API docs
  .github/workflows/qc_checks.yaml
  .gitignore
  InvenTree/InvenTree/api.py
  InvenTree/InvenTree/magic_login.py
  InvenTree/InvenTree/serializers.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/social_auth_urls.py
  InvenTree/InvenTree/test_api_version.py
  InvenTree/common/api.py
  InvenTree/common/models.py
  InvenTree/common/serializers.py
  InvenTree/generic/states/api.py
  InvenTree/part/api.py
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/plugin/base/action/api.py
  InvenTree/plugin/base/locate/api.py
  InvenTree/plugin/serializers.py
  InvenTree/stock/models.py
  InvenTree/users/api.py
  InvenTree/users/serializers.py
  tasks.py
Labels: enhancement, api, CI

#6455 Log plugin event errors
  InvenTree/InvenTree/models.py
  InvenTree/plugin/base/event/events.py
  InvenTree/report/models.py
  InvenTree/stock/models.py
Labels: enhancement, plugin

#6461 PluginValidationMixin : fix full_clean method
  InvenTree/InvenTree/models.py
Labels: bug

#6467 Fix uncaught Company.DoesNotExist error in SupplierBarcodeMixin
  InvenTree/plugin/base/barcodes/mixins.py
Labels: bug, backport, backport-to-0.13.x

#6466 Use re_path instead of deprecated url function in plugin docs
  docs/docs/extend/plugins/panel.md
  docs/docs/extend/plugins/urls.md
Labels: plugin, documentation

#6468 Fix APICallMixin url_args handling
  InvenTree/plugin/base/integration/APICallMixin.py
  InvenTree/plugin/base/integration/test_mixins.py
Labels: bug, plugin

#6469 Backport #6467
  InvenTree/plugin/base/barcodes/mixins.py
Labels: bug, barcode, plugin

#6440 Add API change detection
  .github/workflows/qc_checks.yaml
  InvenTree/InvenTree/api_version.py
  ci/version_check.py
Labels: enhancement, CI

#6474 Fix schema action
  .github/workflows/qc_checks.yaml
Labels: bug, CI

#6479 Remove maintenance mode wrapper from plugin loading
  InvenTree/plugin/registry.py
Labels: bug

#6477 Add BOM creation to the sofa example
  docs/docs/api/python/examples.md
Labels: documentation

#4824 Machine integration
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/helpers_mixin.py
  InvenTree/InvenTree/metadata.py
  InvenTree/InvenTree/serializers.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/tests.py
  InvenTree/InvenTree/urls.py
  InvenTree/common/models.py
  InvenTree/common/serializers.py
  InvenTree/generic/states/api.py
  InvenTree/label/api.py
  InvenTree/machine/__init__.py
  InvenTree/machine/admin.py
  InvenTree/machine/api.py
  InvenTree/machine/apps.py
  InvenTree/machine/machine_type.py
  InvenTree/machine/machine_types/__init__.py
  InvenTree/machine/machine_types/label_printer.py
  InvenTree/machine/migrations/0001_initial.py
  InvenTree/machine/migrations/__init__.py
  InvenTree/machine/models.py
  InvenTree/machine/registry.py
  InvenTree/machine/serializers.py
  InvenTree/machine/test_api.py
  InvenTree/machine/tests.py
  InvenTree/plugin/base/label/mixins.py
  InvenTree/plugin/base/label/test_label_mixin.py
  InvenTree/plugin/builtin/labels/inventree_machine.py
  InvenTree/plugin/machine/__init__.py
  InvenTree/plugin/machine/machine_types.py
  InvenTree/users/models.py
  docs/docs/extend/machines/label_printer.md
  docs/docs/extend/machines/overview.md
  docs/mkdocs.yml
  docs/requirements.txt
  src/frontend/src/components/forms/fields/ChoiceField.tsx
  src/frontend/src/components/items/ActionDropdown.tsx
  src/frontend/src/components/items/InfoItem.tsx
  src/frontend/src/components/items/UnavailableIndicator.tsx
  src/frontend/src/components/nav/DetailDrawer.tsx
  src/frontend/src/components/settings/SettingItem.tsx
  src/frontend/src/components/settings/SettingList.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/MachineManagementPanel.tsx
  src/frontend/src/states/SettingsState.tsx
  src/frontend/src/states/states.tsx
  src/frontend/src/tables/machine/MachineListTable.tsx
  src/frontend/src/tables/machine/MachineTypeTable.tsx
Labels: enhancement, plugin, feature, Platform UI

#6482 Handle error on logout
  src/frontend/src/functions/auth.tsx
  src/frontend/src/states/SettingsState.tsx
  src/frontend/src/states/UserState.tsx
Labels: bug, Platform UI

#6484 Move CurrencyTable to admin center
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/tables/settings/CurrencyTable.tsx
Labels: Platform UI

#6488 Added pdf2image kwargs
  InvenTree/machine/machine_types/label_printer.py
  InvenTree/plugin/base/label/mixins.py
Labels: enhancement, report

#6487 Fix settings typing and use generics from standard collection
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/tasks.py
  InvenTree/common/models.py
  InvenTree/machine/machine_type.py
  InvenTree/machine/registry.py
  InvenTree/machine/serializers.py
  InvenTree/plugin/base/integration/SettingsMixin.py
  InvenTree/plugin/registry.py
Labels: bug, refactor

#6493 Forms actions fix
  InvenTree/InvenTree/permissions.py
  InvenTree/stock/api.py
  InvenTree/stock/templates/stock/item.html
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/stock.js
Labels: bug, user interface

#6496 Plugin context fix
  InvenTree/plugin/views.py
Labels: bug, user interface, plugin

#6497 Fix broken URL
  InvenTree/templates/js/translated/company.js
Labels: bug, user interface, backport, backport-to-0.13.x

#6503 Default site
  InvenTree/InvenTree/settings.py
  docs/docs/start/config.md
Labels: setup

#6505 Fix schema test on a pass
  .github/workflows/qc_checks.yaml
Labels: bug, CI

#6507 Added doc for status_label to context variables
  docs/docs/report/context_variables.md
Labels: documentation

#6057 Add option to disable the build output completion if are tests not passed
  InvenTree/build/models.py
  InvenTree/build/serializers.py
  InvenTree/build/test_build.py
  InvenTree/common/models.py
  InvenTree/common/settings.py
  InvenTree/templates/InvenTree/settings/build.html
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
Labels: api, build

#6430 [WIP] Test result table
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/management/commands/check_migrations.py
  InvenTree/InvenTree/tests.py
  InvenTree/build/test_build.py
  InvenTree/part/admin.py
  InvenTree/part/api.py
  InvenTree/part/fixtures/test_templates.yaml
  InvenTree/part/migrations/0120_parttesttemplate_key.py
  InvenTree/part/migrations/0121_auto_20240207_0344.py
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/part/test_api.py
  InvenTree/part/test_migrations.py
  InvenTree/part/test_part.py
  InvenTree/report/tests.py
  InvenTree/stock/admin.py
  InvenTree/stock/api.py
  InvenTree/stock/fixtures/stock_tests.yaml
  InvenTree/stock/migrations/0105_stockitemtestresult_template.py
  InvenTree/stock/migrations/0106_auto_20240207_0353.py
  InvenTree/stock/migrations/0107_remove_stockitemtestresult_test_and_more.py
  InvenTree/stock/models.py
  InvenTree/stock/serializers.py
  InvenTree/stock/templates/stock/item.html
  InvenTree/stock/test_api.py
  InvenTree/stock/test_migrations.py
  InvenTree/stock/tests.py
  InvenTree/templates/js/translated/model_renderers.js
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/stock.js
  docs/docs/part/test.md
  docs/docs/stock/test.md
  src/frontend/src/App.tsx
  src/frontend/src/components/items/YesNoButton.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/render/ModelType.tsx
  src/frontend/src/components/render/Part.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/enums/ModelType.tsx
  src/frontend/src/hooks/UseInstance.tsx
  src/frontend/src/hooks/UseTable.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/part/PartTestTemplateTable.tsx
  src/frontend/src/tables/settings/CurrencyTable.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
  src/frontend/src/tables/stock/StockItemTestResultTable.tsx
  tasks.py
Labels: enhancement, stock, user interface, api, breaking, Platform UI

#6512 Tweak PartParameterTable
  InvenTree/part/api.py
  src/frontend/src/tables/part/PartParameterTable.tsx
Labels: Platform UI

#6513 Allow import of part images
  InvenTree/part/admin.py
Labels: import / export

#6514 Fixes for test result updates
  InvenTree/InvenTree/api_version.py
  InvenTree/part/api.py
  InvenTree/stock/migrations/0106_auto_20240207_0353.py
  InvenTree/stock/migrations/0108_auto_20240219_0252.py
  InvenTree/stock/models.py
  InvenTree/stock/serializers.py
  InvenTree/templates/js/translated/stock.js
  src/frontend/src/tables/FilterSelectDrawer.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/part/PartTestTemplateTable.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
Labels: bug, api, migration

#6515 [PUI] Notifications
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/pages/Notifications.tsx
  src/frontend/src/tables/notifications/NotificationsTable.tsx
Labels: Platform UI

#6516 [PUI] Tweaks
  InvenTree/InvenTree/api_version.py
  InvenTree/part/api.py
  src/frontend/src/states/UserState.tsx
  src/frontend/src/tables/part/PartTestTemplateTable.tsx
Labels: Platform UI

#6518 [PUI] Fix for clearable form fields
  src/frontend/src/components/forms/fields/ApiFormField.tsx
Labels: bug, Platform UI

#6522 Bump CI/pre-commit versions
  .pre-commit-config.yaml
  InvenTree/InvenTree/templatetags/inventree_extras.py
  InvenTree/order/api.py
  InvenTree/plugin/builtin/labels/label_sheet.py
  ci/check_js_templates.py
  requirements.txt
  tasks.py
Labels: CI, dependency

#6523 [PUI] Make Category tree theme-aware
  src/frontend/src/components/nav/PartCategoryTree.tsx
Labels: bug, Platform UI

#6521 [PUI] Make API form Select Field theme-aware
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
Labels: bug, Platform UI

#6526 Test template disable
  InvenTree/InvenTree/api_version.py
  InvenTree/part/api.py
  InvenTree/part/migrations/0122_parttesttemplate_enabled.py
  InvenTree/part/models.py
  InvenTree/part/serializers.py
  InvenTree/part/test_part.py
  InvenTree/stock/api.py
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/stock.js
  InvenTree/templates/js/translated/table_filters.js
  docs/docs/part/test.md
  src/frontend/src/tables/part/PartTestTemplateTable.tsx
  src/frontend/src/tables/stock/StockItemTestResultTable.tsx
Labels: enhancement, stock, api

#6527 Update devcontainer docs
  docs/docs/develop/react-frontend.md
Labels: documentation

#6528 Locales fix
  src/frontend/src/components/items/LanguageSelect.tsx
  src/frontend/src/contexts/LanguageContext.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/DisplaySettingsPanel.tsx
  src/frontend/src/states/LocalState.tsx
Labels: bug, Platform UI

#6483 Added various PO fixes
  InvenTree/InvenTree/api_version.py
  InvenTree/order/api.py
  InvenTree/order/models.py
  InvenTree/order/serializers.py
  InvenTree/order/test_api.py
  InvenTree/templates/js/translated/purchase_order.js
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/forms/PurchaseOrderForms.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
Labels: order, user interface, api, Platform UI

#6532 Bug fix for allocating items to build
  InvenTree/build/serializers.py
  InvenTree/build/test_api.py
Labels: bug, build, backport, backport-to-0.13.x

#6536 API Tree filters
  InvenTree/InvenTree/api_version.py
  InvenTree/part/api.py
  InvenTree/part/templates/part/category.html
  InvenTree/part/test_api.py
  InvenTree/stock/api.py
  InvenTree/stock/serializers.py
  InvenTree/stock/templates/stock/location.html
  InvenTree/stock/test_api.py
  src/frontend/src/tables/part/PartCategoryTable.tsx
  src/frontend/src/tables/stock/StockLocationTable.tsx
Labels: api

#6538 Update PartParameterTemplate API
  InvenTree/InvenTree/api_version.py
  InvenTree/part/api.py
  InvenTree/part/serializers.py
  src/frontend/src/tables/part/PartParameterTemplateTable.tsx
Labels: part, api, Platform UI

#6540 Retry table name query
  src/frontend/src/tables/InvenTreeTable.tsx
Labels: bug, Platform UI

#6545 Dependabot/pip/cryptography 42.0.4
  requirements-dev.txt
  requirements.txt
Labels: dependency, security, python, backport, backport-to-0.13.x

#6542 Wrap theme parameters in memo
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
  src/frontend/src/components/nav/PartCategoryTree.tsx
Labels: Platform UI

#6546 Dependabot/pip/cryptography 42.0.4 (#6545)
  InvenTree/build/test_api.py
  requirements-dev.txt
  requirements.txt
Labels: dependency, security

#6539 [Feature] Engineering Units
  InvenTree/InvenTree/conversion.py
  InvenTree/InvenTree/tests.py
  docs/docs/concepts/units.md
Labels: enhancement

#6549 Fix for build output table
  InvenTree/templates/js/translated/build.js
Labels: bug, user interface, javascript

#6553 Remove unused template tag
  InvenTree/InvenTree/templatetags/inventree_extras.py
Labels: refactor

#6543 Seperate CUI url paths and tests
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/test_middleware.py
  InvenTree/InvenTree/test_urls.py
  InvenTree/InvenTree/test_views.py
  InvenTree/InvenTree/tests.py
  InvenTree/InvenTree/urls.py
  InvenTree/build/models.py
  InvenTree/build/tests.py
  InvenTree/company/models.py
  InvenTree/company/test_views.py
  InvenTree/company/tests.py
  InvenTree/label/tests.py
  InvenTree/order/models.py
  InvenTree/order/test_views.py
  InvenTree/order/tests.py
  InvenTree/part/models.py
  InvenTree/part/test_category.py
  InvenTree/part/test_part.py
  InvenTree/part/test_views.py
  InvenTree/plugin/base/integration/test_mixins.py
  InvenTree/plugin/builtin/barcodes/test_inventree_barcode.py
  InvenTree/plugin/plugin.py
  InvenTree/stock/models.py
  InvenTree/stock/test_views.py
  InvenTree/stock/tests.py
  InvenTree/users/tests.py
  tasks.py
Labels: CI, refactor, Platform UI

#6559 Fix tranlation pipeline
  .github/actions/setup/action.yaml
  .github/workflows/check_translations.yaml
  .github/workflows/translations.yml
Labels: bug

#6561 Adjust config template
  InvenTree/config_template.yaml
Labels: setup

#6556 Move get_scheduled_tasks call into register_tasks function
  InvenTree/plugin/base/integration/ScheduleMixin.py
  InvenTree/plugin/samples/integration/test_scheduled_task.py
Labels: bug, plugin, backport, backport-to-0.13.x

#6566 Move get_scheduled_tasks call into register_tasks function (Backport #6556)
  InvenTree/plugin/base/integration/ScheduleMixin.py
  InvenTree/plugin/samples/integration/test_scheduled_task.py
Labels: bug, plugin

#6569 Fix postgresql isolation level
  InvenTree/InvenTree/settings.py
Labels: bug, setup

#6573 Switch tests, docs, database settings from psycopg2 to psycopg
  .github/workflows/qc_checks.yaml
  InvenTree/InvenTree/settings.py
  docs/docs/start/install.md
Labels: bug, CI

#6535 Add config option to fully disable installing plugins
  InvenTree/InvenTree/api.py
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/templatetags/inventree_extras.py
  InvenTree/config_template.yaml
  InvenTree/part/test_part.py
  InvenTree/plugin/installer.py
  InvenTree/plugin/test_api.py
  InvenTree/templates/InvenTree/settings/plugin.html
  docs/docs/start/config.md
  src/frontend/src/defaults/defaults.tsx
  src/frontend/src/states/states.tsx
  src/frontend/src/tables/RowActions.tsx
  src/frontend/src/tables/plugin/PluginListTable.tsx
Labels: enhancement, user interface, plugin, api

#6562 Refactor docker CI for speed increases
  .github/workflows/docker.yaml
  Dockerfile
Labels: CI, docker, refactor

#6580 Allow currency symbol to be omitted from render_currency
  InvenTree/InvenTree/format.py
  InvenTree/InvenTree/helpers_model.py
  InvenTree/InvenTree/tests.py
Labels: bug, report

#6581 Tree fix
  InvenTree/InvenTree/api_version.py
  InvenTree/part/api.py
  InvenTree/part/filters.py
  InvenTree/part/serializers.py
  InvenTree/stock/api.py
  InvenTree/stock/filters.py
  InvenTree/stock/serializers.py
  src/frontend/src/components/nav/PartCategoryTree.tsx
  src/frontend/src/components/nav/StockLocationTree.tsx
Labels: bug, api, Platform UI

#6583 Tree fix
  InvenTree/part/test_api.py
  InvenTree/stock/serializers.py
  InvenTree/stock/test_api.py
  src/frontend/src/components/nav/BreadcrumbList.tsx
Labels: bug, CI, Platform UI

#6584 Temperature units
  InvenTree/InvenTree/conversion.py
  InvenTree/InvenTree/tests.py
Labels: enhancement

#6585 Fix SITE_URL validator
  InvenTree/common/models.py
Labels: bug

#6551 [WIP] docker / Caddy
  .github/actions/setup/action.yaml
  .github/workflows/qc_checks.yaml
  Dockerfile
  InvenTree/InvenTree/settings.py
  InvenTree/config_template.yaml
  docker/.env
  docker/Caddyfile
  docker/docker-compose.sqlite.yml
  docker/docker-compose.yml
  docker/install_build_packages.sh
  docker/nginx.dev.conf
  docker/production/nginx.prod.conf
  docker/requirements.txt
  docs/_includes/django.html
  docs/docs/develop/starting.md
  docs/docs/extend/plugins.md
  docs/docs/extend/plugins/app.md
  docs/docs/extend/plugins/metadata.md
  docs/docs/extend/plugins/urls.md
  docs/docs/faq.md
  docs/docs/report/report.md
  docs/docs/start/advanced.md
  docs/docs/start/bare_prod.md
  docs/docs/start/config.md
  docs/docs/start/docker.md
  docs/docs/start/docker_dev.md
  docs/docs/start/docker_install.md
  docs/docs/start/docker_prod.md
  docs/docs/start/intro.md
  docs/docs/start/serving_files.md
  docs/mkdocs.yml
  docs/mlc_config.json
  requirements.in
  requirements.txt
  tasks.py
Labels: enhancement, dependency, docker, setup, breaking, refactor

#6582 Refactor label/report template copying
  InvenTree/InvenTree/config.py
  InvenTree/generic/templating/__init__.py
  InvenTree/generic/templating/apps.py
  InvenTree/label/apps.py
  InvenTree/label/models.py
  InvenTree/label/tests.py
  InvenTree/machine/tests.py
  InvenTree/plugin/base/label/test_label_mixin.py
  InvenTree/report/apps.py
Labels: report, refactor

#6595 Translation fixes
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/templates/socialaccount/signup.html
Labels: bug, translation

#6590 Devcontainer postgresql
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/postCreateCommand.sh
  .vscode/launch.json
  .vscode/tasks.json
  CONTRIBUTING.md
  Dockerfile
  InvenTree/common/models.py
  InvenTree/plugin/api.py
  InvenTree/plugin/registry.py
  docs/docs/develop/contributing.md
  docs/docs/develop/devcontainer.md
  docs/docs/develop/starting.md
  docs/docs/faq.md
  docs/docs/start/intro.md
  docs/mkdocs.yml
Labels: docker, setup, breaking

#6597 [PUI] Stock item forms
  src/frontend/src/enums/Roles.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
  src/frontend/src/tables/stock/StockLocationTable.tsx
Labels: Platform UI

#6598 [PUI] Adds NewPart form
  src/frontend/src/forms/PartForms.tsx
  src/frontend/src/pages/Index/Playground.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/tables/part/PartTable.tsx
Labels: Platform UI

#6599 [PUI] Part parameter table
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/part/ParametricPartTable.tsx
  src/frontend/src/tables/part/PartParameterTable.tsx
  src/frontend/src/tables/part/PartTable.tsx
Labels: part, Platform UI

#6601 Tweak for devcontainer docker compose
  .devcontainer/docker-compose.yml
Labels: docker, setup

#6603 Details image tweaks
  src/frontend/src/components/images/DetailsImage.tsx
  src/frontend/src/tables/Details.tsx
  src/frontend/src/tables/ItemDetails.tsx
  src/frontend/src/tables/part/PartThumbTable.tsx
Labels: user interface, refactor, Platform UI

#6604 BOM / Build Updates
  InvenTree/InvenTree/api_version.py
  InvenTree/build/api.py
  InvenTree/build/serializers.py
  InvenTree/build/templates/build/detail.html
  InvenTree/part/api.py
  InvenTree/part/filters.py
  InvenTree/part/serializers.py
  InvenTree/templates/js/translated/bom.js
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/part.js
  src/frontend/src/tables/bom/BomTable.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
  src/frontend/src/tables/part/PartTable.tsx
Labels: enhancement, part, user interface, api, build, Platform UI

#6606 Fix docker tags
  .github/workflows/docker.yaml
Labels: bug, CI, docker
