Repository inventree/InvenTree, pull requests merged in 2024-09, with the labels that each got.

#8047 Bump frontend deps
  src/frontend/package.json
  src/frontend/yarn.lock
Labels: dependency

#8048 Add more test coverage for backend
  src/backend/InvenTree/InvenTree/unit_test.py
  src/backend/InvenTree/importer/tests.py
  src/backend/InvenTree/machine/tests.py
  src/backend/InvenTree/report/tests.py
  src/backend/InvenTree/stock/test_api.py
  src/backend/InvenTree/stock/test_views.py
  src/backend/InvenTree/stock/tests.py
  src/backend/InvenTree/users/api.py
  src/backend/InvenTree/users/models.py
  src/backend/InvenTree/users/test_api.py
  src/backend/InvenTree/users/tests.py
  src/backend/InvenTree/web/tests.py
Labels: CI

#8005 [PUI] Make actions recognisable
  src/frontend/src/components/buttons/AdminButton.tsx
  src/frontend/src/components/items/ActionDropdown.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/company/ManufacturerPartDetail.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/machine/MachineListTable.tsx
Labels: refactor, Platform UI

#7980 Notes editor
  src/frontend/package.json
  src/frontend/src/components/editors/NotesEditor.tsx
  src/frontend/tests/pages/pui_part.spec.ts
  src/frontend/vite.config.ts
  src/frontend/yarn.lock
Labels: user interface, Platform UI

#8066 Handle null or undefined TextField values
  src/frontend/src/components/forms/fields/TextField.tsx
Labels: user interface, Platform UI

#8071 Fix for image click events
  src/frontend/src/components/buttons/ActionButton.tsx
Labels: bug, user interface, backport, Platform UI, backport-to-0.16.x

#8069 Fix for part serializer
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/part/serializers.py
Labels: bug, part, api

#8072 PUI: Improve table rendering of link columns
  src/frontend/src/tables/company/AddressTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
Labels: bug, user interface, Platform UI

#7904 Add namespaces to tasks
  .devcontainer/postCreateCommand.sh
  .github/actions/migration/action.yaml
  .github/workflows/check_translations.yaml
  .github/workflows/docker.yaml
  .github/workflows/qc_checks.yaml
  .github/workflows/translations.yaml
  .vscode/tasks.json
  contrib/container/Dockerfile
  contrib/container/dev-docker-compose.yml
  contrib/container/docker-compose.yml
  contrib/packager.io/functions.sh
  contrib/packager.io/preinstall.sh
  docs/docs/api/api.md
  docs/docs/develop/contributing.md
  docs/docs/develop/react-frontend.md
  docs/docs/faq.md
  docs/docs/start/bare_dev.md
  docs/docs/start/docker_install.md
  docs/mlc_config.json
  readthedocs.yml
  src/frontend/playwright.config.ts
  tasks.py
Labels: setup

#8076 Add option for controlling test result uploads
  docs/docs/settings/global.md
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/serializers.py
  src/backend/InvenTree/stock/test_api.py
  src/backend/InvenTree/templates/InvenTree/settings/stock.html
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
Labels: stock, api

#8083 Packager: easier to parse debug messages
  contrib/packager.io/functions.sh
  contrib/packager.io/postinstall.sh
  contrib/packager.io/preinstall.sh
  src/backend/InvenTree/report/migrations/0026_auto_20240422_1301.py
  src/backend/InvenTree/users/migrations/0011_auto_20240523_1640.py
Labels: setup, installer, backport-to-0.16.x

#8086 [PUI] Sales order actions
  src/backend/InvenTree/order/serializers.py
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/forms/SalesOrderForms.tsx
  src/frontend/src/tables/sales/SalesOrderLineItemTable.tsx
Labels: order, user interface, Platform UI

#8018 Remove references to old setting
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/common/tests.py
  src/backend/InvenTree/report/api.py
  src/backend/InvenTree/report/migrations/0028_labeltemplate_attach_to_model_and_more.py
  src/backend/InvenTree/report/models.py
  src/backend/InvenTree/report/serializers.py
  src/backend/InvenTree/report/tests.py
  src/backend/InvenTree/stock/templates/stock/item_base.html
  src/backend/InvenTree/templates/InvenTree/settings/report.html
  src/backend/InvenTree/templates/base.html
  src/frontend/src/pages/Index/Settings/AdminCenter/ReportTemplatePanel.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  tasks.py
Labels: report, refactor

#8082 Package use uv
  contrib/packager.io/functions.sh
Labels: setup, installer, backport-to-0.16.x

#8092 Update used tech stack
  README.md
Labels: documentation

#8093 [PUI] Fix translation of model type strings
  src/frontend/src/components/nav/SearchDrawer.tsx
  src/frontend/src/components/render/Company.tsx
  src/frontend/src/components/render/ModelType.tsx
  src/frontend/src/components/render/Stock.tsx
Labels: bug, user interface, Platform UI

#8104 [PUI] Refactor keeping modelinfo together
  src/frontend/src/components/render/ModelType.tsx
Labels: refactor, Platform UI

#8090 Improve logic for automatically updating part pricing
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/unit_test.py
  src/backend/InvenTree/build/test_api.py
  src/backend/InvenTree/company/models.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/part/tasks.py
  src/backend/InvenTree/part/test_pricing.py
  src/backend/InvenTree/stock/models.py
Labels: bug, pricing, backport, backport-to-0.16.x

#8040 [PUI] Add view of all defined units to Admin center
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/common/api.py
  src/backend/InvenTree/common/serializers.py
  src/backend/InvenTree/common/tests.py
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/UnitManagmentPanel.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/tests/baseFixtures.ts
Labels: enhancement, api, Platform UI

#8119 Fix typo:
  src/frontend/src/tables/stock/StockItemTable.tsx
Labels: translation

#8120 Fix image upload for company page
  src/frontend/src/pages/company/CompanyDetail.tsx
Labels: bug, user interface, backport, Platform UI, backport-to-0.16.x

#8122 Improve logic for automatically updating part pricing (#8090)
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/unit_test.py
  src/backend/InvenTree/build/test_api.py
  src/backend/InvenTree/company/models.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/part/tasks.py
  src/backend/InvenTree/part/test_pricing.py
  src/backend/InvenTree/stock/models.py
Labels: bug, pricing

#8097 [PUI] Add codecov bundler analyzer
  .github/workflows/qc_checks.yaml
  codecov.yml
  src/frontend/package.json
  src/frontend/vite.config.ts
  src/frontend/yarn.lock
Labels: CI, Platform UI

#7944 [PUI] User settings panel updates
  docs/docs/demo.md
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/metadata.py
  src/backend/InvenTree/InvenTree/permissions.py
  src/backend/InvenTree/InvenTree/serializers.py
  src/backend/InvenTree/users/api.py
  src/backend/InvenTree/users/test_api.py
  src/frontend/src/components/buttons/YesNoButton.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/AccountDetailPanel.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/DisplaySettingsPanel.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/UserPanel.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/UserThemePanel.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
Labels: user interface, refactor, Platform UI

#8128 Fix missing trans strings
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
Labels: bug, translation

#7470 PUI Plugin Panels
  docs/docs/extend/plugins/panel.md
  docs/docs/extend/plugins/ui.md
  docs/docs/settings/global.md
  docs/docs/start/config.md
  docs/mkdocs.yml
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/management/commands/collectplugins.py
  src/backend/InvenTree/InvenTree/models.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/unit_test.py
  src/backend/InvenTree/InvenTree/urls.py
  src/backend/InvenTree/build/filters.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/plugin/api.py
  src/backend/InvenTree/plugin/base/integration/UserInterfaceMixin.py
  src/backend/InvenTree/plugin/base/integration/test_mixins.py
  src/backend/InvenTree/plugin/installer.py
  src/backend/InvenTree/plugin/mixins/__init__.py
  src/backend/InvenTree/plugin/registry.py
  src/backend/InvenTree/plugin/samples/integration/templates/uidemo/custom_part_panel.html
  src/backend/InvenTree/plugin/samples/integration/user_interface_sample.py
  src/backend/InvenTree/plugin/samples/static/plugin/sample_panel.js
  src/backend/InvenTree/plugin/serializers.py
  src/backend/InvenTree/plugin/staticfiles.py
  src/frontend/playwright.config.ts
  src/frontend/src/components/nav/Panel.tsx
  src/frontend/src/components/nav/PanelGroup.tsx
  src/frontend/src/components/plugins/PluginContext.tsx
  src/frontend/src/components/plugins/PluginPanel.tsx
  src/frontend/src/components/plugins/PluginSource.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/hooks/UsePluginPanels.tsx
  src/frontend/src/main.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/PluginManagementPanel.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/pages/Index/Settings/UserSettings.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/company/ManufacturerPartDetail.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/purchasing/PurchasingIndex.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesIndex.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/states/UserState.tsx
  src/frontend/src/tables/plugin/PluginListTable.tsx
  src/frontend/tests/pages/pui_part.spec.ts
  src/frontend/tests/pui_plugins.spec.ts
Labels: enhancement, user interface, plugin, feature, Platform UI

#8126 Revert int.worker to worker
  .vscode/tasks.json
  contrib/container/dev-docker-compose.yml
  contrib/container/docker-compose.yml
  docs/docs/faq.md
  docs/docs/start/bare_dev.md
  docs/docs/start/docker_install.md
  tasks.py
Labels: docker, setup

#8133 [PUI] fix a few sonarcloud warnings
  src/frontend/src/components/Boundary.tsx
  src/frontend/src/components/buttons/AdminButton.tsx
  src/frontend/src/components/buttons/PrimaryActionButton.tsx
  src/frontend/src/components/buttons/RemoveRowButton.tsx
  src/frontend/src/components/buttons/YesNoButton.tsx
  src/frontend/src/components/editors/NotesEditor.tsx
  src/frontend/src/components/errors/ClientError.tsx
  src/frontend/src/components/errors/GenericErrorPage.tsx
  src/frontend/src/components/forms/fields/ChoiceField.tsx
  src/frontend/src/components/forms/fields/DependentField.tsx
  src/frontend/src/components/forms/fields/TableField.tsx
  src/frontend/src/components/forms/fields/TextField.tsx
  src/frontend/src/components/images/Thumbnail.tsx
  src/frontend/src/components/importer/ImportDataSelector.tsx
  src/frontend/src/components/importer/ImporterColumnSelector.tsx
  src/frontend/src/components/importer/ImporterDrawer.tsx
  src/frontend/src/components/importer/ImporterImportProgress.tsx
  src/frontend/src/components/items/ActionDropdown.tsx
  src/frontend/src/components/items/QRCode.tsx
  src/frontend/src/components/nav/InstanceDetail.tsx
  src/frontend/src/components/nav/NavigationTree.tsx
  src/frontend/src/components/plugins/PluginPanel.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/render/Plugin.tsx
  src/frontend/src/components/render/Report.tsx
  src/frontend/src/components/settings/FactCollection.tsx
  src/frontend/src/components/settings/FactItem.tsx
  src/frontend/src/forms/BuildForms.tsx
  src/frontend/src/forms/PurchaseOrderForms.tsx
  src/frontend/src/hooks/UsePluginPanels.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/UserThemePanel.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/PluginManagementPanel.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/pages/part/pricing/PurchaseHistoryPanel.tsx
  src/frontend/src/pages/part/pricing/SaleHistoryPanel.tsx
  src/frontend/src/tables/build/BuildAllocatedStockTable.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
  src/frontend/src/tables/build/BuildOrderTestTable.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
  src/frontend/src/tables/general/ExtraLineItemTable.tsx
  src/frontend/src/tables/part/PartParameterTable.tsx
  src/frontend/src/tables/part/PartPurchaseOrdersTable.tsx
  src/frontend/src/tables/part/PartTestTemplateTable.tsx
  src/frontend/src/tables/plugin/PluginListTable.tsx
  src/frontend/src/tables/sales/ReturnOrderLineItemTable.tsx
  src/frontend/src/tables/sales/SalesOrderAllocationTable.tsx
  src/frontend/src/tables/sales/SalesOrderLineItemTable.tsx
  src/frontend/src/tables/sales/SalesOrderShipmentTable.tsx
  src/frontend/src/tables/settings/ImportSessionTable.tsx
  src/frontend/src/tables/settings/UserTable.tsx
  src/frontend/src/tables/stock/StockTrackingTable.tsx
  src/frontend/src/tables/stock/TestStatisticsTable.tsx
  src/frontend/tests/pui_plugins.spec.ts
Labels: Platform UI

#8139 Bug: Remove old setting
  docs/docs/settings/global.md
Labels: bug, documentation

#8142 PUI: Receive items against return order
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/forms/ReturnOrderForms.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/tables/sales/ReturnOrderLineItemTable.tsx
Labels: user interface, Platform UI

#8145 Duplicate orders via API
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/order/test_api.py
  src/backend/InvenTree/templates/js/translated/purchase_order.js
  src/frontend/src/forms/PurchaseOrderForms.tsx
  src/frontend/src/forms/ReturnOrderForms.tsx
  src/frontend/src/forms/SalesOrderForms.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/tables/sales/SalesOrderTable.tsx
Labels: enhancement, order, user interface, api, refactor, Platform UI

#8147 [PUI] Panels plugin fix
  docs/docs/extend/plugins/ui.md
  src/backend/InvenTree/plugin/api.py
  src/backend/InvenTree/plugin/base/integration/UserInterfaceMixin.py
  src/backend/InvenTree/plugin/samples/integration/user_interface_sample.py
Labels: user interface, plugin, refactor, Platform UI

#7704 [PUI] Stocktake
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/company/api.py
  src/backend/InvenTree/company/serializers.py
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/serializers.py
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/forms/PartForms.tsx
  src/frontend/src/functions/notifications.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/StocktakePanel.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/part/PartStocktakeDetail.tsx
  src/frontend/src/pages/part/pricing/SupplierPricingPanel.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/settings/StocktakeReportTable.tsx
  src/frontend/tests/pui_general.spec.ts
  src/frontend/tests/pui_settings.spec.ts
Labels: user interface, api, refactor, Platform UI

#8161 Add part IPN to stock detail page
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: user interface, Platform UI

#8162 [PUI] Fix BOM table
  src/frontend/src/tables/bom/BomTable.tsx
Labels: bug, Platform UI

#8150 Barcode logging
  docs/docs/barcodes/barcodes.md
  docs/docs/settings/global.md
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/mixins.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/common/admin.py
  src/backend/InvenTree/common/migrations/0030_barcodescanresult.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/plugin/base/barcodes/api.py
  src/backend/InvenTree/plugin/base/barcodes/serializers.py
  src/backend/InvenTree/plugin/base/barcodes/test_barcode.py
  src/backend/InvenTree/templates/InvenTree/settings/barcode.html
  src/backend/InvenTree/users/models.py
  src/frontend/src/components/buttons/CopyButton.tsx
  src/frontend/src/components/items/QRCode.tsx
  src/frontend/src/components/modals/AboutInvenTreeModal.tsx
  src/frontend/src/components/nav/PanelGroup.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/functions/tables.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/settings/BarcodeScanHistoryTable.tsx
  src/frontend/src/tables/settings/ErrorTable.tsx
  src/frontend/tests/defaults.ts
  src/frontend/tests/pui_plugins.spec.ts
  src/frontend/tests/pui_settings.spec.ts
  src/frontend/tests/settings.ts
Labels: enhancement, user interface, barcode, Platform UI

#8163 [PUI] Part scheduling
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/templates/js/translated/part.js
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/part/PartSchedulingDetail.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
Labels: user interface, Platform UI

#8174 Enhance exception management
  src/backend/InvenTree/order/views.py
Labels: backport, backport-to-0.16.x

#8173 Remove translation for logged warnings
  src/backend/InvenTree/InvenTree/status.py
Labels: backport, backport-to-0.16.x

#8181 Fix typo
  docs/docs/start/docker_install.md
Labels: bug, documentation, backport, backport-to-0.16.x

#8183 Add 'status' column to build outptut table
  src/frontend/src/tables/build/BuildOutputTable.tsx
Labels: user interface, Platform UI

#8186 [PUI] Importer fixes
  src/frontend/src/components/importer/ImportDataSelector.tsx
  src/frontend/src/tables/settings/ImportSessionTable.tsx
Labels: bug, user interface, Platform UI

#8187 Increase timeout for report printing
  src/frontend/src/components/buttons/PrintingActions.tsx
Labels: bug

#8172 [PUI] Hide "Expiry Date" column if feature not enabled
  src/frontend/src/tables/stock/StockItemTable.tsx
Labels: user interface, Platform UI

#8189 [PUI] Fix for plugin table
  src/frontend/src/tables/plugin/PluginListTable.tsx
Labels: bug, user interface, Platform UI

#8137 UI plugins custom features
  docs/docs/extend/plugins/ui.md
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/plugin/api.py
  src/backend/InvenTree/plugin/base/integration/test_mixins.py
  src/backend/InvenTree/plugin/base/ui/__init__.py
  src/backend/InvenTree/plugin/base/ui/api.py
  src/backend/InvenTree/plugin/base/ui/mixins.py
  src/backend/InvenTree/plugin/base/ui/serializers.py
  src/backend/InvenTree/plugin/base/ui/tests.py
  src/backend/InvenTree/plugin/mixins/__init__.py
  src/backend/InvenTree/plugin/samples/integration/user_interface_sample.py
  src/backend/InvenTree/plugin/samples/static/plugin/sample_template.js
  src/backend/InvenTree/plugin/serializers.py
  src/frontend/src/components/editors/TemplateEditor/TemplateEditor.tsx
  src/frontend/src/components/plugins/PluginContext.tsx
  src/frontend/src/components/plugins/PluginPanel.tsx
  src/frontend/src/components/plugins/PluginSource.tsx
  src/frontend/src/components/plugins/PluginUIFeature.tsx
  src/frontend/src/components/plugins/PluginUIFeatureTypes.ts
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/hooks/UsePluginPanels.tsx
  src/frontend/src/hooks/UsePluginUIFeature.tsx
  src/frontend/src/tables/settings/TemplateTable.tsx
  src/frontend/tests/pui_printing.spec.ts
Labels: plugin, Platform UI

#8190 [PUI] Plugin panel context
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/plugin/base/ui/mixins.py
  src/backend/InvenTree/plugin/base/ui/serializers.py
  src/backend/InvenTree/plugin/samples/integration/user_interface_sample.py
  src/backend/InvenTree/plugin/samples/static/plugin/sample_panel.js
  src/frontend/src/components/plugins/PluginPanel.tsx
  src/frontend/src/hooks/UsePluginPanels.tsx
Labels: enhancement, user interface, plugin, Platform UI

#8193 Ensure that stock item trees are rebuilt correctly after serialization
  src/backend/InvenTree/stock/models.py
Labels: bug

#8184 [PUI] Fix Build Output Forms
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/serializers.py
  src/frontend/src/components/forms/fields/TextField.tsx
  src/frontend/src/forms/BuildForms.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/hooks/UsePlaceholder.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/part/pricing/BomPricingPanel.tsx
  src/frontend/src/pages/part/pricing/VariantPricingPanel.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/bom/UsedInTable.tsx
  src/frontend/src/tables/build/BuildAllocatedStockTable.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
  src/frontend/src/tables/part/ParametricPartTable.tsx
  src/frontend/src/tables/part/PartParameterTable.tsx
  src/frontend/src/tables/part/PartTable.tsx
  src/frontend/src/tables/plugin/PluginListTable.tsx
  src/frontend/src/tables/purchasing/ManufacturerPartTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/tables/purchasing/SupplierPartTable.tsx
  src/frontend/src/tables/sales/ReturnOrderLineItemTable.tsx
  src/frontend/src/tables/sales/SalesOrderAllocationTable.tsx
  src/frontend/src/tables/sales/SalesOrderLineItemTable.tsx
  src/frontend/src/tables/stock/InstalledItemsTable.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
  src/frontend/tests/pages/pui_build.spec.ts
Labels: bug, user interface, refactor, Platform UI

#8129 [PUI] form enter key to submit
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/forms/fields/TextField.tsx
Labels: dependency, Platform UI

#8202 [PUI] Installed items
  src/backend/InvenTree/stock/serializers.py
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/stock/InstalledItemsTable.tsx
Labels: user interface, Platform UI

#8196 [PUI] Adjust stock details page
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/components/items/ErrorItem.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: user interface, Platform UI

#8204 [PUI] Form error fix
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/forms/fields/TextField.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/tests/modals.spec.ts
  src/frontend/tests/pages/pui_build.spec.ts
  src/frontend/tests/pages/pui_index.spec.ts
  src/frontend/tests/pages/pui_orders.spec.ts
  src/frontend/tests/pages/pui_part.spec.ts
  src/frontend/tests/pages/pui_scan.spec.ts
  src/frontend/tests/pui_basic.spec.ts
  src/frontend/tests/pui_command.spec.ts
  src/frontend/tests/pui_forms.spec.ts
  src/frontend/tests/pui_general.spec.ts
  src/frontend/tests/pui_printing.spec.ts
  src/frontend/tests/pui_settings.spec.ts
  src/frontend/tests/pui_stock.spec.ts
  src/frontend/tests/pui_tables.spec.ts
Labels: bug, user interface, CI, Platform UI

#8205 Exception handling for BulkDeleteMixin
  src/backend/InvenTree/InvenTree/api.py
  src/backend/InvenTree/stock/test_api.py
Labels: bug, api, backport, backport-to-0.16.x

#8209 Add exception handling for default template creatoin
  src/backend/InvenTree/report/apps.py
Labels: bug, report, setup, backport, backport-to-0.16.x

#8210 Path management improvements
  tasks.py
Labels: bug, setup, backport, backport-to-0.16.x

#8218 Bump rollup
  src/frontend/yarn.lock
Labels: dependency, javascript

#8215 Bump the dependencies group across 1 directory with 5 updates
  .github/workflows/backport.yaml
  .github/workflows/check_translations.yaml
  .github/workflows/docker.yaml
  .github/workflows/qc_checks.yaml
  .github/workflows/release.yaml
  .github/workflows/scorecard.yaml
  .github/workflows/translations.yaml
Labels: dependency, github_actions

#8220 Plugin helper function
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/plugin/api.py
  src/backend/InvenTree/plugin/plugin.py
  src/frontend/src/tables/plugin/PluginListTable.tsx
Labels: plugin

#8221 Remove unused function
  src/frontend/src/components/editors/NotesEditor.tsx
Labels: refactor

#8222 [PUI] Filter StockTrackingTable by user
  src/frontend/src/tables/stock/StockTrackingTable.tsx
Labels: user interface, Platform UI

#8219 Bump pre-commit
  .pre-commit-config.yaml
  pyproject.toml
  src/backend/InvenTree/InvenTree/fields.py
  src/backend/InvenTree/InvenTree/templatetags/inventree_extras.py
  src/backend/InvenTree/InvenTree/unit_test.py
  src/backend/InvenTree/common/notifications.py
  src/backend/InvenTree/machine/models.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/part/stocktake.py
  src/backend/InvenTree/part/views.py
  src/backend/InvenTree/plugin/base/barcodes/api.py
  src/backend/InvenTree/plugin/base/label/label.py
  src/backend/InvenTree/plugin/base/label/mixins.py
  src/backend/InvenTree/plugin/samples/integration/validation_sample.py
  src/backend/InvenTree/plugin/templatetags/plugin_extras.py
  src/backend/InvenTree/report/templatetags/report.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/views.py
Labels: dependency

#8217 Bump mkdocs-material
  docs/requirements.txt
Labels: dependency, python

#8053 A bit more testing
  src/backend/InvenTree/common/tests.py
  src/backend/InvenTree/plugin/mixins/__init__.py
  src/backend/InvenTree/plugin/samples/integration/test_validation_sample.py
  src/backend/InvenTree/report/tests.py
  src/backend/InvenTree/stock/api.py
  src/backend/InvenTree/stock/fixtures/location.yaml
  src/backend/InvenTree/stock/migrations/0065_auto_20210701_0509.py
  src/backend/InvenTree/stock/migrations/0108_auto_20240219_0252.py
  src/backend/InvenTree/stock/test_api.py
  src/backend/InvenTree/stock/test_migrations.py
Labels: CI, full-run
