Repository inventree/InvenTree, pull requests merged in 2024-08, with the labels that each got.

#7777 [PUI] Build test results
  docs/docs/assets/images/build/build_panel_allocated_stock.png
  docs/docs/assets/images/build/build_panel_details.png
  docs/docs/assets/images/build/build_panel_line_items.png
  docs/docs/assets/images/build/build_panel_test_results.png
  docs/docs/assets/images/build/build_panel_test_statistics.png
  docs/docs/build/build.md
  docs/docs/start/config.md
  docs/main.py
  src/backend/InvenTree/build/api.py
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/tables/build/BuildOrderTestTable.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
  src/frontend/tests/pages/pui_build.spec.ts
Labels: enhancement, user interface, build, Platform UI

#7779 Improve row click handling for tables
  src/frontend/src/tables/InvenTreeTable.tsx
Labels: user interface, Platform UI

#7781 [PUI] Update template tables
  src/frontend/src/tables/settings/TemplateTable.tsx
Labels: user interface, Platform UI

#7783 [PUI] Table Updates
  src/frontend/src/components/images/Thumbnail.tsx
  src/frontend/src/forms/SalesOrderForms.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/tables/bom/UsedInTable.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/tables/sales/SalesOrderLineItemTable.tsx
Labels: user interface, Platform UI

#7771 Add limit to default location annotation
  src/backend/InvenTree/part/filters.py
  src/backend/InvenTree/part/test_api.py
Labels: bug, api

#7784 Add provenance to releases and publish SBOMs
  .github/workflows/release.yaml
  pyproject.toml
Labels: CI, security

#7792 Migration cleanup
  src/backend/InvenTree/build/migrations/0021_auto_20201020_0908_squashed_0026_auto_20201023_1228.py
  src/backend/InvenTree/build/status_codes.py
  src/backend/InvenTree/order/migrations/0028_auto_20200423_0956.py
  src/backend/InvenTree/order/migrations/0084_auto_20230321_1111.py
  src/backend/InvenTree/order/migrations/0087_alter_salesorder_status.py
  src/backend/InvenTree/order/migrations/0099_alter_salesorder_status.py
  src/backend/InvenTree/order/models.py
Labels: refactor, migration

#7785 Make versions_check more reliable in forks
  .github/scripts/version_check.py
Labels: CI

#7795 Fix for holdoff threshold checks
  src/backend/InvenTree/InvenTree/tasks.py
Labels: bug

#7796 [PUI] Fix permission checks for bulk delete actions
  src/frontend/src/tables/bom/BomTable.tsx
  src/frontend/src/tables/build/BuildAllocatedStockTable.tsx
  src/frontend/src/tables/settings/ErrorTable.tsx
  src/frontend/src/tables/settings/FailedTasksTable.tsx
  src/frontend/src/tables/settings/PendingTasksTable.tsx
Labels: user interface, Platform UI

#7794 [API] Improvements for API endpoints
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/company/serializers.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/stock/serializers.py
Labels: api, refactor

#7793 [PUI] Sales order tables
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/order/api.py
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/render/ModelType.tsx
  src/frontend/src/components/render/Order.tsx
  src/frontend/src/components/render/StatusRenderer.tsx
  src/frontend/src/defaults/backendMappings.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/enums/ModelType.tsx
  src/frontend/src/forms/ReturnOrderForms.tsx
  src/frontend/src/forms/SalesOrderForms.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/sales/ReturnOrderLineItemTable.tsx
  src/frontend/src/tables/sales/SalesOrderLineItemTable.tsx
  src/frontend/src/tables/sales/SalesOrderShipmentTable.tsx
  src/frontend/tests/pui_general.spec.ts
Labels: user interface, Platform UI

#7800 Fix docker repo names
  .github/scripts/version_check.py
Labels: bug, CI, docker

#7801 Note about the wrong `invoke` being called.
  docs/docs/start/install.md
Labels: setup, documentation

#7809 [PUI] Fix for part detail display
  src/frontend/src/pages/part/PartDetail.tsx
Labels: bug, user interface, Platform UI

#7807 Adds "ON HOLD" status to order models
  .github/scripts/version_check.py
  docs/docs/build/build.md
  docs/docs/order/purchase_order.md
  docs/docs/order/return_order.md
  docs/docs/order/sales_order.md
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/build/status_codes.py
  src/backend/InvenTree/build/templates/build/build_base.html
  src/backend/InvenTree/build/test_build.py
  src/backend/InvenTree/generic/states/states.py
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/order/status_codes.py
  src/backend/InvenTree/order/templates/order/order_base.html
  src/backend/InvenTree/order/templates/order/return_order_base.html
  src/backend/InvenTree/order/templates/order/sales_order_base.html
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/templates/js/translated/order.js
  src/frontend/src/components/buttons/PrimaryActionButton.tsx
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/importer/ImporterDrawer.tsx
  src/frontend/src/components/importer/ImporterImportProgress.tsx
  src/frontend/src/components/items/ActionDropdown.tsx
  src/frontend/src/components/render/User.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/forms/BuildForms.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/hooks/UseImportSession.tsx
  src/frontend/src/hooks/UseStatusCodes.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/tables/RowActions.tsx
  src/frontend/src/tables/bom/UsedInTable.tsx
  src/frontend/src/tables/sales/SalesOrderLineItemTable.tsx
  src/frontend/src/tables/sales/SalesOrderTable.tsx
  src/frontend/tests/baseFixtures.ts
  src/frontend/tests/pages/pui_build.spec.ts
  src/frontend/tests/pages/pui_orders.spec.ts
Labels: enhancement, order, user interface, api, build, refactor, feature, Platform UI

#7830 [PUI] Make filter choice drop-down searchable
  src/frontend/src/tables/FilterSelectDrawer.tsx
Labels: user interface, backport, Platform UI, backport-to-0.16.x

#7829 Metadata api fix
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/plugin/api.py
  src/backend/InvenTree/plugin/test_api.py
Labels: bug, api, backport, backport-to-0.15.x, backport-to-0.16.x

#7832 Update docs around demo accounts
  docs/docs/demo.md
  docs/docs/start/docker_install.md
Labels: demo, documentation

#7833 [PUI] Active user filter
  src/frontend/src/defaults/backendMappings.tsx
  src/frontend/src/forms/BuildForms.tsx
  src/frontend/src/forms/PurchaseOrderForms.tsx
  src/frontend/src/forms/ReturnOrderForms.tsx
  src/frontend/src/forms/SalesOrderForms.tsx
  src/frontend/src/hooks/UseFilter.tsx
Labels: user interface, Platform UI

#7835 [PUI] Admin tables
  src/frontend/src/pages/Index/Settings/AdminCenter/LabelTemplatePanel.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/ReportTemplatePanel.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/UserManagementPanel.tsx
  src/frontend/src/tables/settings/GroupTable.tsx
  src/frontend/src/tables/settings/TemplateTable.tsx
  src/frontend/src/tables/settings/UserTable.tsx
Labels: user interface, Platform UI

#7836 [PUI] Allocation Tables
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/build/BuildAllocatedStockTable.tsx
  src/frontend/src/tables/sales/SalesOrderAllocationTable.tsx
Labels: user interface, Platform UI

#7837 [PUI] Sales order actions
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/part/serializers.py
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
  src/frontend/src/tables/part/PartTable.tsx
  src/frontend/src/tables/part/PartVariantTable.tsx
  src/frontend/src/tables/sales/SalesOrderLineItemTable.tsx
  src/frontend/tests/pages/pui_build.spec.ts
Labels: user interface, api, Platform UI

#7846 Add more liniting rules (mostly for imports)
  pyproject.toml
  src/backend/InvenTree/InvenTree/api.py
  src/backend/InvenTree/InvenTree/apps.py
  src/backend/InvenTree/InvenTree/conversion.py
  src/backend/InvenTree/InvenTree/exceptions.py
  src/backend/InvenTree/InvenTree/helpers.py
  src/backend/InvenTree/InvenTree/helpers_model.py
  src/backend/InvenTree/InvenTree/models.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/status_codes.py
  src/backend/InvenTree/InvenTree/test_sso.py
  src/backend/InvenTree/InvenTree/tests.py
  src/backend/InvenTree/InvenTree/version.py
  src/backend/InvenTree/common/tests.py
  src/backend/InvenTree/common/validators.py
  src/backend/InvenTree/importer/admin.py
  src/backend/InvenTree/machine/admin.py
  src/backend/InvenTree/machine/registry.py
  src/backend/InvenTree/machine/tests.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/stocktake.py
  src/backend/InvenTree/part/test_api.py
  src/backend/InvenTree/part/test_bom_export.py
  src/backend/InvenTree/part/test_pricing.py
  src/backend/InvenTree/plugin/base/label/mixins.py
  src/backend/InvenTree/plugin/base/locate/api.py
  src/backend/InvenTree/plugin/builtin/labels/label_sheet.py
  src/backend/InvenTree/plugin/registry.py
  src/backend/InvenTree/plugin/samples/integration/report_plugin_sample.py
  src/backend/InvenTree/plugin/staticfiles.py
  src/backend/InvenTree/report/api.py
  src/backend/InvenTree/report/models.py
  src/backend/InvenTree/report/tests.py
  src/backend/InvenTree/stock/api.py
  src/backend/InvenTree/stock/filters.py
  src/backend/InvenTree/stock/generators.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/users/api.py
Labels: CI, refactor

#7844 [PUI] Part po table
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/order/serializers.py
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/tables/part/PartPurchaseOrdersTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
Labels: user interface, Platform UI

#7842 Build order rules
  .gitignore
  docs/docs/assets/images/settings/user_notifications.png
  docs/docs/assets/images/settings/user_reporting.png
  docs/docs/build/build.md
  docs/docs/order/purchase_order.md
  docs/docs/order/return_order.md
  docs/docs/order/sales_order.md
  docs/docs/settings/currency.md
  docs/docs/settings/global.md
  docs/docs/settings/user.md
  docs/main.py
  readthedocs.yml
  src/backend/InvenTree/InvenTree/management/commands/export_settings_definitions.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/build/test_api.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/templates/InvenTree/settings/build.html
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  tasks.py
Labels: build, documentation

#7850 [PUI] Placeholder panels
  src/frontend/src/components/settings/SettingList.tsx
  src/frontend/src/pages/Index/Settings/UserSettings.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: user interface, Platform UI

#7773 Adjust docker labels to modern OCI schema
  .github/scripts/version_check.py
  .github/workflows/docker.yaml
  contrib/container/Dockerfile
Labels: CI, docker

#7863 [Bug] Attachment permissions
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/common/api.py
  src/backend/InvenTree/common/serializers.py
  src/backend/InvenTree/common/tests.py
  src/backend/InvenTree/users/models.py
Labels: bug, user interface, backport, backport-to-0.16.x

#7864 [PUI] Search preview enhancements
  src/frontend/src/components/nav/SearchDrawer.tsx
Labels: user interface, Platform UI

#7865 [PUI] Build detail IPN
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
Labels: user interface, Platform UI

#7867 Panel tab click fix
  src/frontend/src/components/nav/PanelGroup.tsx
Labels: bug, user interface, backport, Platform UI, backport-to-0.16.x

#7868 Fix usePartFields hook
  src/frontend/src/forms/PartForms.tsx
Labels: bug, user interface, Platform UI

#7871 [Bug] Check before calling schedule_pricing_update
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/stock/models.py
Labels: bug, backport, backport-to-0.16.x

#7874 Build line assembly filter
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/api.py
  src/frontend/src/tables/bom/BomTable.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
Labels: user interface, api, build, Platform UI

#7880 Fix for usePartFields
  src/frontend/src/forms/PartForms.tsx
Labels: user interface, refactor, Platform UI

#7878 Update Chinese language support
  src/backend/InvenTree/locale/pt_BR/LC_MESSAGES/django.po
  src/backend/InvenTree/locale/zh/LC_MESSAGES/django.po
  src/backend/InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
  src/backend/InvenTree/locale/zh_Hant/LC_MESSAGES/django.po
  src/frontend/.linguirc
  src/frontend/src/contexts/LanguageContext.tsx
  src/frontend/src/locales/es_MX/messages.d.ts
  src/frontend/src/locales/es_MX/messages.po
  src/frontend/src/locales/pt_BR/messages.d.ts
  src/frontend/src/locales/pt_BR/messages.po
  src/frontend/src/locales/zh-hans/messages.po
  src/frontend/src/locales/zh_Hans/messages.d.ts
  src/frontend/src/locales/zh_Hans/messages.po
  src/frontend/src/locales/zh_Hant/messages.d.ts
  src/frontend/src/locales/zh_Hant/messages.po
Labels: bug

#7881 Update default fonts for docker image
  contrib/container/Dockerfile
Labels: enhancement, docker, setup, backport, backport-to-0.16.x

#7888 [WIP] Testable parts
  docs/docs/part/part.md
  docs/docs/part/test.md
  docs/docs/part/views.md
  docs/docs/stock/test.md
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/build/templates/build/build_base.html
  src/backend/InvenTree/build/templates/build/detail.html
  src/backend/InvenTree/build/templates/build/sidebar.html
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/migrations/0128_part_testable.py
  src/backend/InvenTree/part/migrations/0129_auto_20240815_0214.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/part/templates/part/part_sidebar.html
  src/backend/InvenTree/stock/templates/stock/stock_sidebar.html
  src/backend/InvenTree/templates/js/translated/build.js
  src/backend/InvenTree/templates/js/translated/part.js
  src/backend/InvenTree/templates/js/translated/table_filters.js
  src/frontend/src/forms/PartForms.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/bom/BomTable.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
  src/frontend/src/tables/part/PartTable.tsx
Labels: part, user interface, api, feature, Platform UI

#7898 [PUI] Build output table
  src/frontend/src/tables/build/BuildOutputTable.tsx
Labels: user interface, build, Platform UI

#7899 [PUI] Report print timeout
  src/frontend/src/components/buttons/PrintingActions.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
Labels: user interface, report, Platform UI

#7889 [PUI] Extra line table
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/forms/CommonForms.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/tables/general/ExtraLineItemTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
Labels: order, user interface, Platform UI

#7900 Improve "issued by" filter for Build list API
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/templates/js/translated/table_filters.js
  src/frontend/src/tables/build/BuildOrderTable.tsx
Labels: api, build, breaking, refactor

#7905 [PUI] Fix settings indentation
  src/frontend/src/components/nav/SettingsHeader.tsx
  src/frontend/src/pages/Index/Settings/UserSettings.tsx
Labels: bug, user interface, Platform UI

#7906 [PUI] Fix user detail save on PUI
  src/backend/InvenTree/InvenTree/serializers.py
  src/frontend/src/pages/Index/Settings/AccountSettings/AccountDetailPanel.tsx
Labels: bug, Platform UI

#7909 [PUI] Fix broken SKU link
  src/frontend/src/tables/purchasing/SupplierPriceBreakTable.tsx
Labels: bug, Platform UI

#7907 [PUI] Add theme changer to navbar
  src/backend/InvenTree/InvenTree/api_version.py
  src/frontend/src/components/nav/MainMenu.tsx
Labels: Platform UI

#7908 [PUI] Add AdminCenter to cmd k
  src/frontend/src/defaults/actions.tsx
Labels: Platform UI

#7911 Cleanup notification drawer
  src/frontend/src/components/nav/NotificationDrawer.tsx
Labels: user interface, Platform UI

#7912 Add "description" column to <UsedInTable />
  src/frontend/src/tables/bom/UsedInTable.tsx
Labels: user interface, Platform UI

#7914 Add more columns to BuildLineTable
  src/frontend/src/tables/build/BuildLineTable.tsx
Labels: user interface, Platform UI

#7915 [PUI] Pass sales order through to sub-builds table
  src/frontend/src/pages/build/BuildDetail.tsx
Labels: user interface, build, Platform UI

#7916 [PUI] Show warning for insufficient stock
  src/frontend/src/functions/icons.tsx
  src/frontend/src/tables/TableHoverCard.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
Labels: user interface, build, Platform UI

#7921 [PUI] Improve loading of "details" panel
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/pages/part/PartDetail.tsx
Labels: user interface, refactor, Platform UI

#7918 [PUI] Order Currency
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/tables/general/ExtraLineItemTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/tables/sales/ReturnOrderLineItemTable.tsx
  src/frontend/src/tables/sales/SalesOrderLineItemTable.tsx
Labels: bug, order, user interface, backport, Platform UI, backport-to-0.16.x

#7923 [PUI] Check length before access
  src/frontend/src/pages/part/PartDetail.tsx
Labels: bug, user interface, Platform UI

#7913 [PUI] Refactor "notYetImplemented"
  src/frontend/src/components/buttons/ActionButton.tsx
  src/frontend/src/components/buttons/PrimaryActionButton.tsx
  src/frontend/src/components/importer/ImportDataSelector.tsx
  src/frontend/src/components/items/ActionDropdown.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/part/pricing/PriceBreakPanel.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/RowActions.tsx
  src/frontend/src/tables/UploadAction.tsx
  src/frontend/src/tables/bom/BomTable.tsx
  src/frontend/src/tables/build/BuildAllocatedStockTable.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
  src/frontend/src/tables/build/BuildOrderTestTable.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
  src/frontend/src/tables/company/AddressTable.tsx
  src/frontend/src/tables/company/CompanyTable.tsx
  src/frontend/src/tables/company/ContactTable.tsx
  src/frontend/src/tables/general/AttachmentTable.tsx
  src/frontend/src/tables/general/ExtraLineItemTable.tsx
  src/frontend/src/tables/part/PartCategoryTable.tsx
  src/frontend/src/tables/part/PartCategoryTemplateTable.tsx
  src/frontend/src/tables/part/PartParameterTable.tsx
  src/frontend/src/tables/part/PartParameterTemplateTable.tsx
  src/frontend/src/tables/part/PartTestTemplateTable.tsx
  src/frontend/src/tables/part/RelatedPartTable.tsx
  src/frontend/src/tables/plugin/PluginListTable.tsx
  src/frontend/src/tables/purchasing/ManufacturerPartParameterTable.tsx
  src/frontend/src/tables/purchasing/ManufacturerPartTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/tables/purchasing/SupplierPartTable.tsx
  src/frontend/src/tables/purchasing/SupplierPriceBreakTable.tsx
  src/frontend/src/tables/sales/ReturnOrderLineItemTable.tsx
  src/frontend/src/tables/sales/SalesOrderAllocationTable.tsx
  src/frontend/src/tables/sales/SalesOrderLineItemTable.tsx
  src/frontend/src/tables/sales/SalesOrderShipmentTable.tsx
  src/frontend/src/tables/settings/TemplateTable.tsx
  src/frontend/src/tables/stock/LocationTypesTable.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
  src/frontend/src/tables/stock/StockItemTestResultTable.tsx
  src/frontend/src/tables/stock/StockLocationTable.tsx
Labels: user interface, refactor, Platform UI

#7931 Fix columns for build line table
  src/frontend/src/tables/build/BuildLineTable.tsx
Labels: bug, user interface, Platform UI

#7932 [PUI] Sub builds table
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/build/serializers.py
  src/frontend/src/tables/Filter.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
Labels: user interface, api, build, Platform UI

#7933 [PUI] Fix for hovering in parameteric part table
  src/frontend/src/forms/PartForms.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/TableHoverCard.tsx
  src/frontend/src/tables/part/ParametricPartTable.tsx
  src/frontend/src/tables/part/PartParameterTable.tsx
Labels: user interface, refactor, Platform UI

#7934 [PUI] Fix parameter formatting
  src/frontend/src/defaults/formatters.tsx
  src/frontend/src/tables/part/ParametricPartTable.tsx
  src/frontend/src/tables/part/PartParameterTable.tsx
Labels: user interface, Platform UI

#7938 Required quantity display
  src/backend/InvenTree/part/templates/part/part_base.html
  src/frontend/src/functions/icons.tsx
  src/frontend/src/pages/part/PartDetail.tsx
Labels: user interface, Platform UI

#7940 Build table fix
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/api.py
  src/frontend/src/tables/build/BuildOrderTable.tsx
Labels: enhancement, user interface, api, build, Platform UI

#7942 Enhance plugin SN validation
  docs/docs/extend/plugins/validation.md
  docs/docs/part/pricing.md
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/plugin/base/integration/ValidationMixin.py
  src/backend/InvenTree/plugin/samples/integration/validation_sample.py
Labels: enhancement, plugin

#7943 Bug fix for PurchaseOrderCancelSerializer
  src/backend/InvenTree/order/serializers.py
Labels: bug, order

#7941 [Build] Create child builds
  docs/docs/build/build.md
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/build/tasks.py
  src/backend/InvenTree/build/test_api.py
  src/backend/InvenTree/templates/js/translated/build.js
  src/frontend/src/forms/BuildForms.tsx
Labels: user interface, api, build, feature, Platform UI

#7953 [PUI] fix missing key in currency table
  src/frontend/src/tables/settings/CurrencyTable.tsx
Labels: bug, Platform UI

#7939 [PUI] Add Link/Unlink Barcode action
  src/frontend/src/components/items/ActionDropdown.tsx
  src/frontend/src/components/items/QRCode.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/tests/pages/pui_orders.spec.ts
Labels: enhancement, barcode, Platform UI

#7956 [PUI] Test result fixes
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/stock/serializers.py
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/tables/build/BuildOrderTestTable.tsx
  src/frontend/src/tables/stock/StockItemTestResultTable.tsx
Labels: bug, user interface, api, Platform UI

#7957 Table borders
  src/frontend/src/hooks/UseTable.tsx
  src/frontend/src/tables/Column.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
Labels: user interface, Platform UI

#7958 [PUI] Add pagination controls
  src/frontend/src/hooks/UseTable.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
Labels: enhancement, user interface, Platform UI

#7929 [CI] Switch to using Crowdin GitHub Action
  .github/workflows/translations.yaml
Labels: CI

#7978 [BUG] Order of states in schema descriptions is not stable
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/generic/states/custom.py
Labels: bug, api

#7961 Chore: Bump python requirements
  contrib/container/requirements.in
  contrib/container/requirements.txt
  contrib/dev_reqs/requirements.txt
  src/backend/requirements-dev.txt
  src/backend/requirements.in
  src/backend/requirements.txt
Labels: CI, dependency, full-run

#7975 fix: translation action wrong location
  .github/workflows/translations.yaml
  crowdin.yml
Labels: bug, CI, translation

#7976 Fix state changes on stock items
  src/backend/InvenTree/generic/states/fields.py
  src/backend/InvenTree/stock/test_api.py
  src/backend/InvenTree/templates/js/translated/stock.js
  src/frontend/src/forms/StockForms.tsx
Labels: bug

#7971 [PUI] Add currency stats
  src/frontend/src/components/settings/FactCollection.tsx
  src/frontend/src/components/settings/FactItem.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/CurrencyManagmentPanel.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/TaskManagementPanel.tsx
Labels: refactor, Platform UI

#7979 Fix path
  .github/workflows/translations.yaml
Labels: bug

#7945 [PUI] Build actions
  src/backend/InvenTree/build/serializers.py
  src/frontend/src/components/buttons/RemoveRowButton.tsx
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/forms/StandaloneField.tsx
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
  src/frontend/src/components/forms/fields/TableField.tsx
  src/frontend/src/components/items/ProgressBar.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/forms/BuildForms.tsx
  src/frontend/src/forms/PurchaseOrderForms.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/hooks/UseSelectedRows.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
Labels: user interface, build, Platform UI

#7981 Forms refactor
  src/frontend/src/components/forms/fields/TableField.tsx
  src/frontend/src/forms/BuildForms.tsx
  src/frontend/src/forms/PurchaseOrderForms.tsx
  src/frontend/src/forms/StockForms.tsx
Labels: user interface, refactor, Platform UI

#7983 Add git config for CI
  .github/workflows/translations.yaml
Labels: bug, CI

#7984 Another Crowdin Fix
  crowdin.yml
Labels: bug, CI, translation

#7985 Update crowdin.yml
  crowdin.yml
Labels: bug, CI, translation

#7992 Hide "build orders" tab for inactive parts
  src/frontend/src/pages/part/PartDetail.tsx
Labels: user interface, backport, Platform UI, backport-to-0.16.x

#7994 Reset page offset when changing page size
  src/frontend/src/tables/InvenTreeTable.tsx
Labels: user interface, Platform UI

#7999 fix translatable string
  src/frontend/src/components/items/QRCode.tsx
  src/frontend/src/tables/TableHoverCard.tsx
Labels: bug, Platform UI

#8006 chore: pin 2 missing actions
  .github/workflows/release.yaml
Labels: CI

#8007 Allow edit of build allocations from part context
  src/frontend/src/pages/part/PartDetail.tsx
Labels: user interface, Platform UI

#7960 [PUI] Add image based QR code assigment
  src/frontend/src/components/items/QRCode.tsx
  src/frontend/src/pages/Index/Scan.tsx
Labels: Platform UI

#8004 Reduce code duplication for QR code scan
  src/frontend/src/components/items/BarcodeInput.tsx
  src/frontend/src/components/items/QRCode.tsx
  src/frontend/src/components/modals/QrCodeModal.tsx
  src/frontend/src/pages/Index/Scan.tsx
Labels: refactor, Platform UI

#8008 Add extra undefined check for table filters
  src/frontend/src/tables/FilterSelectDrawer.tsx
Labels: bug, user interface, backport, Platform UI, backport-to-0.16.x

#8015 Change target branch for translation
  .github/workflows/translations.yaml
  .gitignore
Labels: CI

#8021 [PUI] Fix for attachment table
  src/frontend/src/tables/general/AttachmentTable.tsx
Labels: user interface, Platform UI

#8024 Fix "sales_order" filter for build table
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
Labels: bug, user interface, Platform UI

#8017 Adjust "render_currency" behaviour
  docs/docs/report/helpers.md
  src/backend/InvenTree/InvenTree/helpers_model.py
Labels: report

#8028 Update pint library to latest version
  src/backend/InvenTree/InvenTree/validators.py
  src/backend/requirements.in
  src/backend/requirements.txt
Labels: dependency

#8030 Allow notifications to be opened in new tab or window
  src/frontend/src/components/nav/NotificationDrawer.tsx
Labels: user interface, Platform UI

#8032 [PUI] Test result table improvements
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/tables/stock/StockItemTestResultTable.tsx
Labels: user interface, Platform UI

#8031 Test template fix
  src/backend/InvenTree/build/test_build.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/fixtures/part.yaml
  src/backend/InvenTree/part/migrations/0130_alter_parttesttemplate_part.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/part/test_api.py
  src/backend/InvenTree/stock/test_api.py
Labels: bug, migration

#8034 Fix package upgrade process
  contrib/packager.io/postinstall.sh
  contrib/packager.io/preinstall.sh
Labels: setup, backport, installer, backport-to-0.16.x

#8038 Fix return type of detail queries
  src/frontend/src/pages/part/PartDetail.tsx
Labels: bug, user interface, backport, Platform UI, backport-to-0.16.x

#8042 Adds exchange backend settings to AdminCenter
  src/frontend/src/pages/Index/Settings/AdminCenter/CurrencyManagmentPanel.tsx
Labels: Platform UI

#8043 Surpress error if no changes exsist
  .github/workflows/translations.yaml
Labels: bug, CI
