Repository inventree/InvenTree, pull requests merged in 2024-12, with the labels that each got.

#8611 [PUI] Make dashboard header look less like a widget
  src/frontend/src/components/dashboard/DashboardLayout.tsx
  src/frontend/src/components/dashboard/DashboardMenu.tsx
Labels: Platform UI

#8613 refactor Make logic simpler
  src/backend/InvenTree/InvenTree/sso.py
  src/backend/InvenTree/plugin/base/event/events.py
  src/backend/InvenTree/stock/models.py
Labels: refactor

#8610 Build required widget
  src/frontend/src/components/dashboard/DashboardWidget.tsx
  src/frontend/src/components/dashboard/DashboardWidgetLibrary.tsx
  src/frontend/src/components/dashboard/widgets/QueryCountDashboardWidget.tsx
  src/frontend/src/hooks/UseDashboardItems.tsx
Labels: Platform UI

#8615 [PUI] Url fixes
  src/frontend/src/components/buttons/AdminButton.tsx
  src/frontend/src/components/buttons/PrintingActions.tsx
  src/frontend/src/components/images/ApiImage.tsx
  src/frontend/src/components/items/AttachmentLink.tsx
  src/frontend/src/components/modals/AboutInvenTreeModal.tsx
  src/frontend/src/components/plugins/PluginSource.tsx
  src/frontend/src/states/IconState.tsx
Labels: refactor, Platform UI

#8614 [PUI] fix infinite loop if classic frontend is disabled
  src/backend/InvenTree/plugin/plugin.py
Labels: bug, Platform UI

#8625 [PUI] Supplier part badges
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/company/api.py
  src/backend/InvenTree/company/filters.py
  src/backend/InvenTree/company/serializers.py
  src/backend/InvenTree/part/filters.py
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/tables/purchasing/SupplierPartTable.tsx
Labels: enhancement, api, Platform UI

#8626 Fix ordering issue in notifications table
  src/frontend/src/pages/Notifications.tsx
  src/frontend/src/tables/notifications/NotificationTable.tsx
Labels: bug, Platform UI

#8631 Bug fix for stock transfer
  src/backend/InvenTree/stock/models.py
Labels: bug, stock

#8630 Fix URL generation error
  src/frontend/src/components/buttons/AdminButton.tsx
  src/frontend/src/components/buttons/PrintingActions.tsx
  src/frontend/src/components/images/ApiImage.tsx
  src/frontend/src/components/items/AttachmentLink.tsx
  src/frontend/src/components/modals/AboutInvenTreeModal.tsx
  src/frontend/src/components/plugins/PluginSource.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/functions/urls.tsx
  src/frontend/src/states/IconState.tsx
Labels: bug, refactor, Platform UI

#8650 Add IPN column to RelatedPartTable
  src/frontend/src/tables/part/RelatedPartTable.tsx
Labels: Platform UI

#8636 Added first example to plugin unit test
  docs/docs/extend/plugins/test.md
  docs/mkdocs.yml
  src/backend/InvenTree/.config.yaml.swp
Labels: plugin, documentation

#8585 SalesOrder Data Migration
  src/backend/InvenTree/order/migrations/0105_auto_20241128_0431.py
  src/backend/InvenTree/order/test_migrations.py
Labels: bug, migration, full-run

#8652 Filter fix
  src/backend/InvenTree/order/api.py
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
Labels: order, api, Platform UI

#8646 Refactor: Move settings definitions (and most validators) out of models.py
  src/backend/InvenTree/InvenTree/validators.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/common/setting/__init__.py
  src/backend/InvenTree/common/setting/system.py
  src/backend/InvenTree/common/setting/tests.py
  src/backend/InvenTree/common/setting/type.py
  src/backend/InvenTree/common/setting/user.py
  src/backend/InvenTree/plugin/base/barcodes/helper.py
  src/backend/InvenTree/plugin/base/integration/AppMixin.py
  src/backend/InvenTree/plugin/base/integration/UrlsMixin.py
  src/backend/InvenTree/plugin/registry.py
Labels: refactor, full-run

#8662 fix namespace of frontend install command
  .devcontainer/postCreateCommand.sh
Labels: bug, setup

#8667 PUI: Adjust test result table
  src/frontend/src/tables/stock/StockItemTestResultTable.tsx
Labels: Platform UI

#8602 [PUI] Order Parts Wizard
  src/frontend/src/components/items/Expand.tsx
  src/frontend/src/components/render/Company.tsx
  src/frontend/src/components/wizards/OrderPartsWizard.tsx
  src/frontend/src/components/wizards/WizardDrawer.tsx
  src/frontend/src/forms/CompanyForms.tsx
  src/frontend/src/forms/PurchaseOrderForms.tsx
  src/frontend/src/hooks/UseWizard.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
  src/frontend/src/tables/part/PartTable.tsx
  src/frontend/src/tables/purchasing/SupplierPartTable.tsx
  src/frontend/src/tables/sales/SalesOrderLineItemTable.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
  src/frontend/tests/pages/pui_purchase_order.spec.ts
Labels: enhancement, order, Platform UI

#8658 [Refactor] Barcode scanning
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/exceptions.py
  src/backend/InvenTree/InvenTree/models.py
  src/backend/InvenTree/common/icons.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/plugin/base/action/api.py
  src/backend/InvenTree/plugin/base/barcodes/api.py
  src/backend/InvenTree/plugin/base/barcodes/mixins.py
  src/backend/InvenTree/plugin/base/barcodes/serializers.py
  src/backend/InvenTree/plugin/base/barcodes/test_barcode.py
  src/backend/InvenTree/plugin/base/locate/api.py
  src/backend/InvenTree/plugin/builtin/barcodes/inventree_barcode.py
  src/backend/InvenTree/plugin/builtin/suppliers/test_supplier_barcodes.py
  src/backend/InvenTree/report/models.py
  src/backend/InvenTree/stock/models.py
Labels: enhancement, barcode, plugin, api, refactor

#8639 [CI] Add zimor to check github action security
  .github/actions/setup/action.yaml
  .github/workflows/check_translations.yaml
  .github/workflows/docker.yaml
  .github/workflows/qc_checks.yaml
  .github/workflows/release.yaml
  .github/workflows/translations.yaml
  .github/workflows/update.yml.disabled
Labels: CI, security, full-run

#8680 Docker improve build times
  .github/workflows/docker.yaml
  README.md
Labels: CI, docker

#8540 Remove custom context processors
  src/backend/InvenTree/InvenTree/context.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/templatetags/inventree_extras.py
Labels: refactor

#8687 Refactor auth adaptations into dedicated file
  src/backend/InvenTree/InvenTree/auth_overrides.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/social_auth_urls.py
  src/backend/InvenTree/InvenTree/sso.py
  src/backend/InvenTree/InvenTree/test_sso.py
Labels: refactor

#8697 Remove old javascript file
  src/backend/InvenTree/InvenTree/static/script/purify.min.js
Labels: old user interface, refactor

#8684 Remove "crispy forms" integration
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/requirements.in
  src/backend/requirements.txt
Labels: refactor

#8698 Fix for table update
  src/frontend/src/hooks/UseTable.tsx
Labels: bug, backport, Platform UI, backport-to-0.17.x

#8701 Cast barcode scan IDs to list
  src/backend/InvenTree/plugin/base/barcodes/api.py
Labels: bug, barcode, backport, backport-to-0.17.x

#8700 Image upload error
  src/frontend/src/components/details/DetailsImage.tsx
  src/frontend/src/functions/notifications.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/CurrencyManagmentPanel.tsx
Labels: bug, backport, Platform UI, backport-to-0.17.x

#8706 [UI] Enhanced null checks
  src/frontend/src/components/forms/AuthenticationForm.tsx
  src/frontend/src/components/settings/SettingList.tsx
  src/frontend/src/pages/Auth/Set-Password.tsx
Labels: bug, backport, Platform UI, backport-to-0.17.x

#8710 [Refactor] Template fix
  src/backend/InvenTree/templates/base.html
  src/backend/InvenTree/templates/favicon.html
  src/backend/InvenTree/templates/skeleton.html
Labels: refactor, Platform UI

#8709 Cleanup old settings
  docs/docs/settings/global.md
  src/backend/InvenTree/common/setting/system.py
  src/backend/InvenTree/common/setting/user.py
  src/backend/InvenTree/common/tests.py
  src/backend/InvenTree/templates/base.html
  src/frontend/src/components/buttons/PrintingActions.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/pages/Index/Settings/UserSettings.tsx
Labels: refactor, Platform UI

#8713 Remove javascript rendering
  src/backend/InvenTree/InvenTree/ci_render_js.py
  src/backend/InvenTree/InvenTree/middleware.py
  tasks.py
Labels: refactor

#8717 [PUI] Consider "restrict about" setting before showing about link in UI
  src/frontend/src/components/nav/NavigationDrawer.tsx
  src/frontend/src/defaults/links.tsx
Labels: enhancement, Platform UI

#8719 Allow backup_value to be specified to the 'getkey' report helper
  src/backend/InvenTree/report/templatetags/report.py
Labels: report

#8720 Fix MFA auth flow
  src/backend/InvenTree/templates/403_csrf.html
  src/backend/InvenTree/templates/account/base.html
Labels: bug, old user interface, backport, Platform UI, backport-to-0.17.x

#8724 [Backport] Fix MFA auth flow
  src/backend/InvenTree/templates/403_csrf.html
  src/backend/InvenTree/templates/account/base.html
Labels: bug

#8725 Badge fix
  src/frontend/src/pages/sales/SalesOrderShipmentDetail.tsx
Labels: bug, backport, Platform UI, backport-to-0.17.x

#8726 [UI] Link fix
  src/frontend/src/components/render/Instance.tsx
Labels: bug, backport, Platform UI, backport-to-0.17.x

#8731 Remove unused setting
  src/backend/InvenTree/common/setting/system.py
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
Labels: refactor

#8734 Add separate dialog for 'Ship Order' button
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
Labels: enhancement, backport, Platform UI, backport-to-0.17.x

#7645 Switch to zoneinfo from pytz
  src/backend/InvenTree/InvenTree/helpers.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/tests.py
  src/backend/InvenTree/report/tests.py
Labels: security, breaking, refactor

#8685 Remove django-import-export
  docs/docs/assets/images/admin/export.png
  docs/docs/assets/images/admin/import.png
  docs/docs/assets/images/admin/import_error.png
  docs/docs/assets/images/admin/import_preview.png
  docs/docs/assets/images/admin/import_session_create.png
  docs/docs/assets/images/admin/import_session_map.png
  docs/docs/assets/images/admin/import_session_process.png
  docs/docs/assets/images/admin/import_upload.png
  docs/docs/settings/export.md
  docs/docs/settings/import.md
  src/backend/InvenTree/InvenTree/admin.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/views.py
  src/backend/InvenTree/build/admin.py
  src/backend/InvenTree/common/admin.py
  src/backend/InvenTree/company/admin.py
  src/backend/InvenTree/importer/admin.py
  src/backend/InvenTree/order/admin.py
  src/backend/InvenTree/part/admin.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/bom.py
  src/backend/InvenTree/part/test_bom_export.py
  src/backend/InvenTree/part/test_bom_import.py
  src/backend/InvenTree/part/test_views.py
  src/backend/InvenTree/part/views.py
  src/backend/InvenTree/stock/admin.py
  src/backend/requirements.in
  src/backend/requirements.txt
Labels: enhancement, dependency, breaking, refactor

#8744 Factor out helper
  src/backend/InvenTree/InvenTree/tests.py
  src/backend/InvenTree/InvenTree/unit_test.py
Labels: refactor

#8745 MFA add better logging
  src/backend/InvenTree/users/api.py
Labels: setup, refactor

#8753 Handle error when loading icon pack
  src/frontend/src/states/IconState.tsx
Labels: bug, backport, Platform UI, backport-to-0.17.x

#8738 Fix REST registration endpoint
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/auth_override_views.py
  src/backend/InvenTree/InvenTree/auth_overrides.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/social_auth_urls.py
  src/backend/InvenTree/InvenTree/test_auth.py
  src/backend/InvenTree/InvenTree/urls.py
  src/backend/requirements.in
  src/frontend/src/components/forms/AuthenticationForm.tsx
Labels: bug, api, backport, backport-to-0.17.x

#8759 Fix missing permission for push schema action
  .github/workflows/qc_checks.yaml
Labels: bug, CI

#8746 Refactor fix formatting exclusion
  pyproject.toml
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/admin.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/build/apps.py
  src/backend/InvenTree/build/filters.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/build/status_codes.py
  src/backend/InvenTree/build/tasks.py
  src/backend/InvenTree/build/test_api.py
  src/backend/InvenTree/build/test_build.py
  src/backend/InvenTree/build/test_migrations.py
  src/backend/InvenTree/build/tests.py
  src/backend/InvenTree/build/validators.py
Labels: CI, refactor

#8766 Zero stock fix
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/serializers.py
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: stock, backport, Platform UI, backport-to-0.17.x

#8767 Fix default value for SESSION_COOKIE_SECURE
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/config_template.yaml
Labels: bug, setup, backport, backport-to-0.17.x

#8773 DB CI Checks
  .github/workflows/qc_checks.yaml
Labels: CI, migration, full-run

#8772 Update dependabot settings for python packages
  .github/dependabot.yml
Labels: CI, dependency

#8770 [PUI] Set password
  src/backend/InvenTree/plugin/samples/integration/user_interface_sample.py
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/pages/Auth/ChangePassword.tsx
  src/frontend/src/pages/Auth/ResetPassword.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/AccountDetailPanel.tsx
  src/frontend/src/router.tsx
  src/frontend/tests/pages/pui_part.spec.ts
  src/frontend/tests/pui_login.spec.ts
Labels: security

#8777 [Docs] Update FAQ
  docs/docs/faq.md
  docs/docs/start/config.md
  docs/docs/start/docker_install.md
  docs/docs/start/installer.md
Labels: setup, documentation, backport, backport-to-0.17.x

#8732 Barcode scanning
  docs/docs/assets/images/barcode/barcode_link_1.png
  docs/docs/assets/images/barcode/barcode_link_2.png
  docs/docs/assets/images/barcode/barcode_nav_menu.png
  docs/docs/assets/images/barcode/barcode_no_match.png
  docs/docs/assets/images/barcode/barcode_scan.png
  docs/docs/assets/images/barcode/barcode_scan_page.png
  docs/docs/assets/images/barcode/barcode_unlink.png
  docs/docs/assets/images/barcode/barcode_unlink_1.png
  docs/docs/assets/images/barcode/barcode_unlink_2.png
  docs/docs/barcodes/barcodes.md
  docs/docs/barcodes/external.md
  docs/docs/settings/global.md
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/plugin/builtin/barcodes/inventree_barcode.py
  src/backend/InvenTree/stock/api.py
  src/frontend/src/App.tsx
  src/frontend/src/components/barcodes/BarcodeCameraInput.tsx
  src/frontend/src/components/barcodes/BarcodeInput.tsx
  src/frontend/src/components/barcodes/BarcodeKeyboardInput.tsx
  src/frontend/src/components/barcodes/BarcodeScanDialog.tsx
  src/frontend/src/components/barcodes/BarcodeScanItem.tsx
  src/frontend/src/components/barcodes/QRCode.tsx
  src/frontend/src/components/buttons/ScanButton.tsx
  src/frontend/src/components/items/ActionDropdown.tsx
  src/frontend/src/components/items/BarcodeInput.tsx
  src/frontend/src/components/modals/QrCodeModal.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/render/Stock.tsx
  src/frontend/src/contexts/ThemeContext.tsx
  src/frontend/src/functions/api.tsx
  src/frontend/src/functions/notifications.tsx
  src/frontend/src/hooks/UseTable.tsx
  src/frontend/src/pages/Index/Scan.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/CurrencyManagmentPanel.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/UnitManagmentPanel.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/InvenTreeTableHeader.tsx
  src/frontend/src/tables/general/BarcodeScanTable.tsx
  src/frontend/src/tables/plugin/PluginErrorTable.tsx
  src/frontend/src/tables/stock/StockItemTestResultTable.tsx
  src/frontend/tests/baseFixtures.ts
  src/frontend/tests/modals.spec.ts
  src/frontend/tests/pages/pui_build.spec.ts
  src/frontend/tests/pages/pui_purchase_order.spec.ts
  src/frontend/tests/pages/pui_sales_order.spec.ts
  src/frontend/tests/pages/pui_scan.spec.ts
  src/frontend/tests/pages/pui_stock.spec.ts
  src/frontend/tests/pui_general.spec.ts
  src/frontend/tests/pui_login.spec.ts
  src/frontend/tests/pui_plugins.spec.ts
Labels: enhancement, barcode, refactor, Platform UI

#8781 Add scan to action menu
  src/frontend/src/components/barcodes/BarcodeScanDialog.tsx
  src/frontend/src/components/modals/QrModal.tsx
  src/frontend/src/contexts/ThemeContext.tsx
  src/frontend/src/defaults/actions.tsx
Labels: enhancement, Platform UI

#8438 [Refactor] Custom states
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/build/migrations/0052_build_status_custom_key_alter_build_status.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/common/migrations/0034_alter_inventreecustomuserstatemodel_unique_together_and_more.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/common/serializers.py
  src/backend/InvenTree/common/validators.py
  src/backend/InvenTree/generic/states/__init__.py
  src/backend/InvenTree/generic/states/api.py
  src/backend/InvenTree/generic/states/custom.py
  src/backend/InvenTree/generic/states/fields.py
  src/backend/InvenTree/generic/states/serializers.py
  src/backend/InvenTree/generic/states/states.py
  src/backend/InvenTree/generic/states/tests.py
  src/backend/InvenTree/generic/states/validators.py
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/order/migrations/0101_purchaseorder_status_custom_key_and_more.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/stock/api.py
  src/backend/InvenTree/stock/migrations/0113_stockitem_status_custom_key_and_more.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/serializers.py
  src/frontend/src/components/render/StatusRenderer.tsx
  src/frontend/src/defaults/backendMappings.tsx
  src/frontend/src/forms/CommonForms.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/hooks/UseStatusCodes.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/states/StatusState.tsx
  src/frontend/src/tables/Filter.tsx
  src/frontend/src/tables/settings/CustomStateTable.tsx
  src/frontend/tests/helpers.ts
  src/frontend/tests/pages/pui_build.spec.ts
  src/frontend/tests/pages/pui_stock.spec.ts
  src/frontend/tests/pui_settings.spec.ts
Labels: enhancement, old user interface, refactor, Platform UI

#8784 Url refactor
  src/backend/InvenTree/InvenTree/config.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/config_template.yaml
Labels: refactor, Platform UI

#8785 [UI] Permission Enhancements
  src/frontend/src/components/nav/InstanceDetail.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/purchasing/PurchasingIndex.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesIndex.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderShipmentDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: enhancement, Platform UI

#8790 [Setup] Support X-Forwarded-Proto header
  docs/docs/start/config.md
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/config_template.yaml
Labels: security, setup, backport, backport-to-0.17.x

#8798 Caddyfile documentation
  contrib/container/Caddyfile
  docs/docs/start/config.md
  docs/docs/start/processes.md
Labels: setup, documentation, backport, backport-to-0.17.x

#8801 Add docs for secret_key
  docs/docs/start/config.md
Labels: documentation

#8803 Add documentation on transferring media files
  docs/docs/start/migrate.md
Labels: setup, documentation, backport, backport-to-0.17.x

#8805 Add FAQ on cookie setting change
  docs/docs/faq.md
Labels: setup, documentation, backport, backport-to-0.17.x

#8799 Update .env file
  contrib/container/.env
Labels: docker, setup, documentation, backport, backport-to-0.17.x

#8809 Fix FAQ typo
  docs/docs/faq.md
Labels: documentation

#8802 Allow barcode linking for stock location
  src/frontend/src/pages/stock/LocationDetail.tsx
Labels: bug, barcode, backport, Platform UI, backport-to-0.17.x

#8812 Reintroduce FAQ entry
  docs/docs/faq.md
Labels: documentation, backport, backport-to-0.17.x

#8793 Fix package install in envs using python lower than 3.12 on debian like OSs
  contrib/packager.io/functions.sh
Labels: bug, installer, backport-to-0.17.x
