Repository inventree/InvenTree, pull requests merged in 2024-10, with the labels that each got.

#8194 Shipment Reports
  docs/docs/report/samples.md
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/report/apps.py
  src/backend/InvenTree/report/templates/report/inventree_sales_order_shipment_report.html
  src/backend/InvenTree/templates/js/translated/sales_order.js
  src/frontend/src/tables/sales/SalesOrderShipmentTable.tsx
Labels: enhancement, order, report

#8226 New event triggers
  src/backend/InvenTree/stock/models.py
Labels: enhancement, stock, plugin

#8227 PUI: Return item from customer
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: user interface, Platform UI

#8229 Merge commit from fork
  src/backend/InvenTree/InvenTree/serializers.py
Labels: bug, security

#8231 Shipment Attachments
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/order/models.py
Labels: enhancement, report

#8232 [PUI] Chart tweaks
  src/frontend/src/pages/part/PartSchedulingDetail.tsx
  src/frontend/src/pages/part/PartStocktakeDetail.tsx
Labels: user interface, Platform UI

#8235 Fix build item over-allocation checks
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/test_api.py
  src/backend/InvenTree/stock/models.py
Labels: bug, build, backport, backport-to-0.16.x

#8243 Add additional information on demo dataset
  docs/docs/demo.md
  docs/docs/develop/devcontainer.md
Labels: documentation

#8230 [PUI] download image
  src/frontend/src/components/details/DetailsImage.tsx
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/functions/notifications.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
Labels: user interface, Platform UI

#8244 Markdown xss backport
  src/backend/InvenTree/InvenTree/helpers.py
  src/backend/InvenTree/InvenTree/mixins.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/company/test_api.py
Labels: bug, security

#8245 Unit Test Fixes
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/templates/js/translated/helpers.js
  src/frontend/package.json
  src/frontend/yarn.lock
Labels: bug, dependency, Platform UI

#8228 [PUI] Plugin settings UI
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/plugin/api.py
  src/backend/InvenTree/plugin/base/ui/mixins.py
  src/backend/InvenTree/plugin/base/ui/tests.py
  src/backend/InvenTree/plugin/models.py
  src/backend/InvenTree/plugin/plugin.py
  src/backend/InvenTree/plugin/samples/integration/user_interface_sample.py
  src/backend/InvenTree/plugin/samples/static/plugins/sampleui/sample_panel.js
  src/backend/InvenTree/plugin/samples/static/plugins/sampleui/ui_settings.js
  src/backend/InvenTree/plugin/serializers.py
  src/frontend/src/components/nav/SettingsHeader.tsx
  src/frontend/src/components/plugins/PluginDrawer.tsx
  src/frontend/src/components/plugins/PluginInterface.tsx
  src/frontend/src/components/plugins/PluginPanel.tsx
  src/frontend/src/components/plugins/PluginSettingsPanel.tsx
  src/frontend/src/components/plugins/PluginSource.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/hooks/UsePluginPanels.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/pages/Index/Settings/UserSettings.tsx
  src/frontend/src/tables/plugin/PluginListTable.tsx
  src/frontend/src/tables/settings/ErrorTable.tsx
  src/frontend/tests/baseFixtures.ts
  src/frontend/tests/pui_plugins.spec.ts
  src/frontend/tests/pui_settings.spec.ts
Labels: enhancement, user interface, plugin, Platform UI

#8249 [Refactor] Sales Order Shipment
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/order/tasks.py
Labels: enhancement, order, refactor

#8255 fix part qr lable
  src/backend/InvenTree/part/templates/part/part_base.html
Labels: bug, user interface, barcode, backport, backport-to-0.16.x

#8258 Allow orders to be completed without any "lines"
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/test_api.py
Labels: order

#8260 TemplateEditor: Handle fetch error
  src/frontend/src/components/editors/TemplateEditor/TemplateEditor.tsx
Labels: user interface, report, Platform UI

#8261 [PUI] Build output labels
  src/frontend/src/components/items/ActionDropdown.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
Labels: user interface, report, build, Platform UI

#8264 [PUI] Part IPN display
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/company/ManufacturerPartDetail.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/tables/sales/ReturnOrderLineItemTable.tsx
Labels: user interface, Platform UI

#8263 Translation fixes
  .github/scripts/check_source_strings.py
  .github/workflows/check_translations.yaml
  src/backend/InvenTree/InvenTree/conversion.py
  src/backend/InvenTree/InvenTree/helpers.py
  src/backend/InvenTree/InvenTree/magic_login.py
  src/backend/InvenTree/InvenTree/serializers.py
  src/backend/InvenTree/common/files.py
  src/backend/InvenTree/common/forms.py
  src/backend/InvenTree/common/migrations/0005_auto_20190915_1256.py
  src/backend/InvenTree/common/migrations/0011_auto_20210722_2114.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/locale/he/LC_MESSAGES/django.po
  src/backend/InvenTree/machine/migrations/0001_initial.py
  src/backend/InvenTree/order/templates/order/order_base.html
  src/backend/InvenTree/part/test_bom_import.py
  src/backend/InvenTree/plugin/migrations/0003_pluginsetting.py
  src/backend/InvenTree/plugin/migrations/0004_alter_pluginsetting_key.py
  src/backend/InvenTree/plugin/migrations/0005_notificationusersetting.py
  src/backend/InvenTree/templates/js/translated/sales_order.js
  src/backend/InvenTree/templates/js/translated/stock.js
  src/backend/InvenTree/templates/socialaccount/authentication_error.html
  src/frontend/src/components/importer/ImporterImportProgress.tsx
  src/frontend/src/components/items/GettingStartedCarousel.tsx
  src/frontend/src/components/nav/MainMenu.tsx
  src/frontend/src/components/nav/SearchDrawer.tsx
  src/frontend/src/components/widgets/GetStartedWidget.tsx
  src/frontend/src/defaults/menuItems.tsx
  src/frontend/src/functions/notifications.tsx
  src/frontend/src/pages/Auth/Reset.tsx
  src/frontend/src/pages/Auth/Set-Password.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/TaskManagementPanel.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/UserManagementPanel.tsx
  src/frontend/src/pages/part/pricing/SaleHistoryPanel.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
  src/frontend/src/tables/part/PartParameterTemplateTable.tsx
  src/frontend/src/tables/part/RelatedPartTable.tsx
  src/frontend/src/tables/plugin/PluginListTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/tables/sales/ReturnOrderLineItemTable.tsx
  src/frontend/src/tables/sales/SalesOrderLineItemTable.tsx
  src/frontend/src/tables/settings/CustomStateTable.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
Labels: bug, CI, translation

#8268 Fix for COOKIE_MODE in settings.py
  src/backend/InvenTree/InvenTree/settings.py
Labels: bug

#8265 [PUI] Notes Editor UX
  src/frontend/src/components/editors/NotesEditor.tsx
  src/frontend/tests/pages/pui_index.spec.ts
  src/frontend/tests/pages/pui_part.spec.ts
Labels: user interface, Platform UI

#8250 [PUI] Sales order shipments
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/templates/js/translated/sales_order.js
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
  src/frontend/src/components/forms/fields/TableField.tsx
  src/frontend/src/components/panels/AttachmentPanel.tsx
  src/frontend/src/components/panels/NotesPanel.tsx
  src/frontend/src/components/panels/Panel.tsx
  src/frontend/src/components/panels/PanelGroup.tsx
  src/frontend/src/components/render/ModelType.tsx
  src/frontend/src/components/render/Order.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/forms/BuildForms.tsx
  src/frontend/src/forms/SalesOrderForms.tsx
  src/frontend/src/hooks/UsePluginPanels.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/pages/Index/Settings/UserSettings.tsx
  src/frontend/src/pages/Notifications.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/company/ManufacturerPartDetail.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/purchasing/PurchasingIndex.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesIndex.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderShipmentDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/router.tsx
  src/frontend/src/tables/RowActions.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
  src/frontend/src/tables/sales/SalesOrderAllocationTable.tsx
  src/frontend/src/tables/sales/SalesOrderLineItemTable.tsx
  src/frontend/src/tables/sales/SalesOrderShipmentTable.tsx
  src/frontend/tests/pages/pui_orders.spec.ts
Labels: enhancement, user interface, feature, Platform UI

#8273 [PUI] Hide "allocated" column for inactive builds
  src/frontend/src/tables/build/BuildLineTable.tsx
Labels: user interface, build, Platform UI

#8274 [PUI] Stock Detail
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/serializers.py
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/components/render/StatusRenderer.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
Labels: stock, user interface, api, Platform UI

#8246 [Refactor] Serial generation
  src/backend/InvenTree/InvenTree/helpers.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/unit_test.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/stock/api.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/tasks.py
  src/backend/InvenTree/stock/test_api.py
  src/frontend/src/components/buttons/SpotlightButton.tsx
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/components/nav/SearchDrawer.tsx
  src/frontend/src/components/panels/PanelGroup.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
  src/frontend/tests/modals.spec.ts
  src/frontend/tests/pages/pui_orders.spec.ts
  src/frontend/tests/pages/pui_stock.spec.ts
  src/frontend/tests/pui_command.spec.ts
  src/frontend/tests/pui_stock.spec.ts
Labels: stock, refactor

#8272 [PUI] subscribe
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/models.py
  src/frontend/src/forms/PartForms.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/pages/Index/Playground.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/part/PartCategoryTable.tsx
Labels: user interface, Platform UI

#8276 Remove <Playground> from PUI frontend
  src/frontend/src/defaults/links.tsx
  src/frontend/src/defaults/menuItems.tsx
  src/frontend/src/pages/Index/Playground.tsx
  src/frontend/src/router.tsx
  src/frontend/tests/pages/pui_index.spec.ts
  src/frontend/tests/pui_command.spec.ts
Labels: user interface, refactor, Platform UI

#8279 [PUI] Table query params
  src/frontend/src/components/forms/AuthenticationForm.tsx
  src/frontend/src/components/nav/Layout.tsx
  src/frontend/src/functions/auth.tsx
  src/frontend/src/pages/Auth/Logged-In.tsx
  src/frontend/src/pages/Auth/Login.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
Labels: enhancement, user interface, Platform UI

#8284 Fix bug in merge_stock_items
  src/backend/InvenTree/stock/models.py
Labels: bug, stock, backport, backport-to-0.16.x

#8286 [CUI] Fix rendering issues for barcodes
  src/backend/InvenTree/build/templates/build/build_base.html
  src/backend/InvenTree/company/templates/company/supplier_part.html
  src/backend/InvenTree/order/templates/order/order_base.html
  src/backend/InvenTree/order/templates/order/return_order_base.html
  src/backend/InvenTree/order/templates/order/sales_order_base.html
  src/backend/InvenTree/part/templates/part/part_base.html
  src/backend/InvenTree/report/templatetags/barcode.py
  src/backend/InvenTree/stock/templates/stock/item_base.html
  src/backend/InvenTree/stock/templates/stock/location.html
Labels: bug, user interface, barcode, security, backport, backport-to-0.16.x

#8287 [PUI] Add "index" page for build orders
  src/frontend/src/components/render/ModelType.tsx
  src/frontend/src/defaults/links.tsx
  src/frontend/src/defaults/menuItems.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/build/BuildIndex.tsx
  src/frontend/src/router.tsx
  src/frontend/tests/pages/pui_build.spec.ts
  src/frontend/tests/pui_tables.spec.ts
Labels: user interface, build, Platform UI

#8290 Bump backend deps
  src/backend/requirements-dev.txt
  src/backend/requirements.txt
Labels: dependency, security, python

#8298 Clear allocations when manually returning an item into stock
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/stock/models.py
Labels: bug, stock, backport, backport-to-0.16.x

#8297 Simplify display of "locked" part status
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/tests/pages/pui_part.spec.ts
Labels: part, user interface, Platform UI

#8299 Table date filters
  src/frontend/src/tables/Filter.tsx
  src/frontend/src/tables/FilterSelectDrawer.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/tables/sales/SalesOrderTable.tsx
  src/frontend/src/tables/settings/TemplateTable.tsx
Labels: user interface, Platform UI

#8302 Improve API query
  src/backend/InvenTree/build/api.py
Labels: api

#8306 Bug fix: Manually create serialized stock
  src/backend/InvenTree/stock/api.py
Labels: bug, stock

#8309 [CUI] Shipment fixes
  src/backend/InvenTree/templates/js/translated/sales_order.js
Labels: bug, order, user interface

#8310 Fix for add_tracking_entry in build.create_output
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/test_api.py
  src/backend/InvenTree/order/models.py
Labels: bug, build

#8311 [Plugin] Enhancements for serial number validation
  src/backend/InvenTree/InvenTree/helpers.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/plugin/base/integration/ValidationMixin.py
  src/backend/InvenTree/plugin/plugin.py
  src/backend/InvenTree/plugin/samples/integration/validation_sample.py
  src/backend/InvenTree/stock/api.py
  src/backend/InvenTree/stock/generators.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/serializers.py
  src/backend/InvenTree/stock/tests.py
Labels: enhancement, plugin

#8305 Fix breadcrumb for <BuildOrderDetail />
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/tests/pages/pui_stock.spec.ts
Labels: bug, user interface, Platform UI

#8318 Bump dev dep
  .pre-commit-config.yaml
Labels: dependency

#8307 Refactoring / Enhancements
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/build/status_codes.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/order/status_codes.py
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/pages/part/PartAllocationPanel.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/states/UserState.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
  src/frontend/src/tables/company/CompanyTable.tsx
  src/frontend/src/tables/part/PartPurchaseOrdersTable.tsx
  src/frontend/src/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/tables/sales/SalesOrderAllocationTable.tsx
  src/frontend/src/tables/sales/SalesOrderShipmentTable.tsx
Labels: user interface, refactor, Platform UI

#8319 [PUI] Tweaks for part purchase order table
  src/backend/InvenTree/order/api.py
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/part/PartPurchaseOrdersTable.tsx
Labels: order, user interface, Platform UI

#8321 [docs] Add documentation about user management
  docs/docs/start/accounts.md
  docs/mkdocs.yml
Labels: documentation, backport, backport-to-0.16.x

#8324 [PUI] Platform fixes
  src/backend/InvenTree/build/api.py
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/hooks/UseInstance.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/part/PartSchedulingDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/build/BuildAllocatedStockTable.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
  src/frontend/src/tables/part/PartPurchaseOrdersTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
Labels: user interface, Platform UI

#8328 Markdown link fix
  src/backend/InvenTree/InvenTree/helpers.py
  src/backend/InvenTree/company/test_api.py
Labels: bug, backport, backport-to-0.16.x

#8334 Hide "allocations" tab for items which are not in stock
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: user interface, Platform UI

#8331 [API] Sales order filters
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/order/test_api.py
  src/frontend/src/tables/sales/SalesOrderLineItemTable.tsx
  src/frontend/tests/pages/pui_stock.spec.ts
Labels: order, user interface, api, CI, Platform UI

#8335 [PUI] Add "View Part" action in BuildLineTable
  src/frontend/src/tables/build/BuildLineTable.tsx
Labels: user interface, Platform UI

#8337 Bump container deps
  contrib/container/requirements.txt
Labels: dependency, python

#8341 Add "active" field to SupplierPart form
  src/backend/InvenTree/templates/js/translated/company.js
Labels: bug, user interface, backport, backport-to-0.16.x

#8339 Fix display of purchase order lines
  src/backend/InvenTree/templates/js/translated/purchase_order.js
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
Labels: bug, user interface, Platform UI

#8340 Part pricing cleanup
  src/frontend/src/pages/part/pricing/PurchaseHistoryPanel.tsx
  src/frontend/tests/pages/pui_stock.spec.ts
Labels: user interface, Platform UI

#8330 use LABEL_DEFAULT_PRINTER user setting to pre-select plugin in label printing forms
  src/frontend/src/components/buttons/PrintingActions.tsx
Labels: bug, report, Platform UI

#8345 PUI: Show "Return from customer" option
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/tests/pages/pui_stock.spec.ts
Labels: bug, stock, user interface, Platform UI

#8336 Bump dev deps
  src/backend/requirements-dev.txt
Labels: dependency, python

#8352 [PUI] Machines table refactor
  src/frontend/src/pages/Index/Settings/AdminCenter/MachineManagementPanel.tsx
  src/frontend/src/tables/machine/MachineListTable.tsx
  src/frontend/src/tables/machine/MachineTypeTable.tsx
Labels: user interface, refactor, Platform UI

#8333 Log failed task
  src/backend/InvenTree/InvenTree/models.py
  src/backend/InvenTree/InvenTree/test_tasks.py
  src/backend/InvenTree/build/tasks.py
  src/backend/InvenTree/common/notifications.py
  src/backend/InvenTree/common/serializers.py
Labels: enhancement

#8357 Fix dev docs
  docs/docs/develop/react-frontend.md
Labels: documentation

#8359 Bug fix for auto-allocation against build order
  src/backend/InvenTree/build/models.py
Labels: bug, api, build

#8343 [WIP] Build line filter fix
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/build/test_api.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/templates/js/translated/build.js
Labels: bug, api, CI

#8360 Notifications fix
  src/backend/InvenTree/InvenTree/apps.py
  src/backend/InvenTree/common/notifications.py
  src/backend/InvenTree/plugin/templatetags/plugin_extras.py
Labels: bug, backport, backport-to-0.16.x

#8362 Bug fix for attachment updating
  src/backend/InvenTree/common/serializers.py
Labels: bug

#8367 [Bug] Ensure links are prepended with base URL on receipt
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/common/migrations/0010_migrate_currency_setting.py
  src/backend/InvenTree/common/migrations/0031_auto_20241026_0024.py
  src/backend/InvenTree/common/tasks.py
Labels: bug, backport, migration, backport-to-0.16.x

#8369 [PUI] Task table enhancements
  src/frontend/src/pages/Index/Settings/AdminCenter/TaskManagementPanel.tsx
  src/frontend/src/tables/settings/FailedTasksTable.tsx
  src/frontend/src/tables/settings/PendingTasksTable.tsx
Labels: user interface, Platform UI

#8373 Invoke docs
  docs/docs/demo.md
  docs/docs/develop/contributing.md
  docs/docs/develop/react-frontend.md
  docs/docs/faq.md
  docs/docs/start/accounts.md
  docs/docs/start/intro.md
  docs/docs/start/invoke.md
  docs/mkdocs.yml
Labels: setup, documentation, backport, backport-to-0.16.x

#8376 [Bug] Fix issue with build order lines table
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/serializers.py
  src/frontend/src/tables/build/BuildOutputTable.tsx
Labels: bug, user interface, api, build, Platform UI

#8377 [PUI] Add "received" filter to PurchaseOrderLineTable
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
Labels: user interface, Platform UI

#8381 [PUI] Search tweak
  src/frontend/src/components/nav/SearchDrawer.tsx
Labels: user interface, refactor, Platform UI

#8314 Add example for INVENTREE_CUSTOMIZE environment variable
  docs/docs/start/config.md
Labels: documentation

#8387 Update docker_install.md
  docs/docs/start/docker_install.md
Labels: docker, setup, documentation, backport, backport-to-0.16.x

#8380 [PUI] Build allocation sub tables
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/templates/js/translated/build.js
  src/frontend/src/components/forms/fields/TableField.tsx
  src/frontend/src/forms/BuildForms.tsx
  src/frontend/src/hooks/UseTable.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/build/BuildAllocatedStockTable.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
  src/frontend/tests/pages/pui_build.spec.ts
Labels: user interface, build, Platform UI

#8392 [PUI] notifications fix
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/helpers.py
  src/frontend/src/components/nav/NotificationDrawer.tsx
  src/frontend/src/components/plugins/PluginDrawer.tsx
  src/frontend/src/components/render/Generic.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/render/ModelType.tsx
  src/frontend/src/enums/ModelType.tsx
  src/frontend/src/pages/Notifications.tsx
  src/frontend/src/tables/settings/ErrorTable.tsx
Labels: user interface, refactor, Platform UI

#8396 [PUI] stock table
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/stock/api.py
  src/backend/InvenTree/stock/serializers.py
  src/frontend/src/tables/stock/StockItemTable.tsx
Labels: enhancement, stock, user interface, api, import / export, Platform UI

#8398 [PUI] Image tweak
  src/frontend/src/components/nav/PageDetail.tsx
Labels: user interface, Platform UI

#8399 [Bug] Fix for create_child_builds
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/build/tasks.py
Labels: bug, build

#8401 Prevent multiple background workers without global cache
  docs/docs/start/bare_dev.md
  docs/docs/start/bare_prod.md
  docs/docs/start/config.md
  docs/docs/start/docker.md
  docs/docs/start/docker_install.md
  docs/docs/start/install.md
  docs/docs/start/installer.md
  docs/docs/start/intro.md
  docs/docs/start/processes.md
  docs/docs/start/serving_files.md
  docs/mkdocs.yml
  src/backend/InvenTree/InvenTree/api.py
  src/backend/InvenTree/InvenTree/settings.py
Labels: bug, enhancement, breaking, backport, refactor, backport-to-0.16.x
