Repository inventree/InvenTree, pull requests merged in 2024-01, with the labels that each got.

#6142 New Crowdin updates
  InvenTree/locale/bg/LC_MESSAGES/django.po
  InvenTree/locale/cs/LC_MESSAGES/django.po
  InvenTree/locale/da/LC_MESSAGES/django.po
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/en/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/es_MX/LC_MESSAGES/django.po
  InvenTree/locale/fa/LC_MESSAGES/django.po
  InvenTree/locale/fi/LC_MESSAGES/django.po
  InvenTree/locale/fr/LC_MESSAGES/django.po
  InvenTree/locale/he/LC_MESSAGES/django.po
  InvenTree/locale/hi/LC_MESSAGES/django.po
  InvenTree/locale/hu/LC_MESSAGES/django.po
  InvenTree/locale/id/LC_MESSAGES/django.po
  InvenTree/locale/it/LC_MESSAGES/django.po
  InvenTree/locale/ja/LC_MESSAGES/django.po
  InvenTree/locale/ko/LC_MESSAGES/django.po
  InvenTree/locale/nl/LC_MESSAGES/django.po
  InvenTree/locale/no/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/pt/LC_MESSAGES/django.po
  InvenTree/locale/pt_br/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/sl/LC_MESSAGES/django.po
  InvenTree/locale/sr/LC_MESSAGES/django.po
  InvenTree/locale/sv/LC_MESSAGES/django.po
  InvenTree/locale/th/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  InvenTree/locale/vi/LC_MESSAGES/django.po
  InvenTree/locale/zh/LC_MESSAGES/django.po
  InvenTree/locale/zh_Hans/LC_MESSAGES/django.po
  InvenTree/locale/zh_hant/LC_MESSAGES/django.po
  src/frontend/src/locales/bg/messages.po
  src/frontend/src/locales/cs/messages.po
  src/frontend/src/locales/da/messages.po
  src/frontend/src/locales/de/messages.po
  src/frontend/src/locales/el/messages.po
  src/frontend/src/locales/es/messages.po
  src/frontend/src/locales/fa/messages.po
  src/frontend/src/locales/fi/messages.po
  src/frontend/src/locales/fr/messages.po
  src/frontend/src/locales/he/messages.po
  src/frontend/src/locales/hi/messages.po
  src/frontend/src/locales/hu/messages.po
  src/frontend/src/locales/it/messages.po
  src/frontend/src/locales/ja/messages.po
  src/frontend/src/locales/ko/messages.po
  src/frontend/src/locales/nl/messages.po
  src/frontend/src/locales/no/messages.po
  src/frontend/src/locales/pl/messages.po
  src/frontend/src/locales/pt/messages.po
  src/frontend/src/locales/ru/messages.po
  src/frontend/src/locales/sl/messages.po
  src/frontend/src/locales/sr/messages.po
  src/frontend/src/locales/sv/messages.po
  src/frontend/src/locales/th/messages.po
  src/frontend/src/locales/tr/messages.po
  src/frontend/src/locales/vi/messages.po
Labels: translation

#6144 [FR] Support creating reading initial superuser account password from file
  InvenTree/InvenTree/apps.py
  InvenTree/config_template.yaml
  docs/docs/start/config.md
Labels: enhancement, security, setup

#6165 Added update notification
  InvenTree/InvenTree/tasks.py
Labels: enhancement, setup

#6180 Simplify translations
  InvenTree/part/templates/part/bom.html
Labels: translation

#6183 Re-implement no-frontend flag in "invoke update"
  tasks.py
Labels: setup, backport, backport-to-0.13.x

#6182 Improve data import for PartParameterTemplate
  InvenTree/InvenTree/admin.py
  InvenTree/part/admin.py
  InvenTree/part/models.py
Labels: bug, importer, backport, backport-to-0.13.x

#6186 Handle case where ref_url is invalid
  InvenTree/part/templatetags/inventree_extras.py
Labels: bug, backport, backport-to-0.13.x

#6167 CI updates
  .devcontainer/devcontainer.json
  .djlintrc
  .github/workflows/qc_checks.yaml
  .pre-commit-config.yaml
  InvenTree/common/notifications.py
  InvenTree/part/stocktake.py
  InvenTree/part/test_api.py
  InvenTree/plugin/base/integration/APICallMixin.py
  InvenTree/plugin/base/label/mixins.py
  InvenTree/plugin/models.py
  InvenTree/plugins/__init__.py
  InvenTree/stock/test_api.py
  pyproject.toml
  requirements-dev.in
  requirements-dev.txt
  requirements.txt
  setup.cfg
Labels: enhancement, CI

#6191 Ready fix
  InvenTree/InvenTree/apps.py
  InvenTree/InvenTree/ready.py
  InvenTree/common/apps.py
  InvenTree/label/apps.py
  InvenTree/part/apps.py
  InvenTree/report/apps.py
  InvenTree/users/apps.py
Labels: backport, backport-to-0.13.x

#6129 [PUI] Add optional link to CUI detail pages
  src/frontend/src/components/render/ModelType.tsx
Labels: Platform UI

#6196 Remove support for django-debug-toolbar
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/urls.py
  docs/docs/credits.md
  requirements-dev.in
  requirements-dev.txt
Labels: dependency

#6198 Fix for mobile app documentation URL
  InvenTree/InvenTree/version.py
Labels: bug, backport, backport-to-0.13.x

#6205 Specify ForeignKey widget for importing destination field
  InvenTree/order/admin.py
Labels: bug, order, importer, backport, backport-to-0.13.x

#6162 Fix reassigning supplier barcodes
  InvenTree/plugin/base/barcodes/api.py
Labels: bug, barcode, backport, backport-to-0.13.x

#6210 [BUG] Fixed depreceated is_ajax
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/views.py
  InvenTree/part/api.py
  InvenTree/stock/api.py
Labels: bug, backport, backport-to-0.13.x

#6216 fixed depreceated is_ajax (#6210)
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/views.py
  InvenTree/part/api.py
  InvenTree/stock/api.py
Labels: bug

#6218 Fix URL regex
  InvenTree/report/api.py
Labels: bug, api, build

#6219 Fix build API URL
  InvenTree/report/api.py
Labels: bug, api, build

#6223 Fix placeholder text values
  src/frontend/src/components/forms/AuthenticationForm.tsx
  src/frontend/src/pages/Auth/Reset.tsx
Labels: Platform UI

#6226 Fix rendering of supplier part pack quantity
  InvenTree/company/serializers.py
  InvenTree/templates/js/translated/part.js
Labels: bug, user interface, backport, backport-to-0.13.x

#6222 Error API
  InvenTree/InvenTree/api_version.py
  InvenTree/common/api.py
  InvenTree/common/serializers.py
  InvenTree/company/serializers.py
  src/frontend/src/components/tables/InvenTreeTable.tsx
  src/frontend/src/components/tables/settings/ErrorTable.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/states/ApiState.tsx
Labels: api, Platform UI

#6228 Fix rendering of supplier pack quantity
  InvenTree/company/serializers.py
  InvenTree/templates/js/translated/part.js
Labels: bug, user interface

#6232 Fix display of error notifications
  src/frontend/src/components/nav/NotificationDrawer.tsx
Labels: bug, Platform UI

#6231 Add settings for return orders
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
Labels: Platform UI

#6235 Cleanup about and version dialogs
  InvenTree/InvenTree/api.py
  src/frontend/src/components/items/CopyButton.tsx
  src/frontend/src/components/modals/AboutInvenTreeModal.tsx
  src/frontend/src/components/modals/ServerInfoModal.tsx
  src/frontend/src/defaults/links.tsx
Labels: Platform UI

#6236 Add tests for get_purchase_orders logic
  InvenTree/plugin/base/barcodes/test_barcode.py
Labels: barcode, CI, backport, backport-to-0.13.x

#6237 Backport #6162 to 0.13
  InvenTree/plugin/base/barcodes/api.py
Labels: bug, barcode

#6239 Backport #6158
  InvenTree/plugin/base/barcodes/mixins.py
  InvenTree/plugin/builtin/suppliers/lcsc.py
  InvenTree/plugin/builtin/suppliers/mouser.py
  InvenTree/plugin/builtin/suppliers/tme.py
Labels: bug, barcode

#6234 Fix escape codes in translated strings
  InvenTree/InvenTree/api.py
  InvenTree/InvenTree/templatetags/__init__.py
  InvenTree/InvenTree/templatetags/i18n.py
  InvenTree/InvenTree/templatetags/inventree_extras.py
  InvenTree/InvenTree/templatetags/sso.py
  InvenTree/part/test_part.py
  tasks.py
Labels: bug, user interface, backport, backport-to-0.13.x

#6243 Update callback when base currency is adjusted
  InvenTree/common/models.py
Labels: enhancement, part, pricing

#6245 Add new setting PURCHASEORDER_AUTO_COMPLETE
  InvenTree/common/models.py
  InvenTree/order/models.py
  InvenTree/templates/InvenTree/settings/po.html
  src/frontend/src/components/settings/SettingItem.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
Labels: order

#6244 Updates to data import/export steps
  tasks.py
Labels: bug, import / export, backport, backport-to-0.13.x

#6253 Import data fix
  InvenTree/InvenTree/apps.py
  tasks.py
Labels: bug, import / export

#6256 Backport changes to tasks.py
  tasks.py
Labels: bug, import / export

#6247 Prevent creation of new PluginConfig during data import
  InvenTree/plugin/plugin.py
Labels: bug, import / export

#6248 Do not translate string
  InvenTree/InvenTree/templatetags/inventree_extras.py
Labels: bug, translation

#6214 Add tests for report API
  InvenTree/InvenTree/unit_test.py
  InvenTree/label/test_api.py
  InvenTree/report/tests.py
Labels: report, CI

#6263 Update invoke docs
  docs/docs/faq.md
  docs/docs/start/intro.md
Labels: dependency, documentation

#6257 [React] UI Translation Updates
  .gitignore
  InvenTree/InvenTree/api.py
  InvenTree/InvenTree/locales.py
  InvenTree/InvenTree/management/commands/prerender.py
  InvenTree/InvenTree/settings.py
  src/frontend/src/contexts/LanguageContext.tsx
  src/frontend/src/defaults/defaults.tsx
  src/frontend/src/locales/bg/messages.ts
  src/frontend/src/locales/cs/messages.ts
  src/frontend/src/locales/da/messages.ts
  src/frontend/src/locales/de/messages.ts
  src/frontend/src/locales/el/messages.ts
  src/frontend/src/locales/en/messages.ts
  src/frontend/src/locales/es-mx/messages.ts
  src/frontend/src/locales/es/messages.ts
  src/frontend/src/locales/fa/messages.ts
  src/frontend/src/locales/fi/messages.ts
  src/frontend/src/locales/fr/messages.ts
  src/frontend/src/locales/he/messages.ts
  src/frontend/src/locales/hi/messages.ts
  src/frontend/src/locales/hu/messages.ts
  src/frontend/src/locales/it/messages.ts
  src/frontend/src/locales/ja/messages.ts
  src/frontend/src/locales/ko/messages.ts
  src/frontend/src/locales/nl/messages.ts
  src/frontend/src/locales/no/messages.ts
  src/frontend/src/locales/pl/messages.ts
  src/frontend/src/locales/pseudo-LOCALE/messages.ts
  src/frontend/src/locales/pt-br/messages.ts
  src/frontend/src/locales/pt/messages.ts
  src/frontend/src/locales/ru/messages.ts
  src/frontend/src/locales/sl/messages.ts
  src/frontend/src/locales/sr/messages.d.ts
  src/frontend/src/locales/sv/messages.ts
  src/frontend/src/locales/th/messages.ts
  src/frontend/src/locales/tr/messages.ts
  src/frontend/src/locales/vi/messages.ts
  src/frontend/src/locales/zh-hans/messages.ts
  src/frontend/src/locales/zh-hant/messages.ts
  src/frontend/src/pages/Index/Settings/AccountSettings/AccountDetailPanel.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/states/states.tsx
  tasks.py
Labels: user interface, Platform UI

#6264 Report copy fix
  InvenTree/InvenTree/helpers.py
  InvenTree/label/apps.py
  InvenTree/report/apps.py
Labels: report

#6250 Fix task timeout when news_feed is unreachable
  InvenTree/common/tasks.py
  InvenTree/common/test_tasks.py
Labels: bug, backport, backport-to-0.13.x

#6265 Fix news feed task timeout (#6250)
  InvenTree/common/tasks.py
  InvenTree/common/test_tasks.py
Labels: bug

#6271 Do not create owners when importing data
  InvenTree/users/models.py
Labels: bug, import / export, backport, backport-to-0.13.x

#6251 Move more paths to basic path
  InvenTree/InvenTree/middleware.py
  InvenTree/InvenTree/urls.py
  InvenTree/build/api.py
  InvenTree/build/urls.py
  InvenTree/common/api.py
  InvenTree/company/api.py
  InvenTree/company/urls.py
  InvenTree/label/api.py
  InvenTree/order/api.py
  InvenTree/order/urls.py
  InvenTree/part/api.py
  InvenTree/part/urls.py
  InvenTree/plugin/api.py
  InvenTree/plugin/base/barcodes/api.py
  InvenTree/plugin/base/integration/test_mixins.py
  InvenTree/plugin/samples/integration/sample.py
  InvenTree/report/api.py
  InvenTree/stock/api.py
  InvenTree/stock/urls.py
  InvenTree/users/api.py
  InvenTree/web/urls.py
  docs/docs/extend/plugins/urls.md
Labels: refactor

#6275 News updates
  InvenTree/common/api.py
  InvenTree/templates/js/translated/news.js
Labels: user interface

#6274 Import Fix
  InvenTree/InvenTree/admin.py
  InvenTree/InvenTree/settings.py
  InvenTree/order/admin.py
  InvenTree/order/models.py
Labels: bug, import / export, backport, backport-to-0.13.x

#6211 [FR] Add tracing support
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/tracing.py
  InvenTree/config_template.yaml
  InvenTree/manage.py
  docs/docs/start/advanced.md
  requirements.in
  requirements.txt
Labels: enhancement, setup

#6277 Import Fix (#6274)
  InvenTree/InvenTree/admin.py
  InvenTree/order/admin.py
  InvenTree/order/models.py
Labels: bug, import / export

#6284 [PUI] Fix logout
  InvenTree/web/urls.py
  src/frontend/src/App.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/functions/auth.tsx
  src/frontend/src/states/ApiState.tsx
Labels: bug, Platform UI

#6287 [PUI] Fix global login
  InvenTree/users/api.py
  src/frontend/src/functions/auth.tsx
  src/frontend/src/pages/Auth/Login.tsx
Labels: bug, Platform UI

#6288 JS translation fix
  InvenTree/InvenTree/templatetags/i18n.py
  InvenTree/build/templates/build/build_base.html
  InvenTree/build/templates/build/detail.html
  InvenTree/company/templates/company/company_base.html
  InvenTree/company/templates/company/manufacturer_part.html
  InvenTree/company/templates/company/supplier_part.html
  InvenTree/order/templates/order/order_base.html
  InvenTree/order/templates/order/return_order_base.html
  InvenTree/order/templates/order/sales_order_base.html
  InvenTree/part/templates/part/detail.html
  InvenTree/part/templates/part/part_base.html
  InvenTree/part/templates/part/pricing_javascript.html
  InvenTree/stock/templates/stock/item.html
  InvenTree/stock/templates/stock/item_base.html
  InvenTree/stock/templates/stock/location.html
  InvenTree/templates/InvenTree/index.html
  InvenTree/templates/InvenTree/notifications/notifications.html
  InvenTree/templates/InvenTree/search.html
  InvenTree/templates/InvenTree/settings/settings_js.html
  InvenTree/templates/InvenTree/settings/settings_staff_js.html
  InvenTree/templates/InvenTree/settings/user.html
  InvenTree/templates/js/translated/api.js
  InvenTree/templates/js/translated/attachment.js
  InvenTree/templates/js/translated/barcode.js
  InvenTree/templates/js/translated/bom.js
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/company.js
  InvenTree/templates/js/translated/filters.js
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/helpers.js
  InvenTree/templates/js/translated/index.js
  InvenTree/templates/js/translated/label.js
  InvenTree/templates/js/translated/modals.js
  InvenTree/templates/js/translated/model_renderers.js
  InvenTree/templates/js/translated/news.js
  InvenTree/templates/js/translated/notification.js
  InvenTree/templates/js/translated/order.js
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/plugin.js
  InvenTree/templates/js/translated/pricing.js
  InvenTree/templates/js/translated/purchase_order.js
  InvenTree/templates/js/translated/report.js
  InvenTree/templates/js/translated/return_order.js
  InvenTree/templates/js/translated/sales_order.js
  InvenTree/templates/js/translated/search.js
  InvenTree/templates/js/translated/stock.js
  InvenTree/templates/js/translated/table_filters.js
  InvenTree/templates/js/translated/tables.js
  ci/check_js_templates.py
Labels: bug, user interface, backport, backport-to-0.13.x

#6289 JS translation fix (#6288)
  InvenTree/build/templates/build/build_base.html
  InvenTree/build/templates/build/detail.html
  InvenTree/company/templates/company/company_base.html
  InvenTree/company/templates/company/manufacturer_part.html
  InvenTree/company/templates/company/supplier_part.html
  InvenTree/order/templates/order/order_base.html
  InvenTree/order/templates/order/return_order_base.html
  InvenTree/order/templates/order/sales_order_base.html
  InvenTree/part/templates/part/detail.html
  InvenTree/part/templates/part/part_base.html
  InvenTree/part/templates/part/pricing_javascript.html
  InvenTree/part/templatetags/i18n.py
  InvenTree/stock/templates/stock/item.html
  InvenTree/stock/templates/stock/item_base.html
  InvenTree/stock/templates/stock/location.html
  InvenTree/templates/InvenTree/index.html
  InvenTree/templates/InvenTree/notifications/notifications.html
  InvenTree/templates/InvenTree/search.html
  InvenTree/templates/InvenTree/settings/settings_js.html
  InvenTree/templates/InvenTree/settings/settings_staff_js.html
  InvenTree/templates/InvenTree/settings/user.html
  InvenTree/templates/js/translated/api.js
  InvenTree/templates/js/translated/attachment.js
  InvenTree/templates/js/translated/barcode.js
  InvenTree/templates/js/translated/bom.js
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/company.js
  InvenTree/templates/js/translated/filters.js
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/helpers.js
  InvenTree/templates/js/translated/index.js
  InvenTree/templates/js/translated/label.js
  InvenTree/templates/js/translated/modals.js
  InvenTree/templates/js/translated/model_renderers.js
  InvenTree/templates/js/translated/news.js
  InvenTree/templates/js/translated/notification.js
  InvenTree/templates/js/translated/order.js
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/plugin.js
  InvenTree/templates/js/translated/pricing.js
  InvenTree/templates/js/translated/purchase_order.js
  InvenTree/templates/js/translated/report.js
  InvenTree/templates/js/translated/return_order.js
  InvenTree/templates/js/translated/sales_order.js
  InvenTree/templates/js/translated/search.js
  InvenTree/templates/js/translated/stock.js
  InvenTree/templates/js/translated/table_filters.js
  InvenTree/templates/js/translated/tables.js
  ci/check_js_templates.py
Labels: bug, user interface

#6297 SSO config docs
  docs/docs/settings/SSO.md
  docs/docs/start/config.md
Labels: documentation

#6301 Update django-allauth version
  requirements.txt
Labels: bug, dependency, setup, backport, backport-to-0.13.x

#6298 Remove {% jstrans %} tag
  InvenTree/InvenTree/templatetags/i18n.py
  InvenTree/build/templates/build/build_base.html
  InvenTree/build/templates/build/detail.html
  InvenTree/company/templates/company/company_base.html
  InvenTree/company/templates/company/manufacturer_part.html
  InvenTree/company/templates/company/supplier_part.html
  InvenTree/order/templates/order/order_base.html
  InvenTree/order/templates/order/return_order_base.html
  InvenTree/order/templates/order/sales_order_base.html
  InvenTree/part/templates/part/detail.html
  InvenTree/part/templates/part/part_base.html
  InvenTree/part/templates/part/pricing_javascript.html
  InvenTree/stock/templates/stock/item.html
  InvenTree/stock/templates/stock/item_base.html
  InvenTree/stock/templates/stock/location.html
  InvenTree/templates/InvenTree/index.html
  InvenTree/templates/InvenTree/notifications/notifications.html
  InvenTree/templates/InvenTree/search.html
  InvenTree/templates/InvenTree/settings/settings_js.html
  InvenTree/templates/InvenTree/settings/settings_staff_js.html
  InvenTree/templates/InvenTree/settings/user.html
  InvenTree/templates/js/translated/api.js
  InvenTree/templates/js/translated/attachment.js
  InvenTree/templates/js/translated/barcode.js
  InvenTree/templates/js/translated/bom.js
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/company.js
  InvenTree/templates/js/translated/filters.js
  InvenTree/templates/js/translated/forms.js
  InvenTree/templates/js/translated/helpers.js
  InvenTree/templates/js/translated/index.js
  InvenTree/templates/js/translated/label.js
  InvenTree/templates/js/translated/modals.js
  InvenTree/templates/js/translated/model_renderers.js
  InvenTree/templates/js/translated/news.js
  InvenTree/templates/js/translated/notification.js
  InvenTree/templates/js/translated/order.js
  InvenTree/templates/js/translated/part.js
  InvenTree/templates/js/translated/plugin.js
  InvenTree/templates/js/translated/pricing.js
  InvenTree/templates/js/translated/purchase_order.js
  InvenTree/templates/js/translated/report.js
  InvenTree/templates/js/translated/return_order.js
  InvenTree/templates/js/translated/sales_order.js
  InvenTree/templates/js/translated/search.js
  InvenTree/templates/js/translated/stock.js
  InvenTree/templates/js/translated/table_filters.js
  InvenTree/templates/js/translated/tables.js
  ci/check_js_templates.py
Labels: bug

#6246 SSO Error Improvememts
  InvenTree/InvenTree/exceptions.py
  InvenTree/InvenTree/forms.py
Labels: backport, backport-to-0.13.x

#6304 SSO Error Improvememts (#6246)
  InvenTree/InvenTree/exceptions.py
  InvenTree/InvenTree/forms.py
Labels: bug

#6310 CORS fixes:
  InvenTree/InvenTree/middleware.py
  InvenTree/InvenTree/settings.py
Labels: api

#6309 [PUI] Registration
  src/frontend/src/components/forms/AuthenticationForm.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/pages/Auth/Login.tsx
  src/frontend/src/states/ApiState.tsx
Labels: enhancement, Platform UI

#6320 [PUI] Small updates
  src/frontend/src/components/buttons/ActionButton.tsx
  src/frontend/src/components/nav/SearchDrawer.tsx
  src/frontend/src/components/render/Part.tsx
  src/frontend/src/components/tables/InvenTreeTable.tsx
  src/frontend/src/components/tables/bom/BomTable.tsx
  src/frontend/src/components/tables/bom/UsedInTable.tsx
  src/frontend/src/components/tables/build/BuildOrderTable.tsx
  src/frontend/src/components/tables/company/AddressTable.tsx
  src/frontend/src/components/tables/company/ContactTable.tsx
  src/frontend/src/components/tables/general/AttachmentTable.tsx
  src/frontend/src/components/tables/part/PartCategoryTable.tsx
  src/frontend/src/components/tables/part/PartParameterTable.tsx
  src/frontend/src/components/tables/part/PartParameterTemplateTable.tsx
  src/frontend/src/components/tables/part/PartTable.tsx
  src/frontend/src/components/tables/part/PartTestTemplateTable.tsx
  src/frontend/src/components/tables/part/PartVariantTable.tsx
  src/frontend/src/components/tables/part/RelatedPartTable.tsx
  src/frontend/src/components/tables/plugin/PluginListTable.tsx
  src/frontend/src/components/tables/purchasing/ManufacturerPartTable.tsx
  src/frontend/src/components/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/components/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/components/tables/purchasing/SupplierPartTable.tsx
  src/frontend/src/components/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/components/tables/sales/SalesOrderTable.tsx
  src/frontend/src/components/tables/settings/CurrencyTable.tsx
  src/frontend/src/components/tables/settings/CustomUnitsTable.tsx
  src/frontend/src/components/tables/settings/GroupTable.tsx
  src/frontend/src/components/tables/settings/ProjectCodeTable.tsx
  src/frontend/src/components/tables/settings/UserTable.tsx
  src/frontend/src/components/tables/stock/StockItemTable.tsx
  src/frontend/src/components/tables/stock/StockLocationTable.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  tasks.py
Labels: user interface, Platform UI

#6314 [PUI] Auth behaviour controls
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/social_auth_urls.py
  src/frontend/src/components/forms/AuthenticationForm.tsx
  src/frontend/src/states/ApiState.tsx
  src/frontend/src/states/states.tsx
Labels: Platform UI

#6324 Specify empty OIDC prefix
  InvenTree/InvenTree/settings.py
Labels: bug, dependency, backport, backport-to-0.13.x

#6330 fix(docker): SELinux volume labels
  docker/production/docker-compose.yml
Labels: docker, backport, backport-to-0.13.x

#6326 [PUI] Add missing pages
  src/frontend/src/components/render/ModelType.tsx
  src/frontend/src/components/tables/purchasing/ManufacturerPartTable.tsx
  src/frontend/src/components/tables/purchasing/SupplierPartTable.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/company/ManufacturerPartDetail.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/router.tsx
  src/frontend/src/states/ApiState.tsx
Labels: Platform UI

#6335 Fix stock item splitting bug
  InvenTree/part/migrations/0112_auto_20230525_1606.py
  InvenTree/stock/models.py
  InvenTree/stock/tests.py
Labels: bug, api, backport, backport-to-0.13.x

#6334 [PUI] Child item table
  InvenTree/stock/api.py
  InvenTree/stock/filters.py
  InvenTree/stock/serializers.py
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: user interface, Platform UI

#6338 Backport of #6335
  InvenTree/part/migrations/0112_auto_20230525_1606.py
  InvenTree/stock/models.py
  InvenTree/stock/tests.py
Labels: bug

#6343 Build order improvements
  InvenTree/InvenTree/api_version.py
  InvenTree/build/serializers.py
  InvenTree/build/templates/build/detail.html
  InvenTree/order/templates/order/sales_order_detail.html
  InvenTree/part/filters.py
  InvenTree/templates/js/translated/build.js
  InvenTree/templates/js/translated/sales_order.js
  src/frontend/src/components/images/Thumbnail.tsx
  src/frontend/src/components/tables/bom/UsedInTable.tsx
  src/frontend/src/components/tables/build/BuildLineTable.tsx
  src/frontend/src/components/tables/build/BuildOrderTable.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/states/ApiState.tsx
Labels: user interface, api, build

#6356 URL nav improvements
  src/frontend/src/components/tables/bom/BomTable.tsx
  src/frontend/src/components/tables/bom/UsedInTable.tsx
  src/frontend/src/components/tables/build/BuildLineTable.tsx
  src/frontend/src/components/tables/build/BuildOrderTable.tsx
  src/frontend/src/components/tables/part/PartCategoryTable.tsx
  src/frontend/src/components/tables/part/PartTable.tsx
  src/frontend/src/components/tables/purchasing/ManufacturerPartTable.tsx
  src/frontend/src/components/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/components/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/components/tables/purchasing/SupplierPartTable.tsx
  src/frontend/src/components/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/components/tables/sales/SalesOrderTable.tsx
  src/frontend/src/components/tables/stock/StockItemTable.tsx
  src/frontend/src/components/tables/stock/StockLocationTable.tsx
  src/frontend/src/functions/urls.tsx
Labels: Platform UI

#6357 [PUI] Tables
  src/frontend/src/components/tables/purchasing/ManufacturerPartParameterTable.tsx
  src/frontend/src/components/tables/purchasing/SupplierPartTable.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/forms/CompanyForms.tsx
  src/frontend/src/functions/forms.tsx
  src/frontend/src/pages/company/ManufacturerPartDetail.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/states/ApiState.tsx
Labels: Platform UI

#6359 Remove proxy support in vite server
  src/frontend/vite.config.ts
Labels: Platform UI

#6362 Bug fix for javascript rendering
  InvenTree/InvenTree/templatetags/i18n.py
Labels: bug, backport, backport-to-0.13.x

#6365 Forms initial data
  InvenTree/users/api.py
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/forms/fields/ChoiceField.tsx
  src/frontend/src/components/forms/fields/DateField.tsx
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
  src/frontend/src/components/render/Company.tsx
  src/frontend/src/components/tables/build/BuildOrderTable.tsx
  src/frontend/src/components/tables/company/AddressTable.tsx
  src/frontend/src/components/tables/company/CompanyTable.tsx
  src/frontend/src/components/tables/company/ContactTable.tsx
  src/frontend/src/components/tables/part/PartCategoryTable.tsx
  src/frontend/src/components/tables/part/PartParameterTable.tsx
  src/frontend/src/components/tables/part/PartParameterTemplateTable.tsx
  src/frontend/src/components/tables/part/PartTestTemplateTable.tsx
  src/frontend/src/components/tables/part/RelatedPartTable.tsx
  src/frontend/src/components/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/components/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/components/tables/sales/SalesOrderTable.tsx
  src/frontend/src/components/tables/settings/CustomUnitsTable.tsx
  src/frontend/src/components/tables/settings/GroupTable.tsx
  src/frontend/src/components/tables/settings/ProjectCodeTable.tsx
  src/frontend/src/components/tables/stock/StockLocationTable.tsx
  src/frontend/src/forms/CommonForms.tsx
  src/frontend/src/forms/CompanyForms.tsx
  src/frontend/src/forms/PartForms.tsx
  src/frontend/src/forms/PurchaseOrderForms.tsx
  src/frontend/src/forms/SalesOrderForms.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/hooks/UseForm.tsx
  src/frontend/src/main.tsx
  src/frontend/src/pages/Index/Playground.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/build/BuildIndex.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchasingIndex.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
Labels: enhancement, Platform UI
