Repository inventree/InvenTree, pull requests merged in 2024-05, with the labels that each got.

#7148 Fix icon
  src/frontend/src/pages/build/BuildDetail.tsx
Labels: Platform UI

#7150 Stock transfer dialog fix
  src/backend/InvenTree/templates/js/translated/stock.js
  src/frontend/src/forms/StockForms.tsx
Labels: bug, user interface

#7152 [PUI] Add "name" icon
  src/frontend/src/functions/icons.tsx
Labels: Platform UI

#7151 Fix for react hook
  src/frontend/src/forms/StockForms.tsx
Labels: bug, Platform UI

#7153 Build order cancel
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/build/tasks.py
  src/backend/InvenTree/build/test_api.py
  src/backend/InvenTree/templates/js/translated/build.js
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
Labels: bug, user interface, api, Platform UI

#7160 Build default location
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/serializers.py
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/forms/BuildForms.tsx
  src/frontend/src/hooks/UseTable.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/tables/sales/SalesOrderTable.tsx
  src/frontend/src/tables/stock/InstalledItemsTable.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
Labels: user interface, api, build, Platform UI

#7165 [PUI] Add testing for Scanning page
  src/frontend/playwright.config.ts
  src/frontend/src/pages/Index/Scan.tsx
  src/frontend/tests/pages/pui_scan.spec.ts
Labels: CI, Platform UI

#7158 Refactor login state management
  src/backend/InvenTree/InvenTree/api.py
  src/backend/InvenTree/InvenTree/middleware.py
  src/backend/InvenTree/users/models.py
  src/frontend/playwright.config.ts
  src/frontend/src/App.tsx
  src/frontend/src/components/forms/AuthenticationForm.tsx
  src/frontend/src/components/items/MenuLinks.tsx
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/components/nav/Layout.tsx
  src/frontend/src/components/nav/PartCategoryTree.tsx
  src/frontend/src/components/nav/StockLocationTree.tsx
  src/frontend/src/contexts/LanguageContext.tsx
  src/frontend/src/functions/auth.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/AccountDetailPanel.tsx
  src/frontend/src/states/SettingsState.tsx
  src/frontend/src/states/StatusState.tsx
  src/frontend/src/states/UserState.tsx
  src/frontend/src/states/states.tsx
  src/frontend/src/views/DesktopAppView.tsx
  src/frontend/tests/baseFixtures.ts
  src/frontend/tests/login.ts
  src/frontend/tests/pui_basic.spec.ts
  src/frontend/tests/pui_general.spec.ts
  src/frontend/tests/pui_stock.spec.ts
Labels: enhancement, user interface, refactor, Platform UI

#7174 Bump django and adjacent deps
  src/backend/requirements-dev.txt
  src/backend/requirements.txt
  src/frontend/tests/modals.spec.ts
Labels: dependency, security

#7176 [PUI] Error boundary
  src/frontend/src/components/Boundary.tsx
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/nav/Layout.tsx
  src/frontend/src/components/nav/PanelGroup.tsx
  src/frontend/src/components/nav/SearchDrawer.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
Labels: user interface, Platform UI

#7179 [PUI] part stock
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
Labels: user interface, Platform UI

#7178 Fix BuildItem with empty BuildLine reference
  src/backend/InvenTree/build/migrations/0049_alter_builditem_build_line.py
  src/backend/InvenTree/build/migrations/0050_auto_20240508_0138.py
  src/backend/InvenTree/build/models.py
Labels: bug, migration

#7180 [PUI] Tweaks
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/hooks/UseTable.tsx
  src/frontend/src/pages/part/pricing/BomPricingPanel.tsx
  src/frontend/src/pages/part/pricing/PricingPanel.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
Labels: bug, user interface, Platform UI

#7181 Refactor PanelMixin class into its own file
  src/backend/InvenTree/plugin/base/integration/PanelMixin.py
  src/backend/InvenTree/plugin/base/integration/mixins.py
  src/backend/InvenTree/plugin/base/integration/test_mixins.py
  src/backend/InvenTree/plugin/mixins/__init__.py
Labels: plugin, refactor

#7182 Updates to StockOperationsRow
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
Labels: bug, user interface, Platform UI

#7183 Add more fields to BuildDetail page
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
Labels: Platform UI

#7184 Fix for details links
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/functions/navigation.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/bom/BomTable.tsx
Labels: user interface, Platform UI

#7195 Fixed the app/app link to point to the latest app version. #7193
  src/backend/InvenTree/InvenTree/version.py
Labels: bug, documentation

#7194 Transfer out of stock items
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/test_api.py
  src/backend/InvenTree/templates/InvenTree/settings/stock.html
  src/frontend/src/pages/Index/Settings/AdminCenter/TaskManagementPanel.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/tables/settings/FailedTasksTable.tsx
Labels: stock

#7196 Trackable build part fix
  src/backend/InvenTree/build/templates/build/detail.html
  src/backend/InvenTree/templates/js/translated/build.js
Labels: bug, user interface, javascript, backport, backport-to-0.14.x

#7201 Revert "Fixed the app/app link to point to the latest app version. #7193 "
  src/backend/InvenTree/InvenTree/version.py
Labels: documentation

#7204 [PUI] stock item delete
  src/frontend/src/components/forms/fields/ChoiceField.tsx
  src/frontend/src/components/forms/fields/TableField.tsx
  src/frontend/src/components/items/ActionDropdown.tsx
  src/frontend/src/components/modals/ServerInfoModal.tsx
  src/frontend/src/forms/PurchaseOrderForms.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/UserThemePanel.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: user interface, Platform UI

#7207 Nginx example
  contrib/container/Caddyfile
  contrib/container/docker-compose.yml
  contrib/container/nginx.conf
  docs/docs/start/docker.md
Labels: setup, documentation

#7215 Running worker status
  src/frontend/src/hooks/UseInstance.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/TaskManagementPanel.tsx
Labels: Platform UI

#7228 Docker fix
  .github/workflows/docker.yaml
  contrib/container/Dockerfile
  tasks.py
Labels: bug, docker, setup, backport, backport-to-0.15.x

#7224 Plugin API lookup key
  src/backend/InvenTree/InvenTree/api.py
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/common/tests.py
  src/backend/InvenTree/plugin/api.py
  src/backend/InvenTree/plugin/migrations/0009_alter_pluginconfig_key.py
  src/backend/InvenTree/plugin/models.py
  src/backend/InvenTree/plugin/serializers.py
  src/backend/InvenTree/plugin/test_api.py
  src/backend/InvenTree/templates/js/translated/plugin.js
  src/frontend/src/components/settings/SettingList.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/hooks/UseInstance.tsx
  src/frontend/src/tables/plugin/PluginListTable.tsx
Labels: plugin, api, breaking, refactor

#7231 [PUI] Test table tweaks
  src/frontend/src/tables/FilterSelectDrawer.tsx
  src/frontend/src/tables/stock/StockItemTestResultTable.tsx
Labels: user interface, Platform UI

#7202 Add location type to location overview
  src/backend/InvenTree/stock/templates/stock/location.html
Labels: user interface

#7238 PUI location type
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/render/ModelType.tsx
  src/frontend/src/components/render/Stock.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/enums/ModelType.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/tables/part/ParametricPartTable.tsx
  src/frontend/src/tables/part/PartCategoryTemplateTable.tsx
  src/frontend/src/tables/part/PartParameterTable.tsx
  src/frontend/src/tables/part/PartParameterTemplateTable.tsx
  src/frontend/src/tables/part/PartTestTemplateTable.tsx
  src/frontend/src/tables/stock/LocationTypesTable.tsx
Labels: enhancement, Platform UI

#7239 [PUI] Refactoring forms
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/settings/SettingItem.tsx
  src/frontend/src/components/settings/SettingList.tsx
  src/frontend/src/forms/CompanyForms.tsx
  src/frontend/src/pages/part/pricing/PriceBreakPanel.tsx
  src/frontend/src/tables/bom/BomTable.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
  src/frontend/src/tables/company/AddressTable.tsx
  src/frontend/src/tables/company/ContactTable.tsx
  src/frontend/src/tables/part/PartCategoryTable.tsx
  src/frontend/src/tables/part/PartCategoryTemplateTable.tsx
  src/frontend/src/tables/part/PartParameterTable.tsx
  src/frontend/src/tables/part/PartParameterTemplateTable.tsx
  src/frontend/src/tables/part/PartTestTemplateTable.tsx
  src/frontend/src/tables/part/RelatedPartTable.tsx
  src/frontend/src/tables/plugin/PluginListTable.tsx
  src/frontend/src/tables/purchasing/ManufacturerPartParameterTable.tsx
  src/frontend/src/tables/purchasing/ManufacturerPartTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/tables/purchasing/SupplierPartTable.tsx
  src/frontend/src/tables/purchasing/SupplierPriceBreakTable.tsx
  src/frontend/src/tables/settings/CustomUnitsTable.tsx
  src/frontend/src/tables/settings/ErrorTable.tsx
  src/frontend/src/tables/settings/GroupTable.tsx
  src/frontend/src/tables/settings/ProjectCodeTable.tsx
  src/frontend/src/tables/settings/TemplateTable.tsx
  src/frontend/src/tables/settings/UserTable.tsx
  src/frontend/src/tables/stock/StockItemTestResultTable.tsx
  src/frontend/src/tables/stock/StockLocationTable.tsx
Labels: user interface, Platform UI

#6449 Add support for a Completed status (Fixes: #6434)
  src/backend/InvenTree/InvenTree/status_codes.py
  src/backend/InvenTree/order/migrations/0099_alter_salesorder_status.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/order/templates/order/sales_order_base.html
  src/backend/InvenTree/order/test_sales_order.py
  src/backend/InvenTree/templates/js/translated/sales_order.js
Labels: enhancement, order, api, breaking

#7232 [PUI] Attachment table fix
  src/frontend/src/forms/AttachmentForms.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/general/AttachmentTable.tsx
  src/frontend/tests/pages/pui_part.spec.ts
Labels: bug, user interface, refactor, Platform UI

#7242 [PUI] Column Refactoring
  src/frontend/src/tables/Column.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/bom/BomTable.tsx
  src/frontend/src/tables/bom/UsedInTable.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/tables/purchasing/SupplierPartTable.tsx
  src/frontend/src/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/tables/sales/SalesOrderTable.tsx
  src/frontend/src/tables/settings/ProjectCodeTable.tsx
  src/frontend/src/tables/stock/StockItemTestResultTable.tsx
Labels: user interface, javascript, refactor, Platform UI

#7248 Admin tweaks
  src/backend/InvenTree/common/admin.py
  src/backend/InvenTree/company/admin.py
  src/backend/InvenTree/order/admin.py
  src/backend/InvenTree/part/admin.py
  src/backend/InvenTree/stock/admin.py
  src/frontend/src/components/buttons/ActionButton.tsx
  src/frontend/src/components/buttons/AdminButton.tsx
  src/frontend/src/components/render/ModelType.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/company/ManufacturerPartDetail.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: user interface, Platform UI

#7249 Fix for email template
  src/backend/InvenTree/templates/email/build_order_required_stock.html
Labels: bug, build, backport, backport-to-0.15.x

#7258 Plugin setting fix
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/common/tests.py
  src/backend/InvenTree/plugin/api.py
  src/backend/InvenTree/plugin/test_api.py
  src/backend/InvenTree/templates/InvenTree/settings/settings_js.html
  src/backend/InvenTree/templates/js/dynamic/settings.js
  src/frontend/src/components/settings/SettingList.tsx
Labels: bug, user interface, api, Platform UI

#7261 fix: SELinux labels for Caddyfile
  contrib/container/docker-compose.yml
Labels: docker, setup, backport, backport-to-0.15.x

#7260 Prevent deletion of part which is used in an assembly
  src/backend/InvenTree/InvenTree/models.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/company/tests.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/part/test_api.py
  src/backend/InvenTree/part/test_bom_item.py
  src/backend/InvenTree/part/test_part.py
  src/backend/InvenTree/plugin/base/integration/ValidationMixin.py
  src/backend/InvenTree/templates/InvenTree/settings/part.html
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
Labels: enhancement, part

#7263 Docs: Update plugins and compose
  docs/docs/develop/contributing.md
  docs/docs/extend/how_to_plugin.md
  docs/docs/extend/plugins.md
  docs/docs/extend/plugins/barcode.md
  docs/docs/extend/plugins/install.md
Labels: setup, documentation

#7265 Remove dead code
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/stock/api.py
Labels: refactor

#7264 Update part filters
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/part/test_api.py
Labels: part, api, refactor

#7000 Batch code generation
  docs/docs/extend/plugins/validation.md
  src/backend/InvenTree/InvenTree/api.py
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/helpers.py
  src/backend/InvenTree/InvenTree/urls.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/plugin/base/integration/ValidationMixin.py
  src/backend/InvenTree/plugin/samples/integration/validation_sample.py
  src/backend/InvenTree/stock/api.py
  src/backend/InvenTree/stock/generators.py
  src/backend/InvenTree/stock/migrations/0074_alter_stockitem_batch.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/serializers.py
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/forms/BuildForms.tsx
  src/frontend/src/forms/PurchaseOrderForms.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/hooks/UseGenerator.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
Labels: enhancement, user interface, plugin, api, Platform UI

#7280 Add documentation on 'validate_model_deletion'
  docs/docs/extend/plugins/validation.md
  src/backend/InvenTree/plugin/base/integration/ValidationMixin.py
Labels: plugin, documentation

#7273 [PUI] StockTrackingTable
  src/frontend/src/components/render/Build.tsx
  src/frontend/src/components/render/Company.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/render/Order.tsx
  src/frontend/src/components/render/Part.tsx
  src/frontend/src/components/render/Stock.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/stock/StockTrackingTable.tsx
Labels: stock, user interface, refactor, Platform UI

#7154 Performance improvement for notifications API endpoint
  src/backend/InvenTree/common/api.py
Labels: enhancement, api

#7290 Test result table tweaks
  src/backend/InvenTree/part/api.py
  src/frontend/src/tables/build/BuildOutputTable.tsx
  src/frontend/src/tables/stock/StockItemTestResultTable.tsx
Labels: user interface, Platform UI

#7296 Report Migration Fix
  src/backend/InvenTree/report/migrations/0022_reporttemplate.py
  src/backend/InvenTree/report/migrations/0025_labeltemplate.py
  src/backend/InvenTree/report/models.py
Labels: bug, report, migration

#7299 [PUI] Add initial part data to manufacturer part table
  src/frontend/src/tables/purchasing/ManufacturerPartTable.tsx
Labels: user interface, Platform UI

#7298 [PUI] Dynamic PartParameter field
  src/frontend/src/components/buttons/ActionButton.tsx
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
  src/frontend/src/forms/PartForms.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/RowActions.tsx
  src/frontend/src/tables/general/AttachmentTable.tsx
  src/frontend/src/tables/part/PartParameterTable.tsx
  src/frontend/tests/pages/pui_part.spec.ts
Labels: user interface, Platform UI

#7305 Fix sales order shipment / completed buttons
  .github/actions/setup/action.yaml
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/templates/order/sales_order_base.html
Labels: bug, order, user interface

#7311 Add clearer error message for invalid SITE_URL
  src/backend/InvenTree/InvenTree/settings.py
Labels: setup, backport, backport-to-0.15.x

#7315 Add Meta subclass for build serializers
  src/backend/InvenTree/build/serializers.py
Labels: bug, api, build

#7317 Use `UV_SYSTEM_PYTHON` to allow the system Python interpreter
  .github/actions/setup/action.yaml
Labels: CI, dependency

#7322 Handle exception on migration
  src/backend/InvenTree/users/migrations/0011_auto_20240523_1640.py
Labels: bug, CI, migration, full-run

#7320 Merge pull request from GHSA-2crp-q9pc-457j
  .github/actions/setup/action.yaml
  docs/docs/develop/contributing.md
  docs/docs/extend/plugins.md
  docs/docs/extend/plugins/locate.md
  docs/docs/extend/plugins/report.md
  docs/docs/extend/plugins/schedule.md
  docs/docs/extend/plugins/urls.md
  docs/docs/extend/plugins/validation.md
  docs/docs/report/bom.md
  docs/docs/report/build.md
  docs/docs/report/helpers.md
  docs/docs/report/purchase_order.md
  docs/docs/report/return_order.md
  docs/docs/report/sales_order.md
  docs/docs/report/stock_location.md
  docs/docs/report/test.md
  docs/docs/start/config.md
  src/backend/InvenTree/users/api.py
  src/backend/InvenTree/users/migrations/0011_auto_20240523_1640.py
Labels: bug, security, migration, full-run

#7327 CUI: Don't load stock test results for non-trackable part
  src/backend/InvenTree/stock/templates/stock/item.html
Labels: bug, user interface, backport, backport-to-0.15.x

#7339 Update docs
  docs/docs/start/installer.md
Labels: setup, documentation, backport, backport-to-0.15.x

#7343 Updates for metadata information
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/metadata.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/part/test_api.py
Labels: bug

#7348 Fix for 'restore' command
  tasks.py
Labels: bug, setup, backport, backport-to-0.15.x

#7344 Fixes for installer
  .github/workflows/docker.yaml
  .github/workflows/qc_checks.yaml
  .github/workflows/release.yaml
  .pre-commit-config.yaml
  contrib/dev_reqs/requirements.in
  contrib/dev_reqs/requirements.txt
  contrib/packager.io/functions.sh
  contrib/packager.io/postinstall.sh
Labels: bug, setup, backport, installer, backport-to-0.15.x

#7324 Bug fix for label printing with plugin on CUI
  src/backend/InvenTree/report/api.py
  src/backend/InvenTree/templates/js/translated/forms.js
  src/backend/InvenTree/templates/js/translated/label.js
Labels: bug, plugin, report

#7350 Fixes for installer (#7344)
  .github/workflows/docker.yaml
  .github/workflows/qc_checks.yaml
  .github/workflows/release.yaml
  .pre-commit-config.yaml
  contrib/dev_reqs/requirements.in
  contrib/dev_reqs/requirements.txt
  contrib/packager.io/functions.sh
  contrib/packager.io/postinstall.sh
Labels: bug, setup, installer, full-run

#7354 [PUI] Open links in new window
  src/frontend/src/components/nav/BreadcrumbList.tsx
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/components/nav/PanelGroup.tsx
Labels: Platform UI

#7355 Include "config template" in docs
  docs/docs/start/config.md
  docs/main.py
  src/backend/InvenTree/config_template.yaml
Labels: documentation

#7360 Handle case where serializer does not have 'Meta' class
  src/backend/InvenTree/InvenTree/metadata.py
  src/backend/InvenTree/plugin/serializers.py
Labels: bug, api, backport, backport-to-0.15.x

#7361 Plugin reload fix
  src/backend/InvenTree/plugin/base/event/events.py
Labels: bug, plugin, backport, backport-to-0.15.x

#7366 Add option to hide active sessions from settings panel
  src/backend/InvenTree/templates/InvenTree/settings/user.html
Labels: user interface

#7357 [PUI] Mantine tree
  src/backend/InvenTree/InvenTree/filters.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/stock/api.py
  src/frontend/package.json
  src/frontend/src/components/details/DetailsImage.tsx
  src/frontend/src/components/nav/BreadcrumbList.tsx
  src/frontend/src/components/nav/NavigationTree.tsx
  src/frontend/src/components/nav/PanelGroup.tsx
  src/frontend/src/components/nav/PartCategoryTree.tsx
  src/frontend/src/components/nav/StockLocationTree.tsx
  src/frontend/src/functions/conversion.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/tests/pui_general.spec.ts
  src/frontend/tests/pui_stock.spec.ts
  src/frontend/yarn.lock
Labels: user interface, refactor, Platform UI

#7368 Add new "available" badge to stock page
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: Platform UI

#7369 [PUI] Update mantine components
  src/frontend/yarn.lock
Labels: dependency, Platform UI

#7157 Query count test
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/unit_test.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/build/test_api.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/common/tests.py
  src/backend/InvenTree/order/test_api.py
  src/backend/InvenTree/part/test_api.py
  src/backend/InvenTree/plugin/base/barcodes/test_barcode.py
  src/backend/InvenTree/plugin/base/event/events.py
  src/backend/InvenTree/plugin/base/integration/ScheduleMixin.py
  src/backend/InvenTree/plugin/builtin/barcodes/test_inventree_barcode.py
  src/backend/InvenTree/plugin/builtin/suppliers/test_supplier_barcodes.py
  src/backend/InvenTree/plugin/registry.py
  src/backend/InvenTree/plugin/templatetags/plugin_extras.py
  src/backend/InvenTree/plugin/test_api.py
  src/backend/InvenTree/plugin/urls.py
  src/backend/InvenTree/report/migrations/0026_auto_20240422_1301.py
  src/backend/InvenTree/report/tests.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/test_api.py
  src/backend/InvenTree/users/models.py
Labels: api, CI

#7367 PO shipped complete
  docs/docs/build/build.md
  docs/docs/order/purchase_order.md
  docs/docs/order/return_order.md
  docs/docs/order/sales_order.md
  docs/docs/stock/status.md
  src/backend/InvenTree/InvenTree/status_codes.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/build/status_codes.py
  src/backend/InvenTree/build/tasks.py
  src/backend/InvenTree/build/test_api.py
  src/backend/InvenTree/build/tests.py
  src/backend/InvenTree/build/views.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/company/models.py
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/order/migrations/0055_auto_20211025_0645.py
  src/backend/InvenTree/order/migrations/0058_auto_20211126_1210.py
  src/backend/InvenTree/order/migrations/0096_alter_returnorderlineitem_outcome.py
  src/backend/InvenTree/order/migrations/0099_alter_salesorder_status.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/order/status_codes.py
  src/backend/InvenTree/order/tasks.py
  src/backend/InvenTree/order/test_api.py
  src/backend/InvenTree/order/test_migrations.py
  src/backend/InvenTree/order/tests.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/filters.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/part/test_api.py
  src/backend/InvenTree/part/test_pricing.py
  src/backend/InvenTree/plugin/base/barcodes/serializers.py
  src/backend/InvenTree/plugin/samples/integration/transition.py
  src/backend/InvenTree/stock/api.py
  src/backend/InvenTree/stock/migrations/0061_auto_20210511_0911.py
  src/backend/InvenTree/stock/migrations/0096_auto_20230330_1121.py
  src/backend/InvenTree/stock/migrations/0102_alter_stockitem_status.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/serializers.py
  src/backend/InvenTree/stock/status_codes.py
  src/backend/InvenTree/stock/test_api.py
  src/backend/InvenTree/stock/test_views.py
  src/backend/InvenTree/stock/tests.py
  src/backend/InvenTree/templates/InvenTree/settings/so.html
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
Labels: order

#7373 Catch edge case for merge_stock_items:
  src/backend/InvenTree/stock/models.py
Labels: bug, backport, backport-to-0.15.x

#7378 Update link for mobile app docs
  README.md
  src/backend/InvenTree/InvenTree/version.py
  src/frontend/src/defaults/links.tsx
Labels: documentation, backport, backport-to-0.15.x

#7379 Migration fix
  src/backend/InvenTree/report/migrations/0023_auto_20240421_0455.py
Labels: bug, setup, migration

#7380 Fix parameter dialog for parametericparttable
  src/frontend/src/tables/part/ParametricPartTable.tsx
Labels: user interface, Platform UI
