Repository inventree/InvenTree, pull requests merged in 2024-11, with the labels that each got.

#8403 Purchase Order Destination
  docs/docs/order/purchase_order.md
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/order/migrations/0102_purchaseorder_destination_and_more.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/order/templates/order/order_base.html
  src/backend/InvenTree/order/templates/order/purchase_order_detail.html
  src/backend/InvenTree/order/test_api.py
  src/backend/InvenTree/plugin/base/barcodes/api.py
  src/backend/InvenTree/plugin/test_api.py
  src/backend/InvenTree/templates/js/translated/purchase_order.js
  src/frontend/src/forms/PurchaseOrderForms.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/tests/pages/pui_purchase_order.spec.ts
  src/frontend/tests/pages/pui_sales_order.spec.ts
Labels: enhancement, order, api, migration

#8407 Re-render panels when context changes
  src/frontend/src/hooks/UsePluginPanels.tsx
Labels: user interface, plugin, Platform UI

#8408 More error logging during plugin loads
  src/backend/InvenTree/plugin/registry.py
Labels: plugin

#8411 Bug fix for plugin table
  src/frontend/src/tables/plugin/PluginListTable.tsx
Labels: bug, plugin, Platform UI

#8413 Offload initial email task
  src/backend/InvenTree/InvenTree/serializers.py
  src/backend/InvenTree/InvenTree/tasks.py
Labels: enhancement

#8417 [Bug] Build Output Create
  src/backend/InvenTree/build/models.py
Labels: bug, build

#8418 Remove unnecessary code
  src/backend/InvenTree/order/models.py
Labels: pricing, refactor

#8422 Fix for potential MissingKey error
  src/backend/InvenTree/stock/api.py
Labels: bug, backport, backport-to-0.16.x

#8419 Importer permissions
  src/backend/InvenTree/importer/api.py
  src/backend/InvenTree/importer/models.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/tests.py
  src/backend/InvenTree/users/models.py
  src/frontend/src/components/forms/fields/DateField.tsx
Labels: bug, import / export

#8423 PO receive fix
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/templates/js/translated/purchase_order.js
  src/frontend/src/forms/PurchaseOrderForms.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
Labels: bug, order

#8424 Add docs on running playwright tests
  docs/docs/develop/react-frontend.md
Labels: documentation

#8431 Improve optional chaining checks
  src/frontend/src/forms/PurchaseOrderForms.tsx
  src/frontend/src/forms/StockForms.tsx
Labels: bug, user interface, Platform UI

#8435 [PUI] Notification fix
  src/frontend/src/components/nav/NotificationDrawer.tsx
Labels: bug, user interface, Platform UI

#8434 [PUI] Updates for AdminButton
  src/backend/InvenTree/InvenTree/api.py
  src/frontend/playwright.config.ts
  src/frontend/src/components/buttons/AdminButton.tsx
  src/frontend/src/defaults/defaults.tsx
  src/frontend/src/states/states.tsx
  src/frontend/tests/pui_general.spec.ts
Labels: user interface, refactor, Platform UI

#8437 Enable ordering of BomList by 'reference'
  src/backend/InvenTree/part/api.py
Labels: enhancement, part, api

#8432 Cleanup modals
  src/frontend/src/components/modals/AboutInvenTreeModal.tsx
  src/frontend/src/components/modals/LicenseModal.tsx
  src/frontend/src/components/modals/ServerInfoModal.tsx
  src/frontend/tests/modals.spec.ts
  src/frontend/tests/pages/pui_scan.spec.ts
  src/frontend/tests/pui_command.spec.ts
  src/frontend/tests/pui_general.spec.ts
Labels: user interface, refactor, Platform UI

#8441 fix: Narrow scope of cleanup
  tasks.py
Labels: bug, setup, backport, backport-to-0.16.x

#8442 narrw scope of cleanup (#8441)
  tasks.py
Labels: bug, setup

#8440 Adjustments to default template file
  src/backend/InvenTree/config_template.yaml
Labels: setup

#8451 [PUI] Fix for stock item edit
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
Labels: bug, user interface, Platform UI

#8389 Remove coupling of tests to cui
  src/backend/InvenTree/InvenTree/middleware.py
  src/backend/InvenTree/InvenTree/test_middleware.py
  src/backend/InvenTree/InvenTree/tests.py
  src/backend/InvenTree/InvenTree/urls.py
  src/backend/InvenTree/build/tests.py
  src/backend/InvenTree/company/tests.py
  src/backend/InvenTree/order/tests.py
  src/backend/InvenTree/part/test_category.py
  src/backend/InvenTree/part/test_part.py
  src/backend/InvenTree/plugin/builtin/barcodes/test_inventree_barcode.py
  src/backend/InvenTree/stock/tests.py
  src/backend/InvenTree/users/tests.py
Labels: refactor

#8450 UI consolidation
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/part/PartSupplierDetail.tsx
  src/frontend/tests/pages/pui_part.spec.ts
Labels: user interface, Platform UI

#8445 Sales order improvements
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/order/migrations/0103_alter_salesorderallocation_shipment.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/order/test_api.py
  src/backend/InvenTree/stock/api.py
  src/backend/InvenTree/templates/js/translated/sales_order.js
  src/frontend/src/forms/SalesOrderForms.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/RowActions.tsx
  src/frontend/src/tables/bom/BomTable.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
  src/frontend/src/tables/part/PartTestTemplateTable.tsx
  src/frontend/src/tables/sales/SalesOrderAllocationTable.tsx
  src/frontend/src/tables/sales/SalesOrderLineItemTable.tsx
  src/frontend/src/tables/sales/SalesOrderShipmentTable.tsx
  src/frontend/src/tables/sales/SalesOrderTable.tsx
  src/frontend/tests/pages/pui_sales_order.spec.ts
  src/frontend/tests/pages/pui_scan.spec.ts
Labels: enhancement, order, user interface, api, migration, Platform UI

#8457 Add doc on external stock locations
  docs/docs/assets/images/stock/stock_external_icon.png
  docs/docs/stock/stock.md
Labels: documentation

#8454 Invoke error handling
  tasks.py
Labels: enhancement, setup

#8458 [PUI] Part allocations
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/order/api.py
  src/frontend/src/forms/BuildForms.tsx
  src/frontend/src/pages/part/PartAllocationPanel.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/RowExpansionIcon.tsx
  src/frontend/src/tables/bom/UsedInTable.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
  src/frontend/src/tables/part/PartBuildAllocationsTable.tsx
  src/frontend/src/tables/part/PartSalesAllocationsTable.tsx
  src/frontend/src/tables/sales/SalesOrderLineItemTable.tsx
  src/frontend/tests/pages/pui_build.spec.ts
  src/frontend/tests/pages/pui_part.spec.ts
Labels: enhancement, order, user interface, api, refactor, Platform UI

#8461 Remove unneeded AjaxView usage
  docs/extract_schema.py
  src/backend/InvenTree/InvenTree/api.py
  src/backend/InvenTree/InvenTree/api_version.py
Labels: api, refactor

#8462 Fix for useReturnOrderLineItemFields
  src/frontend/src/forms/ReturnOrderForms.tsx
Labels: bug, Platform UI

#8366 Add level indicators and path to stock location and part category dropdowns
  src/frontend/src/components/render/Part.tsx
  src/frontend/src/components/render/Stock.tsx
  src/frontend/tests/pages/pui_scan.spec.ts
  src/frontend/tests/pui_forms.spec.ts
Labels: enhancement, Platform UI

#8469 Improve null checks for SalesOrder.shipment
  src/backend/InvenTree/order/serializers.py
Labels: bug, order

#8471 More playwright docs
  docs/docs/develop/react-frontend.md
Labels: documentation

#8472 CUI: Fix for navbar logo
  src/backend/InvenTree/templates/navbar.html
Labels: user interface

#8467 [PUI] Page titles
  src/frontend/src/components/nav/PageDetail.tsx
  src/frontend/src/components/nav/PageTitle.tsx
  src/frontend/src/pages/Index/Home.tsx
  src/frontend/src/pages/Index/Scan.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/pages/Index/Settings/UserSettings.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/tests/login.ts
  src/frontend/tests/pages/pui_part.spec.ts
  src/frontend/tests/pages/pui_sales_order.spec.ts
  src/frontend/tests/pui_basic.spec.ts
  src/frontend/tests/pui_command.spec.ts
  src/frontend/tests/pui_forms.spec.ts
Labels: user interface, Platform UI

#8473 Fix for locate item plugins
  src/backend/InvenTree/plugin/base/locate/api.py
  src/backend/InvenTree/plugin/registry.py
  src/backend/InvenTree/plugin/samples/integration/test_scheduled_task.py
  src/backend/InvenTree/stock/api.py
  src/frontend/src/components/buttons/AdminButton.tsx
  src/frontend/src/components/items/ActionDropdown.tsx
  src/frontend/src/components/plugins/LocateItemButton.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/hooks/UsePlugins.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/company/ManufacturerPartDetail.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/settings/GroupTable.tsx
  src/frontend/tests/pui_plugins.spec.ts
Labels: bug, user interface, plugin, Platform UI

#8476 Additional output for invoke tasks
  tasks.py
Labels: setup

#8482 Format number
  docs/docs/extend/machines/overview.md
  docs/docs/report/helpers.md
  docs/docs/report/templates.md
  src/backend/InvenTree/InvenTree/helpers_model.py
  src/backend/InvenTree/report/templatetags/__init__.py
  src/backend/InvenTree/report/templatetags/report.py
  src/backend/InvenTree/report/tests.py
Labels: enhancement, report, documentation

#8477 Remove duplicate "locked" badge
  src/frontend/src/pages/part/PartDetail.tsx
Labels: user interface, Platform UI

#8013 Add row context (right click) additionally to actions in tables
  src/frontend/package.json
  src/frontend/src/contexts/ThemeContext.tsx
  src/frontend/src/main.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/yarn.lock
Labels: Platform UI

#8486 [Plugins] Pass queryClient through to plugin
  src/frontend/src/components/plugins/PluginContext.tsx
Labels: plugin, Platform UI

#8489 Update faq.md
  docs/docs/faq.md
Labels: documentation, backport, backport-to-0.16.x

#8480 Fix for "installed in" display
  docs/main.py
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/stock/api.py
  src/backend/InvenTree/stock/serializers.py
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/stock/StockTrackingTable.tsx
  src/frontend/tests/pages/pui_stock.spec.ts
Labels: bug, user interface, Platform UI

#8475 configurable ldap group classes
  .pre-commit-config.yaml
  docs/docs/start/advanced.md
  src/backend/InvenTree/InvenTree/helpers_mixin.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/tests.py
  src/backend/InvenTree/machine/machine_type.py
  src/backend/InvenTree/machine/models.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/part/views.py
  src/backend/InvenTree/plugin/samples/integration/label_sample.py
  src/backend/InvenTree/plugin/test_plugin.py
  src/backend/InvenTree/script/translation_stats.py
  src/backend/InvenTree/web/urls.py
  tasks.py
Labels: enhancement, setup

#8496 [PUI] Use ApiIcon for plugin panels
  src/frontend/src/components/items/ApiIcon.tsx
  src/frontend/src/hooks/UsePluginPanels.tsx
Labels: enhancement, user interface, plugin, Platform UI

#8497 Update UI plugin docs
  docs/docs/extend/plugins.md
  docs/docs/extend/plugins/ui.md
Labels: plugin, documentation

#8498 Small tweak to plugin staticfile collection output
  src/backend/InvenTree/plugin/staticfiles.py
Labels: plugin

#8499 Env var docs
  docs/docs/start/config.md
Labels: setup, documentation, backport, backport-to-0.16.x

#8501 Enable redis by default for docker setup
  contrib/container/.env
  contrib/container/docker-compose.yml
Labels: docker, setup

#8508 UI link fix
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/templatetags/inventree_extras.py
  src/backend/InvenTree/InvenTree/urls.py
  src/backend/InvenTree/templates/pui_banner.html
Labels: bug, user interface, backport, Platform UI, backport-to-0.16.x

#8487 [Refactor] Remove 'test statistics'
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/static/css/inventree.css
  src/backend/InvenTree/InvenTree/urls.py
  src/backend/InvenTree/build/templates/build/build_base.html
  src/backend/InvenTree/build/templates/build/detail.html
  src/backend/InvenTree/build/templates/build/sidebar.html
  src/backend/InvenTree/part/templates/part/detail.html
  src/backend/InvenTree/part/templates/part/part_sidebar.html
  src/backend/InvenTree/stock/api.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/serializers.py
  src/backend/InvenTree/stock/test_api.py
  src/backend/InvenTree/templates/js/translated/stock.js
  src/backend/InvenTree/templates/js/translated/table_filters.js
  src/backend/InvenTree/templates/test_statistics_table.html
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/tables/stock/TestStatisticsTable.tsx
Labels: user interface, plugin, breaking, refactor, Platform UI

#8516 github/workflows: fix missing dotfiles in frontend-build.zip
  .github/workflows/qc_checks.yaml
Labels: bug, CI, setup, backport, backport-to-0.16.x

#8520 Update react-frontend.md
  docs/docs/develop/react-frontend.md
Labels: documentation, Platform UI

#8522 Update tasks.py
  tasks.py
Labels: setup

#8524 Relation update
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/migrations/0131_partrelated_note.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/part/serializers.py
  src/frontend/src/tables/part/RelatedPartTable.tsx
Labels: part, api, Platform UI

#8526 Bump backend linting deps
  src/backend/package-lock.json
  src/backend/package.json
Labels: dependency, javascript

#8523 Improve plugin panels
  src/frontend/src/components/panels/PanelGroup.tsx
  src/frontend/src/hooks/UsePluginPanels.tsx
Labels: plugin, refactor, Platform UI

#8531 Better handling for undefined values in SettingsList
  src/frontend/src/components/settings/SettingList.tsx
Labels: Platform UI

#8503 Plugins installation improvements
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/tests.py
  src/backend/InvenTree/plugin/apps.py
  src/backend/InvenTree/plugin/helpers.py
  src/backend/InvenTree/plugin/installer.py
  src/backend/InvenTree/plugin/models.py
  src/backend/InvenTree/plugin/plugin.py
  src/backend/InvenTree/plugin/registry.py
Labels: enhancement, plugin, docker, setup, breaking

#8541 Add info on --skip-backup
  docs/docs/faq.md
Labels: setup, documentation, backport, backport-to-0.16.x

#8527 [PUI] SSO improvments
  src/backend/InvenTree/InvenTree/social_auth_urls.py
  src/backend/InvenTree/InvenTree/urls.py
  src/frontend/src/components/buttons/SSOButton.tsx
Labels: bug, security

#8544 API date filter updates
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/stock/api.py
  src/backend/InvenTree/templates/js/translated/table_filters.js
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/Filter.tsx
  src/frontend/src/tables/FilterSelectDrawer.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/tables/sales/SalesOrderTable.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
  src/frontend/tests/helpers.ts
  src/frontend/tests/pages/pui_build.spec.ts
  src/frontend/tests/pages/pui_dashboard.spec.ts
  src/frontend/tests/pages/pui_part.spec.ts
  src/frontend/tests/pages/pui_purchase_order.spec.ts
  src/frontend/tests/pages/pui_stock.spec.ts
  src/frontend/tests/pui_tables.spec.ts
Labels: enhancement, order, api, breaking, Platform UI

#8546 after_save_stock_item
  src/backend/InvenTree/stock/models.py
Labels: bug, stock, backport, backport-to-0.16.x

#8549 Additional playwright tests
  src/frontend/src/components/forms/AuthenticationForm.tsx
  src/frontend/tests/pui_basic.spec.ts
  src/frontend/tests/pui_login.spec.ts
Labels: CI, Platform UI

#8550 Add unit test
  src/backend/InvenTree/stock/tests.py
Labels: CI

#8561 Fix spelling of InvenTree in code base
  contrib/container/Caddyfile
  docs/docs/features.md
  docs/docs/order/company.md
  docs/docs/releases/0.7.0.md
  docs/docs/start/advanced.md
  docs/docs/start/installer.md
  docs/docs/start/intro.md
  docs/docs/start/processes.md
  src/backend/InvenTree/InvenTree/helpers_mixin.py
  src/backend/InvenTree/plugin/builtin/suppliers/digikey.py
  src/backend/InvenTree/plugin/builtin/suppliers/lcsc.py
  src/backend/InvenTree/plugin/builtin/suppliers/mouser.py
  src/backend/InvenTree/plugin/builtin/suppliers/tme.py
  src/frontend/src/defaults/actions.tsx
  src/frontend/src/defaults/links.tsx
  src/frontend/src/states/states.tsx
  src/frontend/tests/modals.spec.ts
  src/frontend/tests/pui_command.spec.ts
Labels: refactor

#8559 Bump backend deps
  contrib/container/requirements.txt
  contrib/dev_reqs/requirements.txt
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/requirements-dev.txt
  src/backend/requirements.txt
Labels: dependency, python

#8564 Add location when creating multiple serials
  src/backend/InvenTree/build/models.py
Labels: bug, build

#8563 Handle pre-rendering when classic frontend is disabled
  src/backend/InvenTree/InvenTree/management/commands/prerender.py
Labels: bug, setup

#8565 Set null location on stock item:
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/stock/models.py
Labels: bug, stock, breaking

#8547 Remove regex dependency
  src/backend/InvenTree/InvenTree/helpers.py
  src/backend/InvenTree/InvenTree/mixins.py
  src/backend/InvenTree/part/test_api.py
  src/backend/requirements.in
  src/backend/requirements.txt
Labels: dependency, refactor

#8560 Add new report filters for accessing database tables
  docs/docs/report/helpers.md
  src/backend/InvenTree/report/templatetags/report.py
Labels: enhancement, report

#8054 Add SelectionList concept
  docs/docs/part/parameter.md
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/common/api.py
  src/backend/InvenTree/common/migrations/0032_selectionlist_selectionlistentry_and_more.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/common/serializers.py
  src/backend/InvenTree/common/tests.py
  src/backend/InvenTree/part/migrations/0132_partparametertemplate_selectionlist.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/templates/js/translated/model_renderers.js
  src/backend/InvenTree/templates/js/translated/part.js
  src/backend/InvenTree/users/models.py
  src/frontend/playwright.config.ts
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/forms/fields/TableField.tsx
  src/frontend/src/components/render/Generic.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/render/ModelType.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/enums/ModelType.tsx
  src/frontend/src/forms/PartForms.tsx
  src/frontend/src/forms/selectionListFields.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/PartParameterPanel.tsx
  src/frontend/src/tables/part/PartParameterTemplateTable.tsx
  src/frontend/src/tables/part/SelectionListTable.tsx
  src/frontend/tests/settings/selectionList.spec.ts
Labels: enhancement, api, Platform UI, full-run

#8569 [PUI] Fix stock actions
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
  src/frontend/tests/pages/pui_stock.spec.ts
Labels: bug, Platform UI

#8571 Set status when returning from customer
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/common/tests.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/serializers.py
  src/frontend/src/forms/ReturnOrderForms.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/sales/ReturnOrderTable.tsx
Labels: enhancement, stock, api, Platform UI

#8574 Consumed filter
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/stock/api.py
  src/frontend/src/tables/stock/StockItemTable.tsx
Labels: api, Platform UI

#8570 Stock Transfer Improvements
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/serializers.py
  src/backend/InvenTree/stock/test_api.py
  src/backend/InvenTree/stock/tests.py
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/forms/fields/TableField.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/tests/helpers.ts
  src/frontend/tests/pages/pui_sales_order.spec.ts
  src/frontend/tests/pages/pui_stock.spec.ts
Labels: enhancement, stock, api, Platform UI

#8579 Add "stock" table to "category" page
  src/frontend/src/pages/part/CategoryDetail.tsx
Labels: Platform UI

#8580 Bug fix: record shipment date
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/test_api.py
Labels: bug, order, backport, backport-to-0.16.x

#8572 [PUI] Fix stock item state rendering
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: bug, Platform UI

#8587 [PUI] Hide "location" column in certain conditions
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
Labels: enhancement, stock, Platform UI

#8573 Event enum
  docs/docs/extend/plugins/event.md
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/unit_test.py
  src/backend/InvenTree/build/events.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/tasks.py
  src/backend/InvenTree/build/test_api.py
  src/backend/InvenTree/build/test_build.py
  src/backend/InvenTree/generic/events.py
  src/backend/InvenTree/order/events.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/tasks.py
  src/backend/InvenTree/order/test_api.py
  src/backend/InvenTree/part/events.py
  src/backend/InvenTree/plugin/base/event/events.py
  src/backend/InvenTree/plugin/events.py
  src/backend/InvenTree/plugin/models.py
  src/backend/InvenTree/plugin/registry.py
  src/backend/InvenTree/stock/events.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/users/authentication.py
Labels: enhancement, plugin, documentation, refactor

#8590 Return Order - Improvements
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/order/migrations/0104_alter_returnorderlineitem_quantity.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/order/test_api.py
  src/frontend/src/forms/ReturnOrderForms.tsx
  src/frontend/src/tables/sales/ReturnOrderLineItemTable.tsx
Labels: enhancement, order, api, Platform UI

#8591 [PUI] Barcode title
  src/frontend/src/components/items/ActionDropdown.tsx
  src/frontend/src/components/items/QRCode.tsx
Labels: Platform UI

#8598 Fix requirements.txt
  docs/mlc_config.json
  src/backend/InvenTree/build/test_api.py
  src/backend/requirements.txt
Labels: bug, dependency, setup

#8596 Allow settings value to be nullified
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/common/serializers.py
  src/frontend/src/components/settings/SettingList.tsx
Labels: enhancement, api

#8600 Fix for hasOwn
  src/frontend/src/functions/auth.tsx
Labels: bug, Platform UI
