Repository inventree/InvenTree, pull requests merged in 2024-03, with the labels that each got.

#6608 Adjust pkgr.yml
  .pkgr.yml
  contrib/packager.io/functions.sh
  contrib/packager.io/nginx.prod.conf
Labels: bug, dependency, installer

#6610 Fix devcontainer setup
  .devcontainer/docker-compose.yml
  .devcontainer/postCreateCommand.sh
Labels: bug, docker, setup

#6605 Details updates
  InvenTree/InvenTree/api_version.py
  InvenTree/company/serializers.py
  InvenTree/part/serializers.py
  InvenTree/stock/serializers.py
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/components/details/DetailsImage.tsx
  src/frontend/src/components/details/ItemDetails.tsx
  src/frontend/src/components/details/PartIcons.tsx
  src/frontend/src/components/render/StatusRenderer.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/functions/urls.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/ItemDetails.tsx
Labels: user interface, api, refactor, Platform UI

#6613 Plugin table fix
  src/frontend/src/tables/plugin/PluginListTable.tsx
Labels: bug, Platform UI

#6616 devcontainer volume permission fix
  .devcontainer/docker-compose.yml
Labels: bug, docker, setup

#6463 Render API docs
  .github/workflows/qc_checks.yaml
  .gitignore
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/settings.py
  InvenTree/machine/api.py
  docs/.gitignore
  docs/docs/api/api.md
  docs/docs/api/schema.md
  docs/docs/api/schema/auth.md
  docs/docs/api/schema/background-task.md
  docs/docs/api/schema/barcode.md
  docs/docs/api/schema/bom.md
  docs/docs/api/schema/build.md
  docs/docs/api/schema/company.md
  docs/docs/api/schema/general.md
  docs/docs/api/schema/label.md
  docs/docs/api/schema/machine.md
  docs/docs/api/schema/order.md
  docs/docs/api/schema/part.md
  docs/docs/api/schema/plugins.md
  docs/docs/api/schema/report.md
  docs/docs/api/schema/settings.md
  docs/docs/api/schema/stock.md
  docs/docs/api/schema/user.md
  docs/docs/concepts/units.md
  docs/docs/extend/plugins/tags.md
  docs/docs/part/create.md
  docs/docs/part/notification.md
  docs/docs/part/trackable.md
  docs/docs/releases/0.1.5.md
  docs/docs/releases/0.2.1.md
  docs/docs/releases/0.6.0.md
  docs/docs/stock/owner.md
  docs/docs/stylesheets/neoteroi-mkdocs.css
  docs/extract_schema.py
  docs/mkdocs.yml
  docs/requirements.txt
  readthedocs.yml
  tasks.py
Labels: enhancement, api, documentation

#6614 docker: push both multiple image tags
  .github/workflows/docker.yaml
Labels: bug, CI, docker

#6619 Run build completion in background
  InvenTree/build/models.py
  InvenTree/build/tasks.py
Labels: build

#6621 [Docker] Fix broken image
  .github/workflows/docker.yaml
  Dockerfile
  docker/install_build_packages.sh
  requirements.in
  requirements.txt
Labels: bug, CI, docker, setup, backport, backport-to-0.14.x

#6541 PUI Template editor
  InvenTree/InvenTree/api_version.py
  InvenTree/label/serializers.py
  InvenTree/report/serializers.py
  docs/docs/assets/images/report/template-editor.png
  docs/docs/assets/images/report/template-table.png
  docs/docs/report/template_editor.md
  docs/mkdocs.yml
  src/frontend/package.json
  src/frontend/src/components/buttons/SplitButton.tsx
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/components/details/PartIcons.tsx
  src/frontend/src/components/editors/TemplateEditor/CodeEditor/CodeEditor.tsx
  src/frontend/src/components/editors/TemplateEditor/CodeEditor/index.tsx
  src/frontend/src/components/editors/TemplateEditor/PdfPreview/PdfPreview.tsx
  src/frontend/src/components/editors/TemplateEditor/PdfPreview/index.tsx
  src/frontend/src/components/editors/TemplateEditor/TemplateEditor.tsx
  src/frontend/src/components/editors/TemplateEditor/index.tsx
  src/frontend/src/components/forms/StandaloneField.tsx
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
  src/frontend/src/components/items/ActionDropdown.tsx
  src/frontend/src/components/items/InfoItem.tsx
  src/frontend/src/components/nav/DetailDrawer.tsx
  src/frontend/src/components/nav/PanelGroup.tsx
  src/frontend/src/components/render/ModelType.tsx
  src/frontend/src/defaults/templates.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/TemplateManagementPanel.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/states/LocalState.tsx
  src/frontend/src/tables/machine/MachineListTable.tsx
  src/frontend/src/tables/machine/MachineTypeTable.tsx
  src/frontend/src/tables/settings/TemplateTable.tsx
  src/frontend/src/tables/settings/UserTable.tsx
  src/frontend/yarn.lock
Labels: enhancement, report, feature, Platform UI

#6652 Fix data migration
  InvenTree/part/migrations/0109_auto_20230517_1048.py
Labels: bug, backport, migration, backport-to-0.14.x

#6657 Fix for RelatedModelField
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
Labels: bug, Platform UI

#6662 Use whitenoise for static file handling
  InvenTree/InvenTree/settings.py
  InvenTree/config_template.yaml
  requirements.in
  requirements.txt
Labels: bug, dependency

#6675 Cache exception handling
  InvenTree/common/models.py
  InvenTree/common/settings.py
  InvenTree/users/models.py
Labels: bug

#6676 Fix typecasting in settings.py
  InvenTree/InvenTree/settings.py
Labels: bug, backport, backport-to-0.14.x

#6659 New Crowdin updates
  InvenTree/locale/de/LC_MESSAGES/django.po
  InvenTree/locale/el/LC_MESSAGES/django.po
  InvenTree/locale/es/LC_MESSAGES/django.po
  InvenTree/locale/pl/LC_MESSAGES/django.po
  InvenTree/locale/ru/LC_MESSAGES/django.po
  InvenTree/locale/tr/LC_MESSAGES/django.po
  src/frontend/src/locales/bg/messages.po
  src/frontend/src/locales/cs/messages.po
  src/frontend/src/locales/da/messages.po
  src/frontend/src/locales/de/messages.po
  src/frontend/src/locales/el/messages.po
  src/frontend/src/locales/es/messages.po
  src/frontend/src/locales/fa/messages.po
  src/frontend/src/locales/fi/messages.po
  src/frontend/src/locales/fr/messages.po
  src/frontend/src/locales/he/messages.po
  src/frontend/src/locales/hi/messages.po
  src/frontend/src/locales/hu/messages.po
  src/frontend/src/locales/it/messages.po
  src/frontend/src/locales/ja/messages.po
  src/frontend/src/locales/ko/messages.po
  src/frontend/src/locales/nl/messages.po
  src/frontend/src/locales/no/messages.po
  src/frontend/src/locales/pl/messages.po
  src/frontend/src/locales/pt/messages.po
  src/frontend/src/locales/ru/messages.po
  src/frontend/src/locales/sk/messages.po
  src/frontend/src/locales/sl/messages.po
  src/frontend/src/locales/sr/messages.po
  src/frontend/src/locales/sv/messages.po
  src/frontend/src/locales/th/messages.po
  src/frontend/src/locales/tr/messages.po
  src/frontend/src/locales/vi/messages.po
Labels: translation

#6685 Test key fix
  InvenTree/InvenTree/helpers.py
  InvenTree/part/models.py
  InvenTree/part/test_part.py
Labels: bug, backport, migration, backport-to-0.14.x

#6690 Caddy fix
  InvenTree/config_template.yaml
  docker/Caddyfile
Labels: docker, setup

#6691 Cleanup settings.py
  InvenTree/InvenTree/settings.py
Labels: refactor

#6692 ParametricPartTable Updates
  InvenTree/InvenTree/conversion.py
  src/frontend/src/tables/part/ParametricPartTable.tsx
Labels: Platform UI

#6694 Fix undefined tabValue (#6470)
  src/frontend/src/components/nav/Header.tsx
Labels: bug, Platform UI

#6698 Unit tests for HOST settings
  InvenTree/InvenTree/tests.py
Labels: CI

#6700 Update .env
  docker/.env
Labels: docker, setup

#6706 Report: Add date rendering
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/tests.py
  InvenTree/common/models.py
  InvenTree/report/api.py
  InvenTree/report/templates/report/inventree_bill_of_materials_report.html
  InvenTree/report/templates/report/inventree_build_order_base.html
  InvenTree/report/templates/report/inventree_order_report_base.html
  InvenTree/report/templates/report/inventree_slr_report.html
  InvenTree/report/templates/report/inventree_test_report_base.html
  InvenTree/report/templatetags/report.py
  InvenTree/report/tests.py
  InvenTree/templates/InvenTree/settings/report.html
  docs/docs/report/bom.md
  docs/docs/report/build.md
  docs/docs/report/helpers.md
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
Labels: enhancement, report

#6707 [PUI] Updates
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
Labels: Platform UI

#6709 handle report previewing errors
  src/frontend/src/components/editors/TemplateEditor/PdfPreview/PdfPreview.tsx
Labels: bug, report, Platform UI

#6712 Fix for caddyfile
  docker/Caddyfile
Labels: docker, setup

#6714 Report enhancements
  InvenTree/InvenTree/api_version.py
  InvenTree/report/api.py
  InvenTree/report/models.py
  InvenTree/report/serializers.py
  src/frontend/src/tables/settings/TemplateTable.tsx
Labels: bug, report, api

#6717 Reporting: Build line label fix
  InvenTree/report/templatetags/report.py
  docs/docs/report/report.md
  src/frontend/src/components/nav/DetailDrawer.tsx
  src/frontend/src/components/render/Build.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/render/ModelType.tsx
  src/frontend/src/enums/ModelType.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/TemplateManagementPanel.tsx
  src/frontend/src/tables/settings/TemplateTable.tsx
Labels: bug, report, Platform UI

#6718 [PUI] Details Pages
  src/frontend/src/components/buttons/ActionButton.tsx
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/pages/company/ManufacturerPartDetail.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/tables/purchasing/ManufacturerPartTable.tsx
Labels: Platform UI

#6719 Disable BOM requirement
  InvenTree/common/models.py
  InvenTree/stock/serializers.py
  InvenTree/stock/templates/stock/item.html
  InvenTree/templates/InvenTree/settings/stock.html
  InvenTree/templates/js/translated/stock.js
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/stock/InstalledItemsTable.tsx
Labels: stock

#6723 Update docker_install.md
  docs/docs/start/docker_install.md
Labels: documentation, backport, backport-to-0.14.x

#6726 Code Cleanup
  src/frontend/src/App.tsx
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/nav/Header.tsx
Labels: refactor, Platform UI

#6733 Worker thread fix
  Dockerfile
  InvenTree/plugin/apps.py
Labels: bug, plugin, backport, backport-to-0.14.x

#6731 Site access updates
  .devcontainer/docker-compose.yml
  .github/workflows/qc_checks.yaml
  .github/workflows/translations.yml
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/settings.py
  InvenTree/InvenTree/tests.py
  InvenTree/common/tests.py
  InvenTree/part/test_part.py
  docs/docs/start/config.md
Labels: setup, backport, backport-to-0.14.x

#6739 Fix CSS for long details field
  src/frontend/src/components/details/Details.tsx
Labels: bug, Platform UI

#6738 Site access tweaks
  .github/workflows/docker.yaml
  .github/workflows/qc_checks.yaml
  InvenTree/InvenTree/api_version.py
  InvenTree/InvenTree/settings.py
Labels: bug

#6740 Test result table fix
  InvenTree/common/models.py
  InvenTree/stock/serializers.py
  InvenTree/stock/templates/stock/item.html
  InvenTree/templates/InvenTree/settings/stock.html
  InvenTree/templates/js/translated/stock.js
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
Labels: bug, user interface

#6742 Typo fix
  InvenTree/common/models.py
Labels: bug

#6741 Error handling fix
  InvenTree/InvenTree/serializers.py
Labels: bug, backport, backport-to-0.14.x

#6746 Add ability to test event triggers
  InvenTree/InvenTree/settings.py
  InvenTree/plugin/base/event/events.py
Labels: CI

#6747 Test result table
  src/frontend/src/tables/FilterSelectDrawer.tsx
  src/frontend/src/tables/stock/StockItemTestResultTable.tsx
Labels: Platform UI

#6749 Add Latvian language support
  InvenTree/InvenTree/locales.py
  InvenTree/locale/lv/LC_MESSAGES/django.po
  src/frontend/.linguirc
  src/frontend/src/contexts/LanguageContext.tsx
  src/frontend/src/locales/lv/messages.d.ts
  src/frontend/src/locales/lv/messages.po
Labels: enhancement

#6750 [PUI] Tweaks
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/part/ParametricPartTable.tsx
  src/frontend/src/tables/part/PartParameterTemplateTable.tsx
Labels: Platform UI

#6752 Name details
  src/frontend/src/pages/part/PartDetail.tsx
Labels: Platform UI

#6754 Fix PUI build workflow
  .github/workflows/qc_checks.yaml
  .github/workflows/release.yml
Labels: bug, CI, setup, backport, Platform UI, backport-to-0.14.x

#6757 Fix docs: Remove INVENTREE_BASE_URL
  docs/docs/start/config.md
Labels: documentation, backport, backport-to-0.14.x

#6758 [Backport] PUI build
  .github/workflows/qc_checks.yaml
  .github/workflows/release.yml
Labels: bug, setup, Platform UI

#6760 Parameter table editing
  src/frontend/src/hooks/UseTable.tsx
  src/frontend/src/tables/Column.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/part/ParametricPartTable.tsx
Labels: enhancement, Platform UI

#6763 [PUI] Parameter title
  src/frontend/src/pages/part/CategoryDetail.tsx
Labels: user interface, Platform UI

#6699 Make modal footer fixed (#6696)
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/tables/settings/UserTable.tsx
Labels: Platform UI

#6743 Details CSS tweaks (again)
  src/frontend/src/components/details/Details.tsx
Labels: Platform UI

#6764 [PUI] table fixes
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/components/items/AttachmentLink.tsx
  src/frontend/src/forms/AttachmentForms.tsx
  src/frontend/src/hooks/UseTable.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/bom/BomTable.tsx
  src/frontend/src/tables/bom/UsedInTable.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
  src/frontend/src/tables/company/AddressTable.tsx
  src/frontend/src/tables/company/CompanyTable.tsx
  src/frontend/src/tables/company/ContactTable.tsx
  src/frontend/src/tables/general/AttachmentTable.tsx
  src/frontend/src/tables/part/ParametricPartTable.tsx
  src/frontend/src/tables/part/PartCategoryTable.tsx
  src/frontend/src/tables/part/PartParameterTemplateTable.tsx
  src/frontend/src/tables/part/PartTable.tsx
  src/frontend/src/tables/part/PartTestTemplateTable.tsx
  src/frontend/src/tables/purchasing/ManufacturerPartTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/tables/purchasing/SupplierPartTable.tsx
  src/frontend/src/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/tables/sales/SalesOrderTable.tsx
  src/frontend/src/tables/settings/CustomUnitsTable.tsx
  src/frontend/src/tables/settings/ProjectCodeTable.tsx
  src/frontend/src/tables/stock/InstalledItemsTable.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
  src/frontend/src/tables/stock/StockLocationTable.tsx
Labels: Platform UI

#6765 [PUI] Enable "link" column for tables
  src/frontend/src/components/details/DetailsImage.tsx
  src/frontend/src/functions/events.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/RowActions.tsx
  src/frontend/src/tables/part/ParametricPartTable.tsx
  src/frontend/src/tables/part/PartTable.tsx
  src/frontend/src/tables/purchasing/ManufacturerPartTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/tables/purchasing/SupplierPartTable.tsx
Labels: Platform UI

#6766 Table row click fix
  src/frontend/src/tables/InvenTreeTable.tsx
Labels: bug, Platform UI

#6771 Tz docs
  docker.dev.env
  docs/docs/start/config.md
Labels: documentation

#6769 Add OSSF Scorecard
  .github/dependabot.yml
  .github/workflows/docker.yaml
  .github/workflows/qc_checks.yaml
  .github/workflows/scorecard.yml
  .github/workflows/stale.yml
  .pre-commit-config.yaml
  README.md
Labels: enhancement, CI, security

#6592 Run publish CI actions only on main repo
  .github/workflows/docker.yaml
  .github/workflows/qc_checks.yaml
Labels: CI

#6790 Python dependency bump
  .pre-commit-config.yaml
  requirements-dev.txt
  requirements.txt
Labels: dependency

#6579 Bump frontend dependencies
  .github/workflows/qc_checks.yaml
  .github/workflows/translations.yml
  .pre-commit-config.yaml
  src/frontend/package.json
  src/frontend/yarn.lock
Labels: dependency, javascript

#6814 Fix new manifest path
  InvenTree/web/templatetags/spa_helper.py
  InvenTree/web/tests.py
Labels: bug, Platform UI

#6815 Fix for registering scheduled tasks
  InvenTree/plugin/base/integration/ScheduleMixin.py
  InvenTree/plugin/plugin.py
Labels: bug, plugin, backport, backport-to-0.14.x

#6478 Move media operations to storages backend
  InvenTree/InvenTree/files.py
  InvenTree/InvenTree/helpers.py
  InvenTree/generic/templating/apps.py
  InvenTree/report/tests.py
Labels: setup, refactor

#6791 Fix for initial form data
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/functions/forms.tsx
Labels: bug, Platform UI

#6830 Allauth settings update
  InvenTree/InvenTree/settings.py
  docs/docs/start/config.md
Labels: dependency

#6827 Switch to offical uv action
  .pre-commit-config.yaml
Labels: dependency

#6836 Fix a few warnings in api generation
  InvenTree/InvenTree/api.py
  InvenTree/InvenTree/api_version.py
  InvenTree/common/serializers.py
  InvenTree/company/api.py
  InvenTree/order/api.py
  InvenTree/part/api.py
  InvenTree/plugin/api.py
  InvenTree/plugin/test_api.py
  InvenTree/stock/api.py
  InvenTree/web/urls.py
Labels: api

#6835 CI-Actions: Security fixes
  .github/actions/setup/action.yaml
  .github/workflows/backport.yml
  .github/workflows/check_translations.yaml
  .github/workflows/docker.yaml
  .github/workflows/qc_checks.yaml
  .github/workflows/release.yml
  .github/workflows/translations.yml
Labels: CI, security

#6812 Document security measures
  README.md
  docs/docs/security.md
  docs/mkdocs.yml
  docs/mlc_config.json
Labels: documentation

#6837 [CI] Bump upload to v4 to ensure schema-push still works
  .github/workflows/qc_checks.yaml
Labels: bug, CI

#6854 Platform tweaks
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/plugin/PluginListTable.tsx
Labels: Platform UI

#6865 Fix: add write permissions to translation workflow
  .github/workflows/translations.yml
Labels: bug, CI

#6866 Order responsible requirement
  InvenTree/build/models.py
  InvenTree/common/api.py
  InvenTree/common/models.py
  InvenTree/order/models.py
  InvenTree/order/test_api.py
  InvenTree/part/helpers.py
  InvenTree/part/test_api.py
  InvenTree/stock/test_api.py
  InvenTree/templates/InvenTree/settings/build.html
  InvenTree/templates/InvenTree/settings/po.html
  InvenTree/templates/InvenTree/settings/returns.html
  InvenTree/templates/InvenTree/settings/so.html
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
Labels: enhancement, order, build

#6867 Timestamp issues
  InvenTree/InvenTree/helpers.py
  InvenTree/InvenTree/settings.py
  InvenTree/build/models.py
  InvenTree/build/tasks.py
  InvenTree/common/models.py
  InvenTree/common/tasks.py
  InvenTree/company/models.py
  InvenTree/label/models.py
  InvenTree/order/models.py
  InvenTree/order/serializers.py
  InvenTree/part/models.py
  InvenTree/part/stocktake.py
  InvenTree/report/models.py
  InvenTree/stock/api.py
  InvenTree/stock/migrations/0109_add_additional_test_fields.py
  InvenTree/stock/migrations/0110_alter_stockitemtestresult_finished_datetime_and_more.py
  InvenTree/stock/models.py
  InvenTree/stock/serializers.py
  InvenTree/users/models.py
Labels: CI

#6868 [PUI] Small tweaks
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/pages/company/ManufacturerPartDetail.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/FilterSelectDrawer.tsx
Labels: bug, user interface, Platform UI

#6871 Remove port from ALLOWED_HOST entries
  InvenTree/InvenTree/settings.py
Labels: bug

#6873 Fix for broken migration
  InvenTree/stock/migrations/0109_add_additional_test_fields.py
Labels: bug, migration

#6872 Implement URL redirect for PUI
  src/frontend/src/components/forms/AuthenticationForm.tsx
  src/frontend/src/components/nav/Layout.tsx
  src/frontend/src/functions/auth.tsx
  src/frontend/src/pages/Auth/Logged-In.tsx
  src/frontend/src/pages/Auth/Login.tsx
  src/frontend/tests/ui_plattform.spec.ts
Labels: enhancement, user interface, Platform UI
