Repository inventree/InvenTree, pull requests merged in 2024-07, with the labels that each got.

#7544 [PUI] Update table filters
  src/frontend/src/tables/bom/BomTable.tsx
  src/frontend/src/tables/part/PartCategoryTable.tsx
  src/frontend/src/tables/part/PartTable.tsx
  src/frontend/src/tables/stock/StockLocationTable.tsx
Labels: user interface, Platform UI

#7547 Detect python version for installer
  contrib/packager.io/functions.sh
Labels: enhancement, setup, installer

#7548 Fix call to add_label_context
  src/backend/InvenTree/machine/machine_types/label_printer.py
  src/backend/InvenTree/report/models.py
Labels: bug

#7554 [PUI] Error pages
  src/frontend/src/components/errors/ClientError.tsx
  src/frontend/src/components/errors/GenericErrorPage.tsx
  src/frontend/src/components/errors/NotAuthenticated.tsx
  src/frontend/src/components/errors/NotFound.tsx
  src/frontend/src/components/errors/PermissionDenied.tsx
  src/frontend/src/components/errors/ServerError.tsx
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/nav/InstanceDetail.tsx
  src/frontend/src/hooks/UseInstance.tsx
  src/frontend/src/pages/ErrorPage.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/pages/NotFound.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/company/ManufacturerPartDetail.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/router.tsx
  src/frontend/tests/baseFixtures.ts
  src/frontend/tests/login.ts
  src/frontend/tests/pages/pui_part.spec.ts
  src/frontend/tests/pui_basic.spec.ts
  src/frontend/tests/pui_general.spec.ts
  src/frontend/tests/pui_settings.spec.ts
Labels: user interface, Platform UI

#7553 Display barcode text near qrcode
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/templates/InvenTree/settings/barcode.html
  src/backend/InvenTree/templates/js/translated/modals.js
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
Labels: enhancement, user interface, barcode

#7557 Fix 'symbol' field for CustomUnit
  src/backend/InvenTree/common/migrations/0027_alter_customunit_symbol.py
  src/backend/InvenTree/common/models.py
Labels: bug, migration

#7556 Fix SSO theme selection
  src/backend/InvenTree/InvenTree/templatetags/inventree_extras.py
  src/backend/InvenTree/InvenTree/views.py
  src/backend/InvenTree/common/migrations/0028_colortheme_user_obj.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/templates/InvenTree/settings/user_display.html
  src/backend/InvenTree/templates/account/base.html
  src/backend/InvenTree/templates/base.html
  src/backend/InvenTree/users/models.py
Labels: bug, user interface

#7555 Package is not checking for already existing installs
  contrib/packager.io/functions.sh
  contrib/packager.io/postinstall.sh
Labels: bug, setup, installer

#7560 [Build] Add extra validation options
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/tests.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/templates/InvenTree/settings/build.html
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
Labels: enhancement, build

#7561 [PUI] BOM table updates
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/serializers.py
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/bom/BomTable.tsx
Labels: user interface, Platform UI

#7545 [PUI] Fix saveNotes callback
  src/frontend/src/components/editors/NotesEditor.tsx
  src/frontend/tests/pages/pui_part.spec.ts
Labels: bug, user interface, CI, Platform UI

#7527 [Feature] Part lock
  docs/docs/build/build.md
  docs/docs/part/part.md
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/models.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/tests.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/migrations/0125_part_locked.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/part/test_bom_item.py
  src/backend/InvenTree/part/test_param.py
  src/backend/InvenTree/part/test_part.py
  src/backend/InvenTree/templates/InvenTree/settings/build.html
  src/backend/InvenTree/templates/js/translated/bom.js
  src/backend/InvenTree/templates/js/translated/label.js
  src/backend/InvenTree/templates/js/translated/part.js
  src/backend/InvenTree/templates/js/translated/table_filters.js
  src/frontend/src/components/details/PartIcons.tsx
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/forms/PartForms.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/bom/BomTable.tsx
  src/frontend/src/tables/part/PartParameterTable.tsx
  src/frontend/src/tables/part/PartTable.tsx
  src/frontend/tests/pages/pui_part.spec.ts
Labels: enhancement, part, api, migration

#7575 [PUI] Update part duplicate forms
  src/backend/InvenTree/part/serializers.py
  src/frontend/src/forms/PartForms.tsx
  src/frontend/src/pages/part/PartDetail.tsx
Labels: user interface, Platform UI

#7577 Disable 3.12 testing for now
  .github/workflows/qc_checks.yaml
Labels: CI

#7576 Fix schema version commit text
  .github/workflows/qc_checks.yaml
Labels: bug, CI

#7580 Add variable to stop creation of admin account
  contrib/packager.io/functions.sh
  contrib/packager.io/postinstall.sh
Labels: enhancement, installer

#7521 General backend deps bump
  src/backend/requirements-dev.txt
  src/backend/requirements.in
  src/backend/requirements.txt
Labels: dependency, python

#7586 BOM delete fix
  src/backend/InvenTree/InvenTree/api.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/models.py
Labels: bug, part

#7589 Use more pathlib instead of os
  tasks.py
Labels: refactor

#7587 Default location column
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/company/serializers.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/stock/serializers.py
  src/backend/InvenTree/templates/js/translated/part.js
  src/frontend/src/tables/part/PartTable.tsx
Labels: user interface, api, Platform UI

#7584 PUI form framework: dependent field
  src/frontend/src/components/buttons/PrintingActions.tsx
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/forms/fields/DependentField.tsx
  src/frontend/src/components/forms/fields/NestedObjectField.tsx
  src/frontend/src/functions/forms.tsx
  src/frontend/tests/pui_printing.spec.ts
Labels: enhancement, user interface, api, Platform UI

#7581 Add cleanup task
  .pkgr.yml
  contrib/packager.io/preinstall.sh
  tasks.py
Labels: setup, installer

#7591 Build Line Updates
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/templates/js/translated/build.js
  src/frontend/src/tables/build/BuildLineTable.tsx
Labels: enhancement, api, build

#7595 Move duplicate schema endpoint
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/common/api.py
Labels: bug, api

#7599 [Bug] Project code fix
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/order/test_api.py
Labels: bug, api

#7601 Parameter value bug
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/part/test_param.py
Labels: bug, backport, backport-to-0.15.x

#7598 Tweak checks for error messages
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/components/nav/InstanceDetail.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/pages/Index/Settings/UserSettings.tsx
  src/frontend/src/pages/part/PartDetail.tsx
Labels: bug, user interface, Platform UI

#7609 [PUI] Query cache improvements
  src/frontend/src/components/buttons/PrintingActions.tsx
  src/frontend/src/contexts/LanguageContext.tsx
  src/frontend/src/hooks/UseFilter.tsx
  src/frontend/src/hooks/UseGenerator.tsx
  src/frontend/src/pages/Auth/Logged-In.tsx
  src/frontend/src/states/states.tsx
Labels: user interface, refactor, Platform UI

#7610 Fix "Scan barcode" modal input
  src/backend/InvenTree/templates/js/translated/barcode.js
Labels: enhancement, user interface, barcode

#7616 [PUI] Fix line-break for "details" field
  src/frontend/src/components/details/Details.tsx
Labels: bug, user interface, Platform UI

#7618 [PUI] Add more columns
  src/frontend/src/tables/bom/BomTable.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
Labels: user interface, Platform UI

#7619 Add server-side annotation for "can_build"
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/serializers.py
  src/frontend/src/tables/bom/BomTable.tsx
Labels: user interface, api, Platform UI

#7617 [PUI] Add filters for parameteric part table
  src/frontend/src/components/buttons/YesNoButton.tsx
  src/frontend/src/tables/part/ParametricPartTable.tsx
Labels: user interface, Platform UI

#7614 Add debug option to the sheet printer plugin
  src/backend/InvenTree/plugin/builtin/labels/label_sheet.py
Labels: enhancement, plugin, report

#7611 [Feature] Build allocation export
  docs/docs/assets/images/build/allocated_stock_table.png
  docs/docs/build/build.md
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/build/templates/build/detail.html
  src/backend/InvenTree/build/templates/build/sidebar.html
  src/backend/InvenTree/templates/js/translated/build.js
  src/frontend/src/components/render/Build.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/render/ModelType.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/enums/ModelType.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/tables/build/BuildAllocatedStockTable.tsx
  src/frontend/tests/pages/pui_build.spec.ts
  src/frontend/tests/pages/pui_part.spec.ts
  src/frontend/tests/pui_stock.spec.ts
Labels: enhancement, user interface, api, build, Platform UI

#7620 Bump django to 4.2.14
  contrib/container/requirements.txt
  src/backend/requirements-dev.txt
  src/backend/requirements.txt
Labels: dependency, security, backport, backport-to-0.15.x

#7625 Correct tooltips
  src/backend/InvenTree/templates/js/translated/part.js
Labels: bug, user interface

#7626 Various small code quality cleanups
  src/backend/InvenTree/InvenTree/tracing.py
  src/backend/InvenTree/InvenTree/unit_test.py
  src/backend/InvenTree/common/forms.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/templates/js/dynamic/nav.js
  src/backend/InvenTree/templates/js/dynamic/permissions.js
  src/frontend/src/components/buttons/CopyButton.tsx
  src/frontend/src/tables/settings/GroupTable.tsx
Labels: refactor

#7627 Bump Django to fix various vulns
  contrib/container/requirements.txt
  src/backend/requirements-dev.txt
  src/backend/requirements.txt
Labels: dependency, security

#7629 Update part detail
  src/frontend/src/pages/part/PartDetail.tsx
Labels: user interface, Platform UI

#7585 Revision Improvements
  docs/docs/assets/images/part/part_create_revision.png
  docs/docs/assets/images/part/part_revision_b.png
  docs/docs/assets/images/part/part_revision_select.png
  docs/docs/assets/images/part/part_revision_settings.png
  docs/docs/part/revision.md
  docs/docs/part/views.md
  docs/mkdocs.yml
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/company/test_api.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/migrations/0126_part_revision_of.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/part/templates/part/part_base.html
  src/backend/InvenTree/part/test_part.py
  src/backend/InvenTree/stock/serializers.py
  src/backend/InvenTree/templates/InvenTree/settings/part.html
  src/backend/InvenTree/templates/js/translated/part.js
  src/frontend/src/App.tsx
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/components/details/PartIcons.tsx
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/items/ActionDropdown.tsx
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/components/nav/NotificationDrawer.tsx
  src/frontend/src/components/nav/SearchDrawer.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/render/Part.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/forms/PartForms.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/hooks/UseInstance.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/bom/BomTable.tsx
  src/frontend/src/tables/part/PartParameterTable.tsx
  src/frontend/src/tables/part/PartTable.tsx
  src/frontend/tests/baseFixtures.ts
  src/frontend/tests/pages/pui_part.spec.ts
Labels: enhancement, part

#6772 Fix machine request pickeling and settings
  docs/docs/extend/machines/overview.md
  src/backend/InvenTree/InvenTree/helpers_mixin.py
  src/backend/InvenTree/machine/apps.py
  src/backend/InvenTree/machine/machine_type.py
  src/backend/InvenTree/machine/machine_types/label_printer.py
  src/backend/InvenTree/machine/registry.py
  src/backend/InvenTree/machine/tests.py
  src/backend/InvenTree/plugin/builtin/labels/inventree_machine.py
  src/frontend/src/functions/forms.tsx
  src/frontend/src/main.tsx
  src/frontend/src/tables/machine/MachineListTable.tsx
Labels: bug, plugin, report

#7647 Add Estonian language support
  src/backend/InvenTree/InvenTree/locales.py
  src/backend/InvenTree/locale/et/LC_MESSAGES/django.po
  src/frontend/.linguirc
  src/frontend/src/contexts/LanguageContext.tsx
  src/frontend/src/locales/et/messages.d.ts
  src/frontend/src/locales/et/messages.po
Labels: enhancement, translation

#7636 Allocated stock table fix
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/stock/serializers.py
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/build/BuildAllocatedStockTable.tsx
  src/frontend/tests/pages/pui_build.spec.ts
Labels: bug, user interface, api, import / export, Platform UI

#7635 [PUI] Add BOM import tool
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/importer/migrations/0002_dataimportsession_field_overrides.py
  src/backend/InvenTree/importer/models.py
  src/backend/InvenTree/importer/serializers.py
  src/backend/InvenTree/importer/validators.py
  src/backend/InvenTree/part/serializers.py
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/forms/fields/TextField.tsx
  src/frontend/src/components/importer/ImportDataSelector.tsx
  src/frontend/src/components/importer/ImporterColumnSelector.tsx
  src/frontend/src/components/importer/ImporterDrawer.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/forms/ImporterForms.tsx
  src/frontend/src/hooks/UseImportSession.tsx
  src/frontend/src/hooks/UseInstance.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/bom/BomTable.tsx
  src/frontend/tests/pages/pui_part.spec.ts
Labels: enhancement, part, user interface, api, import / export, Platform UI

#7651 Fix small typo in docs
  docs/docs/develop/devcontainer.md
Labels: documentation

#7652 Add stock location type documentation
  docs/docs/stock/stock.md
Labels: stock, documentation

#7656 [PUI] Tweak purchase order line table
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
Labels: user interface, Platform UI

#7658 Fix location icon field
  src/frontend/src/forms/StockForms.tsx
Labels: bug, Platform UI

#7663 bump setuptools
  contrib/container/requirements.txt
  src/backend/requirements-dev.txt
  src/backend/requirements.txt
Labels: dependency, security

#7657 Logic fix for UI elements
  src/frontend/src/components/modals/ServerInfoModal.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/TaskManagementPanel.tsx
Labels: user interface, Platform UI

#7660 Added onInput event for fields in forms - fix for issue #7600
  src/backend/InvenTree/templates/js/translated/forms.js
  src/backend/InvenTree/templates/js/translated/purchase_order.js
Labels: bug, user interface, backport, backport-to-0.15.x

#7649 Adjust packaging at different stages
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/order/test_api.py
  src/backend/InvenTree/templates/js/translated/purchase_order.js
  src/backend/InvenTree/templates/js/translated/stock.js
  src/frontend/src/components/editors/NotesEditor.tsx
  src/frontend/src/components/forms/fields/TableField.tsx
  src/frontend/src/forms/PurchaseOrderForms.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
  src/frontend/tests/pages/pui_part.spec.ts
Labels: bug, order, user interface, api

#7668 Fix rendering bug with company image
  src/frontend/src/components/render/Instance.tsx
Labels: bug, Platform UI

#7667 Add notes to mp and sp
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/company/migrations/0071_manufacturerpart_notes_supplierpart_notes.py
  src/backend/InvenTree/company/models.py
  src/backend/InvenTree/company/serializers.py
  src/backend/InvenTree/company/templates/company/manufacturer_part.html
  src/backend/InvenTree/company/templates/company/manufacturer_part_sidebar.html
  src/backend/InvenTree/company/templates/company/supplier_part.html
  src/backend/InvenTree/company/templates/company/supplier_part_sidebar.html
  src/frontend/src/pages/company/ManufacturerPartDetail.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
Labels: enhancement

#7671 [PUI] PO line item import
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/importer/migrations/0003_dataimportsession_field_filters.py
  src/backend/InvenTree/importer/models.py
  src/backend/InvenTree/importer/serializers.py
  src/backend/InvenTree/order/serializers.py
  src/frontend/src/components/importer/ImportDataSelector.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/render/ModelType.tsx
  src/frontend/src/defaults/backendMappings.tsx
  src/frontend/src/enums/ModelType.tsx
  src/frontend/src/forms/ImporterForms.tsx
  src/frontend/src/hooks/UseImportSession.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/tables/bom/BomTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
Labels: api, import / export, Platform UI

#7672 [CUI] Non field errors
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/templates/js/translated/forms.js
Labels: user interface, javascript

#7644 Various SAST fixes
  src/backend/InvenTree/plugin/api.py
  src/backend/InvenTree/report/templatetags/barcode.py
  src/backend/InvenTree/templates/js/dynamic/nav.js
  src/frontend/src/components/editors/TemplateEditor/PdfPreview/PdfPreview.tsx
  src/frontend/src/forms/PartForms.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/functions/auth.tsx
  src/frontend/src/pages/Index/Playground.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/SecurityContent.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/part/pricing/PricingPanel.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/part/PartCategoryTable.tsx
  src/frontend/src/tables/part/PartCategoryTemplateTable.tsx
  src/frontend/src/tables/stock/StockLocationTable.tsx
Labels: refactor

#7002 [CI] Add nicer OpenAPI diffs
  .github/scripts/version_check.py
  .github/workflows/qc_checks.yaml
Labels: CI

#7606 Bump development deps
  .pre-commit-config.yaml
  contrib/container/requirements.txt
  contrib/dev_reqs/requirements.txt
  docs/requirements.txt
  src/backend/requirements-dev.txt
  src/backend/requirements.txt
Labels: dependency

#7673 [PUI] Tweaks
  src/frontend/src/forms/CompanyForms.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/pages/company/ManufacturerPartDetail.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/tests/pui_settings.spec.ts
Labels: user interface, Platform UI

#7676 Cast width / height to integer
  src/backend/InvenTree/report/templatetags/report.py
Labels: bug, report, backport, backport-to-0.15.x

#7678 Fix loading sequence for PUI form fields
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/forms/fields/ApiFormField.tsx
Labels: bug, user interface, Platform UI

#7655 Optimize PUI package delivery for package installs
  .github/workflows/qc_checks.yaml
  .github/workflows/release.yaml
  contrib/packager.io/before.sh
  tasks.py
Labels: setup, backport, installer, backport-to-0.15.x

#7680 Cui tree fix
  src/backend/InvenTree/templates/js/dynamic/nav.js
Labels: bug, user interface, javascript, backport, backport-to-0.15.x

#7686 Various small packaging fixes
  .pkgr.yml
  contrib/packager.io/before.sh
  contrib/packager.io/functions.sh
  contrib/packager.io/preinstall.sh
  src/backend/InvenTree/config_template.yaml
Labels: setup, installer

#7685 Small typescript cleanups
  src/frontend/src/components/DashboardItemProxy.tsx
  src/frontend/src/components/buttons/AdminButton.tsx
  src/frontend/src/components/buttons/PrintingActions.tsx
  src/frontend/src/components/details/DetailsImage.tsx
  src/frontend/src/components/errors/GenericErrorPage.tsx
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/forms/fields/TableField.tsx
  src/frontend/src/components/importer/ImporterImportProgress.tsx
  src/frontend/src/components/items/GettingStartedCarousel.tsx
  src/frontend/src/components/modals/QrCodeModal.tsx
  src/frontend/src/components/nav/NotificationDrawer.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/render/Part.tsx
  src/frontend/src/forms/BuildForms.tsx
  src/frontend/src/forms/PurchaseOrderForms.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/hooks/UseImportSession.tsx
  src/frontend/src/hooks/UseInstance.tsx
  src/frontend/src/pages/Auth/Logged-In.tsx
  src/frontend/src/pages/Auth/Logout.tsx
  src/frontend/src/pages/Index/Playground.tsx
  src/frontend/src/pages/Index/Scan.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/SecurityContent.tsx
  src/frontend/src/pages/Index/Settings/UserSettings.tsx
  src/frontend/src/pages/Notifications.tsx
  src/frontend/src/pages/build/BuildIndex.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/part/PartPricingPanel.tsx
  src/frontend/src/pages/part/pricing/BomPricingPanel.tsx
  src/frontend/src/pages/purchasing/PurchasingIndex.tsx
  src/frontend/src/pages/sales/SalesIndex.tsx
  src/frontend/src/tables/DownloadAction.tsx
  src/frontend/src/tables/UploadAction.tsx
  src/frontend/src/tables/general/AttachmentTable.tsx
  src/frontend/src/tables/part/PartThumbTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/tables/settings/ImportSessionTable.tsx
  src/frontend/src/tables/stock/InstalledItemsTable.tsx
  src/frontend/tests/login.ts
  src/frontend/tests/pui_basic.spec.ts
  src/frontend/tests/pui_general.spec.ts
  src/frontend/tests/pui_settings.spec.ts
Labels: Platform UI

#7692 [PUI] Tab permissions
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/defaults/links.tsx
  src/frontend/src/pages/build/BuildIndex.tsx
  src/frontend/src/pages/purchasing/PurchasingIndex.tsx
  src/frontend/src/pages/sales/SalesIndex.tsx
Labels: user interface, Platform UI

#7689 [PUI] form error fix
  src/frontend/package.json
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/forms/fields/ChoiceField.tsx
  src/frontend/src/components/forms/fields/TextField.tsx
  src/frontend/src/forms/PartForms.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/part/PartCategoryTable.tsx
  src/frontend/src/tables/stock/StockLocationTable.tsx
  src/frontend/tests/baseFixtures.ts
  src/frontend/tests/pages/pui_part.spec.ts
  src/frontend/tests/pages/pui_scan.spec.ts
  src/frontend/tests/pui_general.spec.ts
  src/frontend/tests/pui_settings.spec.ts
  src/frontend/tests/pui_tables.spec.ts
  src/frontend/yarn.lock
Labels: bug, user interface, refactor, Platform UI

#7698 Bump node to 20
  .github/workflows/qc_checks.yaml
  .github/workflows/translations.yaml
  docs/docs/develop/contributing.md
Labels: CI, dependency

#7699 Bump docker image alpine base from 3.18 to 3.20
  .devcontainer/docker-compose.yml
  contrib/container/Dockerfile
  contrib/container/dev-docker-compose.yml
  contrib/container/docker-compose.yml
  contrib/container/install_build_packages.sh
Labels: dependency, docker, breaking

#7700 cI: Test color theme again
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/common/tests.py
Labels: user interface, CI

#7648 Add barcode generation capabilities to plugins
  docs/docs/barcodes/internal.md
  docs/docs/extend/plugins/barcode.md
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/helpers.py
  src/backend/InvenTree/InvenTree/helpers_model.py
  src/backend/InvenTree/InvenTree/models.py
  src/backend/InvenTree/InvenTree/tests.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/templates/build/build_base.html
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/company/models.py
  src/backend/InvenTree/company/templates/company/supplier_part.html
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/templates/order/order_base.html
  src/backend/InvenTree/order/templates/order/return_order_base.html
  src/backend/InvenTree/order/templates/order/sales_order_base.html
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/part/templates/part/part_base.html
  src/backend/InvenTree/part/test_part.py
  src/backend/InvenTree/plugin/base/barcodes/api.py
  src/backend/InvenTree/plugin/base/barcodes/helper.py
  src/backend/InvenTree/plugin/base/barcodes/mixins.py
  src/backend/InvenTree/plugin/base/barcodes/serializers.py
  src/backend/InvenTree/plugin/base/barcodes/test_barcode.py
  src/backend/InvenTree/plugin/builtin/barcodes/inventree_barcode.py
  src/backend/InvenTree/plugin/builtin/barcodes/test_inventree_barcode.py
  src/backend/InvenTree/report/templatetags/barcode.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/templates/stock/item_base.html
  src/backend/InvenTree/stock/templates/stock/location.html
  src/backend/InvenTree/stock/tests.py
  src/backend/InvenTree/templates/InvenTree/settings/barcode.html
  src/frontend/package.json
  src/frontend/src/components/buttons/ButtonMenu.tsx
  src/frontend/src/components/buttons/CopyButton.tsx
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/components/editors/TemplateEditor/CodeEditor/CodeEditor.tsx
  src/frontend/src/components/items/ActionDropdown.tsx
  src/frontend/src/components/items/QRCode.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/yarn.lock
Labels: enhancement, barcode, plugin, report, api, feature

#7621 [PUI] Add permissions to groups
  src/backend/InvenTree/InvenTree/test_api.py
  src/backend/InvenTree/InvenTree/test_middleware.py
  src/backend/InvenTree/InvenTree/unit_test.py
  src/backend/InvenTree/company/test_api.py
  src/backend/InvenTree/order/test_api.py
  src/backend/InvenTree/part/test_api.py
  src/backend/InvenTree/users/api.py
  src/backend/InvenTree/users/migrations/0012_alter_ruleset_can_view.py
  src/backend/InvenTree/users/models.py
  src/backend/InvenTree/users/serializers.py
  src/backend/InvenTree/users/tests.py
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/components/render/ModelType.tsx
  src/frontend/src/components/render/User.tsx
  src/frontend/src/enums/ModelType.tsx
  src/frontend/src/tables/settings/GroupTable.tsx
Labels: enhancement, api, Platform UI

#7702 [PUI] Remember state of table sorting
  src/frontend/src/states/LocalState.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
Labels: user interface, Platform UI

#7703 Fix tooltip location for panel icon
  src/frontend/src/components/nav/PanelGroup.tsx
Labels: user interface, Platform UI

#7706 Update SSO.md
  docs/docs/settings/SSO.md
Labels: documentation

#7693 [FR] Add Tokens to PUI
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/users/api.py
  src/backend/InvenTree/users/serializers.py
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/SecurityContent.tsx
Labels: enhancement, Platform UI

#7734 Make libffi version more flexible
  .pkgr.yml
  contrib/install.sh
Labels: setup, backport, installer, backport-to-0.15.x

#7739 Backport Optimize PUI package delivery for package installs
  .github/workflows/qc_checks.yaml
  .github/workflows/release.yaml
  contrib/packager.io/before.sh
  tasks.py
Labels: setup, installer

#7730 try to fix tests
  src/backend/requirements-dev.txt
Labels: bug, full-run

#7563 Add substitute details to BOM export
  src/backend/InvenTree/part/admin.py
  src/backend/InvenTree/part/bom.py
  src/backend/InvenTree/part/test_bom_export.py
Labels: enhancement, import / export

#7741 [PUI] Add more barcode actions
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
Labels: user interface, barcode, Platform UI

#7740 Backport Docs code links
  docs/.gitignore
  docs/docs/develop/contributing.md
  docs/docs/extend/plugins.md
  docs/docs/extend/plugins/locate.md
  docs/docs/extend/plugins/urls.md
  docs/docs/extend/plugins/validation.md
  docs/docs/report/helpers.md
  docs/docs/security.md
  docs/docs/start/config.md
  docs/docs/start/docker_install.md
  docs/docs/start/install.md
  docs/docs/start/intro.md
  docs/main.py
Labels: documentation

#7756 Update ruff settings to new preference
  pyproject.toml
Labels: CI

#7745 Add detection of current commit / branch
  docs/main.py
Labels: CI, documentation

#7752 Add how to install custom packages to the docker image section
  docs/docs/start/docker_install.md
Labels: setup, documentation

#7763 Plugin static files
  src/backend/InvenTree/InvenTree/ready.py
  src/backend/InvenTree/plugin/staticfiles.py
  src/backend/InvenTree/plugin/templatetags/plugin_extras.py
Labels: plugin, breaking

#7764 Backport `plugin_static` template tag to 0.15.x
  src/backend/InvenTree/plugin/templatetags/plugin_extras.py
Labels: plugin

#7755 fix path to CI dependencies
  .github/dependabot.yml
Labels: CI

#7757 Add option to disable MFA
  docs/docs/start/config.md
  src/backend/InvenTree/InvenTree/forms.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/social_auth_urls.py
Labels: security, setup

#7760 Removed obsoleted version element from docker-compose examples
  .devcontainer/docker-compose.yml
  contrib/container/dev-docker-compose.yml
  contrib/container/docker-compose.yml
Labels: docker, setup

#7758 [PUI] Bug fix for API forms
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/tests/pages/pui_scan.spec.ts
  src/frontend/tests/pui_general.spec.ts
  src/frontend/tests/pui_stock.spec.ts
Labels: bug, user interface, Platform UI

#7775 Add extra fields to BOM export
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/part/serializers.py
Labels: api, import / export

#7776 Fix permissions for importing data
  src/backend/InvenTree/importer/api.py
Labels: bug, api
