Repository inventree/InvenTree, pull requests merged in 2025-05, with the labels that each got.

#9600 feat: add action to remove all pending tasks
  src/backend/InvenTree/InvenTree/api.py
  src/frontend/src/tables/settings/PendingTasksTable.tsx
Labels: enhancement, User Interface

#9575 Add highlightToday for date inputs
  src/frontend/src/components/forms/fields/DateField.tsx
Labels: User Interface

#9621 refactor(docs): better security linking and references for docs
  README.md
  SECURITY.md
  docs/docs/security.md
Labels: documentation

#9620 feat(docs): add stable links for external sites
  docs/main.py
  docs/mkdocs.yml
  docs/requirements.in
  docs/requirements.txt
Labels: documentation

#9638 Update config.md
  docs/docs/start/config.md
Labels: documentation, backport, backport-to-0.17.x

#9643 feat(backend): record contexts for coverage
  .github/workflows/qc_checks.yaml
  docs/docs/develop/contributing.md
  pyproject.toml
Labels: CI

#9642 fix generation / upload path
  .github/workflows/qc_checks.yaml
Labels: bug, CI

#9646 feat(docs): add admin center docs
  docs/docs/api/index.md
  docs/docs/concepts/custom_states.md
  docs/docs/part/parameter.md
  docs/docs/report/template_editor.md
  docs/docs/settings/admin.md
  docs/docs/settings/import.md
  docs/docs/start/config.md
Labels: setup, documentation

#9641 Add configurable page margins to label sheet plugin
  src/backend/InvenTree/plugin/builtin/labels/label_sheet.py
Labels: enhancement, plugin, report

#8913 chore: bump react to current major versions
  pyproject.toml
  src/backend/InvenTree/web/templates/web/index.html
  src/frontend/index.html
  src/frontend/lib/types/Forms.tsx
  src/frontend/src/components/Boundary.tsx
  src/frontend/src/components/buttons/CopyButton.tsx
  src/frontend/src/components/buttons/SSOButton.tsx
  src/frontend/src/components/buttons/StarredToggleButton.tsx
  src/frontend/src/components/dashboard/DashboardWidget.tsx
  src/frontend/src/components/editors/TemplateEditor/TemplateEditor.tsx
  src/frontend/src/components/items/DocTooltip.tsx
  src/frontend/src/components/items/LanguageToggle.tsx
  src/frontend/src/components/items/MenuLinks.tsx
  src/frontend/src/components/items/StylishText.tsx
  src/frontend/src/components/modals/AboutInvenTreeModal.tsx
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/components/nav/Layout.tsx
  src/frontend/src/contexts/LanguageContext.tsx
  src/frontend/src/contexts/ThemeContext.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/functions/loading.tsx
  src/frontend/src/hooks/UseCalendar.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/useConfirm.tsx
  src/frontend/tests/pui_printing.spec.ts
  src/frontend/tests/settings/selectionList.spec.ts
Labels: dependency, javascript

#9649 fix(backend): ensure deps are coupled
  contrib/container/requirements.in
  contrib/container/requirements.txt
  contrib/dev_reqs/requirements.in
  contrib/dev_reqs/requirements.txt
  docs/requirements.in
  docs/requirements.txt
  src/backend/requirements-dev.txt
  src/backend/requirements.txt
Labels: dependency

#9659 Update 0111_auto_20230521_1350.py
  src/backend/InvenTree/part/migrations/0111_auto_20230521_1350.py
Labels: bug, setup, backport, migration, full-run, backport-to-0.17.x

#9645 ci: more granular coverage flags
  codecov.yml
Labels: CI, full-run

#9685 Backport reqres token fix to 0.17.x
  src/backend/InvenTree/plugin/base/integration/test_mixins.py
  src/backend/InvenTree/plugin/samples/integration/api_caller.py
Labels: bug, CI, full-run

#9689 fix(frontend): make error code target more stable using sref
  docs/mkdocs.yml
  src/frontend/src/defaults/links.tsx
Labels: bug, documentation
