Repository inventree/InvenTree, pull requests merged in 2025-06, with the labels that each got.

#9723 Handle failed partial_rebuild
  src/backend/InvenTree/InvenTree/models.py
Labels: bug, backport, backport-to-0.17.x

#9728 Fix style
  src/backend/InvenTree/plugin/base/label/test_label_mixin.py
  src/backend/InvenTree/plugin/builtin/labels/label_sheet.py
Labels: bug

#9731 Add generic StringEnum class
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/generic/enums.py
  src/backend/InvenTree/generic/events.py
  src/backend/InvenTree/plugin/plugin.py
  src/backend/InvenTree/users/ruleset.py
Labels: refactor

#9655 feat(frontend): Improve barcode scanning text input on Platform UI.
  src/frontend/src/components/barcodes/BarcodeKeyboardInput.tsx
Labels: enhancement, barcode, User Interface

#9714 chore(backend): bump allauth version
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/requirements.txt
  src/frontend/lib/enums/ApiEndpoints.tsx
  src/frontend/lib/types/Auth.tsx
  src/frontend/src/functions/auth.tsx
  src/frontend/src/pages/Auth/MFA.tsx
Labels: security, dependencies

#9740 [plugin] Simplify checkPluginVersion
  src/frontend/lib/functions/Plugins.tsx
  src/frontend/package.json
Labels: plugin, refactor

#9745 Add barcode to salesordershipment
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/order/migrations/0110_salesordershipment_barcode_data_and_more.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/serializers.py
Labels: barcode, api, migration

#9743 Rearrange UI menu
  src/frontend/src/components/nav/MainMenu.tsx
Labels: User Interface

#9746 Add barcode actions for SalesOrderShipment
  src/backend/InvenTree/InvenTree/tasks.py
  src/frontend/src/pages/sales/SalesOrderShipmentDetail.tsx
Labels: barcode, User Interface

#9748 chore(backend): remove constraints
  .pre-commit-config.yaml
  contrib/container/requirements.in
  contrib/container/requirements.txt
  contrib/dev_reqs/requirements.in
  contrib/dev_reqs/requirements.txt
  docs/requirements.in
  docs/requirements.txt
  src/backend/requirements-dev.txt
  src/backend/requirements.txt
Labels: CI, dependency

#9749 Param filters 2
  docs/docs/assets/images/part/filter_by_param.png
  docs/docs/assets/images/part/filter_with_unit.png
  docs/docs/assets/images/part/multiple_filters_same_param.png
  docs/docs/assets/images/part/remove_param_filter.png
  docs/docs/part/parameter.md
  src/backend/InvenTree/common/serializers.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/filters.py
  src/frontend/src/tables/part/ParametricPartTable.tsx
  src/frontend/src/tables/part/ParametricPartTableFilters.tsx
  src/frontend/tests/pages/pui_build.spec.ts
  src/frontend/tests/pages/pui_part.spec.ts
  src/frontend/tests/pui_login.spec.ts
Labels: enhancement, User Interface

#9753 chore: make issue template clearer
  .github/ISSUE_TEMPLATE/bug_report.yaml
  docs/mkdocs.yml
Labels: documentation

#9755 chore: bump tooling
  .pre-commit-config.yaml
Labels: dependencies

#9762 Table col fix
  src/frontend/package.json
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/build/BuildOrderTestTable.tsx
  src/frontend/tests/pages/pui_core.spec.ts
  src/frontend/yarn.lock
Labels: bug, User Interface

#9764 Part copy test
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/part/fixtures/part.yaml
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/part/test_api.py
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/tests/pages/pui_part.spec.ts
Labels: bug, api, User Interface

#9767 Fix for yarn.lock
  src/frontend/yarn.lock
Labels: dependency, User Interface

#9770 Fix error handling for template editor
  src/frontend/src/components/editors/TemplateEditor/PdfPreview/PdfPreview.tsx
Labels: bug, User Interface

#9775 feat(frontend): add edit-part function in part table
  src/frontend/src/tables/part/PartTable.tsx
Labels: enhancement, User Interface

#9574 [Plugin] Auto-create builds
  docs/docs/plugins/builtin/auto_create_builds.md
  docs/docs/plugins/builtin/auto_issue.md
  docs/docs/plugins/builtin/index.md
  docs/mkdocs.yml
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/build/tasks.py
  src/backend/InvenTree/build/test_api.py
  src/backend/InvenTree/plugin/builtin/events/auto_create_builds.py
Labels: enhancement, order, plugin, api, build, breaking

#9782 Documentation fix
  docs/docs/report/helpers.md
Labels: documentation

#9785 Add extra context to "invoke version"
  tasks.py
Labels: setup

#9792 Enhance docs for devcontainer / frontend development
  docs/docs/develop/react-frontend.md
Labels: documentation, User Interface

#9796 fix: docs build on stable release
  .github/workflows/release.yaml
Labels: bug, CI, documentation

#9400 Plugin Walkthrough
  docs/docs/assets/images/plugin/plugin_admin_interface.png
  docs/docs/assets/images/plugin/plugin_attachment_carousel.png
  docs/docs/assets/images/plugin/plugin_attachment_carousel_icon.png
  docs/docs/assets/images/plugin/plugin_attachment_carousel_icon_wrong.png
  docs/docs/assets/images/plugin/plugin_interface_integration.png
  docs/docs/assets/images/plugin/plugin_vite_dev_site.png
  docs/docs/assets/images/plugin/plugin_vite_mantine_carousel.png
  docs/docs/assets/images/plugin/plugin_vite_running.png
  docs/docs/assets/images/plugin/plugin_vscode_layout.png
  docs/docs/assets/images/plugin/plugin_wizard.png
  docs/docs/assets/images/plugin/plugin_wizard_items.png
  docs/docs/assets/images/plugin/plugin_wizard_mixins.png
  docs/docs/plugins/index.md
  docs/docs/plugins/walkthrough.md
  docs/mkdocs.yml
Labels: plugin, documentation

#9791 [UI] Query Improvements
  src/frontend/lib/types/Forms.tsx
  src/frontend/lib/types/Modals.tsx
  src/frontend/src/components/forms/fields/TableField.tsx
  src/frontend/src/forms/BuildForms.tsx
  src/frontend/src/forms/PurchaseOrderForms.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/hooks/UseForm.tsx
  src/frontend/src/hooks/UseGenerator.tsx
  src/frontend/src/hooks/UseModal.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/states/ModalState.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
  src/frontend/src/tables/sales/SalesOrderLineItemTable.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
Labels: bug, backport, User Interface, backport-to-0.17.x

#9799 [UI] Enhanced number formatting
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/components/items/ProgressBar.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: User Interface

#9798 [UI] Add "can build" part info
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/part/test_api.py
  src/frontend/lib/enums/ApiEndpoints.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/tests/pages/pui_part.spec.ts
Labels: part, api, breaking, User Interface

#9805 Bump UI version
  src/frontend/package.json
Labels: User Interface

#9602 feat: improve user/group management actions
  .github/workflows/qc_checks.yaml
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/users/api.py
  src/backend/InvenTree/users/serializers.py
  src/backend/InvenTree/users/test_api.py
  src/frontend/lib/enums/ApiEndpoints.tsx
  src/frontend/lib/types/Forms.tsx
  src/frontend/package.json
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/tables/settings/GroupTable.tsx
  src/frontend/src/tables/settings/UserTable.tsx
  src/frontend/tests/pui_permissions.spec.ts
  src/frontend/yarn.lock
Labels: enhancement, setup, User Interface

#9802 fix: package - various changes
  .github/workflows/qc_checks.yaml
  contrib/packager.io/functions.sh
  contrib/packager.io/postinstall.sh
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/version.py
  tasks.py
Labels: setup

#9816 Improve handling of plugin metadata reading
  src/backend/InvenTree/plugin/plugin.py
Labels: bug, plugin

#9811 [Breaking] Remove part scheduling feature
  docs/docs/part/scheduling.md
  docs/docs/part/views.md
  docs/docs/settings/user.md
  docs/mkdocs.yml
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/common/setting/user.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/part/test_api.py
  src/frontend/src/pages/Index/Settings/UserSettings.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/part/PartSchedulingDetail.tsx
  src/frontend/tests/pages/pui_part.spec.ts
Labels: plugin, api, breaking, feature, User Interface

#9818 Small UI improvement to SecurityContext
  src/frontend/src/pages/Index/Settings/AccountSettings/SecurityContent.tsx
  src/frontend/src/tables/plugin/PluginListTable.tsx
Labels: User Interface

#9817 Company reports
  docs/docs/report/context_variables.md
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/company/models.py
  src/backend/InvenTree/part/models.py
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/tables/company/CompanyTable.tsx
Labels: enhancement, report

#9819 Fix missing context items
  src/backend/InvenTree/InvenTree/models.py
  src/backend/InvenTree/company/models.py
Labels: bug, report

#9815 [0.17.x] feat: add cluster monitor task (#9812)
  src/backend/requirements.in
  src/backend/requirements.txt
  tasks.py
Labels: setup

#9826 [bug] Fixes for plugin loading mechanism
  src/backend/InvenTree/plugin/registry.py
  src/backend/InvenTree/plugin/serializers.py
  src/backend/InvenTree/users/apps.py
Labels: bug, plugin

#9828 refactor(docs): restructure barcode plugin section
  docs/docs/plugins/builtin/barcode_digikey.md
  docs/docs/plugins/builtin/barcode_index.md
  docs/docs/plugins/builtin/barcode_lcsc.md
  docs/docs/plugins/builtin/barcode_mouser.md
  docs/docs/plugins/builtin/barcode_tme.md
  docs/docs/plugins/builtin/index.md
  docs/mkdocs.yml
Labels: documentation

#9834 fix flags
  codecov.yml
Labels: CI

#9833 Plugin url fix
  src/backend/InvenTree/plugin/base/integration/UrlsMixin.py
  src/backend/InvenTree/plugin/base/integration/test_mixins.py
  src/backend/InvenTree/plugin/urls.py
Labels: plugin

#9839 Tweak plugin load error messages
  src/backend/InvenTree/plugin/registry.py
  src/backend/InvenTree/plugin/test_plugin.py
Labels: plugin

#9847 Prevent query returning undefined value
  src/frontend/src/hooks/UseGenerator.tsx
Labels: bug, User Interface

#9849 temp: lower targets
  codecov.yml
Labels: bug

#9769 refactor (backend): move config files out of the source directories
  .gitignore
  config/.gitignore
  config/README
  docs/docs/settings/error_codes.md
  src/backend/InvenTree/InvenTree/config.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/tests.py
  src/backend/InvenTree/common/setting/system.py
  src/backend/InvenTree/common/settings.py
  src/backend/InvenTree/common/tests.py
  src/backend/InvenTree/part/test_api.py
  src/backend/InvenTree/plugin/base/label/test_label_mixin.py
  src/backend/InvenTree/plugin/samples/integration/label_sample.py
  src/backend/InvenTree/report/test_tags.py
Labels: setup

#9857 [API] Return stock item list when creating multiple items
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/stock/api.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/serializers.py
  src/backend/InvenTree/stock/test_api.py
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
Labels: stock, api

#8779 feat(PUI): Make header tabs links to simpilfy new tab behaviour
  src/frontend/lib/functions/Navigation.tsx
  src/frontend/src/components/buttons/AdminButton.tsx
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/components/nav/NavigationTree.tsx
  src/frontend/src/components/nav/SearchDrawer.tsx
  src/frontend/src/components/panels/PanelGroup.tsx
Labels: enhancement, User Interface

#9859 [UI] Description col tweaks
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/bom/UsedInTable.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
  src/frontend/src/tables/general/ExtraLineItemTable.tsx
  src/frontend/src/tables/machine/MachineTypeTable.tsx
  src/frontend/src/tables/part/SelectionListTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/tables/sales/ReturnOrderLineItemTable.tsx
  src/frontend/src/tables/sales/SalesOrderAllocationTable.tsx
  src/frontend/src/tables/sales/SalesOrderLineItemTable.tsx
  src/frontend/src/tables/settings/TemplateTable.tsx
  src/frontend/src/tables/stock/LocationTypesTable.tsx
  src/frontend/src/tables/stock/StockItemTestResultTable.tsx
Labels: User Interface

#9860 [bug] Fix for tracing init
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/tracing.py
Labels: bug, setup

#9858 [bug] Custom state fix
  src/backend/InvenTree/generic/states/states.py
  src/backend/InvenTree/stock/api.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/serializers.py
  src/backend/InvenTree/stock/test_views.py
Labels: bug, stock, api

#9863 Fix syntax again
  codecov.yml
Labels: bug, CI

#9864 fix(backend): change notification for INVE-W10
  src/backend/InvenTree/InvenTree/api.py
  src/backend/InvenTree/InvenTree/config.py
  src/backend/InvenTree/InvenTree/templatetags/inventree_extras.py
  src/backend/InvenTree/InvenTree/version.py
Labels: setup

#9865 Tweak for tracing setup
  src/backend/InvenTree/InvenTree/tracing.py
Labels: bug, setup

#9868 Table default cols
  src/frontend/lib/types/Tables.tsx
  src/frontend/src/hooks/UseTable.tsx
  src/frontend/src/tables/Column.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/bom/BomTable.tsx
  src/frontend/src/tables/bom/UsedInTable.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
  src/frontend/src/tables/part/ParametricPartTable.tsx
  src/frontend/src/tables/part/PartCategoryTable.tsx
  src/frontend/src/tables/part/PartParameterTable.tsx
  src/frontend/src/tables/part/PartTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/tables/purchasing/SupplierPartTable.tsx
  src/frontend/src/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/tables/sales/SalesOrderTable.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
  src/frontend/src/tables/stock/StockLocationTable.tsx
  src/frontend/tests/pages/pui_purchase_order.spec.ts
Labels: User Interface

#9876 Plugin install errors
  src/backend/InvenTree/InvenTree/auth_overrides.py
  src/backend/InvenTree/InvenTree/exceptions.py
  src/backend/InvenTree/InvenTree/tasks.py
  src/backend/InvenTree/InvenTree/tests.py
  src/backend/InvenTree/plugin/base/barcodes/api.py
  src/backend/InvenTree/plugin/base/barcodes/mixins.py
  src/backend/InvenTree/plugin/base/label/mixins.py
  src/backend/InvenTree/plugin/helpers.py
  src/backend/InvenTree/plugin/installer.py
  src/backend/InvenTree/plugin/registry.py
  src/backend/InvenTree/report/apps.py
  src/backend/InvenTree/report/models.py
Labels: plugin, setup

#9878 Prevent multiple fetch of settings stage
  src/frontend/lib/types/Settings.tsx
  src/frontend/src/components/settings/SettingList.tsx
  src/frontend/src/states/SettingsState.tsx
Labels: User Interface

#9882 [UI] Simplify dashboard items
  src/frontend/src/components/dashboard/widgets/QueryCountDashboardWidget.tsx
Labels: User Interface

#9881 Better handling of initial state fetching
  src/frontend/src/states/ApiState.tsx
  src/frontend/src/states/StatusState.tsx
  src/frontend/src/states/states.tsx
Labels: User Interface

#9886 [UI] Data table tweaks
  src/frontend/src/tables/InvenTreeTable.tsx
Labels: User Interface

#9887 [Bug] Report fix
  src/backend/InvenTree/InvenTree/middleware.py
  src/backend/InvenTree/InvenTree/templatetags/inventree_extras.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/data_exporter/mixins.py
  src/backend/InvenTree/plugin/base/label/mixins.py
  src/backend/InvenTree/plugin/builtin/labels/inventree_machine.py
  src/backend/InvenTree/plugin/builtin/labels/label_sheet.py
  src/backend/InvenTree/report/models.py
  src/backend/InvenTree/report/templates/report/inventree_purchase_order_report.html
  src/frontend/src/hooks/UseDataOutput.tsx
Labels: bug, report

#9893 Add title when creating child build
  src/backend/InvenTree/plugin/builtin/events/auto_create_builds.py
Labels: plugin, build

#9896 fix(frontend): Incorrect redirect to MFA set up
  src/frontend/src/states/states.tsx
Labels: bug, User Interface

#9900 Fix for invoke dev.translate task
  tasks.py
Labels: bug, setup, translation

#9894 [UI] Refactor useQuery hooks
  src/frontend/src/components/buttons/PrintingActions.tsx
  src/frontend/src/components/dashboard/DashboardLayout.tsx
  src/frontend/src/components/dashboard/widgets/QueryCountDashboardWidget.tsx
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/components/editors/NotesEditor.tsx
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
  src/frontend/src/components/modals/LicenseModal.tsx
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/components/nav/NavigationTree.tsx
  src/frontend/src/components/nav/NotificationDrawer.tsx
  src/frontend/src/components/nav/SearchDrawer.tsx
  src/frontend/src/components/render/Instance.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/functions/api.tsx
  src/frontend/src/functions/notifications.tsx
  src/frontend/src/hooks/UseCalendar.tsx
  src/frontend/src/hooks/UseDashboardItems.tsx
  src/frontend/src/hooks/UseDataExport.tsx
  src/frontend/src/hooks/UseFilter.tsx
  src/frontend/src/hooks/UseGenerator.tsx
  src/frontend/src/hooks/UsePluginPanels.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/build/BuildOrderTestTable.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
  src/frontend/src/tables/part/ParametricPartTable.tsx
  src/frontend/src/tables/part/PartThumbTable.tsx
  src/frontend/src/tables/stock/StockItemTestResultTable.tsx
Labels: bug, refactor, User Interface

#9902 [UI] Stored table state
  src/frontend/lib/types/Tables.tsx
  src/frontend/src/contexts/LanguageContext.tsx
  src/frontend/src/hooks/UseTable.tsx
  src/frontend/src/states/LocalState.tsx
  src/frontend/src/states/StoredTableState.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
Labels: refactor, User Interface

#9906 [UI] Build test results fix
  src/frontend/src/tables/build/BuildOrderTestTable.tsx
Labels: bug, User Interface

#9904 [UI] Dashboard Update
  src/frontend/src/components/dashboard/DashboardWidget.tsx
  src/frontend/tests/pages/pui_part.spec.ts
Labels: User Interface

#9909 Negative annotations
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/company/filters.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/part/filters.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/part/test_api.py
Labels: bug, api, refactor

#9895 [FR] Add proactive system check for site_url
  docs/docs/settings/error_codes.md
  src/backend/InvenTree/InvenTree/middleware.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/test_middleware.py
  src/backend/InvenTree/InvenTree/test_views.py
  src/backend/InvenTree/InvenTree/tests.py
  src/backend/InvenTree/InvenTree/unit_test.py
  src/backend/InvenTree/plugin/samples/integration/test_sample.py
  src/backend/InvenTree/plugin/test_api.py
  src/backend/InvenTree/templates/config_error.html
Labels: setup
