Repository inventree/InvenTree, pull requests merged in 2025-10, with the labels that each got.

#10439 [Report] Queryset ordering
  CHANGELOG.md
  docs/docs/report/helpers.md
  src/backend/InvenTree/report/templatetags/report.py
Labels: enhancement, report, documentation

#10447 fix(backend): move tests to api mocking to remove jitter in ci
  src/backend/InvenTree/plugin/base/integration/test_mixins.py
  src/backend/InvenTree/plugin/samples/integration/api_caller.py
  src/backend/InvenTree/plugin/samples/integration/test_api_caller.py
  src/backend/requirements-dev.in
  src/backend/requirements-dev.txt
Labels: CI, refactor

#10451 [ci] Bump required query time for testing
  src/backend/InvenTree/build/test_api.py
Labels: CI

#10438 Refactor API endpoint: Build (2/6)
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/mixins.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/build/fixtures/build_line.yaml
  src/backend/InvenTree/build/test_api.py
Labels: api, refactor

#10441 Refactor API endpoint: Part (3/6)
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/filters.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/test_api.py
Labels: api, refactor

#10478 rollback mysql CI change
  .github/workflows/qc_checks.yaml
Labels: bug, CI, full-run

#10462 fix: log ENV key as it needs to be set
  src/backend/InvenTree/InvenTree/settings.py
Labels: setup

#10444 Refactor API endpoint: Stock (5/6)
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/stock/api.py
  src/backend/InvenTree/stock/fixtures/stock.yaml
  src/backend/InvenTree/stock/test_api.py
  src/backend/InvenTree/stock/tests.py
Labels: api, refactor

#10464 chore(backend): improve error message in api tests
  src/backend/InvenTree/InvenTree/unit_test.py
  src/backend/InvenTree/build/test_api.py
Labels: CI

#10445 Refactor API endpoint: Order (6/6)
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/mixins.py
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/order/fixtures/sales_order.yaml
  src/backend/InvenTree/order/test_api.py
Labels: api, refactor, full-run

#10485 feat(ui/choice field): select old content on click, auto select first row
  src/frontend/src/components/forms/fields/ChoiceField.tsx
Labels: bug, backport, User Interface, backport-to-1.0.x

#10490 Tweak docker setup
  contrib/container/.env
Labels: docker, setup, backport, backport-to-1.0.x

#10492 Fix rendering for custom status values
  src/frontend/src/components/render/StatusRenderer.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
Labels: bug, backport, User Interface, backport-to-1.0.x

#10481 add duplicate part action to parts table
  src/frontend/src/tables/part/PartTable.tsx
Labels: User Interface

#10381 Machine properties and periodic ping
  CHANGELOG.md
  docs/docs/plugins/machines/overview.md
  docs/docs/settings/global.md
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/cache.py
  src/backend/InvenTree/common/setting/system.py
  src/backend/InvenTree/generic/states/tests.py
  src/backend/InvenTree/machine/__init__.py
  src/backend/InvenTree/machine/machine_type.py
  src/backend/InvenTree/machine/machine_types/label_printer.py
  src/backend/InvenTree/machine/registry.py
  src/backend/InvenTree/machine/serializers.py
  src/backend/InvenTree/machine/tasks.py
  src/backend/InvenTree/machine/tests.py
  src/backend/InvenTree/plugin/machine/__init__.py
  src/backend/InvenTree/plugin/samples/machines/sample_printer.py
  src/frontend/src/pages/Index/Settings/AdminCenter/MachineManagementPanel.tsx
  src/frontend/src/tables/machine/MachineListTable.tsx
Labels: enhancement, plugin, report, full-run

#10495 refactor(backend): fix remaining undocumented path based serializer mutations
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/fields.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/part/api.py
Labels: api, refactor

#10501 [UI] Tweak dashboard filters
  src/frontend/src/components/dashboard/DashboardWidgetLibrary.tsx
Labels: User Interface

#10502 fix(backend): ensure internal notifications are created in a valid format
  src/backend/InvenTree/plugin/builtin/integration/core_notifications.py
Labels: bug, backport, backport-to-1.0.x

#10505 Update docs regarding `INVENTREE_AUTO_UPDATE`
  docs/docs/start/config.md
Labels: setup, documentation, backport, backport-to-1.0.x

#10512 chore(backend): fix missing ignore
  src/backend/InvenTree/InvenTree/sentry.py
  src/backend/InvenTree/InvenTree/settings.py
Labels: CI

#10517 [docs] BOM import
  docs/docs/manufacturing/bom.md
Labels: documentation, backport, backport-to-1.0.x

#10518 feat(backend): Improve error message on INVE-7
  src/backend/InvenTree/InvenTree/middleware.py
  src/backend/InvenTree/InvenTree/test_middleware.py
Labels: setup, backport, backport-to-1.0.x
