Repository inventree/InvenTree, pull requests merged in 2025-04, with the labels that each got.

#9434 Template Editor Improvements
  src/backend/InvenTree/plugin/samples/integration/user_interface_sample.py
  src/backend/InvenTree/plugin/samples/static/plugins/sampleui/sample_preview.js
  src/frontend/src/components/editors/TemplateEditor/CodeEditor/index.tsx
  src/frontend/src/components/editors/TemplateEditor/PdfPreview/index.tsx
  src/frontend/src/components/editors/TemplateEditor/TemplateEditor.tsx
  src/frontend/src/components/plugins/PluginUIFeature.tsx
  src/frontend/src/components/plugins/PluginUIFeatureTypes.ts
  src/frontend/src/hooks/UsePluginUIFeature.tsx
  src/frontend/src/tables/settings/TemplateTable.tsx
  src/frontend/tests/pui_printing.spec.ts
Labels: enhancement, plugin, report, User Interface

#9431 Typed report context
  docs/.gitignore
  docs/docs/report/context_variables.md
  docs/docs/settings/error_codes.md
  docs/main.py
  pyproject.toml
  src/backend/InvenTree/InvenTree/helpers_model.py
  src/backend/InvenTree/InvenTree/management/commands/export_report_context.py
  src/backend/InvenTree/InvenTree/models.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/plugin/base/barcodes/mixins.py
  src/backend/InvenTree/report/mixins.py
  src/backend/InvenTree/report/models.py
  src/backend/InvenTree/stock/models.py
  tasks.py
Labels: enhancement, report, documentation

#9441 Serialize stock fix
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/tests/pages/pui_stock.spec.ts
Labels: bug, backport, User Interface, backport-to-0.17.x

#9444 Update overdue order notification
  src/backend/InvenTree/order/tasks.py
Labels: order

#9446 Notify subscribed users
  src/backend/InvenTree/InvenTree/helpers_model.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/tasks.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/tasks.py
  src/backend/InvenTree/order/test_sales_order.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/templates/email/overdue_return_order.html
Labels: enhancement, order, build

#9447 Report cache fix
  src/backend/InvenTree/InvenTree/settings.py
  src/frontend/src/components/editors/TemplateEditor/TemplateEditor.tsx
Labels: bug, report, backport, User Interface, backport-to-0.17.x

#9442 refactor(frontend): seperate Alerts into own component
  docs/docs/settings/error_codes.md
  docs/docs/start/intro.md
  src/backend/InvenTree/InvenTree/helpers_email.py
  src/backend/InvenTree/InvenTree/status.py
  src/backend/InvenTree/InvenTree/test_tasks.py
  src/frontend/src/components/modals/ServerInfoModal.tsx
  src/frontend/src/components/nav/Alerts.tsx
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/defaults/links.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/TaskManagementPanel.tsx
Labels: setup, User Interface

#9428 fix(backend): enforce docstring args
  docs/main.py
  pyproject.toml
  src/backend/InvenTree/InvenTree/format.py
  src/backend/InvenTree/InvenTree/helpers.py
  src/backend/InvenTree/InvenTree/helpers_mixin.py
  src/backend/InvenTree/InvenTree/metadata.py
  src/backend/InvenTree/InvenTree/tracing.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/filters.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/plugin/base/barcodes/api.py
  src/backend/InvenTree/plugin/base/label/mixins.py
  src/backend/InvenTree/plugin/base/ui/mixins.py
  src/backend/InvenTree/plugin/registry.py
  src/backend/InvenTree/plugin/test_plugin.py
  src/backend/InvenTree/report/templatetags/barcode.py
  src/backend/InvenTree/report/templatetags/report.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/users/admin.py
  tasks.py
Labels: CI

#9451 fix: ci security issues
  .devcontainer/Dockerfile
  .github/actions/setup/action.yaml
  contrib/container/Dockerfile
Labels: CI, docker, security

#9393 User Setting To Search Notes
  docs/docs/settings/user.md
  src/backend/InvenTree/InvenTree/api.py
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/filters.py
  src/backend/InvenTree/InvenTree/test_api.py
  src/backend/InvenTree/common/setting/user.py
  src/frontend/src/components/nav/SearchDrawer.tsx
  src/frontend/src/pages/Index/Settings/UserSettings.tsx
Labels: enhancement, api

#9460 Fix icons API endpoint
  src/backend/InvenTree/common/api.py
Labels: bug, api, backport, backport-to-0.17.x

#9462 Handle potential null header
  src/backend/InvenTree/importer/operations.py
Labels: bug, import / export, backport, backport-to-0.17.x

#9449 Notification permissions
  src/backend/InvenTree/InvenTree/test_tasks.py
  src/backend/InvenTree/InvenTree/unit_test.py
  src/backend/InvenTree/common/notifications.py
  src/backend/InvenTree/common/tests.py
  src/backend/InvenTree/order/test_sales_order.py
  src/backend/InvenTree/order/tests.py
  src/backend/InvenTree/part/test_part.py
  src/backend/InvenTree/users/models.py
  src/frontend/src/components/buttons/StarredToggleButton.tsx
  src/frontend/tests/pui_plugins.spec.ts
Labels: bug, backport, backport-to-0.17.x

#9464 Notification permissions (#9449)
  src/backend/InvenTree/InvenTree/test_tasks.py
  src/backend/InvenTree/InvenTree/unit_test.py
  src/backend/InvenTree/common/notifications.py
  src/backend/InvenTree/common/tests.py
  src/backend/InvenTree/order/test_sales_order.py
  src/backend/InvenTree/order/tests.py
  src/backend/InvenTree/part/test_part.py
  src/backend/InvenTree/users/models.py
Labels: bug

#9465 [UI] Row hover
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/main.tsx
  src/frontend/src/styles/overrides.css
  src/frontend/src/tables/InvenTreeTable.tsx
Labels: enhancement, User Interface, backport-to-0.17.x

#9466 [UI] Row hover (#9465)
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/main.tsx
  src/frontend/src/styles/overrides.css
  src/frontend/src/tables/InvenTreeTable.tsx
Labels: User Interface

#9470 Cleanup tests
  src/frontend/playwright.config.ts
  src/frontend/tests/helpers.ts
  src/frontend/tests/pui_plugins.spec.ts
Labels: CI, User Interface

#9452 Schema: (Redo) Remove hardcoded enum values from customizable fields
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/serializers.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/generic/states/fields.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/stock/serializers.py
Labels: api, refactor

#9453 fix(backend): repair remaining schema generation errors
  .github/workflows/qc_checks.yaml
  .vscode/launch.json
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/schema.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/common/api.py
  src/backend/InvenTree/common/migrations/0038_alter_attachment_model_type.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/generic/states/api.py
  src/backend/InvenTree/importer/api.py
  src/backend/InvenTree/importer/migrations/0004_alter_dataimportsession_model_type.py
  src/backend/InvenTree/importer/models.py
  src/backend/InvenTree/plugin/api.py
  src/backend/InvenTree/plugin/serializers.py
  src/backend/InvenTree/report/migrations/0030_alter_labeltemplate_model_type_and_more.py
  src/backend/InvenTree/report/models.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/users/api.py
  src/backend/InvenTree/users/migrations/0015_alter_userprofile_type.py
  src/backend/InvenTree/users/models.py
Labels: api

#9479 feat(backend): test custom schema command
  src/backend/InvenTree/InvenTree/management/commands/schema.py
  src/backend/InvenTree/InvenTree/test_commands.py
Labels: CI

#9478 feat(backend): api schema stats
  src/backend/InvenTree/InvenTree/schema.py
  src/backend/InvenTree/InvenTree/settings.py
Labels: enhancement

#9484 Adjust layout of warning / error messages
  src/frontend/src/components/nav/Alerts.tsx
Labels: User Interface

#9488 refactor(backend): metadata endpoint
  src/backend/InvenTree/InvenTree/api.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/common/api.py
  src/backend/InvenTree/company/api.py
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/plugin/api.py
  src/backend/InvenTree/report/api.py
  src/backend/InvenTree/stock/api.py
Labels: CI, refactor

#9476 [Refactor] Users and Groups
  src/backend/InvenTree/InvenTree/api.py
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/metadata.py
  src/backend/InvenTree/InvenTree/permissions.py
  src/backend/InvenTree/InvenTree/test_api.py
  src/backend/InvenTree/InvenTree/test_tasks.py
  src/backend/InvenTree/common/api.py
  src/backend/InvenTree/common/notifications.py
  src/backend/InvenTree/common/serializers.py
  src/backend/InvenTree/company/test_api.py
  src/backend/InvenTree/importer/api.py
  src/backend/InvenTree/plugin/base/barcodes/api.py
  src/backend/InvenTree/users/admin.py
  src/backend/InvenTree/users/api.py
  src/backend/InvenTree/users/apps.py
  src/backend/InvenTree/users/migrations/0007_alter_ruleset_name.py
  src/backend/InvenTree/users/models.py
  src/backend/InvenTree/users/permissions.py
  src/backend/InvenTree/users/ruleset.py
  src/backend/InvenTree/users/serializers.py
  src/backend/InvenTree/users/tasks.py
  src/backend/InvenTree/users/test_api.py
  src/backend/InvenTree/users/tests.py
  src/frontend/src/components/items/RoleTable.tsx
  src/frontend/src/components/items/TransferList.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/enums/Roles.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/AccountDetailPanel.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/UserManagementPanel.tsx
  src/frontend/src/pages/core/CoreIndex.tsx
  src/frontend/src/pages/core/GroupDetail.tsx
  src/frontend/src/pages/core/UserDetail.tsx
  src/frontend/src/tables/core/UserTable.tsx
  src/frontend/src/tables/settings/GroupTable.tsx
  src/frontend/src/tables/settings/UserTable.tsx
  src/frontend/tests/pui_permissions.spec.ts
Labels: api, refactor, User Interface

#9493 Fix typo in docs
  docs/docs/concepts/pricing.md
Labels: bug, documentation, backport, backport-to-0.17.x

#9500 refactor(backend): Remove custom role admin
  src/backend/InvenTree/users/admin.py
Labels: CI, refactor

#9505 [UI] Serial Number Navigation
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/helpers.py
  src/backend/InvenTree/stock/api.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/serializers.py
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/functions/icons.tsx
  src/frontend/src/hooks/UseForm.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/tests/pages/pui_stock.spec.ts
Labels: enhancement, User Interface

#9509 Expose ports to outside network
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
Labels: setup

#9513 fix(ci): codecov upload
  .github/workflows/qc_checks.yaml
Labels: bug, CI

#9510 Revert port changes
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/postCreateCommand.sh
Labels: bug, setup

#9514 fix(ci): dependabot config
  .github/dependabot.yml
  src/frontend/package.json
  src/frontend/yarn.lock
Labels: CI, security

#9516 docs: add docs reagrding support the org receives
  docs/docs/project/resources.md
  docs/mkdocs.yml
Labels: documentation

#9519 Prevent duplicate call to "frontend compile"
  tasks.py
Labels: setup

#9520 [UI] Duplicate template action
  src/frontend/src/tables/settings/TemplateTable.tsx
Labels: User Interface

#9521 Edit BOM substitutes
  src/frontend/lib/enums/ApiEndpoints.tsx
  src/frontend/src/forms/BomForms.tsx
  src/frontend/src/tables/Column.tsx
  src/frontend/src/tables/bom/BomTable.tsx
  src/frontend/tests/pages/pui_part.spec.ts
Labels: User Interface

#9526 Fix for email sending
  .devcontainer/docker-compose.yml
  src/backend/InvenTree/InvenTree/helpers_email.py
  src/backend/InvenTree/InvenTree/tasks.py
Labels: bug

#9333 feat(backend): add oauth2
  .github/workflows/docker.yaml
  .gitignore
  .vscode/launch.json
  contrib/container/Dockerfile
  contrib/packager.io/functions.sh
  docs/docs/api/api.md
  docs/docs/settings/error_codes.md
  docs/docs/settings/experimental.md
  docs/docs/start/config.md
  docs/mkdocs.yml
  src/backend/InvenTree/InvenTree/api.py
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/config.py
  src/backend/InvenTree/InvenTree/management/commands/schema.py
  src/backend/InvenTree/InvenTree/metadata.py
  src/backend/InvenTree/InvenTree/middleware.py
  src/backend/InvenTree/InvenTree/permissions.py
  src/backend/InvenTree/InvenTree/schema.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/tasks.py
  src/backend/InvenTree/InvenTree/test_commands.py
  src/backend/InvenTree/InvenTree/urls.py
  src/backend/InvenTree/common/api.py
  src/backend/InvenTree/common/tests.py
  src/backend/InvenTree/config_template.yaml
  src/backend/InvenTree/generic/states/api.py
  src/backend/InvenTree/importer/api.py
  src/backend/InvenTree/machine/api.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/plugin/api.py
  src/backend/InvenTree/plugin/base/action/api.py
  src/backend/InvenTree/plugin/base/barcodes/api.py
  src/backend/InvenTree/plugin/base/locate/api.py
  src/backend/InvenTree/plugin/base/ui/api.py
  src/backend/InvenTree/report/api.py
  src/backend/InvenTree/stock/api.py
  src/backend/InvenTree/users/api.py
  src/backend/InvenTree/users/authentication.py
  src/backend/InvenTree/users/oauth2_scopes.py
  src/backend/InvenTree/users/ruleset.py
  src/backend/InvenTree/users/tests.py
  src/backend/requirements.in
  src/backend/requirements.txt
Labels: enhancement, security, experimental

#9527 feat(backend): clearer behaviour on missing migrations
  src/backend/InvenTree/InvenTree/apps.py
  src/backend/InvenTree/InvenTree/tasks.py
  src/backend/InvenTree/part/apps.py
  tasks.py
Labels: setup, backport-to-0.17.x

#9539 Fix for URL validation
  src/backend/InvenTree/InvenTree/fields.py
  src/backend/InvenTree/InvenTree/tests.py
  src/backend/InvenTree/InvenTree/validators.py
Labels: bug, backport, backport-to-0.17.x

#9533 refactor: fix task helper names
  tasks.py
Labels: refactor

#9283 feat: New / Refactor "Nav Mixin"
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/plugin/base/ui/mixins.py
  src/backend/InvenTree/plugin/base/ui/serializers.py
  src/backend/InvenTree/plugin/base/ui/tests.py
  src/backend/InvenTree/plugin/samples/integration/user_interface_sample.py
  src/frontend/src/components/calendar/OrderCalendar.tsx
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/components/plugins/PluginUIFeature.tsx
  src/frontend/src/components/plugins/PluginUIFeatureTypes.ts
Labels: enhancement, plugin, api, User Interface

#9542 Reduce notification check frequency
  src/frontend/src/components/nav/Header.tsx
Labels: User Interface

#9534 fix(backend): Better error handling for report template generation
  src/backend/InvenTree/report/apps.py
Labels: bug

#9541 [UI] Add CUI compatibility URLs
  src/backend/InvenTree/InvenTree/config.py
  src/backend/InvenTree/InvenTree/tests.py
  src/backend/InvenTree/InvenTree/urls.py
  src/backend/InvenTree/web/urls.py
Labels: User Interface

#9538 [UI] Barcode actions
  src/backend/InvenTree/InvenTree/models.py
  src/frontend/lib/functions/Navigation.tsx
  src/frontend/src/components/barcodes/BarcodeScanDialog.tsx
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/tests/pages/pui_stock.spec.ts
Labels: enhancement, barcode, api, User Interface

#9549 Display "default expiry" on part detail page
  src/frontend/src/pages/part/PartDetail.tsx
Labels: User Interface

#9548 Url fix 2
  src/backend/InvenTree/InvenTree/fields.py
  src/frontend/tests/pages/pui_part.spec.ts
Labels: bug, backport, backport-to-0.17.x

#9550 [Backport] URL fix
  src/backend/InvenTree/InvenTree/fields.py
Labels: bug, api

#9524 feat(docs): include docs in release
  .github/workflows/release.yaml
Labels: CI, backport-to-0.17.x

#9557 Update notification fetching
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/hooks/UseDataOutput.tsx
Labels: User Interface

#9559 Remove trailing slash from SITE_URL
  src/backend/InvenTree/InvenTree/settings.py
Labels: bug, setup, backport, backport-to-0.17.x

#9569 fix(docs): table formatting
  docs/docs/settings/experimental.md
Labels: bug, documentation

#9567 [FR] Save widget state per user
  src/frontend/src/components/dashboard/DashboardLayout.tsx
  src/frontend/src/components/dashboard/DashboardMenu.tsx
  src/frontend/src/functions/auth.tsx
  src/frontend/src/states/LocalState.tsx
  src/frontend/tests/login.ts
  src/frontend/tests/pages/pui_dashboard.spec.ts
Labels: enhancement, User Interface

#9577 chore: bump zustand
  src/frontend/package.json
  src/frontend/src/components/SplashScreen.tsx
  src/frontend/src/components/calendar/Calendar.tsx
  src/frontend/src/components/dashboard/DashboardLayout.tsx
  src/frontend/src/components/forms/AuthFormOptions.tsx
  src/frontend/src/components/forms/AuthenticationForm.tsx
  src/frontend/src/components/forms/InstanceOptions.tsx
  src/frontend/src/components/forms/fields/IconField.tsx
  src/frontend/src/components/items/ApiIcon.tsx
  src/frontend/src/components/items/LanguageSelect.tsx
  src/frontend/src/components/items/OnlyStaff.tsx
  src/frontend/src/components/modals/AboutInvenTreeModal.tsx
  src/frontend/src/components/modals/ServerInfoModal.tsx
  src/frontend/src/components/nav/Alerts.tsx
  src/frontend/src/components/nav/DetailDrawer.tsx
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/components/nav/MainMenu.tsx
  src/frontend/src/components/panels/PanelGroup.tsx
  src/frontend/src/components/plugins/PluginContext.tsx
  src/frontend/src/contexts/LanguageContext.tsx
  src/frontend/src/contexts/ThemeContext.tsx
  src/frontend/src/defaults/actions.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/pages/Auth/Login.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/AccountDetailPanel.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/SecurityContent.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/UserThemePanel.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/PluginManagementPanel.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/pages/Index/Settings/UserSettings.tsx
  src/frontend/src/tables/settings/UserTable.tsx
  src/frontend/src/views/DesktopAppView.tsx
  src/frontend/src/views/MainView.tsx
  src/frontend/src/views/MobileAppView.tsx
  src/frontend/yarn.lock
Labels: dependency

#9523 chore(frontend): bump dep resolution
  src/frontend/yarn.lock
Labels: dependency, security

#9587 fix(ci): Make translation step more robust
  .github/workflows/translations.yaml
Labels: bug, CI

#9581 bump docs deps
  docs/requirements.txt
Labels: dependency, security, backport, backport-to-0.17.x

#9568 docs: add conduct rules
  CODE_OF_CONDUCT.md
Labels: documentation
