Repository inventree/InvenTree, pull requests merged in 2025-02, with the labels that each got.

#8985 [CI] Playwright testing improvements
  src/frontend/tests/helpers.ts
  src/frontend/tests/login.ts
  src/frontend/tests/pages/pui_build.spec.ts
  src/frontend/tests/pages/pui_part.spec.ts
  src/frontend/tests/pages/pui_purchase_order.spec.ts
  src/frontend/tests/pages/pui_sales_order.spec.ts
  src/frontend/tests/pages/pui_scan.spec.ts
  src/frontend/tests/pages/pui_stock.spec.ts
  src/frontend/tests/pui_forms.spec.ts
  src/frontend/tests/pui_general.spec.ts
  src/frontend/tests/pui_login.spec.ts
  src/frontend/tests/pui_plugins.spec.ts
  src/frontend/tests/pui_printing.spec.ts
  src/frontend/tests/pui_settings.spec.ts
  src/frontend/tests/pui_tables.spec.ts
  src/frontend/tests/settings/selectionList.spec.ts
Labels: CI, refactor, User Interface

#9002 Report print update
  src/backend/InvenTree/plugin/base/integration/APICallMixin.py
  src/backend/InvenTree/plugin/base/integration/ReportMixin.py
  src/backend/InvenTree/plugin/base/integration/test_mixins.py
  src/backend/InvenTree/report/api.py
  src/backend/InvenTree/report/models.py
  src/backend/InvenTree/report/test_tags.py
  src/backend/InvenTree/report/tests.py
Labels: enhancement, report, backport, refactor, backport-to-0.17.x

#9005 Login form tweaks
  src/frontend/src/components/forms/AuthFormOptions.tsx
  src/frontend/src/components/forms/InstanceOptions.tsx
  src/frontend/src/components/items/ColorToggle.tsx
  src/frontend/src/components/items/LanguageToggle.tsx
  src/frontend/src/pages/Auth/Login.tsx
Labels: User Interface

#9003 [UI] Report ouputs
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/report/api.py
  src/backend/InvenTree/report/serializers.py
  src/frontend/src/pages/Index/Settings/AdminCenter/CurrencyManagementPanel.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/LabelTemplatePanel.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/ReportTemplatePanel.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/UnitManagementPanel.tsx
  src/frontend/src/tables/settings/TemplateTable.tsx
Labels: enhancement, report, User Interface

#9008 [Bug] mport fix
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/exceptions.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/common/serializers.py
  src/backend/InvenTree/importer/models.py
  src/backend/InvenTree/importer/operations.py
  src/backend/InvenTree/importer/serializers.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/report/migrations/0026_auto_20240422_1301.py
  src/backend/InvenTree/stock/serializers.py
Labels: bug, import / export, backport, refactor, backport-to-0.17.x

#9010 Tweak for data import
  src/backend/InvenTree/importer/models.py
Labels: bug, import / export

#9013 Report bugfix
  src/backend/InvenTree/report/apps.py
Labels: bug, report, backport, backport-to-0.17.x

#9012 Debounce `checkLoginState` (testing reliability)
  src/frontend/src/pages/Auth/Logged-In.tsx
Labels: bug, backport, refactor, User Interface, backport-to-0.17.x

#9017 Cleanup BomItemSerializer
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/serializers.py
Labels: api, refactor

#8970 [Pricing] Add option to convert received items currency
  .github/workflows/qc_checks.yaml
  .gitignore
  docs/docs/concepts/pricing.md
  docs/docs/hooks.py
  docs/docs/order/purchase_order.md
  docs/docs/part/pricing.md
  docs/docs/settings/currency.md
  docs/docs/settings/global.md
  docs/mkdocs.yml
  src/backend/InvenTree/InvenTree/config.py
  src/backend/InvenTree/InvenTree/exceptions.py
  src/backend/InvenTree/InvenTree/fields.py
  src/backend/InvenTree/InvenTree/filters.py
  src/backend/InvenTree/InvenTree/middleware.py
  src/backend/InvenTree/InvenTree/mixins.py
  src/backend/InvenTree/InvenTree/permissions.py
  src/backend/InvenTree/common/currency.py
  src/backend/InvenTree/common/setting/system.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/tests.py
  src/backend/InvenTree/report/apps.py
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/tests/pages/pui_build.spec.ts
  src/frontend/tests/pages/pui_part.spec.ts
  src/frontend/tests/pages/pui_sales_order.spec.ts
  src/frontend/tests/pui_printing.spec.ts
  src/frontend/tests/pui_settings.spec.ts
  tasks.py
Labels: enhancement, pricing, documentation

#9025 Extend plugin docs
  docs/docs/extend/plugins.md
Labels: plugin, documentation

#9028 Enhance creation of default settings
  src/backend/InvenTree/common/models.py
Labels: backport, refactor, backport-to-0.17.x

#9027 Tweak playwright tests
  src/frontend/tests/helpers.ts
  src/frontend/tests/pages/pui_sales_order.spec.ts
Labels: CI

#9032 chore(backend): Bump python deps
  contrib/container/requirements.txt
  src/backend/requirements-dev.txt
  src/backend/requirements.txt
Labels: dependency, python

#9033 feat(frontend): Hide empty args in about dialog
  src/frontend/src/components/modals/AboutInvenTreeModal.tsx
Labels: User Interface

#9035 chore(contrib): include pkg source in pkg logging
  contrib/packager.io/functions.sh
  src/backend/InvenTree/InvenTree/settings.py
Labels: setup

#9043 Adjust playwright testing
  src/frontend/tests/pages/pui_sales_order.spec.ts
Labels: CI, User Interface

#9042 [Backport] Update supported postgres-cli version to 15
  contrib/container/Dockerfile
  contrib/container/install_build_packages.sh
  docs/docs/start/docker.md
Labels: dependency, docker, setup

#9048 Fix typos in settings.py
  src/backend/InvenTree/InvenTree/settings.py
Labels: bug

#9049 [Setup] Enhance version information output
  src/backend/InvenTree/InvenTree/config.py
  tasks.py
Labels: setup

#8955 Update azure testing settings
  .devops/test_stats.yml
  README.md
  docs/mlc_config.json
Labels: CI

#9057 fix(contrib): ensure startup without django is possible
  src/backend/InvenTree/InvenTree/config.py
Labels: setup, refactor

#9056 fix(backend): determine active branch on startup
  docs/docs/settings/error_codes.md
  src/backend/InvenTree/InvenTree/version.py
Labels: bug, setup, documentation

#8027 [PUI] Make breadcrumbs adjustable
  src/backend/InvenTree/common/setting/user.py
  src/frontend/src/components/nav/PageDetail.tsx
  src/frontend/src/pages/Index/Settings/UserSettings.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/company/CustomerDetail.tsx
  src/frontend/src/pages/company/ManufacturerDetail.tsx
  src/frontend/src/pages/company/ManufacturerPartDetail.tsx
  src/frontend/src/pages/company/SupplierDetail.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: User Interface

#9055 chore(backend): bump deps
  src/backend/requirements-dev.txt
  src/backend/requirements.txt
Labels: dependency, python

#9060 Fix for data import
  src/backend/InvenTree/importer/models.py
  src/backend/InvenTree/importer/operations.py
Labels: bug, import / export, backport, backport-to-0.17.x

#9071 Bug fix for receiving line item event
  src/backend/InvenTree/order/models.py
Labels: bug, order, backport, backport-to-0.17.x

#9070 [UI] Settings to control editing of "completed" orders
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/tests.py
Labels: enhancement, order

#9075 [UI] Test Result Table Tweak
  src/frontend/src/tables/stock/StockItemTestResultTable.tsx
Labels: bug, User Interface

#9077 Adds "is_variant" filter for Part API
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/part/api.py
  src/frontend/src/tables/part/PartTable.tsx
Labels: enhancement, part, api

#9076 Setting filter
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/common/serializers.py
  src/frontend/src/components/settings/SettingList.tsx
  src/frontend/src/states/states.tsx
Labels: enhancement, plugin, api, User Interface

#9080 Fix dependabot version detection
  .github/dependabot.yml
  .python-version
  runtime.txt
Labels: bug

#9079 Remove dead code related to BOM import
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/models.py
  src/backend/InvenTree/InvenTree/serializers.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/bom.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/part/serializers.py
Labels: import / export, refactor

#9041 Docker postgres fix
  .devcontainer/Dockerfile
  .devcontainer/docker-compose.yml
  .devcontainer/postCreateCommand.sh
  contrib/container/Dockerfile
  contrib/container/docker-compose.yml
  contrib/container/install_build_packages.sh
  docs/docs/develop/devcontainer.md
  docs/docs/start/docker.md
  docs/mkdocs.yml
  tasks.py
Labels: CI, dependency, docker, setup, breaking

#9039 chore(backend): increase coverage
  src/backend/InvenTree/InvenTree/api.py
  src/backend/InvenTree/InvenTree/helpers.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/test_api.py
  src/backend/InvenTree/InvenTree/test_api_version.py
  src/backend/InvenTree/common/test_notifications.py
  src/backend/InvenTree/common/tests.py
  src/backend/InvenTree/part/test_api.py
  src/backend/InvenTree/plugin/registry.py
  src/backend/InvenTree/plugin/templatetags/plugin_extras.py
  src/backend/InvenTree/plugin/test_api.py
  src/backend/InvenTree/plugin/test_plugin.py
  src/backend/InvenTree/report/test_tags.py
  src/backend/InvenTree/users/test_api.py
Labels: CI

#9092 [dev] Devcontainer tweak
  .devcontainer/docker-compose.yml
  .devcontainer/postCreateCommand.sh
  .gitignore
  .pre-commit-config.yaml
  docs/docs/develop/devcontainer.md
Labels: setup

#9095 Remove 'is_ajax' helper
  src/backend/InvenTree/InvenTree/helpers.py
  src/backend/InvenTree/stock/api.py
Labels: refactor

#9094 PartThumbTable updates
  src/backend/InvenTree/part/api.py
  src/frontend/src/components/details/DetailsImage.tsx
  src/frontend/src/tables/part/PartThumbTable.tsx
Labels: enhancement, User Interface

#9088 chore(backend): bump devtools
  .pre-commit-config.yaml
  docs/docs/part/template.md
  docs/docs/report/templates.md
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/stock/models.py
Labels: dependency

#9087 feat(backend): Add instance id for linked data plugins
  src/backend/InvenTree/InvenTree/api.py
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/tests.py
  src/backend/InvenTree/InvenTree/version.py
  src/backend/InvenTree/common/setting/system.py
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
Labels: enhancement, api

#9101 Devcontainer updates
  .devcontainer/Dockerfile
  .devcontainer/docker-compose.yml
  docs/docs/develop/contributing.md
  docs/docs/develop/devcontainer.md
  docs/docs/develop/react-frontend.md
Labels: setup

#9103 Updates to admin interface
  src/backend/InvenTree/build/admin.py
  src/backend/InvenTree/order/admin.py
  src/backend/InvenTree/users/admin.py
Labels: refactor, User Interface

#9104 Use postgres for playwright testing
  .github/workflows/qc_checks.yaml
  src/frontend/playwright.config.ts
  src/frontend/tests/pui_settings.spec.ts
Labels: CI, refactor, full-run

#9117 Logic fix for label printing plugin
  src/backend/InvenTree/report/models.py
Labels: bug, plugin, report

#9118 [Docker] Alpine image fix
  .devcontainer/Dockerfile
  contrib/container/Dockerfile
  contrib/container/docker.dev.env
  contrib/container/install_build_packages.sh
  docs/docs/start/docker.md
  docs/mkdocs.yml
  src/backend/InvenTree/InvenTree/settings.py
Labels: bug, dependency, docker, full-run

#9119 [UI] Pricing chart fixes
  src/backend/InvenTree/InvenTree/serializers.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/stock/test_api.py
  src/frontend/src/pages/part/pricing/BomPricingPanel.tsx
  src/frontend/src/pages/part/pricing/PricingOverviewPanel.tsx
  src/frontend/src/pages/part/pricing/PurchaseHistoryPanel.tsx
  src/frontend/src/pages/part/pricing/SaleHistoryPanel.tsx
  src/frontend/src/pages/part/pricing/SupplierPricingPanel.tsx
  src/frontend/src/pages/part/pricing/VariantPricingPanel.tsx
  src/frontend/src/tables/purchasing/SupplierPriceBreakTable.tsx
Labels: bug, pricing, backport, User Interface, backport-to-0.17.x

#9124 [UI] Pricing fix backporty
  src/backend/InvenTree/InvenTree/serializers.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/stock/test_api.py
  src/frontend/src/pages/part/pricing/BomPricingPanel.tsx
  src/frontend/src/pages/part/pricing/PricingOverviewPanel.tsx
  src/frontend/src/pages/part/pricing/PurchaseHistoryPanel.tsx
  src/frontend/src/pages/part/pricing/SaleHistoryPanel.tsx
  src/frontend/src/pages/part/pricing/SupplierPricingPanel.tsx
  src/frontend/src/pages/part/pricing/VariantPricingPanel.tsx
  src/frontend/src/tables/purchasing/SupplierPriceBreakTable.tsx
Labels: bug, User Interface

#9125 [Pricing] BOM pricing calculation fix
  src/backend/InvenTree/part/models.py
Labels: bug, pricing, backport, backport-to-0.17.x

#9127 Barcode validation fix
  src/backend/InvenTree/plugin/base/barcodes/serializers.py
Labels: bug, order, barcode, backport, backport-to-0.17.x

#9123 Batch code fix
  src/frontend/src/components/render/StatusRenderer.tsx
  src/frontend/src/forms/PurchaseOrderForms.tsx
  src/frontend/tests/helpers.ts
  src/frontend/tests/pages/pui_purchase_order.spec.ts
Labels: bug, order, backport, User Interface, backport-to-0.17.x

#6293 Remove django-allauth-2fa, dj-rest-auth and django-user-sessions
  docs/docs/start/config.md
  src/backend/InvenTree/InvenTree/AllUserRequire2FAMiddleware.py
  src/backend/InvenTree/InvenTree/api.py
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/auth_override_views.py
  src/backend/InvenTree/InvenTree/auth_overrides.py
  src/backend/InvenTree/InvenTree/magic_login.py
  src/backend/InvenTree/InvenTree/management/commands/schema.py
  src/backend/InvenTree/InvenTree/middleware.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/social_auth_urls.py
  src/backend/InvenTree/InvenTree/static/css/inventree.css
  src/backend/InvenTree/InvenTree/test_auth.py
  src/backend/InvenTree/InvenTree/urls.py
  src/backend/InvenTree/config_template.yaml
  src/backend/InvenTree/generic/states/api.py
  src/backend/InvenTree/templates/403.html
  src/backend/InvenTree/templates/403_csrf.html
  src/backend/InvenTree/templates/404.html
  src/backend/InvenTree/templates/500.html
  src/backend/InvenTree/templates/503.html
  src/backend/InvenTree/templates/account/base.html
  src/backend/InvenTree/templates/skeleton.html
  src/backend/InvenTree/users/api.py
  src/backend/InvenTree/users/migrations/0013_migrate_mfa_20240408_1659.py
  src/backend/InvenTree/users/models.py
  src/backend/InvenTree/users/test_api.py
  src/backend/InvenTree/users/test_migrations.py
  src/backend/InvenTree/users/tests.py
  src/backend/InvenTree/web/urls.py
  src/backend/requirements.in
  src/backend/requirements.txt
  src/frontend/src/components/buttons/SSOButton.tsx
  src/frontend/src/components/forms/AuthenticationForm.tsx
  src/frontend/src/components/panels/PanelGroup.tsx
  src/frontend/src/defaults/defaults.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
  src/frontend/src/functions/auth.tsx
  src/frontend/src/pages/Auth/ChangePassword.tsx
  src/frontend/src/pages/Auth/Login.tsx
  src/frontend/src/pages/Auth/MFALogin.tsx
  src/frontend/src/pages/Auth/MFASetup.tsx
  src/frontend/src/pages/Auth/ResetPassword.tsx
  src/frontend/src/pages/Auth/VerifyEmail.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/QrRegistrationForm.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/SecurityContent.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/useConfirm.tsx
  src/frontend/src/router.tsx
  src/frontend/src/states/ApiState.tsx
  src/frontend/src/states/SettingsState.tsx
  src/frontend/src/states/states.tsx
  src/frontend/src/views/MainView.tsx
  src/frontend/tests/baseFixtures.ts
  src/frontend/tests/login.ts
  src/frontend/tests/pui_login.spec.ts
  tasks.py
Labels: dependency, security, setup, breaking, full-run

#9139 Handle undefined values
  src/frontend/src/components/render/StatusRenderer.tsx
Labels: bug, User Interface

#9138 Batch code backport
  src/frontend/src/components/render/StatusRenderer.tsx
  src/frontend/src/forms/PurchaseOrderForms.tsx
Labels: bug, User Interface

#9137 [UI] Search Improvements
  src/backend/InvenTree/InvenTree/api.py
  src/frontend/src/components/nav/SearchDrawer.tsx
  src/frontend/src/components/render/ModelType.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/purchasing/PurchasingIndex.tsx
  src/frontend/src/pages/sales/SalesIndex.tsx
  src/frontend/src/tables/InvenTreeTableHeader.tsx
  src/frontend/src/tables/Search.tsx
  src/frontend/src/tables/purchasing/SupplierPartTable.tsx
  src/frontend/tests/helpers.ts
  src/frontend/tests/pages/pui_company.spec.ts
  src/frontend/tests/pui_general.spec.ts
Labels: refactor, User Interface

#9140 UI cleanup
  src/frontend/src/components/SplashScreen.tsx
  src/frontend/src/functions/auth.tsx
  src/frontend/src/pages/Auth/ChangePassword.tsx
  src/frontend/src/pages/Auth/Login.tsx
  src/frontend/src/pages/Auth/MFALogin.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/SecurityContent.tsx
  src/frontend/tests/helpers.ts
  src/frontend/tests/pages/pui_build.spec.ts
  src/frontend/tests/pages/pui_company.spec.ts
  src/frontend/tests/pages/pui_part.spec.ts
  src/frontend/tests/pages/pui_purchase_order.spec.ts
  src/frontend/tests/pages/pui_sales_order.spec.ts
  src/frontend/tests/pages/pui_stock.spec.ts
  src/frontend/tests/pui_plugins.spec.ts
  src/frontend/tests/pui_printing.spec.ts
  src/frontend/tests/pui_settings.spec.ts
Labels: CI, refactor, User Interface

#9141 Harden playwright tests
  src/frontend/tests/helpers.ts
  src/frontend/tests/pages/pui_build.spec.ts
Labels: CI, refactor, User Interface

#9144 Update plugin docs
  docs/docs/extend/plugins/settings.md
Labels: plugin, documentation

#9145 [UI] Stock batch codes
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/forms/fields/TableField.tsx
  src/frontend/src/components/render/Stock.tsx
  src/frontend/src/forms/BuildForms.tsx
  src/frontend/src/forms/PurchaseOrderForms.tsx
  src/frontend/src/forms/ReturnOrderForms.tsx
  src/frontend/src/forms/SalesOrderForms.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/forms/selectionListFields.tsx
Labels: enhancement, stock, User Interface

#9146 [UI] Reduce test sensitivity
  src/frontend/tests/pages/pui_part.spec.ts
Labels: CI, User Interface

#9100 Use ref pattern on PO duplicate
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/tests/pages/pui_build.spec.ts
  src/frontend/tests/pages/pui_purchase_order.spec.ts
  src/frontend/tests/pages/pui_sales_order.spec.ts
Labels: bug, order, backport, User Interface, backport-to-0.17.x

#9148 [UI] Settings render
  docs/docs/extend/plugins/settings.md
  src/backend/InvenTree/plugin/samples/integration/sample.py
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/components/settings/SettingItem.tsx
  src/frontend/src/tables/Search.tsx
  src/frontend/tests/pui_plugins.spec.ts
Labels: CI, User Interface

#9151 [UI] Barcode scanner update
  src/frontend/src/components/barcodes/BarcodeInput.tsx
Labels: User Interface

#9149 Slight tweaks to forms
  src/frontend/src/components/buttons/RemoveRowButton.tsx
  src/frontend/src/forms/SalesOrderForms.tsx
Labels: refactor, User Interface

#9156 feat(contrib): Log docker and RTD
  tasks.py
Labels: setup

#9159 Fix CI pipelines
  tasks.py
Labels: bug, CI, full-run

#9158 Cleanup backend code
  src/backend/InvenTree/InvenTree/status.py
  src/backend/InvenTree/machine/tests.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/users/admin.py
  src/backend/InvenTree/users/models.py
Labels: refactor

#9150 Remove 'url' field from serializers
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/company/serializers.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/part/test_api.py
  src/backend/InvenTree/plugin/serializers.py
  src/backend/InvenTree/stock/serializers.py
  src/backend/InvenTree/stock/test_api.py
Labels: api, breaking, refactor

#9163 Dashboard item rendering fixes
  src/frontend/src/components/dashboard/widgets/QueryCountDashboardWidget.tsx
Labels: User Interface

#9168 Refactor API token display
  src/frontend/src/pages/Index/Settings/AccountSettings/SecurityContent.tsx
Labels: refactor, User Interface

#9121 refactor(frontend): Auth component refactor
  src/frontend/src/components/SplashScreen.tsx
  src/frontend/src/components/forms/AuthenticationForm.tsx
  src/frontend/src/components/forms/InstanceOptions.tsx
  src/frontend/src/components/items/LanguageToggle.tsx
  src/frontend/src/functions/auth.tsx
  src/frontend/src/pages/Auth/ChangePassword.tsx
  src/frontend/src/pages/Auth/Layout.tsx
  src/frontend/src/pages/Auth/LoggedIn.tsx
  src/frontend/src/pages/Auth/Login.tsx
  src/frontend/src/pages/Auth/Logout.tsx
  src/frontend/src/pages/Auth/MFA.tsx
  src/frontend/src/pages/Auth/MFALogin.tsx
  src/frontend/src/pages/Auth/MFASetup.tsx
  src/frontend/src/pages/Auth/Register.tsx
  src/frontend/src/pages/Auth/Reset.tsx
  src/frontend/src/pages/Auth/ResetPassword.tsx
  src/frontend/src/pages/Auth/VerifyEmail.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/SecurityContent.tsx
  src/frontend/src/router.tsx
  src/frontend/tests/pui_settings.spec.ts
Labels: refactor, User Interface

#9136 remove: need for hard coded token
  .github/workflows/qc_checks.yaml
  src/frontend/vite.config.ts
Labels: CI, full-run

#9176 Include plugin file location in "invoke version"
  tasks.py
Labels: setup

#9183 Handle case of null stock location
  src/frontend/src/forms/StockForms.tsx
Labels: bug, backport, User Interface, backport-to-0.17.x

#9185 Allow custom icons to be cleared
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/part/migrations/0133_alter_partcategory__icon.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/part/test_category.py
  src/backend/InvenTree/stock/migrations/0114_alter_stocklocation_custom_icon.py
  src/backend/InvenTree/stock/models.py
Labels: bug, migration

#9186 Add 'note' field to form
  src/frontend/src/tables/part/RelatedPartTable.tsx
Labels: bug, backport, User Interface, backport-to-0.17.x

#9194 Add loading indicator for custom panels
  src/frontend/src/components/panels/PanelGroup.tsx
  src/frontend/src/hooks/UsePluginPanels.tsx
Labels: User Interface

#9197 Add part full name to supplier part table
  src/frontend/src/tables/purchasing/SupplierPartTable.tsx
Labels: enhancement, User Interface

#9201 Remove restriction on row action
  src/frontend/src/tables/build/BuildLineTable.tsx
Labels: bug, backport, User Interface, backport-to-0.17.x
