Repository inventree/InvenTree, pull requests merged in 2025-01, with the labels that each got.

#8817 Docs remove old customize options
  docs/docs/start/config.md
Labels: documentation

#8816 Remove admin shell
  docs/docs/start/config.md
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/urls.py
  src/backend/requirements-dev.in
  src/backend/requirements-dev.txt
Labels: refactor

#8828 Remove old PanelMixin class
  src/backend/InvenTree/plugin/base/integration/PanelMixin.py
  src/backend/InvenTree/plugin/mixins/__init__.py
Labels: plugin, breaking, refactor

#8830 Fix for buggy Caddyfile
  contrib/container/Caddyfile
Labels: bug, docker, setup, backport, backport-to-0.17.x

#8831 Navigate to index when deleting a company
  src/frontend/src/pages/company/CompanyDetail.tsx
Labels: bug, backport, Platform UI, backport-to-0.17.x

#8836 fix: remove structlog from invoke internal paths
  src/backend/InvenTree/InvenTree/config.py
  src/backend/InvenTree/InvenTree/version.py
Labels: bug

#8835 Docker fix
  .github/workflows/docker.yaml
  contrib/container/Dockerfile
  contrib/container/init.sh
  docs/docs/develop/contributing.md
  docs/docs/develop/devcontainer.md
  docs/docs/faq.md
  docs/docs/start/install.md
  docs/docs/start/intro.md
  tasks.py
Labels: bug, docker, setup

#8838 Tasks cleanup
  src/backend/InvenTree/InvenTree/settings.py
  tasks.py
Labels: refactor

#8811 [Documentation] Remove package credits
  docs/docs/credits.md
  docs/docs/develop/contributing.md
  docs/docs/settings/SSO.md
  docs/docs/settings/admin.md
  docs/docs/settings/global.md
  docs/docs/settings/reference.md
  docs/docs/start/installer.md
  docs/docs/start/intro.md
  docs/docs/start/migrate.md
  docs/docs/stock/tracking.md
  docs/mkdocs.yml
  src/backend/InvenTree/InvenTree/settings.py
  src/frontend/playwright.config.ts
  src/frontend/src/components/Boundary.tsx
  src/frontend/src/states/IconState.tsx
  src/frontend/tests/login.ts
  src/frontend/tests/pages/pui_purchase_order.spec.ts
Labels: dependency, documentation

#8843 Fix for test results in stock item report context
  src/backend/InvenTree/stock/models.py
Labels: bug, report, backport, backport-to-0.17.x

#8846 Order creation fix
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/order/test_api.py
Labels: bug, order, backport, backport-to-0.17.x

#8840 Fix for notification
  src/frontend/src/pages/Index/Scan.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/CurrencyManagmentPanel.tsx
Labels: bug, Platform UI

#8849 [Bug] Plugin loading errors
  src/backend/InvenTree/plugin/registry.py
Labels: bug, plugin, backport, backport-to-0.17.x

#8848 Created by
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/order/serializers.py
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/Filter.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/tables/sales/SalesOrderTable.tsx
Labels: enhancement, order, api, Platform UI

#8853 Datamatrix
  docs/docs/assets/images/report/datamatrix.png
  docs/docs/assets/images/report/qrcode.png
  docs/docs/hooks.py
  docs/docs/report/barcodes.md
  src/backend/InvenTree/report/helpers.py
  src/backend/InvenTree/report/templatetags/barcode.py
  src/backend/InvenTree/report/tests.py
  src/backend/requirements.in
  src/backend/requirements.txt
Labels: enhancement, barcode, report, dependency, documentation

#8860 Simplify translated string
  src/backend/InvenTree/InvenTree/models.py
Labels: translation

#8869 Adjust StockItem form
  src/frontend/src/forms/StockForms.tsx
Labels: enhancement, stock, Platform UI

#8876 Forms refactor
  src/frontend/src/forms/StockForms.tsx
Labels: refactor, Platform UI

#8880 Add Serbian to LanguageContext.tsx
  src/frontend/src/contexts/LanguageContext.tsx
Labels: bug, translation, backport, backport-to-0.17.x

#8884 Ignore RTD version check
  docs/docs/hooks.py
  docs/mlc_config.json
Labels: bug, CI, documentation

#8867 Add Expiry Date on Receive Line Item
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/order/test_api.py
  src/backend/InvenTree/part/serializers.py
  src/frontend/src/forms/PurchaseOrderForms.tsx
Labels: enhancement, order

#8883 [UI] Reactive Details Columns
  src/frontend/src/components/details/ItemDetails.tsx
  src/frontend/src/components/nav/PageDetail.tsx
Labels: Platform UI

#8886 Allow null value for expiry_date field
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/order/serializers.py
Labels: order, api

#8885 [UI] Responsiveness Improvements
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/components/details/DetailsImage.tsx
  src/frontend/src/components/details/ItemDetails.tsx
  src/frontend/src/components/nav/PageDetail.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/company/CompanyDetail.tsx
  src/frontend/src/pages/company/ManufacturerPartDetail.tsx
  src/frontend/src/pages/company/SupplierPartDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderShipmentDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: enhancement, refactor, Platform UI

#8890 Slight tweak to <DetailsTable>
  src/frontend/src/components/details/Details.tsx
  src/frontend/src/components/items/MenuLinks.tsx
  src/frontend/src/components/settings/FactCollection.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/UserPanel.tsx
  src/frontend/src/pages/part/PartSchedulingDetail.tsx
  src/frontend/src/pages/part/PartStocktakeDetail.tsx
  src/frontend/src/pages/part/pricing/BomPricingPanel.tsx
  src/frontend/src/pages/part/pricing/PriceBreakPanel.tsx
  src/frontend/src/pages/part/pricing/PricingOverviewPanel.tsx
  src/frontend/src/pages/part/pricing/PurchaseHistoryPanel.tsx
  src/frontend/src/pages/part/pricing/SaleHistoryPanel.tsx
  src/frontend/src/pages/part/pricing/SupplierPricingPanel.tsx
  src/frontend/src/pages/part/pricing/VariantPricingPanel.tsx
Labels: Platform UI

#8895 Upload timeout
  docs/main.py
  src/frontend/src/App.tsx
  src/frontend/src/components/forms/ApiForm.tsx
  src/frontend/src/tables/general/AttachmentTable.tsx
Labels: bug, backport, Platform UI, backport-to-0.17.x

#8898 Allow CORS for /plugin/ URLs
  src/backend/InvenTree/InvenTree/settings.py
Labels: bug, backport, backport-to-0.17.x

#8893 fix(plugin): Ensure plugins are only installed if not deactivated
  src/backend/InvenTree/plugin/registry.py
Labels: bug, plugin, backport, backport-to-0.17.x

#8894 refactor: remove preference-view
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/urls.py
  src/backend/InvenTree/users/api.py
  src/backend/InvenTree/users/test_api.py
  src/backend/InvenTree/web/tests.py
  src/backend/InvenTree/web/urls.py
  src/frontend/src/components/buttons/SSOButton.tsx
  src/frontend/src/enums/ApiEndpoints.tsx
Labels: refactor

#8903 feat: Add setting for controling console logs
  .github/workflows/qc_checks.yaml
  docs/docs/start/config.md
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/config_template.yaml
Labels: CI, setup

#8904 chore: bump pre commit
  .pre-commit-config.yaml
  contrib/container/gunicorn.conf.py
  docs/docs/hooks.py
  pyproject.toml
  src/backend/InvenTree/InvenTree/helpers.py
  src/backend/InvenTree/InvenTree/models.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/tests.py
  src/backend/InvenTree/common/api.py
  src/backend/InvenTree/common/setting/system.py
  src/backend/InvenTree/generic/states/fields.py
  src/backend/InvenTree/machine/machine_types/label_printer.py
  src/backend/InvenTree/plugin/base/barcodes/helper.py
  src/backend/InvenTree/report/templatetags/report.py
  src/backend/InvenTree/report/tests.py
  src/backend/InvenTree/stock/models.py
  tasks.py
Labels: CI, dependency

#8905 chore(backend): bump deps
  contrib/container/requirements.txt
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/requirements-dev.txt
  src/backend/requirements.in
  src/backend/requirements.txt
Labels: dependency, security

#8906 chore(frontend): bump frontend deps
  src/frontend/package.json
  src/frontend/yarn.lock
Labels: dependency, javascript

#8912 feat: Do not change source on update/build
  tasks.py
Labels: setup

#8914 Cleanup UserManagementPanel
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/UserManagementPanel.tsx
Labels: User Interface

#8917 Pass locale information through to plugins
  src/frontend/src/components/plugins/PluginContext.tsx
Labels: enhancement, plugin, User Interface

#8915 Build start date
  docs/docs/build/build.md
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/build/migrations/0054_build_start_date.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/serializers.py
  src/frontend/src/components/forms/fields/DateField.tsx
  src/frontend/src/forms/BuildForms.tsx
  src/frontend/src/functions/forms.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
  src/frontend/tests/helpers.ts
  src/frontend/tests/pages/pui_build.spec.ts
  src/frontend/tests/pui_tables.spec.ts
Labels: enhancement, api, build, migration, User Interface

#8911 Update SalesOrderAllocationTable
  src/frontend/src/pages/sales/SalesOrderShipmentDetail.tsx
  src/frontend/src/tables/sales/SalesOrderAllocationTable.tsx
  src/frontend/tests/pages/pui_sales_order.spec.ts
Labels: User Interface

#8924 Import fix
  src/backend/InvenTree/importer/mixins.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/stock/serializers.py
Labels: bug, import / export, backport, refactor, backport-to-0.17.x

#8923 Include location detail in build output table
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/serializers.py
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
Labels: bug, backport, User Interface, backport-to-0.17.x

#8931 Code cleanup
  src/backend/InvenTree/report/api.py
Labels: refactor

#8922 Plugin reload fix
  src/backend/InvenTree/.gitignore
  src/backend/InvenTree/plugin/models.py
  src/backend/InvenTree/plugin/registry.py
  src/backend/InvenTree/plugin/test_api.py
  src/backend/InvenTree/plugin/test_plugin.py
  tasks.py
Labels: bug, plugin, backport, backport-to-0.17.x

#8940 Build category filter
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/api.py
  src/frontend/src/tables/FilterSelectDrawer.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
Labels: enhancement, api, build, User Interface

#8945 Notification cleanup
  src/frontend/src/pages/Index/Scan.tsx
  src/frontend/src/states/IconState.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
Labels: User Interface

#8951 Docs updates:
  docs/docs/hooks.py
  docs/main.py
Labels: documentation, backport, refactor, backport-to-0.17.x

#8952 Add check for minimum invoke version
  tasks.py
Labels: setup, backport, backport-to-0.17.x

#8958 refactor(docs): Remove theme doc
  docs/docs/extend/themes.md
  docs/mkdocs.yml
Labels: documentation

#8959 refactor(backend): remove contrib.messages
  src/backend/InvenTree/templates/base.html
Labels: refactor

#8950 [Refactoring] Data Export
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/models.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/company/serializers.py
  src/backend/InvenTree/importer/mixins.py
  src/backend/InvenTree/part/filters.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/stock/api.py
  src/backend/InvenTree/stock/serializers.py
  src/backend/InvenTree/stock/test_api.py
  src/frontend/src/pages/company/SupplierPartDetail.tsx
Labels: enhancement, import / export, refactor

#8956 [Enhancement] Request cache
  src/backend/InvenTree/InvenTree/cache.py
  src/backend/InvenTree/InvenTree/middleware.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/plugin/registry.py
Labels: refactor

#8957 feat(backend): Improve error with missing manifest
  docs/docs/faq.md
  docs/docs/settings/error_codes.md
  docs/mkdocs.yml
  src/backend/InvenTree/web/templates/web/index.html
  src/backend/InvenTree/web/templatetags/spa_helper.py
  src/backend/InvenTree/web/tests.py
Labels: enhancement, setup

#8814 SalesOrder migration unit test
  src/backend/InvenTree/generic/states/fields.py
  src/backend/InvenTree/order/migrations/0105_auto_20241128_0431.py
  src/backend/InvenTree/order/test_migrations.py
  src/frontend/tests/pui_login.spec.ts
Labels: bug, order, backport, migration, full-run, backport-to-0.17.x

#8962 Fix for 'issued_by' field on BuildDetail page
  src/frontend/src/pages/build/BuildDetail.tsx
Labels: bug, User Interface

#8960 feat(backend): improve tag docs
  .github/workflows/qc_checks.yaml
  docs/docs/report/helpers.md
  docs/main.py
  readthedocs.yml
  src/backend/InvenTree/InvenTree/management/commands/export_filters.py
  src/backend/InvenTree/InvenTree/management/commands/export_tags.py
  src/backend/InvenTree/InvenTree/settings.py
  src/backend/InvenTree/InvenTree/urls.py
  src/backend/requirements.in
  src/backend/requirements.txt
  tasks.py
Labels: enhancement, CI, documentation

#8971 Update docker build workflow
  .github/workflows/docker.yaml
  tasks.py
Labels: CI, docker

#8973 Fix user role caching issues
  src/backend/InvenTree/stock/api.py
  src/backend/InvenTree/stock/models.py
  src/backend/InvenTree/stock/test_api.py
  src/backend/InvenTree/users/models.py
  src/backend/InvenTree/users/test_api.py
Labels: refactor

#8975 [UI] Part pricing breaks
  src/frontend/src/pages/part/PartPricingPanel.tsx
  src/frontend/src/pages/part/pricing/PricingOverviewPanel.tsx
  src/frontend/tests/login.ts
  src/frontend/tests/pages/pui_part.spec.ts
  src/frontend/tests/pages/pui_purchase_order.spec.ts
Labels: bug, backport, User Interface, backport-to-0.17.x

#8981 [UI] Fix for chart rendering
  src/frontend/src/pages/part/PartStocktakeDetail.tsx
Labels: bug, backport, User Interface, backport-to-0.17.x

#8984 Sales Order Barcode Allocate
  src/backend/InvenTree/plugin/base/barcodes/api.py
Labels: bug, barcode, backport, backport-to-0.17.x

#8966 Order start dates
  docs/docs/build/build.md
  docs/docs/order/purchase_order.md
  docs/docs/order/return_order.md
  docs/docs/order/sales_order.md
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/order/migrations/0106_purchaseorder_start_date_returnorder_start_date_and_more.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/serializers.py
  src/frontend/src/forms/PurchaseOrderForms.tsx
  src/frontend/src/forms/ReturnOrderForms.tsx
  src/frontend/src/forms/SalesOrderForms.tsx
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/purchasing/PurchaseOrderDetail.tsx
  src/frontend/src/pages/sales/ReturnOrderDetail.tsx
  src/frontend/src/pages/sales/SalesOrderDetail.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/Filter.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/tables/sales/SalesOrderTable.tsx
  src/frontend/tests/pages/pui_purchase_order.spec.ts
  src/frontend/tests/pui_tables.spec.ts
Labels: enhancement, order, api, migration, User Interface

#8987 Fix for gitignore
  .gitignore
Labels: bug, CI

#8989 fix(backend): api version style
  .github/workflows/qc_checks.yaml
  src/backend/InvenTree/InvenTree/api_version.py
Labels: bug, CI

#8991 fix(backend): ensure only the intended files are pushed
  .github/workflows/qc_checks.yaml
Labels: bug, CI

#8979 fix(contrib): Invoke Path Issues
  .devcontainer/postCreateCommand.sh
  docs/docs/settings/error_codes.md
  tasks.py
Labels: bug, setup, breaking

#8969 feat: Re-Implement customize options
  src/backend/InvenTree/InvenTree/api.py
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/helpers.py
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/defaults/defaults.tsx
  src/frontend/src/pages/Auth/Login.tsx
  src/frontend/src/states/states.tsx
Labels: enhancement, User Interface

#8932 refactor(backend): reduce tags
  src/backend/InvenTree/InvenTree/api.py
  src/backend/InvenTree/InvenTree/helpers.py
  src/backend/InvenTree/InvenTree/templatetags/inventree_extras.py
  src/backend/InvenTree/part/test_part.py
  src/backend/InvenTree/templates/503.html
  src/backend/InvenTree/templates/account/base.html
Labels: refactor

#8897 feat: increase coverage
  src/backend/InvenTree/InvenTree/helpers_model.py
  src/backend/InvenTree/InvenTree/templatetags/inventree_extras.py
  src/backend/InvenTree/part/test_api.py
  src/backend/InvenTree/report/templatetags/report.py
  src/backend/InvenTree/report/test_tags.py
  src/backend/InvenTree/report/tests.py
Labels: CI
