Repository inventree/InvenTree, pull requests merged in 2025-09, with the labels that each got.

#10254 Mantine update
  src/frontend/package.json
  src/frontend/src/components/items/GettingStartedCarousel.tsx
  src/frontend/src/components/panels/PanelGroup.tsx
  src/frontend/src/styles/overrides.css
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/part/ParametricPartTableFilters.tsx
  src/frontend/tests/pages/pui_part.spec.ts
  src/frontend/yarn.lock
Labels: dependency, User Interface

#10255 Bump frontend version
  src/frontend/package.json
Labels: plugin, User Interface

#10256 Fix for allocation of tracked outputs
  src/frontend/src/forms/BuildForms.tsx
Labels: bug, build, User Interface

#10257 Virtual parts enhancements
  docs/docs/part/index.md
  docs/docs/part/virtual.md
  docs/mkdocs.yml
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/tasks.py
  src/backend/InvenTree/order/migrations/0112_alter_salesorderlineitem_part.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/models.py
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/tables/bom/BomTable.tsx
  src/frontend/src/tables/sales/SalesOrderLineItemTable.tsx
Labels: enhancement, order, api, build, documentation, User Interface

#10227 Debian docker image
  .devcontainer/Dockerfile
  contrib/container/Dockerfile
  contrib/container/dev-docker-compose.yml
  contrib/container/docker-compose.yml
  contrib/container/install_build_packages.sh
Labels: docker, setup

#10260 fix a few docker security holes
  contrib/container/Dockerfile
Labels: docker

#10264 [UI] breadcrumb fix
  src/frontend/src/components/nav/BreadcrumbList.tsx
  src/frontend/tests/pages/pui_sales_order.spec.ts
Labels: User Interface

#10266 Build task fix
  src/backend/InvenTree/build/models.py
Labels: build

#10226 chore(backend): improve coverage
  src/backend/InvenTree/users/apps.py
  src/backend/InvenTree/users/models.py
  src/backend/InvenTree/users/permissions.py
  src/backend/InvenTree/users/serializers.py
Labels: CI

#10278 Fix for PartParameterTable
  src/frontend/src/tables/part/ParametricPartTable.tsx
Labels: bug, User Interface

#10280 Fix "Installed Items" table
  src/frontend/src/tables/stock/InstalledItemsTable.tsx
Labels: bug, User Interface

#10298 Data import fix
  src/backend/InvenTree/importer/models.py
  src/frontend/src/components/importer/ImportDataSelector.tsx
Labels: bug, import / export, backport, backport-to-1.0.x

#10279 Refactor (backend): Improve BuildItemList API filters
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/part/test_notification_stale.py
  src/backend/InvenTree/stock/api.py
  src/backend/InvenTree/stock/fixtures/stock.yaml
  src/backend/InvenTree/stock/test_api.py
Labels: api, backport, refactor, backport-to-1.0.x

#10306 feat(frontend): Add samples for dashboard
  src/frontend/src/components/dashboard/DashboardLayout.tsx
  src/frontend/src/states/LocalState.tsx
Labels: enhancement, backport, User Interface, backport-to-1.0.x

#10327 Fix user defined radius
  src/frontend/lib/types/Core.tsx
  src/frontend/src/defaults/defaults.tsx
  src/frontend/src/pages/Index/Settings/AccountSettings/UserThemePanel.tsx
Labels: bug, backport, User Interface, backport-to-1.0.x

#10330 Bump dummy plugin version
  src/backend/InvenTree/InvenTree/version.py
  src/backend/InvenTree/plugin/samples/integration/version.py
Labels: plugin, CI

#10333 Exclude field from stock-item import
  src/backend/InvenTree/stock/serializers.py
Labels: bug, import / export, backport, backport-to-1.0.x

#10336 Fix for RenderStockItem
  src/frontend/src/components/render/Stock.tsx
Labels: bug, backport, User Interface, backport-to-1.0.x

#10341 UI panels fix
  src/backend/InvenTree/plugin/base/ui/tests.py
  src/backend/InvenTree/plugin/samples/integration/user_interface_sample.py
  src/frontend/src/hooks/UsePluginPanels.tsx
Labels: bug, backport, User Interface, backport-to-1.0.x

#10350 [UI] Display Stock link
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: bug, backport, User Interface, backport-to-1.0.x

#10352 Improved error handling
  src/backend/InvenTree/report/apps.py
Labels: bug, backport, backport-to-1.0.x

#9912 feat: speed up docker publishing
  .github/workflows/docker.yaml
Labels: CI, docker, refactor

#10361 Support import of "choice" fields
  src/backend/InvenTree/importer/models.py
Labels: bug, import / export, backport, backport-to-1.0.x

#10362 Handle null user case
  src/backend/InvenTree/stock/serializers.py
Labels: bug, api, backport, backport-to-1.0.x

#10368 [UI] Part test result table
  src/frontend/src/pages/build/BuildDetail.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/stock/StockDetail.tsx
  src/frontend/src/tables/Filter.tsx
  src/frontend/src/tables/part/PartTestResultTable.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
  src/frontend/tests/pages/pui_stock.spec.ts
Labels: User Interface

#10371 Show revision in stock item details
  src/frontend/src/pages/stock/StockDetail.tsx
Labels: User Interface

#10400 [ui] Fix typo
  src/frontend/src/tables/build/BuildLineTable.tsx
Labels: bug, backport, User Interface, backport-to-1.0.x

#10398 [bug] Auto allocate bugfix
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/build/filters.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/test_build.py
Labels: bug, build, backport, backport-to-1.0.x

#10409 Add info badge to part renderer
  src/frontend/src/components/render/Part.tsx
  src/frontend/src/components/render/Stock.tsx
Labels: User Interface

#10406 [UI] Top level text
  src/frontend/src/pages/part/CategoryDetail.tsx
  src/frontend/src/pages/stock/LocationDetail.tsx
  src/frontend/tests/pages/pui_stock.spec.ts
Labels: User Interface

#10418 Fix locale formatting for calendar display
  src/frontend/src/components/calendar/Calendar.tsx
Labels: bug, backport, User Interface, backport-to-1.0.x

#10417 Fix incorrect type hints
  src/backend/InvenTree/build/models.py
Labels: bug

#10422 [UI] Consume tracked
  src/frontend/src/tables/build/BuildAllocatedStockTable.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
Labels: bug, backport, User Interface, backport-to-1.0.x

#10419 Translate each language to their own language
  src/frontend/src/contexts/LanguageContext.tsx
  src/frontend/tests/pui_settings.spec.ts
Labels: User Interface

#10426 Update mobile app link in README
  README.md
Labels: documentation

#10430 Improve printing actions
  src/frontend/src/components/buttons/PrintingActions.tsx
Labels: bug, report, backport, User Interface, backport-to-1.0.x

#10433 Improved error message
  src/backend/InvenTree/stock/serializers.py
Labels: api
