Repository inventree/InvenTree, pull requests merged in 2025-08, with the labels that each got.

#10107 feat: Add support for cache password in Redis configuration
  docs/docs/start/config.md
  src/backend/InvenTree/InvenTree/cache.py
Labels: setup, documentation

#10108 API search field bug
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/order/test_api.py
Labels: bug, api

#10109 Email history enhancements
  docs/docs/settings/global.md
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/tasks.py
  src/backend/InvenTree/common/api.py
  src/backend/InvenTree/common/setting/system.py
  src/frontend/src/components/settings/ConfigValueList.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/settings/EmailTable.tsx
Labels: api, User Interface

#10110 [build order] Auto select SN
  src/frontend/lib/types/Forms.tsx
  src/frontend/src/components/forms/fields/ApiFormField.tsx
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
  src/frontend/src/forms/BuildForms.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
  src/frontend/tests/pages/pui_build.spec.ts
Labels: CI, build, User Interface

#10111 Build on order
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/serializers.py
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/build/BuildAllocatedStockTable.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
  src/frontend/src/tables/general/ExtraLineItemTable.tsx
  src/frontend/src/tables/purchasing/SupplierPartTable.tsx
  src/frontend/src/tables/sales/SalesOrderLineItemTable.tsx
Labels: api, build, User Interface

#10113 Fix glitch in <RelatedModelField />
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
  src/frontend/tests/pages/pui_build.spec.ts
  src/frontend/tests/pages/pui_part.spec.ts
Labels: bug, User Interface

#10122 Tweak form padding
  src/frontend/src/components/forms/ApiForm.tsx
Labels: User Interface

#10127 Enhance formatting for item render functions
  src/frontend/src/components/render/Part.tsx
  src/frontend/src/components/render/Stock.tsx
Labels: User Interface

#10128 Fix issue with <StarredToggleButton />
  src/frontend/src/components/buttons/StarredToggleButton.tsx
Labels: bug, User Interface

#10129 Fix error message
  src/backend/InvenTree/build/serializers.py
Labels: bug

#10124 [refactor] Stocktake -> Stock History
  docs/docs/assets/images/part/part_stocktake_from_category.png
  docs/docs/assets/images/part/part_stocktake_from_location.png
  docs/docs/assets/images/part/part_stocktake_from_part.png
  docs/docs/assets/images/part/part_stocktake_generate.png
  docs/docs/assets/images/part/part_stocktake_report_table.png
  docs/docs/assets/images/part/part_stocktake_settings.png
  docs/docs/assets/images/plugin/builtin/stocktake_exporter_options.png
  docs/docs/part/stocktake.md
  docs/docs/part/views.md
  docs/docs/plugins/builtin/index.md
  docs/docs/plugins/builtin/slack_notification.md
  docs/docs/plugins/builtin/stocktake_exporter.md
  docs/docs/report/index.md
  docs/mkdocs.yml
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/helpers.py
  src/backend/InvenTree/common/setting/system.py
  src/backend/InvenTree/common/setting/user.py
  src/backend/InvenTree/part/admin.py
  src/backend/InvenTree/part/api.py
  src/backend/InvenTree/part/migrations/0097_partstocktakereport.py
  src/backend/InvenTree/part/migrations/0142_remove_part_last_stocktake_remove_partstocktake_note_and_more.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/part/serializers.py
  src/backend/InvenTree/part/stocktake.py
  src/backend/InvenTree/part/tasks.py
  src/backend/InvenTree/part/test_api.py
  src/backend/InvenTree/part/test_part.py
  src/backend/InvenTree/plugin/base/event/events.py
  src/backend/InvenTree/plugin/builtin/exporter/stocktake_exporter.py
  src/backend/InvenTree/plugin/builtin/exporter/test_exporter.py
  src/backend/InvenTree/plugin/test_api.py
  src/backend/InvenTree/users/oauth2_scopes.py
  src/backend/InvenTree/users/ruleset.py
  src/frontend/lib/enums/ApiEndpoints.tsx
  src/frontend/lib/enums/Roles.tsx
  src/frontend/src/forms/PartForms.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/Index.tsx
  src/frontend/src/pages/Index/Settings/AdminCenter/StocktakePanel.tsx
  src/frontend/src/pages/Index/Settings/SystemSettings.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/pages/part/PartStockHistoryDetail.tsx
  src/frontend/src/tables/part/PartTable.tsx
  src/frontend/src/tables/settings/StocktakeReportTable.tsx
  src/frontend/tests/helpers.ts
  src/frontend/tests/pui_settings.spec.ts
Labels: api, import / export, breaking, refactor, migration, User Interface, full-run

#10121 chore(backend): increase coverage
  src/backend/InvenTree/common/apps.py
  src/backend/InvenTree/common/migrations/0001_initial.py
  src/backend/InvenTree/common/migrations/0023_auto_20240602_1332.py
  src/backend/InvenTree/common/models.py
  src/backend/InvenTree/common/notifications.py
  src/backend/InvenTree/common/test_migrations.py
  src/backend/InvenTree/common/tests.py
  src/backend/InvenTree/plugin/builtin/integration/core_notifications.py
  src/backend/InvenTree/plugin/test_api.py
Labels: CI, full-run

#10134 Tweak query count values for plugin install
  src/backend/InvenTree/plugin/test_api.py
Labels: plugin, api, CI

#10135 Fix 'issued_by' filter on BuildOrder API
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/build/test_api.py
Labels: bug, api

#10142 Bom total quantity
  docs/docs/assets/images/plugin/builtin/bom_export_options.png
  src/backend/InvenTree/part/test_api.py
  src/backend/InvenTree/plugin/builtin/exporter/bom_exporter.py
Labels: enhancement, plugin, import / export

#10145 Docker fixes again
  docs/docs/develop/contributing.md
  src/backend/InvenTree/InvenTree/unit_test.py
  src/backend/InvenTree/plugin/test_api.py
Labels: CI, docker

#9969 Fix annotations for returning serialized StockItems as lists
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/schema.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/stock/api.py
  src/backend/InvenTree/stock/serializers.py
  src/backend/InvenTree/stock/test_api.py
  src/frontend/src/tables/stock/StockItemTable.tsx
Labels: stock, api, breaking

#10156 refactor(backend): raise allauth
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/requirements.txt
Labels: dependencies

#10153 Run full docker build if full_run specified
  .github/workflows/docker.yaml
  src/backend/InvenTree/common/test_migrations.py
  src/backend/InvenTree/plugin/installer.py
  src/backend/InvenTree/plugin/registry.py
  src/backend/InvenTree/plugin/test_api.py
Labels: bug, CI, docker, full-run

#10163 Bom export fix
  src/backend/InvenTree/data_exporter/mixins.py
  src/backend/InvenTree/plugin/builtin/exporter/bom_exporter.py
Labels: bug, import / export

#10181 [UI] Search shortcut
  docs/docs/settings/user.md
  src/backend/InvenTree/common/setting/user.py
  src/frontend/src/components/nav/Header.tsx
  src/frontend/src/components/nav/Layout.tsx
  src/frontend/src/pages/Index/Settings/UserSettings.tsx
  src/frontend/tests/pui_general.spec.ts
Labels: User Interface

#10174 [refactor] PO receive fix
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/InvenTree/models.py
  src/backend/InvenTree/InvenTree/unit_test.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/order/api.py
  src/backend/InvenTree/order/models.py
  src/backend/InvenTree/order/serializers.py
  src/backend/InvenTree/order/test_api.py
  src/backend/InvenTree/order/tests.py
  src/backend/InvenTree/part/models.py
  src/backend/InvenTree/plugin/base/integration/test_mixins.py
  src/backend/InvenTree/plugin/registry.py
  src/backend/InvenTree/plugin/samples/integration/test_api_caller.py
  src/backend/InvenTree/stock/models.py
  src/frontend/src/components/forms/fields/RelatedModelField.tsx
  src/frontend/src/components/render/Order.tsx
  src/frontend/src/components/render/Part.tsx
  src/frontend/src/components/render/Stock.tsx
  src/frontend/src/pages/part/PartDetail.tsx
  src/frontend/src/tables/InvenTreeTableHeader.tsx
  src/frontend/tests/pages/pui_part.spec.ts
Labels: order, api, refactor, User Interface

#10182 Fix api_url for 'user' type
  src/backend/InvenTree/InvenTree/metadata.py
  src/backend/InvenTree/users/test_api.py
  src/frontend/src/components/render/User.tsx
Labels: bug, api

#10179 feature(BE): add customization for admin.site.site_header
  docs/docs/start/config.md
  src/backend/InvenTree/InvenTree/urls.py
  src/backend/InvenTree/config_template.yaml
Labels: setup

#8191 Build order consume
  docs/docs/assets/images/build/parts_allocated_consumed.png
  docs/docs/manufacturing/allocate.md
  src/backend/InvenTree/InvenTree/api_version.py
  src/backend/InvenTree/build/api.py
  src/backend/InvenTree/build/migrations/0058_buildline_consumed.py
  src/backend/InvenTree/build/models.py
  src/backend/InvenTree/build/serializers.py
  src/backend/InvenTree/build/test_api.py
  src/backend/InvenTree/part/models.py
  src/frontend/lib/components/YesNoButton.tsx
  src/frontend/lib/enums/ApiEndpoints.tsx
  src/frontend/src/components/render/Part.tsx
  src/frontend/src/components/render/Stock.tsx
  src/frontend/src/forms/BuildForms.tsx
  src/frontend/src/forms/StockForms.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/build/BuildAllocatedStockTable.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
  src/frontend/src/tables/part/PartBuildAllocationsTable.tsx
  src/frontend/tests/pages/pui_build.spec.ts
  src/frontend/tests/pages/pui_part.spec.ts
  src/frontend/tests/pages/pui_stock.spec.ts
  src/frontend/tests/pui_plugins.spec.ts
Labels: enhancement, api, build, feature, User Interface

#10200 fix: remove mfa task
  src/backend/InvenTree/InvenTree/management/commands/remove_mfa.py
  src/backend/InvenTree/InvenTree/test_commands.py
Labels: setup

#10204 Column min width
  src/frontend/lib/types/Tables.tsx
  src/frontend/src/components/wizards/OrderPartsWizard.tsx
  src/frontend/src/forms/BuildForms.tsx
  src/frontend/src/forms/SalesOrderForms.tsx
  src/frontend/src/pages/part/pricing/BomPricingPanel.tsx
  src/frontend/src/pages/part/pricing/VariantPricingPanel.tsx
  src/frontend/src/tables/ColumnRenderers.tsx
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/src/tables/bom/UsedInTable.tsx
  src/frontend/src/tables/build/BuildAllocatedStockTable.tsx
  src/frontend/src/tables/build/BuildLineTable.tsx
  src/frontend/src/tables/build/BuildOrderTable.tsx
  src/frontend/src/tables/build/BuildOutputTable.tsx
  src/frontend/src/tables/company/CompanyTable.tsx
  src/frontend/src/tables/part/ParametricPartTable.tsx
  src/frontend/src/tables/part/PartBuildAllocationsTable.tsx
  src/frontend/src/tables/part/PartParameterTable.tsx
  src/frontend/src/tables/part/PartSalesAllocationsTable.tsx
  src/frontend/src/tables/part/PartTable.tsx
  src/frontend/src/tables/purchasing/ManufacturerPartTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderLineItemTable.tsx
  src/frontend/src/tables/purchasing/PurchaseOrderTable.tsx
  src/frontend/src/tables/purchasing/SupplierPartTable.tsx
  src/frontend/src/tables/sales/ReturnOrderLineItemTable.tsx
  src/frontend/src/tables/sales/ReturnOrderTable.tsx
  src/frontend/src/tables/sales/SalesOrderAllocationTable.tsx
  src/frontend/src/tables/sales/SalesOrderLineItemTable.tsx
  src/frontend/src/tables/sales/SalesOrderTable.tsx
  src/frontend/src/tables/stock/InstalledItemsTable.tsx
  src/frontend/src/tables/stock/StockItemTable.tsx
Labels: User Interface

#10159 Walkthrough Update for v1.0 release
  docs/docs/assets/images/plugin/plugin_attachment_carousel.png
  docs/docs/assets/images/plugin/plugin_attachment_carousel_icon.png
  docs/docs/assets/images/plugin/plugin_attachment_carousel_icon_wrong.png
  docs/docs/assets/images/plugin/plugin_vite_dev_site.png
  docs/docs/assets/images/plugin/plugin_vite_mantine_carousel.png
  docs/docs/assets/images/plugin/plugin_vite_running.png
  docs/docs/assets/images/plugin/plugin_vscode_layout.png
  docs/docs/assets/images/plugin/plugin_walkthrough_admin_interface.png
  docs/docs/assets/images/plugin/plugin_walkthrough_attachment_carousel.png
  docs/docs/assets/images/plugin/plugin_walkthrough_attachment_carousel_picsum.png
  docs/docs/assets/images/plugin/plugin_walkthrough_default.png
  docs/docs/assets/images/plugin/plugin_walkthrough_icon_default.png
  docs/docs/assets/images/plugin/plugin_walkthrough_interface_integration.png
  docs/docs/assets/images/plugin/plugin_walkthrough_vscode_layout.png
  docs/docs/plugins/walkthrough.md
Labels: plugin, documentation

#10216 fix style
  docs/docs/plugins/walkthrough.md
Labels: documentation

#10217 [bug] Part requirements fix
  src/backend/InvenTree/part/models.py
Labels: bug

#10225 Update dockerfile
  contrib/container/Dockerfile
  src/frontend/package.json
Labels: bug, docker, setup

#10231 Display error message in email table
  src/frontend/src/tables/settings/EmailTable.tsx
Labels: User Interface

#10232 Update react-window
  src/frontend/package.json
  src/frontend/yarn.lock
Labels: plugin, dependency, User Interface

#10234 Bump @inventreedb/ui version
  src/frontend/package.json
Labels: plugin, User Interface

#10236 Table pagination fix
  src/frontend/src/tables/InvenTreeTable.tsx
  src/frontend/tests/helpers.ts
  src/frontend/tests/pui_tables.spec.ts
Labels: bug, User Interface

#10243 Allow virtual parts for Bom item
  src/frontend/src/forms/BomForms.tsx
Labels: bug, backport, User Interface, backport-to-0.17.x
